force-app/main/default/objects/Location__c/Location__c.object-meta.xml
<CustomObject>
    <description>Location of a Partner Subscription Event</description>
    <label>Location</label>
    <nameField>
        <label>Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Offer__c/Offer__c.object-meta.xml
<CustomObject>
    <description>Controls price, delivery, term for a subscription including print, digital and alternate publications. Also holds links to the premiums offered and the campaigns which will utilize this offer.</description>
    <label>Offer</label>
    <nameField>
        <label>Offer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Offers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Offer__c/fields/Total_Amount__c.field-meta.xml
<CustomField>
        <fullName>Total_Amount__c</fullName>
        <formula>Sunday_AmountRollup__c + AmountforRollup__c + Activation_Fee__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>This value is Subscription Amount plus Activation Fee if Activation fee exists for Offer</inlineHelpText>
        <label>Total Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </CustomField>

force-app/main/default/objects/Subscription__c/Subscription__c.object-meta.xml
<CustomObject>
    <description>This object stores the actual subscription details, including selected Offer, Premiums. Delivery Schedules, frequency and term.</description>
    <label>Subscription</label>
    <nameField>
        <displayFormat>Sub-{0000}</displayFormat>
        <label>Subscription Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Subscription__c/fields/Contact__c.field-meta.xml
<CustomField>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Subscriptions</relationshipLabel>
        <relationshipName>Subscriptions</relationshipName>
        <type>Lookup</type>
    </CustomField>

force-app/main/default/objects/Subscription__c/fields/SignatureAttachmentURL__c.field-meta.xml
<CustomField>
        <fullName>SignatureAttachmentURL__c</fullName>
        <description>Holds the Signature Attachment URL for signatures from the partner community</description>
        <label>SignatureAttachmentURL</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </CustomField>

force-app/main/default/objects/Subscription__c/fields/SignatureURL__c.field-meta.xml
<CustomField>
        <fullName>SignatureURL__c</fullName>
        <description>Stores the signature URL from customer signatures for partner community subscription purchases</description>
        <label>SignatureURL</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </CustomField>

force-app/main/default/objects/Subscription__c/fields/subscription_Account__c.field-meta.xml
<CustomField>
        <fullName>subscription_Account__c</fullName>
        <description>Relationship between Account and Subscriptions</description>
        <label>Household Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Subscriptions</relationshipLabel>
        <relationshipName>Subscriptions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </CustomField>

force-app/main/default/objects/Subscription__c/fields/subscription_Offer__c.field-meta.xml
<CustomField>
        <fullName>subscription_Offer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Stores the relationship to Offer</description>
        <label>Offer</label>
        <referenceTo>Offer__c</referenceTo>
        <relationshipLabel>Subscriptions</relationshipLabel>
        <relationshipName>Subscriptions1</relationshipName>
        <type>Lookup</type>
    </CustomField>

force-app/main/default/classes/SubscriptionReceiptController.cls
public without sharing class SubscriptionReceiptController {

    public Subscription__c sub {get; set;}
    public decimal totalFee {get; set;}

    public SubscriptionReceiptController(){
        String subID = ApexPages.currentPage().getParameters().get('id');
        system.debug(subId);
        sub = [SELECT
                        id,
                        Name,
                        subscription_Account__r.Name,
                        subscription_Account__r.ShippingStreet,
                        subscription_Account__r.ShippingCity,
                        subscription_Account__r.ShippingState,
                        subscription_Account__r.ShippingPostalCode,
                        subscription_Account__r.Phone,
                        contact__r.Email,
                        subscription_Account__r.BillingStreet,
                        subscription_Account__r.BillingCity,
                        subscription_Account__r.BillingState,
                        subscription_Account__r.BillingPostalCode,
                        subscription_Offer__r.Total_Amount__c,
                        subscription_Account__r.Owner.Name,
                        subscription_Account__r.Owner.location__c,
                        SignatureURL__c,
                        SignatureAttachmentURL__c
                FROM Subscription__c
                WHERE id =: subID ];
        system.debug(sub.SignatureAttachmentURL__c);

        totalFee = sub.subscription_Offer__r.Total_Amount__c;

    }

}