force-app/main/default/objects/Case/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <description>Small test edit made on 2020_03_09 16:38 in Setup on DEV007</description>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Customer Service</fullName>
            </value>
            <value>
                <fullName>Delivery</fullName>
            </value>
            <value>
                <fullName>Billing</fullName>
            </value>
            <value>
                <fullName>eEdition</fullName>
            </value>
            <value>
                <fullName>Digital Membership</fullName>
            </value>
            <value>
                <fullName>Feedback</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Subscription__c.field-meta.xml
<CustomField>
        <fullName>Subscription__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Subscription</label>
        <referenceTo>Subscription__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </CustomField>

force-app/main/default/objects/Journal__c/Journal__c.object-meta.xml
<CustomObject>
    <label>Journal</label>
    <nameField>
        <displayFormat>Entry - {000000}</displayFormat>
        <label>Entry Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Journal Entries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Journal__c/fields/Account__c.field-meta.xml
<CustomField>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Fee Journals</relationshipLabel>
        <relationshipName>Fee_Journals</relationshipName>
        <type>Lookup</type>
    </CustomField>

force-app/main/default/objects/Journal__c/fields/Credit__c.field-meta.xml
<CustomField>
        <fullName>Credit__c</fullName>
        <description>Amount if this is a credit</description>
        <label>Credit</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Currency</type>
    </CustomField>

force-app/main/default/objects/Journal__c/fields/Debit__c.field-meta.xml
<CustomField>
        <fullName>Debit__c</fullName>
        <description>Amount if this item is a debit</description>
        <label>Debit</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Currency</type>
    </CustomField>

force-app/main/default/objects/Journal__c/fields/Entry_Date__c.field-meta.xml
<CustomField>
        <fullName>Entry_Date__c</fullName>
        <defaultValue>today()</defaultValue>
        <description>Date the item was entered</description>
        <label>Entry Date</label>
        <type>Date</type>
    </CustomField>

force-app/main/default/objects/Journal__c/fields/Subscription__c.field-meta.xml
<CustomField>
        <fullName>Subscription__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Subscription</label>
        <referenceTo>Subscription__c</referenceTo>
        <relationshipLabel>Journal Entries</relationshipLabel>
        <relationshipName>Journal_Entries</relationshipName>
        <type>Lookup</type>
    </CustomField>

force-app/main/default/objects/Subscription__c/Subscription__c.object-meta.xml
<CustomObject>
    <description>This object stores the actual subscription details, including selected Offer, Premiums. Delivery Schedules, frequency and term.</description>
    <label>Subscription</label>
    <nameField>
        <displayFormat>Sub-{0000}</displayFormat>
        <label>Subscription Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Subscription__c/fields/subscription_Account__c.field-meta.xml
<CustomField>
        <fullName>subscription_Account__c</fullName>
        <description>Relationship between Account and Subscriptions</description>
        <label>Household Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Subscriptions</relationshipLabel>
        <relationshipName>Subscriptions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </CustomField>

force-app/main/default/objects/Transaction_Log__c/Transaction_Log__c.object-meta.xml
<CustomObject>
    <label>Transaction Log</label>
    <nameField>
        <displayFormat>TL-{0000}</displayFormat>
        <label>Transaction Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transaction Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Transaction_Log__c/fields/Account__c.field-meta.xml
<CustomField>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Transaction Logs</relationshipLabel>
        <relationshipName>Transaction_Logs</relationshipName>
        <type>Lookup</type>
    </CustomField>

force-app/main/default/objects/Transaction_Log__c/fields/Case__c.field-meta.xml
<CustomField>
        <fullName>Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Transaction Logs</relationshipLabel>
        <relationshipName>Transaction_Logs</relationshipName>
        <type>Lookup</type>
    </CustomField>

force-app/main/default/objects/Transaction_Log__c/fields/Category__c.field-meta.xml
<CustomField>
        <fullName>Category__c</fullName>
        <description>The Category of this transaction</description>
        <label>Category</label>
        <length>25</length>
        <type>Text</type>
    </CustomField>

force-app/main/default/objects/Transaction_Log__c/fields/Entry_Date__c.field-meta.xml
<CustomField>
        <fullName>Entry_Date__c</fullName>
        <label>Entry Date</label>
        <type>Date</type>
    </CustomField>

force-app/main/default/objects/Transaction_Log__c/fields/First_Date__c.field-meta.xml
<CustomField>
        <fullName>First_Date__c</fullName>
        <label>First Date</label>
        <type>Date</type>
    </CustomField>

force-app/main/default/objects/Transaction_Log__c/fields/Last_Date__c.field-meta.xml
<CustomField>
        <fullName>Last_Date__c</fullName>
        <label>Last Date</label>
        <type>Date</type>
    </CustomField>

force-app/main/default/objects/Transaction_Log__c/fields/Message__c.field-meta.xml
<CustomField>
        <fullName>Message__c</fullName>
        <label>Message</label>
        <type>TextArea</type>
    </CustomField>

force-app/main/default/objects/Transaction_Log__c/fields/Subscription__c.field-meta.xml
<CustomField>
        <fullName>Subscription__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Subscription</label>
        <referenceTo>Subscription__c</referenceTo>
        <relationshipLabel>Transaction Logs</relationshipLabel>
        <relationshipName>Transaction_Logs</relationshipName>
        <type>Lookup</type>
    </CustomField>

force-app/main/default/objects/Transaction_Log__c/fields/Transaction_Type__c.field-meta.xml
<CustomField>
        <fullName>Transaction_Type__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Transaction Type</label>
        <referenceTo>Transaction_Type__c</referenceTo>
        <relationshipLabel>Transaction Logs</relationshipLabel>
        <relationshipName>Transaction_Logs</relationshipName>
        <type>Lookup</type>
    </CustomField>

force-app/main/default/objects/Transaction_Log__c/fields/Trouble__c.field-meta.xml
<CustomField>
        <fullName>Trouble__c</fullName>
        <label>Trouble</label>
        <length>255</length>
        <type>Text</type>
    </CustomField>

force-app/main/default/objects/Transaction_Log__c/fields/Type_Name__c.field-meta.xml
<CustomField>
        <fullName>Type_Name__c</fullName>
        <formula>Transaction_Type__r.Type_Name__c</formula>
        <label>Type Name</label>
        <type>Text</type>
    </CustomField>

force-app/main/default/objects/Transaction_Log__c/recordTypes/Complaint.recordType-meta.xml
<RecordType>
        <fullName>Complaint</fullName>
        <active>true</active>
        <label>Complaint</label>
    </RecordType>

force-app/main/default/objects/Transaction_Log__c/recordTypes/Message.recordType-meta.xml
<RecordType>
        <fullName>Message</fullName>
        <active>true</active>
        <label>Message</label>
    </RecordType>

force-app/main/default/objects/Transaction_Log__c/recordTypes/Vacation.recordType-meta.xml
<RecordType>
        <fullName>Vacation</fullName>
        <active>true</active>
        <label>Vacation</label>
    </RecordType>

force-app/main/default/objects/Transaction_Type__c/Transaction_Type__c.object-meta.xml
<CustomObject>
    <label>Transaction Type</label>
    <nameField>
        <label>Transaction Type Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Transaction Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Transaction_Type__c/fields/Category__c.field-meta.xml
<CustomField>
        <fullName>Category__c</fullName>
        <inlineHelpText>Choose appropriate for transaction viewer</inlineHelpText>
        <label>Category</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Carrier Me</fullName>
                </value>
                <value>
                    <fullName>CC_Request</fullName>
                </value>
                <value>
                    <fullName>Complaint</fullName>
                </value>
                <value>
                    <fullName>Credit_Card</fullName>
                </value>
                <value>
                    <fullName>Journal</fullName>
                </value>
                <value>
                    <fullName>Memo</fullName>
                </value>
                <value>
                    <fullName>Message</fullName>
                </value>
                <value>
                    <fullName>Move</fullName>
                </value>
                <value>
                    <fullName>Product Change</fullName>
                </value>
                <value>
                    <fullName>Start</fullName>
                </value>
                <value>
                    <fullName>Stop</fullName>
                </value>
                <value>
                    <fullName>Vacation Pack</fullName>
                </value>
                <value>
                    <fullName>VH</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </CustomField>

force-app/main/default/objects/Transaction_Type__c/fields/Message__c.field-meta.xml
<CustomField>
        <fullName>Message__c</fullName>
        <inlineHelpText>default message text</inlineHelpText>
        <label>Message</label>
        <length>255</length>
        <type>Text</type>
    </CustomField>

force-app/main/default/objects/Transaction_Type__c/fields/Trouble__c.field-meta.xml
<CustomField>
        <fullName>Trouble__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Trouble</label>
        <type>Checkbox</type>
    </CustomField>

force-app/main/default/objects/Transaction_Type__c/fields/Type_Name__c.field-meta.xml
<CustomField>
        <fullName>Type_Name__c</fullName>
        <inlineHelpText>Delivery, COMO etc.</inlineHelpText>
        <label>Type Name</label>
        <length>255</length>
        <type>Text</type>
    </CustomField>

force-app/main/default/classes/TransactionLogActionsTest.cls
@isTest
public with sharing class TransactionLogActionsTest {
    @TestSetup
    private static void generateData(){
        TestDataFactory.createTestRecords(3);
        List<Subscription__c> subs = [SELECT Id, subscription_Account__c FROM Subscription__c];
        List<Transaction_Type__c> transTypes = [SELECT Id from Transaction_Type__c];
        List<Transaction_Log__c> tlsToInsert = new List<Transaction_Log__c>();
        List<Journal__c> journalsToInsert = new List<Journal__c>();
        List<recurly_v2__Recurly_Transaction__c> rTransToInsert = new List<recurly_v2__Recurly_Transaction__c>();
        List<recurly_v2__Recurly_Account__c> rAccsToInsert = new List<recurly_v2__Recurly_Account__c>();
        List<recurly_v2__Recurly_Invoice__c> rInvoicesToInsert = new List<recurly_v2__Recurly_Invoice__c>();
        Case casetoInsert = new Case();
        insert caseToInsert;
        for(Subscription__c sub : subs){
            Transaction_Log__c toInsert = new Transaction_Log__c();
            toInsert.First_Date__c = Date.today();
            toInsert.Last_Date__c = Date.today().addDays(5);
            toInsert.Entry_Date__c = System.today();
            toInsert.Transaction_Type__c = transTypes[0].Id;
            toInsert.Subscription__c = sub.Id;
            toInsert.Account__c = sub.subscription_Account__c;
            toInsert.Case__c = casetoInsert.Id;
            toInsert.Category__c = 'Complaint';
            toInsert.Trouble__c = 'N'; 
            toInsert.Message__c = 'Memo';
            tlsToInsert.add(toInsert);

            Journal__c toInsertJournal = new Journal__c();
            toInsertJournal.Credit__c = 1.0;
            toInsertJournal.Debit__c = 1.0;
            toInsertJournal.Entry_Date__c = Date.today();
            toInsertJournal.Subscription__c = sub.Id;
            journalsToInsert.add(toInsertJournal);
            
           recurly_v2__Recurly_Account__c rAcc = new recurly_v2__Recurly_Account__c();
           rAcc.Subscription__c = sub.Id;
           rAccsToInsert.add(rAcc);

           

        }
        recurly_v2__Recurly_Invoice__c rInvoice = new recurly_v2__Recurly_Invoice__c();
           rInvoice.recurly_v2__Total__c = 10.0;
           rInvoice.recurly_v2__InvoiceID__c = '1';
           rInvoicesToInsert.add(rInvoice);

        insert rInvoicesToInsert;
        insert rAccsToInsert;
        for(recurly_v2__Recurly_Account__c rAccIndex : rAccsToInsert){
            recurly_v2__Recurly_Transaction__c rTrans = new recurly_v2__Recurly_Transaction__c();
            rTrans.recurly_v2__Amount__c = 4.0;
            rTrans.Subscription__c = rAccIndex.Subscription__c;
            rTrans.recurly_v2__Recurly_Account_id__c = rAccIndex.Id;
            rTrans.recurly_v2__Recurly_Invoice__c = rInvoicesToInsert[0].Id;
            rTrans.recurly_v2__Collected_At__c = DateTime.now();
            rTransToInsert.add(rTrans);
           
        }
        
        insert tlsToInsert;
        insert rTransToInsert;
        insert journalsToInsert;
    }
    private static testMethod void shouldGetTransactionLogs() {
        Test.startTest();
       List<Subscription__c> subs = [SELECT Id, subscription_Account__c FROM Subscription__c];
       Case caseInserted = [SELECT Id FROM Case LIMIT 1];
       List<Transaction_Type__c> transTypes = [SELECT Id FROM Transaction_Type__c WHERE Type_Name__c = 'Complaint'];
       
       for(Subscription__c sub : subs){
            Transaction_Log__c toInsert = new Transaction_Log__c();
            toInsert.First_Date__c = System.today();
            toInsert.Last_Date__c = System.today();
            toInsert.Entry_Date__c = System.today();
            toInsert.Transaction_Type__c = transTypes[0].Id;
            toInsert.Subscription__c = sub.Id;
            toInsert.Account__c = sub.subscription_Account__c;
            toInsert.Category__c = 'Complaint';
            toInsert.Trouble__c = 'N'; 
            toInsert.Message__c = 'TestMemo';
            insert toInsert;
            String filterType = 'Message,Vacations,Move/Reroute,Complaints,Product Changes,Financial, Start,Stop,Activity';
            TransactionLogActions.getTransactionLogs(sub.id, filterType);
            TransactionLogActions.getAcctTransactionLogs(sub.subscription_Account__c, 'Complaint');
            TransactionLogActions.getCaseTransactionLogs(caseInserted.Id, 'Complaint');
       }
       Test.stopTest();
    }

    private static testmethod void shouldGetTransactionTypes(){
        Test.startTest();
        List<Account> accs = [SELECT Id FROM Account];
        List<Subscription__c> subs = [SELECT Id FROM Subscription__c];
        TransactionLogActions.getTransactionTypes();
        TransactionLogActions.getTransactionLogs(subs[0].Id, '');
        Test.stopTest();
        
    } 
    private static testmethod void shouldUpdateTransactions(){
         Test.startTest();
          List<Transaction_Log__c> transLogs = [SELECT Id FROM Transaction_Log__c];
        if(!transLogs.isEmpty()){
            TransactionLogActions.CancelTransaction(transLogs[0].Id);
            TransactionLogActions.CancelProductChangeTransaction(transLogs[0].Id);
            TransactionLogActions.CancelTransaction('Throw');
            TransactionLogActions.UpdateTransactionMessage(transLogs[0].Id, 'Test');
            TransactionLogActions.UpdateVacationTransaction((String)transLogs[0].Id, '2020-1-20', '2020-1-25');
            
        }
        Test.stopTest();
           
    }

    private static testmethod void shouldFilterCategory(){
        String result = '';
        result = TransactionLogActions.FilterCategory('Memo');
        result = TransactionLogActions.FilterCategory('Carrier Me');
        result = TransactionLogActions.FilterCategory('Message');
        result = TransactionLogActions.FilterCategory('Vacation Pack');
        result = TransactionLogActions.FilterCategory('VH');
        result = TransactionLogActions.FilterCategory('Move');
        result = TransactionLogActions.FilterCategory('Complaint');
        result = TransactionLogActions.FilterCategory('Product Change');
        result = TransactionLogActions.FilterCategory('Journal');
        result = TransactionLogActions.FilterCategory('Credit_Card');
        result = TransactionLogActions.FilterCategory('CC_Request');
        result = TransactionLogActions.FilterCategory('Start');
        result = TransactionLogActions.FilterCategory('Stop');
        result = TransactionLogActions.FilterCategory('SomethingElse');
    }

}