force-app/main/default/objects/Case/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <description>Small test edit made on 2020_03_09 16:38 in Setup on DEV007</description>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Customer Service</fullName>
            </value>
            <value>
                <fullName>Delivery</fullName>
            </value>
            <value>
                <fullName>Billing</fullName>
            </value>
            <value>
                <fullName>eEdition</fullName>
            </value>
            <value>
                <fullName>Digital Membership</fullName>
            </value>
            <value>
                <fullName>Feedback</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Subscription__c.field-meta.xml
<CustomField>
        <fullName>Subscription__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Subscription</label>
        <referenceTo>Subscription__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </CustomField>

force-app/main/default/objects/Delivery_Schedule__c/Delivery_Schedule__c.object-meta.xml
<CustomObject>
    <description>Deliver Schedules control the address and which days a publication will be delivered as part of the press run.</description>
    <label>Delivery Schedule</label>
    <nameField>
        <displayFormat>DS-{0}</displayFormat>
        <label>Delivery Schedule Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Delivery Schedules</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Delivery_Schedule__c/fields/Day_Friday__c.field-meta.xml
<CustomField>
        <fullName>Day_Friday__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Friday</label>
        <type>Checkbox</type>
    </CustomField>

force-app/main/default/objects/Delivery_Schedule__c/fields/Day_Monday__c.field-meta.xml
<CustomField>
        <fullName>Day_Monday__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Monday</label>
        <type>Checkbox</type>
    </CustomField>

force-app/main/default/objects/Delivery_Schedule__c/fields/Day_Saturday__c.field-meta.xml
<CustomField>
        <fullName>Day_Saturday__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Saturday</label>
        <type>Checkbox</type>
    </CustomField>

force-app/main/default/objects/Delivery_Schedule__c/fields/Day_Sunday__c.field-meta.xml
<CustomField>
        <fullName>Day_Sunday__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Sunday</label>
        <type>Checkbox</type>
    </CustomField>

force-app/main/default/objects/Delivery_Schedule__c/fields/Day_Thursday__c.field-meta.xml
<CustomField>
        <fullName>Day_Thursday__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Thursday</label>
        <type>Checkbox</type>
    </CustomField>

force-app/main/default/objects/Delivery_Schedule__c/fields/Day_Tuesday__c.field-meta.xml
<CustomField>
        <fullName>Day_Tuesday__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Tuesday</label>
        <type>Checkbox</type>
    </CustomField>

force-app/main/default/objects/Delivery_Schedule__c/fields/Day_Wednesday__c.field-meta.xml
<CustomField>
        <fullName>Day_Wednesday__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Wednesday</label>
        <type>Checkbox</type>
    </CustomField>

force-app/main/default/objects/Delivery_Schedule__c/fields/End_Date__c.field-meta.xml
<CustomField>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </CustomField>

force-app/main/default/objects/Delivery_Schedule__c/fields/Offer_Product__c.field-meta.xml
<CustomField>
        <fullName>Offer_Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Offer Product</label>
        <referenceTo>Offer_Product__c</referenceTo>
        <relationshipLabel>Delivery Schedules</relationshipLabel>
        <relationshipName>Delivery_Schedules</relationshipName>
        <type>Lookup</type>
    </CustomField>

force-app/main/default/objects/Delivery_Schedule__c/fields/Start_Date__c.field-meta.xml
<CustomField>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </CustomField>

force-app/main/default/objects/Delivery_Schedule__c/fields/subscription_Subscription__c.field-meta.xml
<CustomField>
        <fullName>subscription_Subscription__c</fullName>
        <description>This fields lookups to the shadow object, Subscription</description>
        <label>Subscription</label>
        <referenceTo>Subscription__c</referenceTo>
        <relationshipLabel>Delivery Schedules</relationshipLabel>
        <relationshipName>Delivery_Schedules</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </CustomField>

force-app/main/default/objects/Offer__c/Offer__c.object-meta.xml
<CustomObject>
    <description>Controls price, delivery, term for a subscription including print, digital and alternate publications. Also holds links to the premiums offered and the campaigns which will utilize this offer.</description>
    <label>Offer</label>
    <nameField>
        <label>Offer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Offers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Offer__c/fields/End_Date__c.field-meta.xml
<CustomField>
        <fullName>End_Date__c</fullName>
        <description>Stores the end date of the offer</description>
        <label>End Date</label>
        <type>Date</type>
    </CustomField>

force-app/main/default/objects/Offer__c/fields/Start_Date__c.field-meta.xml
<CustomField>
        <fullName>Start_Date__c</fullName>
        <description>Stores the start date for this offer</description>
        <label>Start Date</label>
        <type>Date</type>
    </CustomField>

force-app/main/default/objects/Offer_Product__c/Offer_Product__c.object-meta.xml
<CustomObject>
    <label>Offer Product</label>
    <nameField>
        <label>Offer Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Offer Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Offer_Product__c/fields/Is_Digital__c.field-meta.xml
<CustomField>
        <fullName>Is_Digital__c</fullName>
        <formula>Product__r.IsDigital__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Is Digital</label>
        <type>Checkbox</type>
    </CustomField>

force-app/main/default/objects/Offer_Product__c/fields/Offer__c.field-meta.xml
<CustomField>
        <fullName>Offer__c</fullName>
        <label>Offer</label>
        <referenceTo>Offer__c</referenceTo>
        <relationshipLabel>Offer Products</relationshipLabel>
        <relationshipName>Offer_Products</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </CustomField>

force-app/main/default/objects/Subscription__c/Subscription__c.object-meta.xml
<CustomObject>
    <description>This object stores the actual subscription details, including selected Offer, Premiums. Delivery Schedules, frequency and term.</description>
    <label>Subscription</label>
    <nameField>
        <displayFormat>Sub-{0000}</displayFormat>
        <label>Subscription Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Subscription__c/fields/Delivery_Schedule__c.field-meta.xml
<CustomField>
        <fullName>Delivery_Schedule__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Stores the relationship between Subscriptions and Delivery Schedule</description>
        <label>Delivery Schedule</label>
        <referenceTo>Delivery_Schedule__c</referenceTo>
        <relationshipLabel>Subscriptions</relationshipLabel>
        <relationshipName>Subscriptions</relationshipName>
        <type>Lookup</type>
    </CustomField>

force-app/main/default/objects/Subscription__c/fields/subscription_Account__c.field-meta.xml
<CustomField>
        <fullName>subscription_Account__c</fullName>
        <description>Relationship between Account and Subscriptions</description>
        <label>Household Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Subscriptions</relationshipLabel>
        <relationshipName>Subscriptions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </CustomField>

force-app/main/default/objects/Subscription__c/fields/subscription_Offer__c.field-meta.xml
<CustomField>
        <fullName>subscription_Offer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Stores the relationship to Offer</description>
        <label>Offer</label>
        <referenceTo>Offer__c</referenceTo>
        <relationshipLabel>Subscriptions</relationshipLabel>
        <relationshipName>Subscriptions1</relationshipName>
        <type>Lookup</type>
    </CustomField>

force-app/main/default/objects/Subscription__c/fields/subscription_Status__c.field-meta.xml
<CustomField>
        <fullName>subscription_Status__c</fullName>
        <description>Stores the status of the subscription</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>New</fullName>
                </value>
                <value>
                    <fullName>TERMINATED</fullName>
                </value>
                <value>
                    <fullName>INACTIVE</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </CustomField>

force-app/main/default/objects/Transaction_Log__c/Transaction_Log__c.object-meta.xml
<CustomObject>
    <label>Transaction Log</label>
    <nameField>
        <displayFormat>TL-{0000}</displayFormat>
        <label>Transaction Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transaction Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Transaction_Log__c/fields/Account__c.field-meta.xml
<CustomField>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Transaction Logs</relationshipLabel>
        <relationshipName>Transaction_Logs</relationshipName>
        <type>Lookup</type>
    </CustomField>

force-app/main/default/objects/Transaction_Log__c/fields/Category__c.field-meta.xml
<CustomField>
        <fullName>Category__c</fullName>
        <description>The Category of this transaction</description>
        <label>Category</label>
        <length>25</length>
        <type>Text</type>
    </CustomField>

force-app/main/default/objects/Transaction_Log__c/fields/Date__c.field-meta.xml
<CustomField>
        <fullName>Date__c</fullName>
        <label>Date</label>
        <type>Date</type>
    </CustomField>

force-app/main/default/objects/Transaction_Log__c/fields/First_Date__c.field-meta.xml
<CustomField>
        <fullName>First_Date__c</fullName>
        <label>First Date</label>
        <type>Date</type>
    </CustomField>

force-app/main/default/objects/Transaction_Log__c/fields/Offer__c.field-meta.xml
<CustomField>
        <fullName>Offer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Offer</label>
        <referenceTo>Offer__c</referenceTo>
        <relationshipLabel>Transaction Logs</relationshipLabel>
        <relationshipName>Transaction_Logs</relationshipName>
        <type>Lookup</type>
    </CustomField>

force-app/main/default/objects/Transaction_Log__c/fields/Offer_Product__c.field-meta.xml
<CustomField>
        <fullName>Offer_Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Offer Product</label>
        <referenceTo>Offer_Product__c</referenceTo>
        <relationshipLabel>Transaction Logs</relationshipLabel>
        <relationshipName>Transaction_Logs</relationshipName>
        <type>Lookup</type>
    </CustomField>

force-app/main/default/objects/Transaction_Log__c/fields/Subscription__c.field-meta.xml
<CustomField>
        <fullName>Subscription__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Subscription</label>
        <referenceTo>Subscription__c</referenceTo>
        <relationshipLabel>Transaction Logs</relationshipLabel>
        <relationshipName>Transaction_Logs</relationshipName>
        <type>Lookup</type>
    </CustomField>

force-app/main/default/objects/Transaction_Log__c/recordTypes/Complaint.recordType-meta.xml
<RecordType>
        <fullName>Complaint</fullName>
        <active>true</active>
        <label>Complaint</label>
    </RecordType>

force-app/main/default/objects/Transaction_Type__c/Transaction_Type__c.object-meta.xml
<CustomObject>
    <label>Transaction Type</label>
    <nameField>
        <label>Transaction Type Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Transaction Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Transaction_Type__c/fields/Category__c.field-meta.xml
<CustomField>
        <fullName>Category__c</fullName>
        <inlineHelpText>Choose appropriate for transaction viewer</inlineHelpText>
        <label>Category</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Carrier Me</fullName>
                </value>
                <value>
                    <fullName>CC_Request</fullName>
                </value>
                <value>
                    <fullName>Complaint</fullName>
                </value>
                <value>
                    <fullName>Credit_Card</fullName>
                </value>
                <value>
                    <fullName>Journal</fullName>
                </value>
                <value>
                    <fullName>Memo</fullName>
                </value>
                <value>
                    <fullName>Message</fullName>
                </value>
                <value>
                    <fullName>Move</fullName>
                </value>
                <value>
                    <fullName>Product Change</fullName>
                </value>
                <value>
                    <fullName>Start</fullName>
                </value>
                <value>
                    <fullName>Stop</fullName>
                </value>
                <value>
                    <fullName>Vacation Pack</fullName>
                </value>
                <value>
                    <fullName>VH</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </CustomField>

force-app/main/default/classes/DeliveryServiceIssueController.cls
public class DeliveryServiceIssueController {
    @AuraEnabled
    public static List<Offer_Product__c> fetchOfferProducts(Id subId) {
        Subscription__c sub = [SELECT Id, subscription_Offer__c FROM Subscription__c WHERE Id = :subId];
        return [SELECT Id, Name FROM Offer_Product__c WHERE Offer__c = :sub.subscription_Offer__c AND Is_Digital__c = FALSE];
    }

    @AuraEnabled 
    public static Id getSubscriptionId(String sObjectType, Id recordId){
        if(sObjectType.equals('Account')){
            List<Subscription__c> subscriptions = [SELECT Id FROM Subscription__c WHERE subscription_Account__c = :recordId AND subscription_Status__c = 'Active'];
            if(!subscriptions.isEmpty()) return subscriptions[0].Id;
        }
        if(sObjectType.equals('Case')){
            List<Case> caseAccount = [SELECT AccountId FROM Case WHERE Id = :recordId LIMIT 1];
            if(!caseAccount.isEmpty()){
                List<Subscription__c> subscriptions = [SELECT Id FROM Subscription__c WHERE subscription_Account__c = :caseAccount[0].AccountId AND subscription_Status__c = 'Active'];
           		if(!subscriptions.isEmpty()) 
                    return subscriptions[0].Id;
            }   
        }
        if(sObjectType.equals('Subscription__c')){
            return recordId;  
        }
        return null;	        
    }

    @AuraEnabled 
    public static String getLatestExpireDate(Id subscriptionId, String firstDate){
        Date convFirstDate = Date.valueOf(firstDate);
        List<Transaction_Log__c> transLogComplaint = [SELECT Id, Expire_Date__c 
                                    FROM Transaction_Log__c 
                                    WHERE Subscription__c = :subscriptionId AND First_Date__c = :convFirstDate
                                    AND category__c = 'Complaint' ORDER BY LastModifiedDate DESC LIMIT 1];

        if(!transLogComplaint.isEmpty()) {
            String strExpDate = transLogComplaint[0].Expire_Date__c.format();
            return strExpDate;
        }

        return '';
    }    

    @AuraEnabled
    public static Boolean validateDeliveryDate(Id subscriptionId, String selectedDate){
        Boolean result = false;
        
        DateTime dateToValidate = (DateTime) Date.valueOf(selectedDate);
       	Date dateObjToValidate = Date.valueOf(selectedDate);
        dateToValidate = dateToValidate.addHours(12);
        String dayOfWeekSelected = dateToValidate.format('EEEE');
        List<Delivery_Schedule__c> relatedSchedules = [SELECT Day_Friday__c, Day_Monday__c, Day_Saturday__c, Day_Sunday__c, Day_Thursday__c, Day_Tuesday__c, Day_Wednesday__c, Id
                                                       FROM Delivery_Schedule__c
                                                      WHERE subscription_Subscription__c = :subscriptionId AND Start_Date__c <= :dateObjToValidate AND End_Date__c >= :dateObjToValidate];
        for(Delivery_Schedule__c schedule : relatedSchedules){
            System.debug(schedule);
            if(dayOfWeekSelected == 'Sunday' && schedule.Day_Sunday__c){
                result = true;
            }
            else if(dayOfWeekSelected == 'Monday' && schedule.Day_Monday__c){
                result = true;
            }
            else if(dayOfWeekSelected == 'Tuesday' && schedule.Day_Tuesday__c){
                result = true;
            }
            else if(dayOfWeekSelected == 'Wednesday' && schedule.Day_Wednesday__c){
                result = true;
            }
            else if(dayOfWeekSelected == 'Thursday' && schedule.Day_Thursday__c){

                result = true;
            }
            else if(dayOfWeekSelected == 'Friday' && schedule.Day_Friday__c){
                result = true;
            }
            else if(dayOfWeekSelected == 'Saturday' && schedule.Day_Saturday__c){
				result = true;                
            }
        }
        return result;
    }

    @AuraEnabled
    public static void InsertTransaction(Id subscriptionId, Id transactionTypeId, String serviceIssue, String request, String selectedDate, List<Id> selectedOfferProducts, String memo){
        Id oldTransTypeId = transactionTypeId;
        Date convertedDate = Date.valueOf(selectedDate);
        Transaction_Type__c communityCutOffTransType = CutOffManager.communityDeliveryHelper(transactionTypeId, convertedDate);
        transactionTypeId = communityCutOffTransType == null ? transactionTypeId : communityCutOffTransType.Id;
        Id newTransTypeId = transactionTypeId;

        if(oldTransTypeId != newTransTypeId){
            memo += ' - ' + [SELECT Name from Transaction_Type__c WHERE Id = :oldTransTypeId LIMIT 1].Name; 
        } 
        Transaction_Type__c transType = [
            SELECT Id, Name, Code__c, Type_Name__c, Category__c 
            FROM Transaction_Type__c 
            WHERE Id = :transactionTypeId];

        Boolean requestRedelivery = isRedelivery(request, serviceIssue);
        //Id transactionTypeId = getTransactionTypeId(request, serviceIssue);
        Id accountId = [SELECT subscription_Account__c FROM Subscription__c WHERE Id = :subscriptionId LIMIT 1].subscription_Account__c;
        List<Transaction_Log__c> existingTLs;
        if(transType.category__c == 'Complaint'){
            existingTLs = [SELECT Id, First_Date__c, Category__c 
                FROM Transaction_Log__c 
                WHERE Subscription__c = :subscriptionId 
                    AND Transaction_Type__c = :transactionTypeId
                    AND category__c = 'Complaint'
                    AND First_Date__c = :convertedDate];
            if(existingTLs.size() > 0){
                throw new AuraHandledException('A delivery complaint already exists on this day.');
            }
        }
        
        for (Id offerProductId : selectedOfferProducts) {
            TransactionLogHandler.InsertComplaint(subscriptionId, accountId, transactionTypeId, offerProductId, convertedDate, requestRedelivery, memo);
        }
	}



    @AuraEnabled
    public static void createDeliveryIssue(Id subscriptionId, String serviceIssue, String request, Date selectedDate){
        Boolean requestRedelivery = isRedelivery(request, serviceIssue);
        Id transactionTypeId = getTransactionTypeId(request, serviceIssue);
        Id accountId = [SELECT subscription_Account__c FROM Subscription__c WHERE Id = :subscriptionId LIMIT 1].subscription_Account__c;
        
        Transaction_Log__c transactionLog = new Transaction_Log__c();
		transactionLog.Date__c = selectedDate;
		transactionLog.Transaction_Type__c = transactionTypeId;
		transactionLog.Subscription__c = subscriptionId;
		transactionLog.Account__c = accountId;
		transactionLog.Redelivery_Requested__c = requestRedelivery;
        if(!Test.isRunningTest())
		insert transactionLog;
	}

    @AuraEnabled
    public static List<Transaction_Type__c> getDeliveryIssueList(String selectedDate){
        Boolean community = false;
        if(UserInfo.getUserType() != 'Standard'){
            community = true;
        }
        System.debug(UserInfo.getUserType() + '...' + community);

		Date currentDate = Date.today();
        // convert selected date string to date
        Date convertedDate = Date.valueOf(selectedDate);
		
        // Redelivery cutoff
        String whenToDisplayClause = 'AND (When_to_Display__c = \'Anytime\' OR When_to_Display__c = \'After cut-off\') ';
        Boolean beforeCutOff = false;
		if (currentDate == convertedDate && CutOffManager.isBeforeCutOff('Re-delivery')) {
            whenToDisplayClause = 'AND (When_to_Display__c = \'Anytime\' OR When_to_Display__c = \'Before cut-off\') ';
		}
                        
        // based on selected date, returns {Weekday, Saturday, Sunday}
        String DeliveryDayType = CutOffManager.DeliveryDayType(convertedDate);
        // delivery day type clause
        String strDelDayTypeClause = 'AND (Delivery_Day_Type__c = \'All\' OR Delivery_Day_Type__c = \'' + DeliveryDayType + '\') ';

        String communityOnlyClause = '';
        if(community == true){
            communityOnlyClause = 'AND Use_in_Self_Serve_Portal__c = true ';
        }

        // head query string
        String query = 'SELECT Id, Name, Type_Complaint__c, Code__c, Apply_Credit_to_Subscription__c, Redeliver__c ';
        query += 'FROM Transaction_Type__c WHERE Use_in_Flows__c = true AND When_to_Display__c != null ';

        query += strDelDayTypeClause;
        query += whenToDisplayClause;
        query += communityOnlyClause;
        query += 'ORDER BY Name';
        system.debug('--query: ' + query);

        // query result and return list
        List<Transaction_Type__c> ttypeList = Database.query(query);
        return ttypeList;
    }

    private static String getTransactionTypeId(String request, String serviceIssue) {
        String transactionTypeName = null;
        if(request == 'Delivery' && serviceIssue == 'Missed Delivery'){
            transactionTypeName = 'Redelivery Today\'s Missing Newspaper';
        }
        else if(request == 'Delivery' && serviceIssue == 'Wet Paper'){
            transactionTypeName = 'Replace Wet Newspaper';
        }
        else if(request == 'Delivery' && serviceIssue == 'Damaged Paper'){
            transactionTypeName = 'Replaced Damaged Paper';
        }
        else if(request == 'Credit' && serviceIssue == 'Missed Delivery'){
            transactionTypeName = 'Credit for Missed Newspaper';
        }
        else if(request == 'Credit' && serviceIssue == 'Wet Paper'){
            transactionTypeName = 'Credit for Wet Newspaper';
        }
        else if(request == 'Credit' && serviceIssue == 'Damaged Paper'){
            transactionTypeName = 'Credit for Damaged';
        }

        if (String.isNotEmpty(transactionTypeName)) {
            List<Transaction_Type__c> transactionTypes = [SELECT Id from Transaction_Type__c WHERE Name = :transactionTypeName LIMIT 1];
            if(!transactionTypes.isEmpty()){
                return transactionTypes[0].Id;
            }
        }
        return null;
    }

    private static Boolean isRedelivery(String request, String serviceIssue) {
        if(request == 'Delivery' && (serviceIssue == 'Missed Delivery' || serviceIssue == 'Wet Paper') || serviceIssue == 'Damaged Paper'){
            return true;
        }
        return false;
    }

}