force-app/main/default/objects/Case/fields/Subscription__c.field-meta.xml
<CustomField>
        <fullName>Subscription__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Subscription</label>
        <referenceTo>Subscription__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </CustomField>

force-app/main/default/objects/Contact/fields/Attention_Line__c.field-meta.xml
<CustomField>
        <fullName>Attention_Line__c</fullName>
        <label>Attention Line</label>
        <length>100</length>
        <type>Text</type>
    </CustomField>

force-app/main/default/objects/Contact/fields/Delivery_Instructions__c.field-meta.xml
<CustomField>
        <fullName>Delivery_Instructions__c</fullName>
        <label>Delivery Instructions</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </CustomField>

force-app/main/default/objects/Delivery_Schedule__c/Delivery_Schedule__c.object-meta.xml
<CustomObject>
    <description>Deliver Schedules control the address and which days a publication will be delivered as part of the press run.</description>
    <label>Delivery Schedule</label>
    <nameField>
        <displayFormat>DS-{0}</displayFormat>
        <label>Delivery Schedule Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Delivery Schedules</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Delivery_Schedule__c/fields/Day_Friday__c.field-meta.xml
<CustomField>
        <fullName>Day_Friday__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Friday</label>
        <type>Checkbox</type>
    </CustomField>

force-app/main/default/objects/Delivery_Schedule__c/fields/Day_Monday__c.field-meta.xml
<CustomField>
        <fullName>Day_Monday__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Monday</label>
        <type>Checkbox</type>
    </CustomField>

force-app/main/default/objects/Delivery_Schedule__c/fields/Day_Saturday__c.field-meta.xml
<CustomField>
        <fullName>Day_Saturday__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Saturday</label>
        <type>Checkbox</type>
    </CustomField>

force-app/main/default/objects/Delivery_Schedule__c/fields/Day_Sunday__c.field-meta.xml
<CustomField>
        <fullName>Day_Sunday__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Sunday</label>
        <type>Checkbox</type>
    </CustomField>

force-app/main/default/objects/Delivery_Schedule__c/fields/Day_Thursday__c.field-meta.xml
<CustomField>
        <fullName>Day_Thursday__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Thursday</label>
        <type>Checkbox</type>
    </CustomField>

force-app/main/default/objects/Delivery_Schedule__c/fields/Day_Tuesday__c.field-meta.xml
<CustomField>
        <fullName>Day_Tuesday__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Tuesday</label>
        <type>Checkbox</type>
    </CustomField>

force-app/main/default/objects/Delivery_Schedule__c/fields/Day_Wednesday__c.field-meta.xml
<CustomField>
        <fullName>Day_Wednesday__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Wednesday</label>
        <type>Checkbox</type>
    </CustomField>

force-app/main/default/objects/Delivery_Schedule__c/fields/Delivery_Instructions__c.field-meta.xml
<CustomField>
        <fullName>Delivery_Instructions__c</fullName>
        <label>Delivery Instructions</label>
        <length>200</length>
        <type>Text</type>
    </CustomField>

force-app/main/default/objects/Delivery_Schedule__c/fields/End_Date__c.field-meta.xml
<CustomField>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </CustomField>

force-app/main/default/objects/Delivery_Schedule__c/fields/Offer_Product__c.field-meta.xml
<CustomField>
        <fullName>Offer_Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Offer Product</label>
        <referenceTo>Offer_Product__c</referenceTo>
        <relationshipLabel>Delivery Schedules</relationshipLabel>
        <relationshipName>Delivery_Schedules</relationshipName>
        <type>Lookup</type>
    </CustomField>

force-app/main/default/objects/Delivery_Schedule__c/fields/Start_Date__c.field-meta.xml
<CustomField>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </CustomField>

force-app/main/default/objects/Delivery_Schedule__c/fields/subscription_Subscription__c.field-meta.xml
<CustomField>
        <fullName>subscription_Subscription__c</fullName>
        <description>This fields lookups to the shadow object, Subscription</description>
        <label>Subscription</label>
        <referenceTo>Subscription__c</referenceTo>
        <relationshipLabel>Delivery Schedules</relationshipLabel>
        <relationshipName>Delivery_Schedules</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </CustomField>

force-app/main/default/objects/Offer__c/Offer__c.object-meta.xml
<CustomObject>
    <description>Controls price, delivery, term for a subscription including print, digital and alternate publications. Also holds links to the premiums offered and the campaigns which will utilize this offer.</description>
    <label>Offer</label>
    <nameField>
        <label>Offer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Offers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Offer__c/fields/End_Date__c.field-meta.xml
<CustomField>
        <fullName>End_Date__c</fullName>
        <description>Stores the end date of the offer</description>
        <label>End Date</label>
        <type>Date</type>
    </CustomField>

force-app/main/default/objects/Offer__c/fields/Per_Copy__c.field-meta.xml
<CustomField>
        <fullName>Per_Copy__c</fullName>
        <label>Per Copy</label>
        <precision>18</precision>
        <scale>4</scale>
        <type>Currency</type>
    </CustomField>

force-app/main/default/objects/Offer__c/fields/Start_Date__c.field-meta.xml
<CustomField>
        <fullName>Start_Date__c</fullName>
        <description>Stores the start date for this offer</description>
        <label>Start Date</label>
        <type>Date</type>
    </CustomField>

force-app/main/default/objects/Offer_Product__c/Offer_Product__c.object-meta.xml
<CustomObject>
    <label>Offer Product</label>
    <nameField>
        <label>Offer Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Offer Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Offer_Product__c/fields/Code__c.field-meta.xml
<CustomField>
        <fullName>Code__c</fullName>
        <formula>Product__r.ProductCode</formula>
        <label>Code</label>
        <type>Text</type>
    </CustomField>

force-app/main/default/objects/Offer_Product__c/fields/Number_of_Weeks__c.field-meta.xml
<CustomField>
        <fullName>Number_of_Weeks__c</fullName>
        <label>Number of Weeks</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </CustomField>

force-app/main/default/objects/Offer_Product__c/fields/Offer__c.field-meta.xml
<CustomField>
        <fullName>Offer__c</fullName>
        <label>Offer</label>
        <referenceTo>Offer__c</referenceTo>
        <relationshipLabel>Offer Products</relationshipLabel>
        <relationshipName>Offer_Products</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </CustomField>

force-app/main/default/objects/Offer_Product__c/fields/Per_Copy_Sunday__c.field-meta.xml
<CustomField>
        <fullName>Per_Copy_Sunday__c</fullName>
        <label>Per Copy Sunday</label>
        <precision>18</precision>
        <scale>4</scale>
        <type>Currency</type>
    </CustomField>

force-app/main/default/objects/Offer_Product__c/fields/Product__c.field-meta.xml
<CustomField>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Offer Products</relationshipLabel>
        <relationshipName>Offer_Products</relationshipName>
        <type>Lookup</type>
    </CustomField>

force-app/main/default/objects/Product2/fields/Code__c.field-meta.xml
<CustomField>
        <fullName>Code__c</fullName>
        <label>Code</label>
        <length>50</length>
        <type>Text</type>
    </CustomField>

force-app/main/default/objects/Product2/fields/IsDigital__c.field-meta.xml
<CustomField>
        <fullName>IsDigital__c</fullName>
        <defaultValue>false</defaultValue>
        <label>IsDigital</label>
        <type>Checkbox</type>
    </CustomField>

force-app/main/default/objects/Subscription__c/Subscription__c.object-meta.xml
<CustomObject>
    <description>This object stores the actual subscription details, including selected Offer, Premiums. Delivery Schedules, frequency and term.</description>
    <label>Subscription</label>
    <nameField>
        <displayFormat>Sub-{0000}</displayFormat>
        <label>Subscription Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Subscription__c/fields/Attention_Line__c.field-meta.xml
<CustomField>
        <fullName>Attention_Line__c</fullName>
        <label>Attention Line</label>
        <length>100</length>
        <type>Text</type>
    </CustomField>

force-app/main/default/objects/Subscription__c/fields/Delivery_Instructions__c.field-meta.xml
<CustomField>
        <fullName>Delivery_Instructions__c</fullName>
        <label>Delivery Instructions</label>
        <type>TextArea</type>
    </CustomField>

force-app/main/default/objects/Subscription__c/fields/Delivery_Schedule__c.field-meta.xml
<CustomField>
        <fullName>Delivery_Schedule__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Stores the relationship between Subscriptions and Delivery Schedule</description>
        <label>Delivery Schedule</label>
        <referenceTo>Delivery_Schedule__c</referenceTo>
        <relationshipLabel>Subscriptions</relationshipLabel>
        <relationshipName>Subscriptions</relationshipName>
        <type>Lookup</type>
    </CustomField>

force-app/main/default/objects/Subscription__c/fields/Outstanding_Credit__c.field-meta.xml
<CustomField>
        <fullName>Outstanding_Credit__c</fullName>
        <label>Today's Balance</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </CustomField>

force-app/main/default/objects/Subscription__c/fields/subscription_Account__c.field-meta.xml
<CustomField>
        <fullName>subscription_Account__c</fullName>
        <description>Relationship between Account and Subscriptions</description>
        <label>Household Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Subscriptions</relationshipLabel>
        <relationshipName>Subscriptions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </CustomField>

force-app/main/default/objects/Subscription__c/fields/subscription_Offer__c.field-meta.xml
<CustomField>
        <fullName>subscription_Offer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Stores the relationship to Offer</description>
        <label>Offer</label>
        <referenceTo>Offer__c</referenceTo>
        <relationshipLabel>Subscriptions</relationshipLabel>
        <relationshipName>Subscriptions1</relationshipName>
        <type>Lookup</type>
    </CustomField>

force-app/main/default/objects/Subscription__c/fields/subscription_Status__c.field-meta.xml
<CustomField>
        <fullName>subscription_Status__c</fullName>
        <description>Stores the status of the subscription</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>New</fullName>
                </value>
                <value>
                    <fullName>TERMINATED</fullName>
                </value>
                <value>
                    <fullName>INACTIVE</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </CustomField>

force-app/main/default/objects/Transaction_Type__c/Transaction_Type__c.object-meta.xml
<CustomObject>
    <label>Transaction Type</label>
    <nameField>
        <label>Transaction Type Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Transaction Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Transaction_Type__c/fields/Code__c.field-meta.xml
<CustomField>
        <fullName>Code__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <inlineHelpText>Matches DSI Code</inlineHelpText>
        <label>Code</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </CustomField>

force-app/main/default/classes/DeliveryServiceIssueControllerTest.cls
@isTest
private class DeliveryServiceIssueControllerTest {
    @isTest static void shouldValidateDeliveryDate(){

                List<Product2> lstPub = new List<Product2>();
        List<Offer__c> lstOffer = new List<Offer__c>();
        List<Offer_Product__c> lstOffProd = new List<Offer_Product__c>();
		//
		// Create Foundational Records
		//
		for(Integer i = 0; i<4; i++){
			Product2 pub = new Product2();
			if(i == 0){
				pub.Name = 'Philadelphia Inquirer';
				pub.ProductCode = '1';
				pub.IsDigital__c = false;

			}
			if(i == 1){
				pub.Name = 'Daily News';
				pub.ProductCode = '2';
				pub.IsDigital__c = false;
			}
			if(i == 2){
				pub.Name = 'Meter All Digital Add On';
				pub.ProductCode = '50';
				pub.IsDigital__c = true;
			}
			if(i == 3){
				pub.Name = 'All Digital Metered';
				pub.ProductCode = '150';
				pub.IsDigital__c = true;
			}
			lstPub.add(pub);
		}
		insert lstPub;

		for(Integer i = 0; i<3; i++){
			Offer__c off = new Offer__c();
			off.Name = 'Test ' + i;
			off.Number_of_Weeks__c = i*4;
			lstOffer.add(off);
            insert lstOffer;
			lstOffProd = new List<Offer_Product__c>();
			for(Integer x = 0; i<2; i++){
				Offer_Product__c op = new Offer_Product__c();
				if(x == 0){
					op.Product__c = lstPub[0].Id;
					op.Per_Copy__c = .50;
					op.Per_Copy_Sunday__c = 1.5;
					op.Offer__c = off.Id;
				}
				if(x == 1){
					op.Product__c = lstPub[2].Id;
					op.Per_Copy__c = .50;
					op.Per_Copy_Sunday__c = 1.5;
					op.Offer__c = off.Id;
				}
				lstOffProd.add(op);
			}
		}
		
		insert lstOffProd;

        Account account = new Account(
            Name = 'RelationEdge');
        insert account;
        Subscription__c subscription = new Subscription__c(
            subscription_Account__c = account.Id,
            Attention_Line__c = 'RelationEdge',
            Delivery_Instructions__c = 'Throw it at the front door.',
            Outstanding_Credit__c = 20.25,
            subscription_Status__c = 'Active',
            subscription_Offer__c = lstOffProd[0].Offer__c
        );
        Case caseToInsert = new Case();
        caseToInsert.AccountId = account.Id;
        insert caseToInsert;
        insert subscription;


        Transaction_Type__c tt = new Transaction_Type__c();
        tt.Name = 'Redelivery Today\'s Missing Newspaper';
        insert tt;
        Transaction_Type__c tt2 = new Transaction_Type__c();
        tt2.Name = 'Replace Wet Newspaper';
        insert tt2;
        Transaction_Type__c tt3 = new Transaction_Type__c();
        tt3.Name = 'Replaced Damaged Paper';
        insert tt3;
        Transaction_Type__c tt4 = new Transaction_Type__c();
        tt4.Name = 'Credit for Missed Newspaper';
        insert tt4;
        Transaction_Type__c tt5 = new Transaction_Type__c();
        tt5.Name = 'Credit for Wet Newspaper';
        insert tt5;
        Transaction_Type__c tt6 = new Transaction_Type__c();
        tt6.Name = 'Credit for Damaged';
        insert tt6;
        Delivery_Schedule__c schedule = new Delivery_Schedule__c(
            subscription_Subscription__c = subscription.Id,
            Start_Date__c = date.newInstance(2019, 1, 1),
            End_Date__c = date.newInstance(2019, 1, 7),
            Day_Wednesday__c = true,
            Day_Tuesday__c = true,
            Day_Monday__c = true,
            Day_Sunday__c = true,
            Day_Thursday__c = true,
            Day_Friday__c = true,
            Day_Saturday__c = true
        );
        insert schedule;
        List<String> stringDates = new List<String>();
        for(integer i = 1; i < 7; ++i){
            DeliveryServiceIssueController.validateDeliveryDate(subscription.Id, '2019-1-' + i);
        }
        DeliveryServiceIssueController.fetchOfferProducts(subscription.Id);
        DeliveryServiceIssueController.getSubscriptionId('Account', account.Id);
        DeliveryServiceIssueController.getLatestExpireDate(subscription.Id, '2019-1-30');
        DeliveryServiceIssueController.createDeliveryIssue(subscription.Id, 'Damaged Paper', 'Credit', Date.today());

    }

    @isTest static void shouldRedeliveryCommunity(){
        TestDataFactory.createTestRecords(3);
        Date currentDate = Date.today();
		DateTime transDateDT = DateTime.newInstance(currentDate.year(), currentDate.month(), currentDate.day(), 12, 0, 0);
        
       Account a = new Account(Name='Test Account Name');
        insert a;
        
        Contact c = new Contact(LastName = 'Contact Last Name', AccountId = a.id);
        insert c;
        
        User user = new User();
        user.ProfileID = [Select Id From Profile Where Name='Subscriber Community'].id;
        user.EmailEncodingKey = 'ISO-8859-1';
        user.LanguageLocaleKey = 'en_US';
        user.TimeZoneSidKey = 'America/New_York';
        user.LocaleSidKey = 'en_US';
        user.FirstName = 'first';
        user.LastName = 'last';
        user.Username = 'test@test.com';   
        user.CommunityNickname = 'testUser123';
        user.Alias = 't1';
        user.Email = 'no@email.com';
        user.IsActive = true;
        user.ContactId = c.Id;
        
        insert user;
        //system.runAs(user) {
            List<Subscription__c> subscriptions = [SELECT Id FROM Subscription__c];
            List<Offer_Product__c> offProducts = [SELECT Id FROM Offer_Product__c LIMIT 3];
            List<Id> offerProductIds = new List<Id>();
            for(Offer_Product__c offProduct :DeliveryServiceIssueController.fetchOfferProducts(subscriptions[0].Id)){
                offerProductIds.add(offProduct.Id);
            }
            Transaction_Type__c transType = [
                SELECT Id 
                FROM Transaction_Type__c 
                WHERE Code__c = 'DD' LIMIT 1
            ];
            CutOffManager.communityDeliveryHelper(transType.Id, currentDate);
            DeliveryServiceIssueController.InsertTransaction(subscriptions[0].Id, transType.Id, 'ServiceIssue', 'Request', '2020-1-20',  offerProductIds, 'memo');
            List<Transaction_Type__c> result = DeliveryServiceIssueController.getDeliveryIssueList('2020-1-20');
        }       
    //}   
}