force-app/main/default/objects/Case/fields/Subscription__c.field-meta.xml
<CustomField>
        <fullName>Subscription__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Subscription</label>
        <referenceTo>Subscription__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </CustomField>

force-app/main/default/objects/Cut_Offs_Time__mdt/Cut_Offs_Time__mdt.object-meta.xml
<CustomObject>
    <label>Cut-Offs Time</label>
    <pluralLabel>Cut Off Times</pluralLabel>
</CustomObject>

force-app/main/default/objects/Cut_Offs_Time__mdt/fields/Cut_Off_Type__c.field-meta.xml
<CustomField>
        <fullName>Cut_Off_Type__c</fullName>
        <description>Type of deadline</description>
        <label>Cut Off Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Re-delivery</fullName>
                    <default>true</default>
                    <label>Re-delivery</label>
                </value>
                <value>
                    <fullName>Press Run</fullName>
                </value>
                <value>
                    <fullName>Carrier Memo</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </CustomField>

force-app/main/default/objects/Cut_Offs_Time__mdt/fields/Day_of_Week__c.field-meta.xml
<CustomField>
        <fullName>Day_of_Week__c</fullName>
        <description>Day of the week for the cut-off</description>
        <label>Day of Week</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Sunday</fullName>
                    <default>true</default>
                    <label>Sunday</label>
                </value>
                <value>
                    <fullName>Monday</fullName>
                </value>
                <value>
                    <fullName>Tuesday</fullName>
                </value>
                <value>
                    <fullName>Wednesday</fullName>
                </value>
                <value>
                    <fullName>Thursday</fullName>
                </value>
                <value>
                    <fullName>Friday</fullName>
                </value>
                <value>
                    <fullName>Saturday</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </CustomField>

force-app/main/default/objects/Cut_Offs_Time__mdt/fields/Hour__c.field-meta.xml
<CustomField>
        <fullName>Hour__c</fullName>
        <description>Hour of deadline</description>
        <label>Hour</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </CustomField>

force-app/main/default/objects/Cut_Offs_Time__mdt/fields/Minute__c.field-meta.xml
<CustomField>
        <fullName>Minute__c</fullName>
        <description>Minute of deadline</description>
        <label>Minute</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </CustomField>

force-app/main/default/objects/Delivery_Schedule__c/Delivery_Schedule__c.object-meta.xml
<CustomObject>
    <description>Deliver Schedules control the address and which days a publication will be delivered as part of the press run.</description>
    <label>Delivery Schedule</label>
    <nameField>
        <displayFormat>DS-{0}</displayFormat>
        <label>Delivery Schedule Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Delivery Schedules</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Delivery_Schedule__c/fields/Day_Friday__c.field-meta.xml
<CustomField>
        <fullName>Day_Friday__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Friday</label>
        <type>Checkbox</type>
    </CustomField>

force-app/main/default/objects/Delivery_Schedule__c/fields/Day_Monday__c.field-meta.xml
<CustomField>
        <fullName>Day_Monday__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Monday</label>
        <type>Checkbox</type>
    </CustomField>

force-app/main/default/objects/Delivery_Schedule__c/fields/Day_Saturday__c.field-meta.xml
<CustomField>
        <fullName>Day_Saturday__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Saturday</label>
        <type>Checkbox</type>
    </CustomField>

force-app/main/default/objects/Delivery_Schedule__c/fields/Day_Sunday__c.field-meta.xml
<CustomField>
        <fullName>Day_Sunday__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Sunday</label>
        <type>Checkbox</type>
    </CustomField>

force-app/main/default/objects/Delivery_Schedule__c/fields/Day_Thursday__c.field-meta.xml
<CustomField>
        <fullName>Day_Thursday__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Thursday</label>
        <type>Checkbox</type>
    </CustomField>

force-app/main/default/objects/Delivery_Schedule__c/fields/Day_Tuesday__c.field-meta.xml
<CustomField>
        <fullName>Day_Tuesday__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Tuesday</label>
        <type>Checkbox</type>
    </CustomField>

force-app/main/default/objects/Delivery_Schedule__c/fields/Day_Wednesday__c.field-meta.xml
<CustomField>
        <fullName>Day_Wednesday__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Wednesday</label>
        <type>Checkbox</type>
    </CustomField>

force-app/main/default/objects/Delivery_Schedule__c/fields/End_Date__c.field-meta.xml
<CustomField>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </CustomField>

force-app/main/default/objects/Delivery_Schedule__c/fields/Routelookup__c.field-meta.xml
<CustomField>
        <fullName>Routelookup__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Route</label>
        <referenceTo>Route__c</referenceTo>
        <relationshipLabel>Delivery Schedules</relationshipLabel>
        <relationshipName>Delivery_Schedules</relationshipName>
        <type>Lookup</type>
    </CustomField>

force-app/main/default/objects/Delivery_Schedule__c/fields/Start_Date__c.field-meta.xml
<CustomField>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </CustomField>

force-app/main/default/objects/Delivery_Schedule__c/fields/subscription_Subscription__c.field-meta.xml
<CustomField>
        <fullName>subscription_Subscription__c</fullName>
        <description>This fields lookups to the shadow object, Subscription</description>
        <label>Subscription</label>
        <referenceTo>Subscription__c</referenceTo>
        <relationshipLabel>Delivery Schedules</relationshipLabel>
        <relationshipName>Delivery_Schedules</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </CustomField>

force-app/main/default/objects/Route__c/Route__c.object-meta.xml
<CustomObject>
    <label>Route</label>
    <nameField>
        <label>Route Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Route</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Route__c/fields/Redelivery_Allowed__c.field-meta.xml
<CustomField>
        <fullName>Redelivery_Allowed__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Redelivery Allowed</label>
        <type>Checkbox</type>
    </CustomField>

force-app/main/default/objects/Route__c/fields/Route_Id__c.field-meta.xml
<CustomField>
        <fullName>Route_Id__c</fullName>
        <caseSensitive>true</caseSensitive>
        <description>Unique Id from DSI used for record matching</description>
        <externalId>true</externalId>
        <label>Route Id</label>
        <length>20</length>
        <type>Text</type>
        <unique>true</unique>
    </CustomField>

force-app/main/default/objects/Route_Delay__c/Route_Delay__c.object-meta.xml
<CustomObject>
    <label>Route Delay</label>
    <nameField>
        <displayFormat>Delay{0000}</displayFormat>
        <label>Delay Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Route Delays</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Route_Delay__c/fields/Date_From__c.field-meta.xml
<CustomField>
        <fullName>Date_From__c</fullName>
        <label>Date From</label>
        <type>DateTime</type>
    </CustomField>

force-app/main/default/objects/Route_Delay__c/fields/Date_Until__c.field-meta.xml
<CustomField>
        <fullName>Date_Until__c</fullName>
        <label>Date Until</label>
        <type>Date</type>
    </CustomField>

force-app/main/default/objects/Route_Delay__c/fields/District_From__c.field-meta.xml
<CustomField>
        <fullName>District_From__c</fullName>
        <label>District From</label>
        <length>3</length>
        <type>Text</type>
    </CustomField>

force-app/main/default/objects/Route_Delay__c/fields/District_Until__c.field-meta.xml
<CustomField>
        <fullName>District_Until__c</fullName>
        <label>District Until</label>
        <length>3</length>
        <type>Text</type>
    </CustomField>

force-app/main/default/objects/Route_Delay__c/fields/Route_From__c.field-meta.xml
<CustomField>
        <fullName>Route_From__c</fullName>
        <label>Route From</label>
        <length>15</length>
        <type>Text</type>
    </CustomField>

force-app/main/default/objects/Route_Delay__c/fields/Route_Until__c.field-meta.xml
<CustomField>
        <fullName>Route_Until__c</fullName>
        <label>Route Until</label>
        <length>8</length>
        <type>Text</type>
    </CustomField>

force-app/main/default/objects/Subscription__c/Subscription__c.object-meta.xml
<CustomObject>
    <description>This object stores the actual subscription details, including selected Offer, Premiums. Delivery Schedules, frequency and term.</description>
    <label>Subscription</label>
    <nameField>
        <displayFormat>Sub-{0000}</displayFormat>
        <label>Subscription Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Subscription__c/fields/Delivery_Schedule__c.field-meta.xml
<CustomField>
        <fullName>Delivery_Schedule__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Stores the relationship between Subscriptions and Delivery Schedule</description>
        <label>Delivery Schedule</label>
        <referenceTo>Delivery_Schedule__c</referenceTo>
        <relationshipLabel>Subscriptions</relationshipLabel>
        <relationshipName>Subscriptions</relationshipName>
        <type>Lookup</type>
    </CustomField>

force-app/main/default/objects/Subscription__c/fields/subscription_Account__c.field-meta.xml
<CustomField>
        <fullName>subscription_Account__c</fullName>
        <description>Relationship between Account and Subscriptions</description>
        <label>Household Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Subscriptions</relationshipLabel>
        <relationshipName>Subscriptions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </CustomField>

force-app/main/default/objects/Subscription__c/fields/subscription_Status__c.field-meta.xml
<CustomField>
        <fullName>subscription_Status__c</fullName>
        <description>Stores the status of the subscription</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>New</fullName>
                </value>
                <value>
                    <fullName>TERMINATED</fullName>
                </value>
                <value>
                    <fullName>INACTIVE</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </CustomField>

force-app/main/default/objects/Transaction_Log__c/Transaction_Log__c.object-meta.xml
<CustomObject>
    <label>Transaction Log</label>
    <nameField>
        <displayFormat>TL-{0000}</displayFormat>
        <label>Transaction Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transaction Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Transaction_Log__c/fields/Subscription__c.field-meta.xml
<CustomField>
        <fullName>Subscription__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Subscription</label>
        <referenceTo>Subscription__c</referenceTo>
        <relationshipLabel>Transaction Logs</relationshipLabel>
        <relationshipName>Transaction_Logs</relationshipName>
        <type>Lookup</type>
    </CustomField>

force-app/main/default/classes/DeliverySchedule.cls
public class DeliverySchedule {
    public Delivery_Schedule__c schedule;

    private static String todaysDayOfWeek = System.now().format('EEEE');

    public DeliverySchedule(Delivery_Schedule__c schedule) {
        this.schedule = schedule;
    }

    public String getTodayCutoffTime() {
        if (isScheduledForToday()) {
            // Redelivery Cutoff Time
            List<Cut_Offs_Time__mdt> times = [SELECT Hour__c, Minute__c FROM Cut_Offs_Time__mdt 
                                              WHERE Day_of_Week__c = :todaysDayOfWeek AND Cut_Off_Type__c = 'Re-delivery' LIMIT 1];
            if (!times.isEmpty()) {
                // converting to integer first, then converting to string before return below
                Integer intHour = Integer.valueOf(times[0].Hour__c);
                Integer intMins = Integer.valueOf(times[0].Minute__c);

                return String.valueOf(intHour).leftPad(2, '0') + ':' + String.valueOf(intMins).leftPad(2, '0');
            }
        }
        return '';
    }

    public Boolean isScheduledForToday() {
        return schedule.Day_Sunday__c && todaysDayOfWeek == 'Sunday' ||
            schedule.Day_Monday__c && todaysDayOfWeek == 'Monday' ||
            schedule.Day_Tuesday__c && todaysDayOfWeek == 'Tuesday' ||
            schedule.Day_Wednesday__c && todaysDayOfWeek == 'Wednesday' ||
            schedule.Day_Thursday__c && todaysDayOfWeek == 'Thursday' ||
            schedule.Day_Friday__c && todaysDayOfWeek == 'Friday' ||
            schedule.Day_Saturday__c && todaysDayOfWeek == 'Saturday';
    }

    public Boolean isRedeliveryAllowed() {
        return schedule.Routelookup__r.Redelivery_Allowed__c;
    }

    public String getScheduleForWeek() {
        String scheduleForWeek = '';
        scheduleForWeek += (schedule.Day_Sunday__c) ? 'Y' : 'N';
        scheduleForWeek += (schedule.Day_Monday__c) ? 'Y' : 'N';
        scheduleForWeek += (schedule.Day_Tuesday__c) ? 'Y' : 'N';
        scheduleForWeek += (schedule.Day_Wednesday__c) ? 'Y' : 'N';
        scheduleForWeek += (schedule.Day_Thursday__c) ? 'Y' : 'N';
        scheduleForWeek += (schedule.Day_Friday__c) ? 'Y' : 'N';
        scheduleForWeek += (schedule.Day_Saturday__c) ? 'Y' : 'N';
        return scheduleForWeek;
    }

    public Boolean hasEscalatedCases() {
        List<Case> escalatedCases = [SELECT Id FROM Case WHERE Subscription__c = :schedule.subscription_Subscription__c AND Status = 'Escalated' AND IsEscalated = TRUE];
        return !escalatedCases.isEmpty();
    }

    public Transaction_Log__c getLastestComplaint() {
        List<Transaction_Log__c> lastComplaints = TransactionDataAccessor.getLatestComplaintTransactions(schedule.subscription_Subscription__r.subscription_Account__c, 1);
        if (!lastComplaints.isEmpty()) {
            return lastComplaints[0];
        }
        return null;
    }

    public static List<Delivery_Schedule__c> getCurrentDayDeliverySchedule(String accountId, String routeId) {
        String baseQuery = 'SELECT Id, Routelookup__r.Route_Id__c FROM Delivery_Schedule__c';
        String identifier = (String.isNotEmpty(routeId)) ? 'Routelookup__c = :routeId' : 'subscription_Subscription__r.subscription_Account__c = :accountId';
        String isSubActive = 'subscription_Subscription__r.subscription_Status__c = \'Active\'';
        String isDSactive = 'Start_Date__c <= TODAY AND End_Date__c >= TODAY'; 
        String todaysFieldIsTrue = 'Day_' + todaysDayOfWeek + '__c' + ' = TRUE';
        return Database.query(String.join(new List<String>{baseQuery, 'WHERE', identifier, 'AND', isSubActive, 'AND', isDSactive, 'AND', todaysFieldIsTrue}, ' '));
    }

    public Boolean hasRouteDelayRec() {
        List<Route_Delay__c> RtDelayList = [SELECT Id, Date_From__c,Date_Until__c,District_From__c,District_Until__c,Route_From__c,Route_Until__c 
                                            FROM Route_Delay__c
                                            WHERE Date_From__c <= TODAY AND Date_Until__c >= TODAY
                                            ORDER BY LastModifiedDate DESC];
        return !RtDelayList.isEmpty();
    }

    public Boolean hasRouteNumInRange() {
        system.debug('==rtNumber: ' + schedule.Routelookup__r.Route_Id__c);
         List<Route_Delay__c> RtDelayByRouteNum = [SELECT Id, Date_From__c,Date_Until__c,Route_From__c,Route_Until__c 
                                                FROM Route_Delay__c
                                                WHERE (Route_From__c <= :schedule.Routelookup__r.Route_Id__c AND Route_Until__c >= :schedule.Routelookup__r.Route_Id__c)
                                                AND (Date_From__c <= TODAY AND Date_Until__c >= TODAY)];
        return !RtDelayByRouteNum.isEmpty();
    }
}