force-app/main/default/objects/Case/fields/Subscription__c.field-meta.xml
<CustomField>
        <fullName>Subscription__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Subscription</label>
        <referenceTo>Subscription__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </CustomField>

force-app/main/default/objects/Delivery_Schedule__c/Delivery_Schedule__c.object-meta.xml
<CustomObject>
    <description>Deliver Schedules control the address and which days a publication will be delivered as part of the press run.</description>
    <label>Delivery Schedule</label>
    <nameField>
        <displayFormat>DS-{0}</displayFormat>
        <label>Delivery Schedule Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Delivery Schedules</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Delivery_Schedule__c/fields/Day_Friday__c.field-meta.xml
<CustomField>
        <fullName>Day_Friday__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Friday</label>
        <type>Checkbox</type>
    </CustomField>

force-app/main/default/objects/Delivery_Schedule__c/fields/Day_Monday__c.field-meta.xml
<CustomField>
        <fullName>Day_Monday__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Monday</label>
        <type>Checkbox</type>
    </CustomField>

force-app/main/default/objects/Delivery_Schedule__c/fields/Day_Saturday__c.field-meta.xml
<CustomField>
        <fullName>Day_Saturday__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Saturday</label>
        <type>Checkbox</type>
    </CustomField>

force-app/main/default/objects/Delivery_Schedule__c/fields/Day_Sunday__c.field-meta.xml
<CustomField>
        <fullName>Day_Sunday__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Sunday</label>
        <type>Checkbox</type>
    </CustomField>

force-app/main/default/objects/Delivery_Schedule__c/fields/Day_Thursday__c.field-meta.xml
<CustomField>
        <fullName>Day_Thursday__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Thursday</label>
        <type>Checkbox</type>
    </CustomField>

force-app/main/default/objects/Delivery_Schedule__c/fields/Day_Tuesday__c.field-meta.xml
<CustomField>
        <fullName>Day_Tuesday__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Tuesday</label>
        <type>Checkbox</type>
    </CustomField>

force-app/main/default/objects/Delivery_Schedule__c/fields/Day_Wednesday__c.field-meta.xml
<CustomField>
        <fullName>Day_Wednesday__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Wednesday</label>
        <type>Checkbox</type>
    </CustomField>

force-app/main/default/objects/Delivery_Schedule__c/fields/District__c.field-meta.xml
<CustomField>
        <fullName>District__c</fullName>
        <label>District</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>105</fullName>
                </value>
                <value>
                    <fullName>108</fullName>
                </value>
                <value>
                    <fullName>110</fullName>
                </value>
                <value>
                    <fullName>111</fullName>
                </value>
                <value>
                    <fullName>112</fullName>
                </value>
                <value>
                    <fullName>113</fullName>
                </value>
                <value>
                    <fullName>114</fullName>
                </value>
                <value>
                    <fullName>117</fullName>
                </value>
                <value>
                    <fullName>118</fullName>
                </value>
                <value>
                    <fullName>119</fullName>
                </value>
                <value>
                    <fullName>121</fullName>
                </value>
                <value>
                    <fullName>127</fullName>
                </value>
                <value>
                    <fullName>148</fullName>
                </value>
                <value>
                    <fullName>218</fullName>
                </value>
                <value>
                    <fullName>245</fullName>
                </value>
                <value>
                    <fullName>252</fullName>
                </value>
                <value>
                    <fullName>255</fullName>
                </value>
                <value>
                    <fullName>366</fullName>
                </value>
                <value>
                    <fullName>367</fullName>
                </value>
                <value>
                    <fullName>368</fullName>
                </value>
                <value>
                    <fullName>392</fullName>
                </value>
                <value>
                    <fullName>399</fullName>
                </value>
                <value>
                    <fullName>492</fullName>
                </value>
                <value>
                    <fullName>495</fullName>
                </value>
                <value>
                    <fullName>499</fullName>
                </value>
                <value>
                    <fullName>593</fullName>
                </value>
                <value>
                    <fullName>608</fullName>
                </value>
                <value>
                    <fullName>609</fullName>
                </value>
                <value>
                    <fullName>612</fullName>
                </value>
                <value>
                    <fullName>613</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </CustomField>

force-app/main/default/objects/Delivery_Schedule__c/fields/Offer_Product__c.field-meta.xml
<CustomField>
        <fullName>Offer_Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Offer Product</label>
        <referenceTo>Offer_Product__c</referenceTo>
        <relationshipLabel>Delivery Schedules</relationshipLabel>
        <relationshipName>Delivery_Schedules</relationshipName>
        <type>Lookup</type>
    </CustomField>

force-app/main/default/objects/Delivery_Schedule__c/fields/Routelookup__c.field-meta.xml
<CustomField>
        <fullName>Routelookup__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Route</label>
        <referenceTo>Route__c</referenceTo>
        <relationshipLabel>Delivery Schedules</relationshipLabel>
        <relationshipName>Delivery_Schedules</relationshipName>
        <type>Lookup</type>
    </CustomField>

force-app/main/default/objects/Offer_Product__c/Offer_Product__c.object-meta.xml
<CustomObject>
    <label>Offer Product</label>
    <nameField>
        <label>Offer Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Offer Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Offer_Product__c/fields/Amount__c.field-meta.xml
<CustomField>
        <fullName>Amount__c</fullName>
        <formula>Per_Copy__c *  Number_of_totals_day__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </CustomField>

force-app/main/default/objects/Offer_Product__c/fields/Is_Digital__c.field-meta.xml
<CustomField>
        <fullName>Is_Digital__c</fullName>
        <formula>Product__r.IsDigital__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Is Digital</label>
        <type>Checkbox</type>
    </CustomField>

force-app/main/default/objects/Offer_Product__c/fields/Term__c.field-meta.xml
<CustomField>
        <fullName>Term__c</fullName>
        <formula>Offer__r.Number_of_Weeks__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Term (weeks)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </CustomField>

force-app/main/default/objects/Route__c/Route__c.object-meta.xml
<CustomObject>
    <label>Route</label>
    <nameField>
        <label>Route Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Route</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Route__c/fields/District__c.field-meta.xml
<CustomField>
        <fullName>District__c</fullName>
        <label>District</label>
        <length>25</length>
        <type>Text</type>
    </CustomField>

force-app/main/default/objects/Subscription__c/Subscription__c.object-meta.xml
<CustomObject>
    <description>This object stores the actual subscription details, including selected Offer, Premiums. Delivery Schedules, frequency and term.</description>
    <label>Subscription</label>
    <nameField>
        <displayFormat>Sub-{0000}</displayFormat>
        <label>Subscription Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Subscription__c/fields/Delivery_Schedule__c.field-meta.xml
<CustomField>
        <fullName>Delivery_Schedule__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Stores the relationship between Subscriptions and Delivery Schedule</description>
        <label>Delivery Schedule</label>
        <referenceTo>Delivery_Schedule__c</referenceTo>
        <relationshipLabel>Subscriptions</relationshipLabel>
        <relationshipName>Subscriptions</relationshipName>
        <type>Lookup</type>
    </CustomField>

force-app/main/default/objects/Subscription__c/fields/subscription_Auto_Renew__c.field-meta.xml
<CustomField>
        <fullName>subscription_Auto_Renew__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Controls Auto Renew of Subscription</description>
        <inlineHelpText>If true, this denotes that the subscription is on EZ-pay</inlineHelpText>
        <label>Auto Renew</label>
        <type>Checkbox</type>
    </CustomField>

force-app/main/default/objects/Subscription__c/fields/subscription_Current_Period_Ends_At__c.field-meta.xml
<CustomField>
        <fullName>subscription_Current_Period_Ends_At__c</fullName>
        <description>Stores the date and time when the current subscription ends</description>
        <inlineHelpText>See the "Expires On" field below to see End date + Grace Days</inlineHelpText>
        <label>End Date</label>
        <type>Date</type>
    </CustomField>

force-app/main/default/objects/Subscription__c/fields/subscription_Status__c.field-meta.xml
<CustomField>
        <fullName>subscription_Status__c</fullName>
        <description>Stores the status of the subscription</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>New</fullName>
                </value>
                <value>
                    <fullName>TERMINATED</fullName>
                </value>
                <value>
                    <fullName>INACTIVE</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </CustomField>

force-app/main/default/objects/Subscription__c/fields/Total_Liability__c.field-meta.xml
<CustomField>
        <fullName>Total_Liability__c</fullName>
        <label>Total Liability</label>
        <precision>8</precision>
        <scale>2</scale>
        <type>Currency</type>
    </CustomField>

force-app/main/default/classes/SubscriptionBilling.cls
public with sharing class SubscriptionBilling {
    public String Status {get;set;}
    public String DeliveryType {get;set;}
    public String Route {get;set;}
    public String District {get;set;}
    public String AutoPay {get;set;}
    public String Publication {get;set;}
    public String ServiceType {get;set;}
    public String LastBillDate {get;set;}
    public Decimal lastBillLen {get;set;}
    public Decimal LastBillAmt {get;set;}
    public String LastBillTerm {get;set;}
    public String LastPayDate {get;set;}
    public String LastPayAmt {get;set;}
    public String Expiration {get;set;}
    public Decimal Balance {get;set;}
    public String BalanceDate {get;set;}

    private transient Subscription subscription;

    public SubscriptionBilling(String subId) {
        this.subscription = new Subscription(subId);
        system.debug('==before initFields: '+ this.subscription);
        initFields();
    }

    private void initFields() {
        setSubscriptionFields();
        setLatestBillFields();
        setLatestJournalFields();
        setCurrentDeliveryScheduleFields();
    }  

    private void setSubscriptionFields() {
        Subscription__c sub = subscription.subscription;
        
        Status = sub.subscription_Status__c;
        AutoPay = sub.subscription_Auto_Renew__c ? 'Y' : 'N';
        Expiration = (sub.subscription_Current_Period_Ends_At__c != null) ? sub.subscription_Current_Period_Ends_At__c.format() : null;
        Balance = sub.Total_Liability__c;
        BalanceDate = Date.today().addDays(-1).format();
    }

    private void setLatestBillFields() {
        if (this.subscription.latestBill != null) {
            LastBillDate = subscription.latestBill.Bill_Date__c.format();
            LastBillLen = subscription.latestBill.Term__c;
            LastBillAmt = subscription.latestBill.Amount__c;
            LastBillTerm = 'Weeks';
        }
    }

    private void setLatestJournalFields() {
        if (subscription.latestJournal != null) {
            // return the latest journal entry date / amount
            LastPayDate = subscription.latestJournal.Entry_Date__c != null ? subscription.latestJournal.Entry_Date__c.format() : '';
            LastPayAmt = subscription.latestJournal.Credit__c != null ? String.valueof(subscription.latestJournal.Credit__c) : '';
        } 
        else if (subscription.latestRecurlyInvoice != null) {
            // return the latest recurly invoice date / amount
            LastPayDate = subscription.latestRecurlyInvoice.recurly_v2__Due_At__c != null ? subscription.latestRecurlyInvoice.recurly_v2__Due_At__c.format('MM/dd/yyyy') : '';
            LastPayAmt  = subscription.latestRecurlyInvoice.recurly_v2__Paid__c != null ? String.valueof(subscription.latestRecurlyInvoice.recurly_v2__Paid__c) : '';
        } else {
            // cover the fallout case
            LastPayDate = '';
            LastPayAmt = '';
        }
    }

    private void setCurrentDeliveryScheduleFields() {
        if (subscription.currentDeliverySchedule != null) {
            Route = subscription.currentDeliverySchedule.schedule.Routelookup__c;
            District = subscription.currentDeliverySchedule.schedule.Routelookup__r.District__c;
            Publication = subscription.currentDeliverySchedule.schedule.Offer_Product__r.Name;
            DeliveryType = subscription.currentDeliverySchedule.schedule.Offer_Product__r.Is_Digital__c ? 'Y' : 'N';
            ServiceType = subscription.currentDeliverySchedule.getScheduleForWeek();
        }
    }

    private String getServiceTypes(Delivery_Schedule__c deliverySchedule) {
        String types = '';
        types += (deliverySchedule.Day_Sunday__c) ? 'Y' : 'N'; 
        types += (deliverySchedule.Day_Monday__c) ? 'Y' : 'N'; 
        types += (deliverySchedule.Day_Tuesday__c) ? 'Y' : 'N'; 
        types += (deliverySchedule.Day_Wednesday__c) ? 'Y' : 'N'; 
        types += (deliverySchedule.Day_Thursday__c) ? 'Y' : 'N'; 
        types += (deliverySchedule.Day_Friday__c) ? 'Y' : 'N'; 
        types += (deliverySchedule.Day_Saturday__c) ? 'Y' : 'N'; 
        return types;
    }
}