force-app/main/default/objects/Campaign_Settings__mdt/Campaign_Settings__mdt.object-meta.xml
<CustomObject>
    <label>Campaign Settings</label>
    <pluralLabel>Campaign Settings</pluralLabel>
</CustomObject>

force-app/main/default/objects/Campaign_Settings__mdt/fields/Campaign_Id__c.field-meta.xml
<CustomField>
        <fullName>Campaign_Id__c</fullName>
        <label>Campaign Id</label>
        <length>20</length>
        <type>Text</type>
    </CustomField>

force-app/main/default/objects/Campaign_Settings__mdt/fields/Campaign_Name__c.field-meta.xml
<CustomField>
        <fullName>Campaign_Name__c</fullName>
        <label>Campaign Name</label>
        <length>200</length>
        <type>Text</type>
    </CustomField>

force-app/main/default/objects/Offer__c/Offer__c.object-meta.xml
<CustomObject>
    <description>Controls price, delivery, term for a subscription including print, digital and alternate publications. Also holds links to the premiums offered and the campaigns which will utilize this offer.</description>
    <label>Offer</label>
    <nameField>
        <label>Offer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Offers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Offer__c/fields/Free_Trial__c.field-meta.xml
<CustomField>
        <fullName>Free_Trial__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This field is used to denote whether this offer is a free trial offer</description>
        <label>Free Trial?</label>
        <type>Checkbox</type>
    </CustomField>

force-app/main/default/objects/Subscription__c/Subscription__c.object-meta.xml
<CustomObject>
    <description>This object stores the actual subscription details, including selected Offer, Premiums. Delivery Schedules, frequency and term.</description>
    <label>Subscription</label>
    <nameField>
        <displayFormat>Sub-{0000}</displayFormat>
        <label>Subscription Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Subscription__c/fields/Contact__c.field-meta.xml
<CustomField>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Subscriptions</relationshipLabel>
        <relationshipName>Subscriptions</relationshipName>
        <type>Lookup</type>
    </CustomField>

force-app/main/default/objects/Subscription__c/fields/Expires_On__c.field-meta.xml
<CustomField>
        <fullName>Expires_On__c</fullName>
        <formula>IF(subscription_Offer__r.Free_Trial__c=True,subscription_Current_Period_Ends_At__c, 
			(subscription_Current_Period_Ends_At__c + $CustomMetadata.Subscription_Settings__mdt.Inquirer_DN_Grace_Days.Number_of_Grace_Days__c + Extend_Grace_by_Days__c)
			)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>End Date + Grace Days + Extended Grace Days</inlineHelpText>
        <label>Expires On</label>
        <type>Date</type>
    </CustomField>

force-app/main/default/objects/Subscription__c/fields/subscription_Offer__c.field-meta.xml
<CustomField>
        <fullName>subscription_Offer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Stores the relationship to Offer</description>
        <label>Offer</label>
        <referenceTo>Offer__c</referenceTo>
        <relationshipLabel>Subscriptions</relationshipLabel>
        <relationshipName>Subscriptions1</relationshipName>
        <type>Lookup</type>
    </CustomField>

force-app/main/default/objects/Subscription__c/fields/subscription_Status__c.field-meta.xml
<CustomField>
        <fullName>subscription_Status__c</fullName>
        <description>Stores the status of the subscription</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>New</fullName>
                </value>
                <value>
                    <fullName>TERMINATED</fullName>
                </value>
                <value>
                    <fullName>INACTIVE</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </CustomField>

force-app/main/default/classes/SubscriptionCampaign.cls
public with sharing class SubscriptionCampaign {
    private Offer__c offer;
    private Subscription__c subscription;
    private Map<String, Campaign_Settings__mdt> campaignSettingsByName;

    private static final String CAMPAIGN_SETTING_FREE_TRIAL = 'Free_Trial';
    private static final String CAMPAIGN_SETTING_ABANDONED_CART = 'Abandoned_Cart';
    private static final String CAMPAIGN_SETTING_ONBOARDING_NEW = 'Onboarding_New';
    private static final String CAMPAIGN_SETTING_ONBOARDING_LAPSED = 'Onboarding_Lapsed';
    private static final String CAMPAIGN_SETTING_ONBOARDING_OLD = 'Onboarding_Old';

    public SubscriptionCampaign(Subscription__c subscription) {
        this.offer = offer;
        this.subscription = subscription;
        this.campaignSettingsByName = getCampaignSettingsByName();
    }

    public void setNewSubscriptionCampaign() {
        String campaignToUse = (subscription.subscription_Offer__r.Free_Trial__c) ? CAMPAIGN_SETTING_FREE_TRIAL : CAMPAIGN_SETTING_ABANDONED_CART;
        Campaign_Settings__mdt campaignSettings = campaignSettingsByName.get(campaignToUse);
        setCurrentCampaign(campaignSettings);
    }

    public void setCheckoutCompleteCampaign() {
        // Determine which campaign we need to push into 
        Campaign_Settings__mdt campaignSettings = campaignSettingsByName.get(CAMPAIGN_SETTING_ONBOARDING_NEW);
        if (subscription.subscription_Status__c == 'Expired') {
            campaignSettings = campaignSettingsByName.get(CAMPAIGN_SETTING_ONBOARDING_LAPSED);
            if (subscription.Expires_On__c.daysBetween(Date.today()) > 90) { // if expired more than 90 days mark as old
                campaignSettings = campaignSettingsByName.get(CAMPAIGN_SETTING_ONBOARDING_OLD);
            }
        }
        if (campaignSettings != null) {
            setCurrentCampaign(campaignSettings);
        }
    }

    private void setCurrentCampaign(Campaign_Settings__mdt campaignSettings) {
        if (campaignSettings != null) {
            removeCurrentCampaigns();
            List<Campaign> campaigns = [SELECT Id FROM Campaign WHERE Id = :campaignSettings.Campaign_Id__c];
            if (!campaigns.isEmpty()) {
                CampaignMember campaignMember = new CampaignMember(CampaignId = campaignSettings.Campaign_Id__c, ContactId = subscription.Contact__c);
                insert campaignMember;
            }
        }
    }

    private Map<String, Campaign_Settings__mdt> getCampaignSettingsByName() {
        Map<String, Campaign_Settings__mdt> campaignSettingByName = new Map<String, Campaign_Settings__mdt>();
        List<Campaign_Settings__mdt> campaignSettings = [SELECT Id, Campaign_Id__c, Campaign_Name__c, DeveloperName FROM Campaign_Settings__mdt];
        for (Campaign_Settings__mdt campaignSetting : campaignSettings) {
            campaignSettingByName.put(campaignSetting.DeveloperName, campaignSetting);
        }
        return campaignSettingByName;
    }   

    private void removeCurrentCampaigns() {
        Set<Id> campaignIds = new Set<Id>();
        for (Campaign_Settings__mdt campaignSetting : campaignSettingsByName.values()) {
            campaignIds.add(campaignSetting.Campaign_Id__c);
        }

        List<CampaignMember> currentCampaigns = [SELECT Id FROM CampaignMember WHERE ContactId = :subscription.Contact__c AND CampaignId IN :campaignIds];
        if (!currentCampaigns.isEmpty()) {
            delete currentCampaigns;
        }
    }
}