force-app/main/default/objects/Offer_Product__c/Offer_Product__c.object-meta.xml
<CustomObject>
    <label>Offer Product</label>
    <nameField>
        <label>Offer Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Offer Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Offer_Product__c/fields/Is_Activation_Fee__c.field-meta.xml
<CustomField>
        <fullName>Is_Activation_Fee__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Activation Fee</label>
        <type>Checkbox</type>
    </CustomField>

force-app/main/default/objects/Subscription__c/Subscription__c.object-meta.xml
<CustomObject>
    <description>This object stores the actual subscription details, including selected Offer, Premiums. Delivery Schedules, frequency and term.</description>
    <label>Subscription</label>
    <nameField>
        <displayFormat>Sub-{0000}</displayFormat>
        <label>Subscription Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/CreditCalculatorControllerTest.cls
@isTest
global class CreditCalculatorControllerTest {
    @isTest 
    private static void test_fetchSubscription() {
        TestDataFactory.createTestRecords(1);
        Subscription__c sub = [SELECT Id FROM Subscription__c LIMIT 1];

        Test.startTest();
            Subscription__c returnedSub = CreditCalculatorController.fetchSubscription(sub.Id);
        Test.stopTest();

        System.assertEquals(true, returnedSub != null, 'Subscription should be found');
    }

    @isTest 
    private static void test_fetchOfferProducts() {
        TestDataFactory.createTestRecords(1);
        Subscription__c sub = [SELECT Id FROM Subscription__c LIMIT 1];

        List<Offer_Product__c> ops = [SELECT Id, Is_Activation_Fee__c FROM Offer_Product__c];
        for (Offer_Product__c op : ops) {
            op.Is_Activation_Fee__c = false;
        }
        update ops;

        Test.startTest();
            List<Offer_Product__c> products = CreditCalculatorController.fetchOfferProducts(sub.Id);
        Test.stopTest();

        System.assertEquals(false, products.isEmpty(), 'Products should be found');
    }

    // @isTest 
    // private static void test_calculate() {
    //     TestDataFactory.createTestRecords(1);
    //     Subscription__c sub = [SELECT Id FROM Subscription__c LIMIT 1];
    //     Map<Id, Offer_Product__c> offerProductById = new Map<Id, Offer_Product__c>([SELECT Id FROM Offer_Product__c]);
    //     List<Id> productIds = new List<Id>(offerProductById.keySet());

    //     Test.startTest();
    //         Decimal calculation = CreditCalculatorController.calculate(sub.Id, Date.today(), Date.today(), productIds);
    //     Test.stopTest();

    //     System.assertEquals(.25, calculation, 'Calculation should equal .25');
    // }

    //     // TEST TEMPORARILY DISABLED (David, 7th March 2020)
    //     // Error message:	System.AssertException: Assertion Failed: Calculation should equal .25: Expected: 0.25, Actual: 0.0000
    //     // Stack trace:	    Class.CreditCalculatorControllerTest.test_calculate: line 44, column 1

    @isTest 
    private static void test_submit() {
        Test.setMock(HttpCalloutMock.class, new RecurlyApiMock());
        TestDataFactory.createTestRecords(1);
        Subscription__c sub = [SELECT Id FROM Subscription__c LIMIT 1];

        Id accountId = CheckoutController.createRecurlyAccount(sub.Id);

        CheckoutPaymentInformation payment = new CheckoutPaymentInformation();
        payment.sendBill = false;
        payment.processPayment = false;
        payment.enableEzPay = true;
        payment.billingToken = '1234';
        payment.subscriptionAmount = 10.0;
        payment.accountId = accountId;
        payment.waiveActivationFee = false;

        
        Test.startTest();
            CheckoutController.submitPayment(sub.Id, JSON.serialize(payment));
            Map<Id, Offer_Product__c> offerProductById = new Map<Id, Offer_Product__c>([SELECT Id FROM Offer_Product__c]);
            List<Id> productIds = new List<Id>(offerProductById.keySet());
            DateTime currentPeriodEndsDate = CreditCalculatorController.submit(sub.Id, null, 10, 'Credit', 'Test Message', Date.today(), Date.today(), productIds);
        Test.stopTest();

        //System.assertEquals(Date.today(), currentPeriodEndsDate, 'Should end');
    }

    @isTest 
    private static void test_submit_withProducts() {
        Test.setMock(HttpCalloutMock.class, new RecurlyApiMock());
        TestDataFactory.createTestRecords(1);
        Subscription__c sub = [SELECT Id FROM Subscription__c LIMIT 1];

        Id accountId = CheckoutController.createRecurlyAccount(sub.Id);

        CheckoutPaymentInformation payment = new CheckoutPaymentInformation();
        payment.sendBill = false;
        payment.processPayment = false;
        payment.enableEzPay = true;
        payment.billingToken = '1234';
        payment.subscriptionAmount = 10.0;
        payment.accountId = accountId;
        payment.waiveActivationFee = false;

        
        Test.startTest();
            CheckoutController.submitPayment(sub.Id, JSON.serialize(payment));
            DateTime currentPeriodEndsDate = CreditCalculatorController.submit(sub.Id, null, 10, 'Credit', 'Test Message', Date.today(), Date.today(), null);
        Test.stopTest();

        //System.assertEquals(Date.today(), currentPeriodEndsDate, 'Should end');
    }
}