force-app/main/default/objects/Billing__c/Billing__c.object-meta.xml
<CustomObject>
    <label>Billing</label>
    <nameField>
        <displayFormat>Billing - {00000}</displayFormat>
        <label>Billing Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Billings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Billing__c/fields/Amount__c.field-meta.xml
<CustomField>
        <fullName>Amount__c</fullName>
        <description>Total amount of this bill</description>
        <label>Amount</label>
        <precision>8</precision>
        <scale>2</scale>
        <type>Currency</type>
    </CustomField>

force-app/main/default/objects/Billing__c/fields/Bill_Date__c.field-meta.xml
<CustomField>
        <fullName>Bill_Date__c</fullName>
        <description>Date this bill was issued</description>
        <label>Bill Date</label>
        <type>Date</type>
    </CustomField>

force-app/main/default/objects/Billing__c/fields/Subscription__c.field-meta.xml
<CustomField>
        <fullName>Subscription__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Subscription</label>
        <referenceTo>Subscription__c</referenceTo>
        <relationshipLabel>Billing</relationshipLabel>
        <relationshipName>Subscription</relationshipName>
        <type>Lookup</type>
    </CustomField>

force-app/main/default/objects/Log__c/Log__c.object-meta.xml
<CustomObject>
    <label>Log</label>
    <nameField>
        <displayFormat>LOG-{0}</displayFormat>
        <label>Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Log__c/fields/Message__c.field-meta.xml
<CustomField>
        <fullName>Message__c</fullName>
        <label>Message</label>
        <length>255</length>
        <type>Text</type>
    </CustomField>

force-app/main/default/objects/Log__c/fields/Subscription__c.field-meta.xml
<CustomField>
        <fullName>Subscription__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Subscription</label>
        <referenceTo>Subscription__c</referenceTo>
        <relationshipLabel>Logs</relationshipLabel>
        <relationshipName>Logs</relationshipName>
        <type>Lookup</type>
    </CustomField>

force-app/main/default/objects/Log__c/fields/Type__c.field-meta.xml
<CustomField>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <length>50</length>
        <type>Text</type>
    </CustomField>

force-app/main/default/objects/Offer__c/Offer__c.object-meta.xml
<CustomObject>
    <description>Controls price, delivery, term for a subscription including print, digital and alternate publications. Also holds links to the premiums offered and the campaigns which will utilize this offer.</description>
    <label>Offer</label>
    <nameField>
        <label>Offer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Offers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Offer__c/fields/Amount__c.field-meta.xml
<CustomField>
        <fullName>Amount__c</fullName>
        <formula>AmountforRollup__c + Sunday_AmountRollup__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </CustomField>

force-app/main/default/objects/Offer__c/fields/Total_Amount__c.field-meta.xml
<CustomField>
        <fullName>Total_Amount__c</fullName>
        <formula>Sunday_AmountRollup__c + AmountforRollup__c + Activation_Fee__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>This value is Subscription Amount plus Activation Fee if Activation fee exists for Offer</inlineHelpText>
        <label>Total Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </CustomField>

force-app/main/default/objects/Subscription__c/Subscription__c.object-meta.xml
<CustomObject>
    <description>This object stores the actual subscription details, including selected Offer, Premiums. Delivery Schedules, frequency and term.</description>
    <label>Subscription</label>
    <nameField>
        <displayFormat>Sub-{0000}</displayFormat>
        <label>Subscription Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Subscription__c/fields/Auto_Renew_Recurly_Account__c.field-meta.xml
<CustomField>
        <fullName>Auto_Renew_Recurly_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Auto Renew Recurly Account</label>
        <referenceTo>recurly_v2__Recurly_Account__c</referenceTo>
        <relationshipLabel>Subscriptions</relationshipLabel>
        <relationshipName>Auto_Renew_Subscriptions</relationshipName>
        <type>Lookup</type>
    </CustomField>

force-app/main/default/objects/Subscription__c/fields/Auto_Renew_Tip__c.field-meta.xml
<CustomField>
        <fullName>Auto_Renew_Tip__c</fullName>
        <description>Tip amount for recurring automated invoices</description>
        <label>Auto Renew Tip</label>
        <precision>7</precision>
        <scale>2</scale>
        <type>Currency</type>
    </CustomField>

force-app/main/default/objects/Subscription__c/fields/One_Time_Tip_Amount__c.field-meta.xml
<CustomField>
        <fullName>One_Time_Tip_Amount__c</fullName>
        <label>One Time Tip Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </CustomField>

force-app/main/default/objects/Subscription__c/fields/Outstanding_Credit__c.field-meta.xml
<CustomField>
        <fullName>Outstanding_Credit__c</fullName>
        <label>Today's Balance</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </CustomField>

force-app/main/default/objects/Subscription__c/fields/Pending_Change_Date__c.field-meta.xml
<CustomField>
        <fullName>Pending_Change_Date__c</fullName>
        <label>Pending Change Date</label>
        <type>Date</type>
    </CustomField>

force-app/main/default/objects/Subscription__c/fields/Pending_Offer__c.field-meta.xml
<CustomField>
        <fullName>Pending_Offer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Pending Offer</label>
        <referenceTo>Offer__c</referenceTo>
        <relationshipLabel>Subscriptions (Pending Offer)</relationshipLabel>
        <relationshipName>Subscriptions2</relationshipName>
        <type>Lookup</type>
    </CustomField>

force-app/main/default/objects/Subscription__c/fields/subscription_Current_Period_Started_At__c.field-meta.xml
<CustomField>
        <fullName>subscription_Current_Period_Started_At__c</fullName>
        <description>Stores the date and time the current subscription started</description>
        <label>Start Date</label>
        <type>Date</type>
    </CustomField>

force-app/main/default/objects/Subscription__c/fields/subscription_Offer__c.field-meta.xml
<CustomField>
        <fullName>subscription_Offer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Stores the relationship to Offer</description>
        <label>Offer</label>
        <referenceTo>Offer__c</referenceTo>
        <relationshipLabel>Subscriptions</relationshipLabel>
        <relationshipName>Subscriptions1</relationshipName>
        <type>Lookup</type>
    </CustomField>

force-app/main/default/classes/SubscriptionRenewal.cls
public with sharing class SubscriptionRenewal {
    private Map<Id, Subscription__c> subscriptionsById;
    private Map<Id, Offer__c> offersMap;

    private RecurlyApi recurlyApi;

    public SubscriptionRenewal(List<Subscription__c> subscriptions) {
        this.recurlyApi = new RecurlyApi();
        this.subscriptionsById = new Map<Id, Subscription__c>(subscriptions);
        this.offersMap = new Map<Id, Offer__c>(OfferDataAccessor.getSubscriptionDigitalOffers(subscriptionsById.keySet()));
    }

    public void processSubscriptions() {
        List<Log__c> logs = new List<Log__c>();
        List<Billing__c> billings = new List<Billing__c>();
        for (Subscription__c sub : subscriptionsById.values()) {
            try {
                createPurchase(sub);
                adjustSubscription(sub);
                billings.add(new Billing__c(Bill_Date__c = Date.today(), Amount__c = sub.subscription_Offer__r.Total_Amount__c, Subscription__c = sub.Id));
                sub.One_Time_Tip_Amount__c = 0;

                if (sub.Pending_Offer__c != null) {
                    sub.subscription_Offer__c = sub.Pending_Offer__c;
                    sub.Pending_Offer__c = null;
                    sub.Pending_Change_Date__c = null;
                }
            } catch (Exception e) {
                System.debug(e.getMessage() + ' ' + e.getStackTraceString());
                logs.add(new Log__c(Type__c = 'Subscription Renewal Exception', Subscription__c = sub.Id, Message__c = e.getMessage() + ' ' + e.getStackTraceString()));
            }
        }
        if (!subscriptionsById.isEmpty()) {
            update subscriptionsById.values();
        }
        if (!billings.isEmpty()) {
            insert billings;
        }
    }

    private void createPurchase(Subscription__c sub) {
        List<RecurlyApiObjects.AdjustmentDetails> adjustments = new List<RecurlyApiObjects.AdjustmentDetails>();
        adjustments.add(new RecurlyApiObjects.AdjustmentDetails(sub.subscription_Offer__r.Total_Amount__c * 100, 1, 'Subscription Amount'));
        if (sub.Auto_Renew_Tip__c != null && sub.Auto_Renew_Tip__c > 0) {
            adjustments.add(new RecurlyApiObjects.AdjustmentDetails(sub.Auto_Renew_Tip__c * 100, 1, 'Tip Amount'));
        } else if (sub.Auto_Renew_Tip__c != null && sub.One_Time_Tip_Amount__c > 0) {
            adjustments.add(new RecurlyApiObjects.AdjustmentDetails(sub.One_Time_Tip_Amount__c * 100, 1, 'Tip Amount'));
        }
        RecurlyApiObjects.Purchase purchase = new RecurlyApiObjects.Purchase(sub.Auto_Renew_Recurly_Account__r.recurly_v2__Code__c, adjustments, null);
        recurlyApi.createPurchase(purchase);
    }

    private void adjustSubscription(Subscription__c subscription) {
        Offer__c digitalOffer = offersMap.get(subscription.subscription_Offer__c);
        subscription.Outstanding_Credit__c = ((subscription.Outstanding_Credit__c != null) ? subscription.Outstanding_Credit__c : 0) + subscription.subscription_Offer__r.Total_Amount__c;
        subscription.subscription_Current_Period_Started_At__c = (subscription.subscription_Current_Period_Started_At__c != null) ? subscription.subscription_Current_Period_Started_At__c : Date.today();
        CreditCalculatorController.ApplyAdjustment(subscription, digitalOffer);
    }
}