force-app/main/default/objects/Billing__c/Billing__c.object-meta.xml
<CustomObject>
    <label>Billing</label>
    <nameField>
        <displayFormat>Billing - {00000}</displayFormat>
        <label>Billing Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Billings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Billing__c/fields/Amount__c.field-meta.xml
<CustomField>
        <fullName>Amount__c</fullName>
        <description>Total amount of this bill</description>
        <label>Amount</label>
        <precision>8</precision>
        <scale>2</scale>
        <type>Currency</type>
    </CustomField>

force-app/main/default/objects/Billing__c/fields/Bill_Date__c.field-meta.xml
<CustomField>
        <fullName>Bill_Date__c</fullName>
        <description>Date this bill was issued</description>
        <label>Bill Date</label>
        <type>Date</type>
    </CustomField>

force-app/main/default/objects/Billing__c/fields/Subscription__c.field-meta.xml
<CustomField>
        <fullName>Subscription__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Subscription</label>
        <referenceTo>Subscription__c</referenceTo>
        <relationshipLabel>Billing</relationshipLabel>
        <relationshipName>Subscription</relationshipName>
        <type>Lookup</type>
    </CustomField>

force-app/main/default/objects/Billing__c/fields/Term__c.field-meta.xml
<CustomField>
        <fullName>Term__c</fullName>
        <description>Number of weeks covered by this bill</description>
        <label>Term</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </CustomField>

force-app/main/default/objects/Delivery_Schedule__c/Delivery_Schedule__c.object-meta.xml
<CustomObject>
    <description>Deliver Schedules control the address and which days a publication will be delivered as part of the press run.</description>
    <label>Delivery Schedule</label>
    <nameField>
        <displayFormat>DS-{0}</displayFormat>
        <label>Delivery Schedule Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Delivery Schedules</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Delivery_Schedule__c/fields/Day_Friday__c.field-meta.xml
<CustomField>
        <fullName>Day_Friday__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Friday</label>
        <type>Checkbox</type>
    </CustomField>

force-app/main/default/objects/Delivery_Schedule__c/fields/Day_Monday__c.field-meta.xml
<CustomField>
        <fullName>Day_Monday__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Monday</label>
        <type>Checkbox</type>
    </CustomField>

force-app/main/default/objects/Delivery_Schedule__c/fields/Day_Saturday__c.field-meta.xml
<CustomField>
        <fullName>Day_Saturday__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Saturday</label>
        <type>Checkbox</type>
    </CustomField>

force-app/main/default/objects/Delivery_Schedule__c/fields/Day_Sunday__c.field-meta.xml
<CustomField>
        <fullName>Day_Sunday__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Sunday</label>
        <type>Checkbox</type>
    </CustomField>

force-app/main/default/objects/Delivery_Schedule__c/fields/Day_Thursday__c.field-meta.xml
<CustomField>
        <fullName>Day_Thursday__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Thursday</label>
        <type>Checkbox</type>
    </CustomField>

force-app/main/default/objects/Delivery_Schedule__c/fields/Day_Tuesday__c.field-meta.xml
<CustomField>
        <fullName>Day_Tuesday__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Tuesday</label>
        <type>Checkbox</type>
    </CustomField>

force-app/main/default/objects/Delivery_Schedule__c/fields/Day_Wednesday__c.field-meta.xml
<CustomField>
        <fullName>Day_Wednesday__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Wednesday</label>
        <type>Checkbox</type>
    </CustomField>

force-app/main/default/objects/Delivery_Schedule__c/fields/District__c.field-meta.xml
<CustomField>
        <fullName>District__c</fullName>
        <label>District</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>105</fullName>
                </value>
                <value>
                    <fullName>108</fullName>
                </value>
                <value>
                    <fullName>110</fullName>
                </value>
                <value>
                    <fullName>111</fullName>
                </value>
                <value>
                    <fullName>112</fullName>
                </value>
                <value>
                    <fullName>113</fullName>
                </value>
                <value>
                    <fullName>114</fullName>
                </value>
                <value>
                    <fullName>117</fullName>
                </value>
                <value>
                    <fullName>118</fullName>
                </value>
                <value>
                    <fullName>119</fullName>
                </value>
                <value>
                    <fullName>121</fullName>
                </value>
                <value>
                    <fullName>127</fullName>
                </value>
                <value>
                    <fullName>148</fullName>
                </value>
                <value>
                    <fullName>218</fullName>
                </value>
                <value>
                    <fullName>245</fullName>
                </value>
                <value>
                    <fullName>252</fullName>
                </value>
                <value>
                    <fullName>255</fullName>
                </value>
                <value>
                    <fullName>366</fullName>
                </value>
                <value>
                    <fullName>367</fullName>
                </value>
                <value>
                    <fullName>368</fullName>
                </value>
                <value>
                    <fullName>392</fullName>
                </value>
                <value>
                    <fullName>399</fullName>
                </value>
                <value>
                    <fullName>492</fullName>
                </value>
                <value>
                    <fullName>495</fullName>
                </value>
                <value>
                    <fullName>499</fullName>
                </value>
                <value>
                    <fullName>593</fullName>
                </value>
                <value>
                    <fullName>608</fullName>
                </value>
                <value>
                    <fullName>609</fullName>
                </value>
                <value>
                    <fullName>612</fullName>
                </value>
                <value>
                    <fullName>613</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </CustomField>

force-app/main/default/objects/Delivery_Schedule__c/fields/Offer_Product__c.field-meta.xml
<CustomField>
        <fullName>Offer_Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Offer Product</label>
        <referenceTo>Offer_Product__c</referenceTo>
        <relationshipLabel>Delivery Schedules</relationshipLabel>
        <relationshipName>Delivery_Schedules</relationshipName>
        <type>Lookup</type>
    </CustomField>

force-app/main/default/objects/Delivery_Schedule__c/fields/Routelookup__c.field-meta.xml
<CustomField>
        <fullName>Routelookup__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Route</label>
        <referenceTo>Route__c</referenceTo>
        <relationshipLabel>Delivery Schedules</relationshipLabel>
        <relationshipName>Delivery_Schedules</relationshipName>
        <type>Lookup</type>
    </CustomField>

force-app/main/default/objects/Journal__c/Journal__c.object-meta.xml
<CustomObject>
    <label>Journal</label>
    <nameField>
        <displayFormat>Entry - {000000}</displayFormat>
        <label>Entry Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Journal Entries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Journal__c/fields/Credit__c.field-meta.xml
<CustomField>
        <fullName>Credit__c</fullName>
        <description>Amount if this is a credit</description>
        <label>Credit</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Currency</type>
    </CustomField>

force-app/main/default/objects/Journal__c/fields/Entry_Date__c.field-meta.xml
<CustomField>
        <fullName>Entry_Date__c</fullName>
        <defaultValue>today()</defaultValue>
        <description>Date the item was entered</description>
        <label>Entry Date</label>
        <type>Date</type>
    </CustomField>

force-app/main/default/objects/Journal__c/fields/Entry_Type__c.field-meta.xml
<CustomField>
        <fullName>Entry_Type__c</fullName>
        <label>Entry Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Publication</fullName>
                </value>
                <value>
                    <fullName>Cash</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </CustomField>

force-app/main/default/objects/Journal__c/fields/Subscription__c.field-meta.xml
<CustomField>
        <fullName>Subscription__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Subscription</label>
        <referenceTo>Subscription__c</referenceTo>
        <relationshipLabel>Journal Entries</relationshipLabel>
        <relationshipName>Journal_Entries</relationshipName>
        <type>Lookup</type>
    </CustomField>

force-app/main/default/objects/Offer_Product__c/Offer_Product__c.object-meta.xml
<CustomObject>
    <label>Offer Product</label>
    <nameField>
        <label>Offer Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Offer Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Offer_Product__c/fields/Amount__c.field-meta.xml
<CustomField>
        <fullName>Amount__c</fullName>
        <formula>Per_Copy__c *  Number_of_totals_day__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </CustomField>

force-app/main/default/objects/Offer_Product__c/fields/Is_Digital__c.field-meta.xml
<CustomField>
        <fullName>Is_Digital__c</fullName>
        <formula>Product__r.IsDigital__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Is Digital</label>
        <type>Checkbox</type>
    </CustomField>

force-app/main/default/objects/Offer_Product__c/fields/Term__c.field-meta.xml
<CustomField>
        <fullName>Term__c</fullName>
        <formula>Offer__r.Number_of_Weeks__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Term (weeks)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </CustomField>

force-app/main/default/objects/Route__c/Route__c.object-meta.xml
<CustomObject>
    <label>Route</label>
    <nameField>
        <label>Route Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Route</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Route__c/fields/District__c.field-meta.xml
<CustomField>
        <fullName>District__c</fullName>
        <label>District</label>
        <length>25</length>
        <type>Text</type>
    </CustomField>

force-app/main/default/objects/Subscription__c/Subscription__c.object-meta.xml
<CustomObject>
    <description>This object stores the actual subscription details, including selected Offer, Premiums. Delivery Schedules, frequency and term.</description>
    <label>Subscription</label>
    <nameField>
        <displayFormat>Sub-{0000}</displayFormat>
        <label>Subscription Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Subscription__c/fields/Delivery_Schedule__c.field-meta.xml
<CustomField>
        <fullName>Delivery_Schedule__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Stores the relationship between Subscriptions and Delivery Schedule</description>
        <label>Delivery Schedule</label>
        <referenceTo>Delivery_Schedule__c</referenceTo>
        <relationshipLabel>Subscriptions</relationshipLabel>
        <relationshipName>Subscriptions</relationshipName>
        <type>Lookup</type>
    </CustomField>

force-app/main/default/objects/Subscription__c/fields/subscription_Auto_Renew__c.field-meta.xml
<CustomField>
        <fullName>subscription_Auto_Renew__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Controls Auto Renew of Subscription</description>
        <inlineHelpText>If true, this denotes that the subscription is on EZ-pay</inlineHelpText>
        <label>Auto Renew</label>
        <type>Checkbox</type>
    </CustomField>

force-app/main/default/objects/Subscription__c/fields/subscription_Current_Period_Ends_At__c.field-meta.xml
<CustomField>
        <fullName>subscription_Current_Period_Ends_At__c</fullName>
        <description>Stores the date and time when the current subscription ends</description>
        <inlineHelpText>See the "Expires On" field below to see End date + Grace Days</inlineHelpText>
        <label>End Date</label>
        <type>Date</type>
    </CustomField>

force-app/main/default/objects/Subscription__c/fields/subscription_Status__c.field-meta.xml
<CustomField>
        <fullName>subscription_Status__c</fullName>
        <description>Stores the status of the subscription</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>New</fullName>
                </value>
                <value>
                    <fullName>TERMINATED</fullName>
                </value>
                <value>
                    <fullName>INACTIVE</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </CustomField>

force-app/main/default/objects/Subscription__c/fields/Total_Liability__c.field-meta.xml
<CustomField>
        <fullName>Total_Liability__c</fullName>
        <label>Total Liability</label>
        <precision>8</precision>
        <scale>2</scale>
        <type>Currency</type>
    </CustomField>

force-app/main/default/classes/Subscription.cls
public with sharing class Subscription {
    public Subscription__c subscription {get;set;}
    
    private List<Billing__c> billings;
    private List<Journal__c> journals;
    private List<Delivery_Schedule__c> deliverySchedules;
    private List<recurly_v2__Recurly_Invoice__c> recurlyInvoices;

    private static String todaysDayOfWeek = System.now().format('EEEE');
    private List<String> recurlyAcctIDs = new List<String>();
    
    public Subscription(String subId) {
        recurlyAcctIDs = RecurlyAccountDataAccessor.getRecurlyAcctIDsBySubscriptionId(subId);
        initObjects(subId);
    }

    public Billing__c latestBill {
        get {
            if (latestBill == null && billings != null && !billings.isEmpty()) {
                latestBill = billings[0]; // latest should be first in array due to order by
            }
            return latestBill;
        } private set;
    }

    public Journal__c latestJournal {
        get {
            if (latestJournal == null && journals != null && !journals.isEmpty()) {
                latestJournal = journals[0]; // latest should be first in array due to order by
            }
            return latestJournal;
        } private set;
    }

    public recurly_v2__Recurly_Invoice__c latestRecurlyInvoice {
        get {
            if (latestRecurlyInvoice == null && recurlyInvoices != null && !recurlyInvoices.isEmpty()) {
                latestRecurlyInvoice = recurlyInvoices[0];
            }
            return latestRecurlyInvoice;
        } private set;
    }

    public DeliverySchedule currentDeliverySchedule {
        get {
            if (currentDeliverySchedule == null && deliverySchedules != null && !deliverySchedules.isEmpty()) {
                for (Delivery_Schedule__c deliverySchedule : deliverySchedules) {
                    currentDeliverySchedule = new DeliverySchedule(deliverySchedule);
                    if (currentDeliverySchedule.isScheduledForToday()) {
                        break;
                    }
                }
            }
            return currentDeliverySchedule;
        } private set;
    }

    private void initObjects(Id subId) {
        this.subscription = [
            SELECT Id, subscription_Current_Period_Ends_At__c, subscription_Status__c, subscription_Auto_Renew__c, Total_Liability__c
            FROM Subscription__c
            WHERE Id = :subId
        ];

        this.billings = [
            SELECT Id, Bill_Date__c, Term__c, Amount__c
            FROM Billing__c
            WHERE Subscription__c = :subId
            ORDER BY Bill_Date__c DESC NULLS LAST
        ];
		
        this.journals = [
            SELECT Id, Entry_Date__c, Credit__c, Entry_Type__c
            FROM Journal__c
            WHERE Subscription__c = :subId
            AND Entry_Type__c = 'Cash'
            ORDER BY Entry_Date__c DESC NULLS LAST
        ];

        // paid invoice associated with recurly account
        this.recurlyInvoices = [
            SELECT Id, LastModifiedDate,
            recurly_v2__Due_At__c,
            recurly_v2__Account__c,
            recurly_v2__Invoice_Type__c,
            recurly_v2__Recurly_Account__c,
            recurly_v2__Status__c,
            recurly_v2__Total__c,
            recurly_v2__Paid__c
            FROM recurly_v2__Recurly_Invoice__c
            WHERE recurly_v2__Recurly_Account__c IN :recurlyAcctIDs
            AND recurly_v2__Status__c = 'Paid'
            ORDER BY LastModifiedDate DESC
        ];

        List<Delivery_Schedule__c> deliverySchedules = [
            SELECT Id, Day_Sunday__c, Day_Monday__c, Day_Tuesday__c, Day_Wednesday__c, Day_Thursday__c, Day_Friday__c, Day_Saturday__c, 
                Routelookup__c, Routelookup__r.District__c, Offer_Product__r.Name, Offer_Product__r.Is_Digital__c
            FROM Delivery_Schedule__c
            WHERE subscription_Subscription__c = :subId
        ];
    }
}