force-app/main/default/objects/Billing__c/Billing__c.object-meta.xml
<CustomObject>
    <label>Billing</label>
    <nameField>
        <displayFormat>Billing - {00000}</displayFormat>
        <label>Billing Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Billings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Billing__c/fields/Subscription__c.field-meta.xml
<CustomField>
        <fullName>Subscription__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Subscription</label>
        <referenceTo>Subscription__c</referenceTo>
        <relationshipLabel>Billing</relationshipLabel>
        <relationshipName>Subscription</relationshipName>
        <type>Lookup</type>
    </CustomField>

force-app/main/default/objects/Offer__c/Offer__c.object-meta.xml
<CustomObject>
    <description>Controls price, delivery, term for a subscription including print, digital and alternate publications. Also holds links to the premiums offered and the campaigns which will utilize this offer.</description>
    <label>Offer</label>
    <nameField>
        <label>Offer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Offers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Subscription__c/Subscription__c.object-meta.xml
<CustomObject>
    <description>This object stores the actual subscription details, including selected Offer, Premiums. Delivery Schedules, frequency and term.</description>
    <label>Subscription</label>
    <nameField>
        <displayFormat>Sub-{0000}</displayFormat>
        <label>Subscription Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Subscription__c/fields/Auto_Renew_Recurly_Account__c.field-meta.xml
<CustomField>
        <fullName>Auto_Renew_Recurly_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Auto Renew Recurly Account</label>
        <referenceTo>recurly_v2__Recurly_Account__c</referenceTo>
        <relationshipLabel>Subscriptions</relationshipLabel>
        <relationshipName>Auto_Renew_Subscriptions</relationshipName>
        <type>Lookup</type>
    </CustomField>

force-app/main/default/objects/Subscription__c/fields/Auto_Renew_Tip__c.field-meta.xml
<CustomField>
        <fullName>Auto_Renew_Tip__c</fullName>
        <description>Tip amount for recurring automated invoices</description>
        <label>Auto Renew Tip</label>
        <precision>7</precision>
        <scale>2</scale>
        <type>Currency</type>
    </CustomField>

force-app/main/default/objects/Subscription__c/fields/Pending_Offer__c.field-meta.xml
<CustomField>
        <fullName>Pending_Offer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Pending Offer</label>
        <referenceTo>Offer__c</referenceTo>
        <relationshipLabel>Subscriptions (Pending Offer)</relationshipLabel>
        <relationshipName>Subscriptions2</relationshipName>
        <type>Lookup</type>
    </CustomField>

force-app/main/default/objects/Subscription__c/fields/subscription_Auto_Renew__c.field-meta.xml
<CustomField>
        <fullName>subscription_Auto_Renew__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Controls Auto Renew of Subscription</description>
        <inlineHelpText>If true, this denotes that the subscription is on EZ-pay</inlineHelpText>
        <label>Auto Renew</label>
        <type>Checkbox</type>
    </CustomField>

force-app/main/default/objects/Subscription__c/fields/subscription_Current_Period_Ends_At__c.field-meta.xml
<CustomField>
        <fullName>subscription_Current_Period_Ends_At__c</fullName>
        <description>Stores the date and time when the current subscription ends</description>
        <inlineHelpText>See the "Expires On" field below to see End date + Grace Days</inlineHelpText>
        <label>End Date</label>
        <type>Date</type>
    </CustomField>

force-app/main/default/objects/Subscription__c/fields/subscription_Status__c.field-meta.xml
<CustomField>
        <fullName>subscription_Status__c</fullName>
        <description>Stores the status of the subscription</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>New</fullName>
                </value>
                <value>
                    <fullName>TERMINATED</fullName>
                </value>
                <value>
                    <fullName>INACTIVE</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </CustomField>

force-app/main/default/classes/NightlySubscriptionRenewalTest.cls
@isTest
global class NightlySubscriptionRenewalTest {
    @isTest
    private static void test_schedule() {
        Test.startTest();
            String sch = '0  00 1 3 * ?';
            System.schedule('Nightly Sub Renewal', sch, new NightlySubscriptionRenewalScheduleable());
        Test.stopTest();
    }

    @isTest
    private static void test_batch() {
        Test.setMock(HttpCalloutMock.class, new RecurlyApiMock());
        TestDataFactory.createTestRecords(1);
        Offer__c existingOffer = [SELECT Id FROM Offer__c LIMIT 1];

        List<recurly_v2__Recurly_Account__c> accts = [SELECT Id FROM recurly_v2__Recurly_Account__c];
        Subscription__c sub = [SELECT Id, subscription_Status__c, subscription_Current_Period_Ends_At__c, subscription_Auto_Renew__c, Auto_Renew_Recurly_Account__c FROM Subscription__c LIMIT 1];
        sub.subscription_Status__c = 'Active';
        sub.Pending_Offer__c = existingOffer.Id;
        sub.subscription_Current_Period_Ends_At__c = Date.today();
        sub.subscription_Auto_Renew__c = true;
        sub.Auto_Renew_Recurly_Account__c = accts[0].Id;
        sub.Auto_Renew_Tip__c = 5;
        update sub;

        Test.startTest();
            Database.executeBatch(new NightlySubscriptionRenewalBatch());
        Test.stopTest();

        List<Billing__c> billings = [SELECT Id FROM Billing__c WHERE Subscription__c = :sub.Id];
        System.assertEquals(3, billings.size(), 'There should be 3 billing records created');
    }
}