force-app/main/default/objects/Auth0ConnectionSettings__c/Auth0ConnectionSettings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Connection Details for Auth0 Rest Callouts in Auth0Connection Apex Class.</description>
    <label>Auth0ConnectionSettings</label>
</CustomObject>

force-app/main/default/objects/Auth0ConnectionSettings__c/fields/Audience__c.field-meta.xml
<CustomField>
        <fullName>Audience__c</fullName>
        <label>Audience</label>
        <length>100</length>
        <type>Text</type>
    </CustomField>

force-app/main/default/objects/Auth0ConnectionSettings__c/fields/Client_ID__c.field-meta.xml
<CustomField>
        <fullName>Client_ID__c</fullName>
        <label>Client ID</label>
        <length>100</length>
        <type>Text</type>
    </CustomField>

force-app/main/default/objects/Auth0ConnectionSettings__c/fields/Client_Secret__c.field-meta.xml
<CustomField>
        <fullName>Client_Secret__c</fullName>
        <label>Client Secret</label>
        <length>100</length>
        <type>Text</type>
    </CustomField>

force-app/main/default/objects/Auth0ConnectionSettings__c/fields/Connection__c.field-meta.xml
<CustomField>
        <fullName>Connection__c</fullName>
        <label>Connection</label>
        <length>100</length>
        <type>Text</type>
    </CustomField>

force-app/main/default/objects/Auth0ConnectionSettings__c/fields/Default_Password__c.field-meta.xml
<CustomField>
        <fullName>Default_Password__c</fullName>
        <label>Default Password</label>
        <length>100</length>
        <type>Text</type>
    </CustomField>

force-app/main/default/objects/Auth0ConnectionSettings__c/fields/Domain__c.field-meta.xml
<CustomField>
        <fullName>Domain__c</fullName>
        <label>Domain</label>
        <length>100</length>
        <type>Text</type>
    </CustomField>

force-app/main/default/objects/Auth0ConnectionSettings__c/fields/Grant_Type__c.field-meta.xml
<CustomField>
        <fullName>Grant_Type__c</fullName>
        <label>Grant Type</label>
        <length>100</length>
        <type>Text</type>
    </CustomField>

force-app/main/default/objects/Delivery_Address__c/Delivery_Address__c.object-meta.xml
<CustomObject>
    <description>Related Addresses to a Subscriber Household or Business and a Delivery Schedule of a Subscription.</description>
    <label>Delivery Address</label>
    <nameField>
        <displayFormat>DA-{0}</displayFormat>
        <label>Delivery Address Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Delivery Addresses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Delivery_Address__c/fields/Address_Street__c.field-meta.xml
<CustomField>
        <fullName>Address_Street__c</fullName>
        <label>Street</label>
        <length>200</length>
        <type>Text</type>
    </CustomField>

force-app/main/default/objects/Offer__c/Offer__c.object-meta.xml
<CustomObject>
    <description>Controls price, delivery, term for a subscription including print, digital and alternate publications. Also holds links to the premiums offered and the campaigns which will utilize this offer.</description>
    <label>Offer</label>
    <nameField>
        <label>Offer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Offers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Subscription__c/Subscription__c.object-meta.xml
<CustomObject>
    <description>This object stores the actual subscription details, including selected Offer, Premiums. Delivery Schedules, frequency and term.</description>
    <label>Subscription</label>
    <nameField>
        <displayFormat>Sub-{0000}</displayFormat>
        <label>Subscription Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Subscription__c/fields/Outstanding_Credit__c.field-meta.xml
<CustomField>
        <fullName>Outstanding_Credit__c</fullName>
        <label>Today's Balance</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </CustomField>

force-app/main/default/objects/Subscription__c/fields/SignatureURL__c.field-meta.xml
<CustomField>
        <fullName>SignatureURL__c</fullName>
        <description>Stores the signature URL from customer signatures for partner community subscription purchases</description>
        <label>SignatureURL</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </CustomField>

force-app/main/default/objects/Subscription__c/fields/subscription_Current_Period_Ends_At__c.field-meta.xml
<CustomField>
        <fullName>subscription_Current_Period_Ends_At__c</fullName>
        <description>Stores the date and time when the current subscription ends</description>
        <inlineHelpText>See the "Expires On" field below to see End date + Grace Days</inlineHelpText>
        <label>End Date</label>
        <type>Date</type>
    </CustomField>

force-app/main/default/objects/Subscription__c/fields/subscription_Status__c.field-meta.xml
<CustomField>
        <fullName>subscription_Status__c</fullName>
        <description>Stores the status of the subscription</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>New</fullName>
                </value>
                <value>
                    <fullName>TERMINATED</fullName>
                </value>
                <value>
                    <fullName>INACTIVE</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </CustomField>

force-app/main/default/classes/CheckoutControllerTest.cls
@isTest
global class CheckoutControllerTest {
    @isTest(SeeAllData=true)
    private static void test_getRecurlyJsUrl() {
        Test.startTest();
        String recurlyUrl = CheckoutController.getRecurlyJsUrl();
        Test.stopTest();

        System.assertEquals(Label.RECURLYJS_VFP_URL, recurlyUrl);
    }

    @isTest
    private static void test_getUserInfo() {
        Test.startTest();
            User userInfo = CheckoutController.getUserInfo();
        Test.stopTest();

        System.assertEquals(true, userInfo != null, 'User should be found');
    }

    @isTest
    private static void test_getSubscriptionById() {
        TestDataFactory.createTestRecords(1);
        Subscription__c sub = [SELECT Id FROM Subscription__c LIMIT 1];

        Test.startTest();
            Subscription__c subscription = CheckoutController.getSubscriptionById(sub.Id);
        Test.stopTest();

        System.assertEquals(subscription != null, true, 'Subscription should be found');
    }

    @isTest
    private static void test_getOfferById() {
        TestDataFactory.createProductsAndOffers(1);
        Offer__c existingOffer = [SELECT Id FROM Offer__c LIMIT 1];

        Test.startTest();
            Offer__c offer = CheckoutController.getOfferById(existingOffer.Id);
        Test.stopTest();

        System.assertEquals(offer != null, true, 'Offer should be found');
    }

    @isTest
    private static void test_getOfferById_withException() {
        TestDataFactory.createProductsAndOffers(1);
        Offer__c existingOffer = [SELECT Id FROM Offer__c LIMIT 1];

        Test.startTest();
        Boolean hasException = false;
        try {
            CheckoutController.getOfferById(null);
        } catch(Exception e) {
            hasException = true;
        }
        Test.stopTest();

        System.assertEquals(true, hasException, 'getOfferById should throw an exception');
    }

    @isTest
    private static void test_callPiano() {
        Test.setMock(HttpCalloutMock.class, new PianoRequestMock(0));

        Test.startTest();
            Boolean error = false;
            try {
                CheckoutController.callPiano('test');
            } catch (Exception e) {
                error = true;
            }
        Test.stopTest();

        System.assertEquals(false, error, 'There should not be an exception');
    }

    @isTest
    private static void test_callPiano_withErrorCode() {
        Test.setMock(HttpCalloutMock.class, new PianoRequestMock(1));

        Test.startTest();
            Boolean error = false;
            try {
                CheckoutController.callPiano(null);
            } catch (Exception e) {
                error = true;
            }
        Test.stopTest();

        System.assertEquals(error, true, 'There should be an exception thrown');
    }

    @isTest
    private static void test_getNewSubscription() {
        Test.setMock(HttpCalloutMock.class, new Auth0Mock());
        
        Auth0ConnectionSettings__c setting = new Auth0ConnectionSettings__c(Default_Password__c = 'test', Audience__c = 'test', Client_Id__c = 'test', Client_Secret__c = 'test', Connection__c = 'test', Domain__c = 'test', Grant_Type__c = 'secret');
        insert setting;

        TestDataFactory.createTestRecords(1);
        Offer__c existingOffer = [SELECT Id FROM Offer__c LIMIT 1];

        Test.startTest();
            Subscription__c newSub = CheckoutController.getNewSubscription(existingOffer.Id, 'test@test.com', 'web', 'test123', false);
            for (Subscription__c sub : [SELECT Id FROM Subscription__c]) {
                sub.subscription_Status__c = 'INACTIVE';
                update sub;
            }
            Subscription__c updatedSub = CheckoutController.getNewSubscription(existingOffer.Id, 'test@test.com', 'web', 'test123', false);
        Test.stopTest();

        System.assertEquals(true, true, '');
    }

    @isTest
    private static void test_exeptions() {
        Boolean getNewSubscription = false;
        Boolean saveDeliveryAddress = false;
        Boolean saveBillingAddress = false;
        Boolean hasValidDeliveryAddress = false;
        Boolean saveAgreementSignature = false;
        Boolean createRecurlyAccount = false;
        Boolean submitPayment = false;

        Test.startTest();
            try { CheckoutController.getNewSubscription(null, null, null, null, null); } catch (Exception e) { getNewSubscription = true; }
            try { CheckoutController.saveDeliveryAddress(null, null); } catch (Exception e) { saveDeliveryAddress = true; }
            try { CheckoutController.saveBillingAddress(null, null); } catch (Exception e) { saveBillingAddress = true; }
            try { CheckoutController.hasValidDeliveryAddress(null); } catch (Exception e) { hasValidDeliveryAddress = true; }
            try { CheckoutController.saveAgreementSignature(null, null); } catch (Exception e) { saveAgreementSignature = true; }
            try { CheckoutController.createRecurlyAccount(null); } catch (Exception e) { createRecurlyAccount = true; }
            try { CheckoutController.submitPayment(null, null); } catch (Exception e) { submitPayment = true; }
        Test.stopTest();

        System.assertEquals(true, getNewSubscription);
        System.assertEquals(true, saveDeliveryAddress);
        System.assertEquals(true, saveBillingAddress);
        System.assertEquals(true, hasValidDeliveryAddress);
        System.assertEquals(true, saveAgreementSignature);
        System.assertEquals(true, createRecurlyAccount);
        System.assertEquals(true, submitPayment);
    }

    @isTest
    private static void test_saveDeliveryAddress() {
        TestDataFactory.createTestRecords(1);
        Subscription__c sub = [SELECT Id FROM Subscription__c LIMIT 1];

        Map<String, String> address = new Map<String, String>{
            'firstName' => 'firstName',
            'lastName' => 'lastName',
            'street' => 'street',
            'city' => 'city',
            'state' => 'state',
            'country' => 'country',
            'postalCode' => 'postalCode'
        };

        Test.startTest();
            CheckoutController.saveDeliveryAddress(sub.Id, address);
        Test.stopTest();

        Delivery_Address__c deliveryAddress = [SELECT Address_Street__c FROM Delivery_Address__c];

        System.assertEquals('street', deliveryAddress.Address_Street__c, 'Should have set the street');
    }

    @isTest
    private static void test_saveBillingAddress() {
        TestDataFactory.createTestRecords(1);
        Subscription__c sub = [SELECT Id FROM Subscription__c LIMIT 1];

        Map<String, String> address = new Map<String, String>{
            'firstName' => 'firstName',
            'lastName' => 'lastName',
            'street' => 'street',
            'city' => 'city',
            'state' => 'state',
            'country' => 'country',
            'postalCode' => 'postalCode'
        };

        Test.startTest();
            CheckoutController.saveBillingAddress(sub.Id, address);
        Test.stopTest();

        Contact cont = [SELECT FirstName FROM Contact];
        Account acct = [SELECT BillingStreet FROM Account];

        System.assertEquals('street', acct.BillingStreet, 'Should have set the street');
        System.assertEquals('firstName', cont.FirstName, 'Should have set the first name');
    }

    @isTest
    private static void test_hasValidDeliveryAddress() {
        TestDataFactory.createTestRecords(1);
        Subscription__c sub = [SELECT Id FROM Subscription__c LIMIT 1];
        Test.startTest();
            Boolean hasValidDeliveryAddress = CheckoutController.hasValidDeliveryAddress(sub.Id);
        Test.stopTest();

        System.assertEquals(true, hasValidDeliveryAddress, 'Delivery address should be valid');
    }

    @isTest
    private static void test_saveAgreementSignature() {
        TestDataFactory.createTestRecords(1);
        Subscription__c sub = [SELECT Id, SignatureURL__c FROM Subscription__c LIMIT 1];
        sub.SignatureURL__c = 'test,signature';
        update sub;
        Test.startTest();
            CheckoutController.saveAgreementSignature(sub.Id, 'test,signature');
        Test.stopTest();

        List<Attachment> newAttachments = [SELECT Id FROM Attachment WHERE ParentId = :sub.Id];

        System.assertEquals(1, newAttachments.size(), 'Attachment should exist');
    }

    @isTest 
    private static void test_createRecurlyAccount() {
        TestDataFactory.createTestRecords(1);
        Subscription__c sub = [SELECT Id FROM Subscription__c LIMIT 1];
        Test.startTest();
            Id recurlyAccountId = CheckoutController.createRecurlyAccount(sub.Id);
        Test.stopTest();

        System.assertEquals(true, recurlyAccountId != null, 'Recurly accoutn id should be set');
    }

    @isTest 
    private static void test_createRecurlyAccount_withException() {
        Test.startTest();
        Boolean hasException = false;
        try {
            CheckoutController.createRecurlyAccount(null);
        } catch (AuraHandledException e) {
            hasException = true;
        }
        Test.stopTest();
        System.assertEquals(true, hasException, 'Exception should be thrown if passing invalid subid');
    }


    @isTest
    private static void test_submitPayment_sendBill() {
        TestDataFactory.createTestRecords(1);
        Subscription__c sub = [SELECT Id FROM Subscription__c LIMIT 1];

        CheckoutPaymentInformation payment = new CheckoutPaymentInformation();
        payment.sendBill = true;
        payment.processPayment = false;
        payment.enableEzPay = false;

        Test.startTest();
            CheckoutController.submitPayment(sub.Id, JSON.serialize(payment));
        Test.stopTest();

        Subscription__c updatedSub = [SELECT Id, subscription_Current_Period_Ends_At__c, Outstanding_Credit__c FROM Subscription__c LIMIT 1];

        System.assertEquals(Date.today(), updatedSub.subscription_Current_Period_Ends_At__c, 'Current Period Ends at should be today');
        System.assertEquals(0, updatedSub.Outstanding_Credit__c, 'Outstanding credit should be 0');
    }

    @isTest
    private static void test_submitPayment_processPayment() {
        Test.setMock(HttpCalloutMock.class, new RecurlyApiMock());
        TestDataFactory.createTestRecords(1);
        Subscription__c sub = [SELECT Id FROM Subscription__c LIMIT 1];

        Id accountId = CheckoutController.createRecurlyAccount(sub.Id);

        CheckoutPaymentInformation payment = new CheckoutPaymentInformation();
        payment.sendBill = false;
        payment.processPayment = true;
        payment.enableEzPay = false;
        payment.subscriptionAmount = 10.0;
        payment.accountId = accountId;
        payment.billingToken = '1234';
        payment.waiveActivationFee = false;

        Test.startTest();
            CheckoutController.submitPayment(sub.Id, JSON.serialize(payment));
        Test.stopTest();

        System.assertEquals(true, true, '');
    }

    @isTest
    private static void test_submitPayment_enableEzPay() {
        Test.setMock(HttpCalloutMock.class, new RecurlyApiMock());
        TestDataFactory.createTestRecords(1);
        Subscription__c sub = [SELECT Id FROM Subscription__c LIMIT 1];

        Id accountId = CheckoutController.createRecurlyAccount(sub.Id);

        CheckoutPaymentInformation payment = new CheckoutPaymentInformation();
        payment.sendBill = false;
        payment.processPayment = false;
        payment.enableEzPay = true;
        payment.billingToken = '1234';
        payment.subscriptionAmount = 10.0;
        payment.accountId = accountId;
        payment.waiveActivationFee = false;

        Test.startTest();
            CheckoutController.submitPayment(sub.Id, JSON.serialize(payment));
        Test.stopTest();

        System.assertEquals(true, true, '');
    }
}