force-app/main/default/objects/Auth0ConnectionSettings__c/Auth0ConnectionSettings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Connection Details for Auth0 Rest Callouts in Auth0Connection Apex Class.</description>
    <label>Auth0ConnectionSettings</label>
</CustomObject>

force-app/main/default/objects/Auth0ConnectionSettings__c/fields/Audience__c.field-meta.xml
<CustomField>
        <fullName>Audience__c</fullName>
        <label>Audience</label>
        <length>100</length>
        <type>Text</type>
    </CustomField>

force-app/main/default/objects/Auth0ConnectionSettings__c/fields/Client_ID__c.field-meta.xml
<CustomField>
        <fullName>Client_ID__c</fullName>
        <label>Client ID</label>
        <length>100</length>
        <type>Text</type>
    </CustomField>

force-app/main/default/objects/Auth0ConnectionSettings__c/fields/Client_Secret__c.field-meta.xml
<CustomField>
        <fullName>Client_Secret__c</fullName>
        <label>Client Secret</label>
        <length>100</length>
        <type>Text</type>
    </CustomField>

force-app/main/default/objects/Auth0ConnectionSettings__c/fields/Connection__c.field-meta.xml
<CustomField>
        <fullName>Connection__c</fullName>
        <label>Connection</label>
        <length>100</length>
        <type>Text</type>
    </CustomField>

force-app/main/default/objects/Auth0ConnectionSettings__c/fields/Default_Password__c.field-meta.xml
<CustomField>
        <fullName>Default_Password__c</fullName>
        <label>Default Password</label>
        <length>100</length>
        <type>Text</type>
    </CustomField>

force-app/main/default/objects/Auth0ConnectionSettings__c/fields/Domain__c.field-meta.xml
<CustomField>
        <fullName>Domain__c</fullName>
        <label>Domain</label>
        <length>100</length>
        <type>Text</type>
    </CustomField>

force-app/main/default/objects/Auth0ConnectionSettings__c/fields/Grant_Type__c.field-meta.xml
<CustomField>
        <fullName>Grant_Type__c</fullName>
        <label>Grant Type</label>
        <length>100</length>
        <type>Text</type>
    </CustomField>

force-app/main/default/classes/Auth0ControllerTest.cls
@isTest
global class Auth0ControllerTest {
    @isTest
    private static void test_confirmPasswordReset() {
        Test.setMock(HttpCalloutMock.class, new Auth0Mock());
        
        Account acct = new Account(Name = 'Test Account');
        insert acct;

        Contact cont = new Contact(LastName = 'LastName', Email = 'test@test.com', AccountId = acct.Id);
        insert cont;

        Test.startTest();
            String success = Auth0Controller.confirmPasswordReset(cont.Id);
        Test.stopTest();

        System.assertEquals('SUCCESS', success, 'API Should pass back success');
    }

    @TestSetup
    static void setup() {
        Auth0ConnectionSettings__c setting = new Auth0ConnectionSettings__c(Default_Password__c = 'test', Audience__c = 'test', Client_Id__c = 'test', Client_Secret__c = 'test', Connection__c = 'test', Domain__c = 'test', Grant_Type__c = 'secret');
        insert setting;
    }
}