force-app/main/default/objects/Auth0ConnectionSettings__c/Auth0ConnectionSettings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Connection Details for Auth0 Rest Callouts in Auth0Connection Apex Class.</description>
    <label>Auth0ConnectionSettings</label>
</CustomObject>

force-app/main/default/objects/Auth0ConnectionSettings__c/fields/Audience__c.field-meta.xml
<CustomField>
        <fullName>Audience__c</fullName>
        <label>Audience</label>
        <length>100</length>
        <type>Text</type>
    </CustomField>

force-app/main/default/objects/Auth0ConnectionSettings__c/fields/Client_ID__c.field-meta.xml
<CustomField>
        <fullName>Client_ID__c</fullName>
        <label>Client ID</label>
        <length>100</length>
        <type>Text</type>
    </CustomField>

force-app/main/default/objects/Auth0ConnectionSettings__c/fields/Client_Secret__c.field-meta.xml
<CustomField>
        <fullName>Client_Secret__c</fullName>
        <label>Client Secret</label>
        <length>100</length>
        <type>Text</type>
    </CustomField>

force-app/main/default/objects/Auth0ConnectionSettings__c/fields/Connection__c.field-meta.xml
<CustomField>
        <fullName>Connection__c</fullName>
        <label>Connection</label>
        <length>100</length>
        <type>Text</type>
    </CustomField>

force-app/main/default/objects/Auth0ConnectionSettings__c/fields/Default_Password__c.field-meta.xml
<CustomField>
        <fullName>Default_Password__c</fullName>
        <label>Default Password</label>
        <length>100</length>
        <type>Text</type>
    </CustomField>

force-app/main/default/objects/Auth0ConnectionSettings__c/fields/Domain__c.field-meta.xml
<CustomField>
        <fullName>Domain__c</fullName>
        <label>Domain</label>
        <length>100</length>
        <type>Text</type>
    </CustomField>

force-app/main/default/objects/Auth0ConnectionSettings__c/fields/Grant_Type__c.field-meta.xml
<CustomField>
        <fullName>Grant_Type__c</fullName>
        <label>Grant Type</label>
        <length>100</length>
        <type>Text</type>
    </CustomField>

force-app/main/default/classes/Auth0ConnectionTest.cls
/*
* -----------------------------------------------------------
* Apex Class Name: Auth0ConnectionTest
* -----------------------------------------------------------
* Description: Tests Auth0Connection.apxc. Uses mock class - Auth0ConnectionMock.apxc
* -----------------------------------------------------------
* Created by: Mitchell McLaughlin, RelationEdge
*/
@isTest
private class Auth0ConnectionTest {
    @testSetup static void setup(){
    Auth0ConnectionSettings__c mockSettings = new Auth0ConnectionSettings__c(
            Default_Password__c = 'password',
            Audience__c = 'audience',
            Domain__c = 'domain',
            Grant_Type__c = 'grantType',
            Client_Id__c = 'clientId',
            Client_Secret__c = 'clientSecret',
            Connection__c = 'connection');
            insert mockSettings;
    }
    @isTest static void shouldGetUsers() {
       Auth0Connection auth0 = new Auth0Connection();
       auth0.getUser('test123');
       auth0.getUserIdByEmail('test123');
    }   

}