force-app/main/default/objects/Account/recordTypes/Household.recordType-meta.xml
<RecordType>
        <fullName>Household</fullName>
        <active>true</active>
        <description>Household Subscriber or Prospect Record Type</description>
        <label>Household</label>
    </RecordType>

force-app/main/default/objects/Contact/fields/Status__c.field-meta.xml
<CustomField>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </CustomField>

force-app/main/default/objects/Email_Subscriber__c/Email_Subscriber__c.object-meta.xml
<CustomObject>
    <label>Email Subscriber</label>
    <nameField>
        <displayFormat>ESN-{0000}</displayFormat>
        <label>Email Subscriber Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Email Subscribers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Email_Subscriber__c/fields/Contact__c.field-meta.xml
<CustomField>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Email Subscribers</relationshipLabel>
        <relationshipName>Email_Subscribers</relationshipName>
        <type>Lookup</type>
    </CustomField>

force-app/main/default/objects/Email_Subscriber__c/fields/Email_Subscription__c.field-meta.xml
<CustomField>
        <fullName>Email_Subscription__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Email Subscription</label>
        <referenceTo>Email_Subscription__c</referenceTo>
        <relationshipLabel>Email Subscribers</relationshipLabel>
        <relationshipName>Email_Subscribers</relationshipName>
        <type>Lookup</type>
    </CustomField>

force-app/main/default/objects/Email_Subscriber__c/fields/Status__c.field-meta.xml
<CustomField>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Subscribed</fullName>
                </value>
                <value>
                    <fullName>Unsubscribed</fullName>
                </value>
                <value>
                    <fullName>No Preference</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </CustomField>

force-app/main/default/objects/Email_Subscriber__c/fields/Subscribe_Date__c.field-meta.xml
<CustomField>
        <fullName>Subscribe_Date__c</fullName>
        <label>Subscribe Date</label>
        <type>Date</type>
    </CustomField>

force-app/main/default/objects/Email_Subscription__c/Email_Subscription__c.object-meta.xml
<CustomObject>
    <label>Email Subscription</label>
    <nameField>
        <label>Email Subscription Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Email Subscriptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/ManageSubscriptionsControllerTest.cls
@isTest
public with sharing class ManageSubscriptionsControllerTest {

    static testMethod void testManageSubController(){

        Id contactRecType = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('Subscriber Contact').getRecordTypeId();
        Id accRecType = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Household').getRecordTypeId();

        //Create Household Account
        Account a = new Account();
        a.name = 'Lady Test Household';
        a.RecordTypeId = accRecType;
        insert a;

        //Create Contact
        Contact c = new Contact();
        c.RecordTypeId = contactRecType;
        c.FirstName = 'Lady';
        c.LastName = 'Test';
        c.AccountId = a.id;
        insert c;

        //Create Email Subscription
        List<Email_Subscription__c> eSubscriptions = New List<Email_Subscription__c>();
        Email_Subscription__c subscription = New Email_Subscription__c();
        subscription.Name = 'Events';
        eSubscriptions.add(subscription);

        Email_Subscription__c subscription2 = New Email_Subscription__c();
        subscription2.Name = 'Promotions';
        eSubscriptions.add(subscription2);

        insert eSubscriptions;

        //Create Email Subscribers
        List<Email_Subscriber__c> eSubscribers = New List<Email_Subscriber__c>();
        Email_Subscriber__c subscriber = New Email_Subscriber__c();
        //subscriber.Name = 'Test Email Subscriber';
        subscriber.Email_Subscription__c = eSubscriptions[0].id;
        subscriber.Contact__c = c.id;
        subscriber.Subscribe_Date__c = system.today();
        subscriber.Status__c = 'Subscribed';

        eSubscribers.add(subscriber);

        Email_Subscriber__c subscriber2 = New Email_Subscriber__c();
        subscriber2.Email_Subscription__c = eSubscriptions[1].id;
        subscriber2.Contact__c = c.id;
        subscriber2.Subscribe_Date__c = system.today();
        subscriber2.Status__c = 'Subscribed';

        eSubscribers.add(subscriber2);
        insert eSubscribers;

        ManageSubscriptionsController cntrl = new ManageSubscriptionsController();
        cntrl.contactid = c.id;
        cntrl.UpdateSubscriptions();
        cntrl.unsubscribe();
        cntrl.unsubscribeToAll();
        cntrl.status = 'Subscribed';
        cntrl.subscriberid = subscriber.id;
        cntrl.UpdateStatus();
        cntrl.status = 'Unsubscribed';
        cntrl.subscriberid = subscriber.id;
        cntrl.UpdateStatus();
        cntrl.Submit();




    }
}