force-app/main/default/objects/Account/recordTypes/Household.recordType-meta.xml
<RecordType>
        <fullName>Household</fullName>
        <active>true</active>
        <description>Household Subscriber or Prospect Record Type</description>
        <label>Household</label>
    </RecordType>

force-app/main/default/objects/Contact/fields/Auth0_User_Id__c.field-meta.xml
<CustomField>
        <fullName>Auth0_User_Id__c</fullName>
        <label>Auth0 User Id</label>
        <length>255</length>
        <type>Text</type>
    </CustomField>

force-app/main/default/objects/Contact/fields/Source__c.field-meta.xml
<CustomField>
        <fullName>Source__c</fullName>
        <label>Source</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Web</fullName>
                </value>
                <value>
                    <fullName>Kiosk</fullName>
                </value>
                <value>
                    <fullName>CSR</fullName>
                </value>
                <value>
                    <fullName>Registered</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </CustomField>

force-app/main/default/objects/Offer__c/Offer__c.object-meta.xml
<CustomObject>
    <description>Controls price, delivery, term for a subscription including print, digital and alternate publications. Also holds links to the premiums offered and the campaigns which will utilize this offer.</description>
    <label>Offer</label>
    <nameField>
        <label>Offer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Offers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Offer__c/fields/Free_Trial__c.field-meta.xml
<CustomField>
        <fullName>Free_Trial__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This field is used to denote whether this offer is a free trial offer</description>
        <label>Free Trial?</label>
        <type>Checkbox</type>
    </CustomField>

force-app/main/default/objects/Offer_Product__c/Offer_Product__c.object-meta.xml
<CustomObject>
    <label>Offer Product</label>
    <nameField>
        <label>Offer Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Offer Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Offer_Product__c/fields/Is_Digital__c.field-meta.xml
<CustomField>
        <fullName>Is_Digital__c</fullName>
        <formula>Product__r.IsDigital__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Is Digital</label>
        <type>Checkbox</type>
    </CustomField>

force-app/main/default/objects/Offer_Product__c/fields/Offer__c.field-meta.xml
<CustomField>
        <fullName>Offer__c</fullName>
        <label>Offer</label>
        <referenceTo>Offer__c</referenceTo>
        <relationshipLabel>Offer Products</relationshipLabel>
        <relationshipName>Offer_Products</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </CustomField>

force-app/main/default/objects/Subscription__c/Subscription__c.object-meta.xml
<CustomObject>
    <description>This object stores the actual subscription details, including selected Offer, Premiums. Delivery Schedules, frequency and term.</description>
    <label>Subscription</label>
    <nameField>
        <displayFormat>Sub-{0000}</displayFormat>
        <label>Subscription Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Subscription__c/fields/Contact__c.field-meta.xml
<CustomField>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Subscriptions</relationshipLabel>
        <relationshipName>Subscriptions</relationshipName>
        <type>Lookup</type>
    </CustomField>

force-app/main/default/objects/Subscription__c/fields/Ready_for_DSI__c.field-meta.xml
<CustomField>
        <fullName>Ready_for_DSI__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Ready for DSI</label>
        <type>Checkbox</type>
    </CustomField>

force-app/main/default/objects/Subscription__c/fields/Source__c.field-meta.xml
<CustomField>
        <fullName>Source__c</fullName>
        <label>Source</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Source</valueSetName>
        </valueSet>
    </CustomField>

force-app/main/default/objects/Subscription__c/fields/Source_Campaign__c.field-meta.xml
<CustomField>
        <fullName>Source_Campaign__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Source Campaign</label>
        <referenceTo>Campaign</referenceTo>
        <relationshipLabel>Subscriptions</relationshipLabel>
        <relationshipName>Subscriptions</relationshipName>
        <type>Lookup</type>
    </CustomField>

force-app/main/default/objects/Subscription__c/fields/subscription_Account__c.field-meta.xml
<CustomField>
        <fullName>subscription_Account__c</fullName>
        <description>Relationship between Account and Subscriptions</description>
        <label>Household Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Subscriptions</relationshipLabel>
        <relationshipName>Subscriptions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </CustomField>

force-app/main/default/objects/Subscription__c/fields/subscription_Current_Period_Ends_At__c.field-meta.xml
<CustomField>
        <fullName>subscription_Current_Period_Ends_At__c</fullName>
        <description>Stores the date and time when the current subscription ends</description>
        <inlineHelpText>See the "Expires On" field below to see End date + Grace Days</inlineHelpText>
        <label>End Date</label>
        <type>Date</type>
    </CustomField>

force-app/main/default/objects/Subscription__c/fields/subscription_Current_Period_Started_At__c.field-meta.xml
<CustomField>
        <fullName>subscription_Current_Period_Started_At__c</fullName>
        <description>Stores the date and time the current subscription started</description>
        <label>Start Date</label>
        <type>Date</type>
    </CustomField>

force-app/main/default/objects/Subscription__c/fields/subscription_Offer__c.field-meta.xml
<CustomField>
        <fullName>subscription_Offer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Stores the relationship to Offer</description>
        <label>Offer</label>
        <referenceTo>Offer__c</referenceTo>
        <relationshipLabel>Subscriptions</relationshipLabel>
        <relationshipName>Subscriptions1</relationshipName>
        <type>Lookup</type>
    </CustomField>

force-app/main/default/objects/Subscription__c/fields/subscription_Status__c.field-meta.xml
<CustomField>
        <fullName>subscription_Status__c</fullName>
        <description>Stores the status of the subscription</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>New</fullName>
                </value>
                <value>
                    <fullName>TERMINATED</fullName>
                </value>
                <value>
                    <fullName>INACTIVE</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </CustomField>

force-app/main/default/objects/Subscription__c/fields/Waive_Activation_Fee__c.field-meta.xml
<CustomField>
        <fullName>Waive_Activation_Fee__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Waive Activation Fee</label>
        <type>Checkbox</type>
    </CustomField>

force-app/main/default/objects/Transaction_Log__c/Transaction_Log__c.object-meta.xml
<CustomObject>
    <label>Transaction Log</label>
    <nameField>
        <displayFormat>TL-{0000}</displayFormat>
        <label>Transaction Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transaction Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Transaction_Log__c/fields/Category__c.field-meta.xml
<CustomField>
        <fullName>Category__c</fullName>
        <description>The Category of this transaction</description>
        <label>Category</label>
        <length>25</length>
        <type>Text</type>
    </CustomField>

force-app/main/default/objects/Transaction_Log__c/fields/Contact__c.field-meta.xml
<CustomField>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Transaction Logs</relationshipLabel>
        <relationshipName>Transaction_Logs</relationshipName>
        <type>Lookup</type>
    </CustomField>

force-app/main/default/objects/Transaction_Log__c/fields/First_Date__c.field-meta.xml
<CustomField>
        <fullName>First_Date__c</fullName>
        <label>First Date</label>
        <type>Date</type>
    </CustomField>

force-app/main/default/objects/Transaction_Log__c/fields/Last_Date__c.field-meta.xml
<CustomField>
        <fullName>Last_Date__c</fullName>
        <label>Last Date</label>
        <type>Date</type>
    </CustomField>

force-app/main/default/objects/Transaction_Log__c/fields/Memo__c.field-meta.xml
<CustomField>
        <fullName>Memo__c</fullName>
        <label>Memo</label>
        <type>TextArea</type>
    </CustomField>

force-app/main/default/objects/Transaction_Log__c/fields/Offer__c.field-meta.xml
<CustomField>
        <fullName>Offer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Offer</label>
        <referenceTo>Offer__c</referenceTo>
        <relationshipLabel>Transaction Logs</relationshipLabel>
        <relationshipName>Transaction_Logs</relationshipName>
        <type>Lookup</type>
    </CustomField>

force-app/main/default/objects/Transaction_Log__c/fields/Offer_Product__c.field-meta.xml
<CustomField>
        <fullName>Offer_Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Offer Product</label>
        <referenceTo>Offer_Product__c</referenceTo>
        <relationshipLabel>Transaction Logs</relationshipLabel>
        <relationshipName>Transaction_Logs</relationshipName>
        <type>Lookup</type>
    </CustomField>

force-app/main/default/objects/Transaction_Log__c/fields/Source__c.field-meta.xml
<CustomField>
        <fullName>Source__c</fullName>
        <label>Source</label>
        <length>255</length>
        <type>Text</type>
    </CustomField>

force-app/main/default/objects/Transaction_Log__c/fields/Subscription__c.field-meta.xml
<CustomField>
        <fullName>Subscription__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Subscription</label>
        <referenceTo>Subscription__c</referenceTo>
        <relationshipLabel>Transaction Logs</relationshipLabel>
        <relationshipName>Transaction_Logs</relationshipName>
        <type>Lookup</type>
    </CustomField>

force-app/main/default/objects/Transaction_Log__c/fields/Transaction_Type__c.field-meta.xml
<CustomField>
        <fullName>Transaction_Type__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Transaction Type</label>
        <referenceTo>Transaction_Type__c</referenceTo>
        <relationshipLabel>Transaction Logs</relationshipLabel>
        <relationshipName>Transaction_Logs</relationshipName>
        <type>Lookup</type>
    </CustomField>

force-app/main/default/objects/Transaction_Type__c/Transaction_Type__c.object-meta.xml
<CustomObject>
    <label>Transaction Type</label>
    <nameField>
        <label>Transaction Type Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Transaction Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Transaction_Type__c/fields/Category__c.field-meta.xml
<CustomField>
        <fullName>Category__c</fullName>
        <inlineHelpText>Choose appropriate for transaction viewer</inlineHelpText>
        <label>Category</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Carrier Me</fullName>
                </value>
                <value>
                    <fullName>CC_Request</fullName>
                </value>
                <value>
                    <fullName>Complaint</fullName>
                </value>
                <value>
                    <fullName>Credit_Card</fullName>
                </value>
                <value>
                    <fullName>Journal</fullName>
                </value>
                <value>
                    <fullName>Memo</fullName>
                </value>
                <value>
                    <fullName>Message</fullName>
                </value>
                <value>
                    <fullName>Move</fullName>
                </value>
                <value>
                    <fullName>Product Change</fullName>
                </value>
                <value>
                    <fullName>Start</fullName>
                </value>
                <value>
                    <fullName>Stop</fullName>
                </value>
                <value>
                    <fullName>Vacation Pack</fullName>
                </value>
                <value>
                    <fullName>VH</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </CustomField>

force-app/main/default/globalValueSets/Source.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>A1</fullName>
    </customValue>
    <customValue>
        <fullName>BM</fullName>
    </customValue>
    <customValue>
        <fullName>BR</fullName>
    </customValue>
    <customValue>
        <fullName>CG</fullName>
    </customValue>
    <customValue>
        <fullName>CR</fullName>
    </customValue>
    <customValue>
        <fullName>CW</fullName>
    </customValue>
    <customValue>
        <fullName>DC</fullName>
    </customValue>
    <customValue>
        <fullName>DG</fullName>
    </customValue>
    <customValue>
        <fullName>DM</fullName>
    </customValue>
    <customValue>
        <fullName>EM</fullName>
    </customValue>
    <customValue>
        <fullName>ES</fullName>
    </customValue>
    <customValue>
        <fullName>FD</fullName>
    </customValue>
    <customValue>
        <fullName>GS</fullName>
    </customValue>
    <customValue>
        <fullName>HR</fullName>
    </customValue>
    <customValue>
        <fullName>IP</fullName>
    </customValue>
    <customValue>
        <fullName>KI</fullName>
    </customValue>
    <customValue>
        <fullName>ME</fullName>
    </customValue>
    <customValue>
        <fullName>MK</fullName>
    </customValue>
    <customValue>
        <fullName>MN</fullName>
    </customValue>
    <customValue>
        <fullName>MS</fullName>
    </customValue>
    <customValue>
        <fullName>MV</fullName>
    </customValue>
    <customValue>
        <fullName>NL</fullName>
    </customValue>
    <customValue>
        <fullName>OL</fullName>
    </customValue>
    <customValue>
        <fullName>OS</fullName>
    </customValue>
    <customValue>
        <fullName>PA</fullName>
    </customValue>
    <customValue>
        <fullName>PD</fullName>
    </customValue>
    <customValue>
        <fullName>PM</fullName>
    </customValue>
    <customValue>
        <fullName>PO</fullName>
    </customValue>
    <customValue>
        <fullName>PR</fullName>
    </customValue>
    <customValue>
        <fullName>PS</fullName>
    </customValue>
    <description>Subscription Source</description>
    <masterLabel>Source</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/CheckoutSubscriptionCreator.cls
public with sharing class CheckoutSubscriptionCreator {
    public static Subscription__c getNewSubscription(String offerId, String email, String source, String password, Boolean waiveActivationFee, String SourceCampaign) {
        Offer__c offer = OfferDataAccessor.getOfferById(offerId);
        Subscription__c subscription = getSubscription(offer, email, source, password, waiveActivationFee, SourceCampaign);
        new SubscriptionCampaign(subscription).setNewSubscriptionCampaign();
        return subscription;
    }

    private static Subscription__c getSubscription(Offer__c offer, String email, String source, String password, Boolean waiveActivationFee, String SourceCampaign) {
        List<Subscription__c> existingSubscriptions = SubscriptionDataAccessor.getSubscriptionsByEmail(email);
        if (!existingSubscriptions.isEmpty()) {
            return getExistingSubscription(existingSubscriptions, offer, waiveActivationFee, SourceCampaign);
        }
        return createDefaultSubscription(offer, email, source, password, waiveActivationFee, SourceCampaign);
    }

    private static Subscription__c getExistingSubscription(List<Subscription__c> existingSubscriptions, Offer__c offer, Boolean waiveActivationFee, String SourceCampaign) {
        for (Subscription__c subscription : existingSubscriptions) {
            if (subscription.subscription_Status__c == 'Active') {
                throw new GenericException('This email already has an active subscription');
            } 
        }
        Subscription__c subscription = existingSubscriptions[0];
        setSubscription(subscription, offer, null, waiveActivationFee, subscription.subscription_Status__c, SourceCampaign);
        update subscription;
        System.debug('here');
        if (subscription.subscription_Status__c != 'New' && isDigitalOnly(offer)) {
            createStartRestartTransaction(offer, subscription);
        }
        return SubscriptionDataAccessor.getSubscriptionById(subscription.Id);
    }

    private static Auth0Manager.AuthUser getAuth0Account(String email, String password) {
        Auth0Manager authManager = new Auth0Manager();
        List<Auth0Manager.AuthUser> authAccounts = authManager.getUsersByEmail(email);
        if (authAccounts.isEmpty()) {
            Auth0Manager.AuthUser authAccount = authManager.createUser(new Map<String, Object>{'email' => email, 'password' => password});
            if (authAccount != null) {
                authAccounts.add(authAccount);
            }
        }
        if (authAccounts.isEmpty()) {
            throw new GenericException('Failed to create authentication account');
        }
        return authAccounts[0];
    }

    private static Subscription__c createDefaultSubscription(Offer__c offer, String email, String source, 
				String password, Boolean waiveActivationFee, String SourceCampaign) {
        // If existing contact exists then use that otherwise create a new default contact/account
        List<Contact> existingContacts = ContactDataAccessor.getContactsByEmail(email);
        if (existingContacts.isEmpty()) {
            Auth0Manager authManager = new Auth0Manager();
            Auth0Manager.AuthUser authAccount = getAuth0Account(email, password);

            Account subscriberAccount = new Account(Name = 'New Subscriber Household');
            insert subscriberAccount;

            Contact subscriberContact = new Contact(FirstName = 'New', LastName = 'Subscriber', Email = email, AccountId = subscriberAccount.Id, Auth0_User_Id__c = (String)authAccount.user_id);
            insert subscriberContact;

            existingContacts.add(subscriberContact);
        }

        Contact subscriberContact = existingContacts[0];
        subscriberContact.Source__c = source;
        upsert subscriberContact;
        
        // Create new default subscription
        Subscription__c subscription = new Subscription__c();
        setSubscription(subscription, offer, subscriberContact, waiveActivationFee, 'New', SourceCampaign);
        insert subscription;

        if (isDigitalOnly(offer)) {
            createStartRestartTransaction(offer, subscription);
        }

        return SubscriptionDataAccessor.getSubscriptionById(subscription.Id);
    }

    private static void createStartRestartTransaction(Offer__c offer, Subscription__c subscription) {
        try {
            Transaction_Type__c vrType = TransactionDataAccessor.getFirstTransactionTypeByCode(System.Label.SubscriptionNewStartRestartTransactionCode);
            insert new Transaction_Log__c(Memo__c = 'Start/Restart Digital Only', Offer__c = offer.Id, First_Date__c = Date.Today(), Last_Date__c = Date.Today(), Subscription__c = subscription.Id, Category__c = 'Start', Transaction_Type__c = vrType.Id);
        } catch (Exception e) {
            System.debug(e.getMessage() + ' ' + e.getStackTraceString());
        }
    }

    private static void setSubscription(Subscription__c subscription, Offer__c offer, Contact subscriberContact, Boolean waiveActivationFee, String status, String SourceCampaign) {
        subscription.subscription_Status__c = status;
        subscription.subscription_Offer__c = offer.Id;
        subscription.Waive_Activation_Fee__c = waiveActivationFee;
		subscription.Source_Campaign__c = SourceCampaign;
        if (subscriberContact != null) {
            subscription.Contact__c = (subscriberContact != null) ? subscriberContact.Id : null;
            subscription.subscription_Account__c = (subscriberContact != null) ? subscriberContact.AccountId : null;
        }
        if (offer.Free_Trial__c) {
            subscription.subscription_Status__c = 'Active';
            subscription.subscription_Current_Period_Started_At__c = Date.today();
            subscription.subscription_Current_Period_Ends_At__c = Date.today().addDays(Integer.valueOf(Label.Free_Trial_Days));
        }
        if (!isDigitalOnly(offer)) {
            subscription.Ready_for_DSI__c = true;
        }
    }

    private static Boolean isDigitalOnly(Offer__c offer) {
        for (Offer_Product__c product : offer.Offer_Products__r) {
            if (!product.Is_Digital__c) {
                return false;
            }
        }
        return true;
    }
}