force-app/main/default/objects/Delivery_Schedule__c/Delivery_Schedule__c.object-meta.xml
<CustomObject>
    <description>Deliver Schedules control the address and which days a publication will be delivered as part of the press run.</description>
    <label>Delivery Schedule</label>
    <nameField>
        <displayFormat>DS-{0}</displayFormat>
        <label>Delivery Schedule Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Delivery Schedules</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Delivery_Schedule__c/fields/District__c.field-meta.xml
<CustomField>
        <fullName>District__c</fullName>
        <label>District</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>105</fullName>
                </value>
                <value>
                    <fullName>108</fullName>
                </value>
                <value>
                    <fullName>110</fullName>
                </value>
                <value>
                    <fullName>111</fullName>
                </value>
                <value>
                    <fullName>112</fullName>
                </value>
                <value>
                    <fullName>113</fullName>
                </value>
                <value>
                    <fullName>114</fullName>
                </value>
                <value>
                    <fullName>117</fullName>
                </value>
                <value>
                    <fullName>118</fullName>
                </value>
                <value>
                    <fullName>119</fullName>
                </value>
                <value>
                    <fullName>121</fullName>
                </value>
                <value>
                    <fullName>127</fullName>
                </value>
                <value>
                    <fullName>148</fullName>
                </value>
                <value>
                    <fullName>218</fullName>
                </value>
                <value>
                    <fullName>245</fullName>
                </value>
                <value>
                    <fullName>252</fullName>
                </value>
                <value>
                    <fullName>255</fullName>
                </value>
                <value>
                    <fullName>366</fullName>
                </value>
                <value>
                    <fullName>367</fullName>
                </value>
                <value>
                    <fullName>368</fullName>
                </value>
                <value>
                    <fullName>392</fullName>
                </value>
                <value>
                    <fullName>399</fullName>
                </value>
                <value>
                    <fullName>492</fullName>
                </value>
                <value>
                    <fullName>495</fullName>
                </value>
                <value>
                    <fullName>499</fullName>
                </value>
                <value>
                    <fullName>593</fullName>
                </value>
                <value>
                    <fullName>608</fullName>
                </value>
                <value>
                    <fullName>609</fullName>
                </value>
                <value>
                    <fullName>612</fullName>
                </value>
                <value>
                    <fullName>613</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </CustomField>

force-app/main/default/objects/Delivery_Schedule__c/fields/Offer_Product__c.field-meta.xml
<CustomField>
        <fullName>Offer_Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Offer Product</label>
        <referenceTo>Offer_Product__c</referenceTo>
        <relationshipLabel>Delivery Schedules</relationshipLabel>
        <relationshipName>Delivery_Schedules</relationshipName>
        <type>Lookup</type>
    </CustomField>

force-app/main/default/objects/Delivery_Schedule__c/fields/Routelookup__c.field-meta.xml
<CustomField>
        <fullName>Routelookup__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Route</label>
        <referenceTo>Route__c</referenceTo>
        <relationshipLabel>Delivery Schedules</relationshipLabel>
        <relationshipName>Delivery_Schedules</relationshipName>
        <type>Lookup</type>
    </CustomField>

force-app/main/default/objects/Delivery_Schedule__c/fields/subscription_Subscription__c.field-meta.xml
<CustomField>
        <fullName>subscription_Subscription__c</fullName>
        <description>This fields lookups to the shadow object, Subscription</description>
        <label>Subscription</label>
        <referenceTo>Subscription__c</referenceTo>
        <relationshipLabel>Delivery Schedules</relationshipLabel>
        <relationshipName>Delivery_Schedules</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </CustomField>

force-app/main/default/objects/Offer_Product__c/Offer_Product__c.object-meta.xml
<CustomObject>
    <label>Offer Product</label>
    <nameField>
        <label>Offer Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Offer Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Route__c/Route__c.object-meta.xml
<CustomObject>
    <label>Route</label>
    <nameField>
        <label>Route Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Route</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Route__c/fields/Complaints_Allowed__c.field-meta.xml
<CustomField>
        <fullName>Complaints_Allowed__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Complaints Allowed</label>
        <type>Checkbox</type>
    </CustomField>

force-app/main/default/objects/Route__c/fields/District__c.field-meta.xml
<CustomField>
        <fullName>District__c</fullName>
        <label>District</label>
        <length>25</length>
        <type>Text</type>
    </CustomField>

force-app/main/default/objects/Route__c/fields/Redelivery_Allowed__c.field-meta.xml
<CustomField>
        <fullName>Redelivery_Allowed__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Redelivery Allowed</label>
        <type>Checkbox</type>
    </CustomField>

force-app/main/default/objects/Route_Delay__c/Route_Delay__c.object-meta.xml
<CustomObject>
    <label>Route Delay</label>
    <nameField>
        <displayFormat>Delay{0000}</displayFormat>
        <label>Delay Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Route Delays</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Route_Delay__c/fields/District_From__c.field-meta.xml
<CustomField>
        <fullName>District_From__c</fullName>
        <label>District From</label>
        <length>3</length>
        <type>Text</type>
    </CustomField>

force-app/main/default/objects/Route_Delay__c/fields/District_Match__c.field-meta.xml
<CustomField>
        <fullName>District_Match__c</fullName>
        <description>District From and District Until match flag</description>
        <formula>IF(isBlank(District_From__c),false,
IF(isBlank(District_Until__c),false,
IF(District_From__c == District_Until__c, true, false)))</formula>
        <inlineHelpText>District From and District Until match flag</inlineHelpText>
        <label>District Match</label>
        <type>Checkbox</type>
    </CustomField>

force-app/main/default/objects/Route_Delay__c/fields/District_Until__c.field-meta.xml
<CustomField>
        <fullName>District_Until__c</fullName>
        <label>District Until</label>
        <length>3</length>
        <type>Text</type>
    </CustomField>

force-app/main/default/objects/Subscription__c/Subscription__c.object-meta.xml
<CustomObject>
    <description>This object stores the actual subscription details, including selected Offer, Premiums. Delivery Schedules, frequency and term.</description>
    <label>Subscription</label>
    <nameField>
        <displayFormat>Sub-{0000}</displayFormat>
        <label>Subscription Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Subscription__c/fields/Delivery_Schedule__c.field-meta.xml
<CustomField>
        <fullName>Delivery_Schedule__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Stores the relationship between Subscriptions and Delivery Schedule</description>
        <label>Delivery Schedule</label>
        <referenceTo>Delivery_Schedule__c</referenceTo>
        <relationshipLabel>Subscriptions</relationshipLabel>
        <relationshipName>Subscriptions</relationshipName>
        <type>Lookup</type>
    </CustomField>

force-app/main/default/objects/Subscription__c/fields/subscription_Account__c.field-meta.xml
<CustomField>
        <fullName>subscription_Account__c</fullName>
        <description>Relationship between Account and Subscriptions</description>
        <label>Household Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Subscriptions</relationshipLabel>
        <relationshipName>Subscriptions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </CustomField>

force-app/main/default/objects/Transaction_Log__c/Transaction_Log__c.object-meta.xml
<CustomObject>
    <label>Transaction Log</label>
    <nameField>
        <displayFormat>TL-{0000}</displayFormat>
        <label>Transaction Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transaction Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Transaction_Log__c/fields/Date__c.field-meta.xml
<CustomField>
        <fullName>Date__c</fullName>
        <label>Date</label>
        <type>Date</type>
    </CustomField>

force-app/main/default/objects/Transaction_Log__c/fields/Offer_Product__c.field-meta.xml
<CustomField>
        <fullName>Offer_Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Offer Product</label>
        <referenceTo>Offer_Product__c</referenceTo>
        <relationshipLabel>Transaction Logs</relationshipLabel>
        <relationshipName>Transaction_Logs</relationshipName>
        <type>Lookup</type>
    </CustomField>

force-app/main/default/classes/ServiceInfo.cls
public class ServiceInfo {
    public String Account {get;set;}
    public String ProductName {get;set;}
    public String ServiceType {get;set;}
    public String AllowComplaints {get;set;}
    public String ReDeliverableRoute {get;set;}
    public String RouteLate {get;set;}
    public String LastComplaint {get;set;}
    public String ExistingComplaint {get;set;}
    public String ExcessiveComplaint {get;set;}
    public String Cutoff {get;set;}

    private transient DeliverySchedule deliverySchedule;

    public ServiceInfo(Delivery_Schedule__c schedule) {
        this.deliverySchedule = new DeliverySchedule(schedule);

        Transaction_Log__c latestComplaint = deliverySchedule.getLastestComplaint();
        Date latestComplaintDate = latestComplaint != null ? latestComplaint.Date__c : null;

        this.Account = schedule.subscription_Subscription__r.subscription_Account__c;
        this.ProductName = schedule.Offer_Product__r.Name;
        this.ServiceType = deliverySchedule.getScheduleForWeek();
        // check value from Route linked to the Delivery schedule
        this.AllowComplaints = (schedule.Routelookup__r.Complaints_Allowed__c) ? 'Y' : 'N';
        // check value from Route linked to the Delivery schedule
        this.ReDeliverableRoute = (schedule.Routelookup__r.Redelivery_Allowed__c) ? 'Y' : 'N';

        // check conditions to set RouteLate output parameter
        String txtDistrict = schedule.Routelookup__r.District__c;
        List<Route_Delay__c> rtDelayDistricts = [SELECT Id, District_From__c,District_Until__c FROM Route_Delay__c 
                                                WHERE (District_From__c = :txtDistrict OR District_Until__c = :txtDistrict) 
                                                AND District_Match__c = true];
        Boolean rtDistFlag = !rtDelayDistricts.isEmpty();
        
        Boolean rtRouteNumFlag = deliverySchedule.hasRouteNumInRange();
        Boolean rtLateCheck = deliverySchedule.hasRouteDelayRec() || rtDistFlag || rtRouteNumFlag;
        this.RouteLate = rtLateCheck ? 'Y' : 'N';

        this.LastComplaint = (latestComplaintDate != null) ? latestComplaintDate.format() : null;
        this.ExistingComplaint = (latestComplaintDate != null && latestComplaintDate == Date.today()) ? 'Y' : 'N';
        this.ExcessiveComplaint = deliverySchedule.hasEscalatedCases() ? 'Y' : 'N';
        this.Cutoff = deliverySchedule.getTodayCutoffTime();
    }
}