force-app/main/default/objects/Delivery_Schedule__c/Delivery_Schedule__c.object-meta.xml
<CustomObject>
    <description>Deliver Schedules control the address and which days a publication will be delivered as part of the press run.</description>
    <label>Delivery Schedule</label>
    <nameField>
        <displayFormat>DS-{0}</displayFormat>
        <label>Delivery Schedule Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Delivery Schedules</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Delivery_Schedule__c/fields/Day_Friday__c.field-meta.xml
<CustomField>
        <fullName>Day_Friday__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Friday</label>
        <type>Checkbox</type>
    </CustomField>

force-app/main/default/objects/Delivery_Schedule__c/fields/Day_Monday__c.field-meta.xml
<CustomField>
        <fullName>Day_Monday__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Monday</label>
        <type>Checkbox</type>
    </CustomField>

force-app/main/default/objects/Delivery_Schedule__c/fields/Day_Saturday__c.field-meta.xml
<CustomField>
        <fullName>Day_Saturday__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Saturday</label>
        <type>Checkbox</type>
    </CustomField>

force-app/main/default/objects/Delivery_Schedule__c/fields/Day_Sunday__c.field-meta.xml
<CustomField>
        <fullName>Day_Sunday__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Sunday</label>
        <type>Checkbox</type>
    </CustomField>

force-app/main/default/objects/Delivery_Schedule__c/fields/Day_Thursday__c.field-meta.xml
<CustomField>
        <fullName>Day_Thursday__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Thursday</label>
        <type>Checkbox</type>
    </CustomField>

force-app/main/default/objects/Delivery_Schedule__c/fields/Day_Tuesday__c.field-meta.xml
<CustomField>
        <fullName>Day_Tuesday__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Tuesday</label>
        <type>Checkbox</type>
    </CustomField>

force-app/main/default/objects/Delivery_Schedule__c/fields/Day_Wednesday__c.field-meta.xml
<CustomField>
        <fullName>Day_Wednesday__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Wednesday</label>
        <type>Checkbox</type>
    </CustomField>

force-app/main/default/objects/Delivery_Schedule__c/fields/Route__c.field-meta.xml
<CustomField>
        <fullName>Route__c</fullName>
        <label>Route</label>
        <length>100</length>
        <type>Text</type>
    </CustomField>

force-app/main/default/objects/Delivery_Schedule__c/fields/Routelookup__c.field-meta.xml
<CustomField>
        <fullName>Routelookup__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Route</label>
        <referenceTo>Route__c</referenceTo>
        <relationshipLabel>Delivery Schedules</relationshipLabel>
        <relationshipName>Delivery_Schedules</relationshipName>
        <type>Lookup</type>
    </CustomField>

force-app/main/default/objects/Route__c/Route__c.object-meta.xml
<CustomObject>
    <label>Route</label>
    <nameField>
        <label>Route Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Route</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Subscription__c/Subscription__c.object-meta.xml
<CustomObject>
    <description>This object stores the actual subscription details, including selected Offer, Premiums. Delivery Schedules, frequency and term.</description>
    <label>Subscription</label>
    <nameField>
        <displayFormat>Sub-{0000}</displayFormat>
        <label>Subscription Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Subscription__c/fields/Delivery_Schedule__c.field-meta.xml
<CustomField>
        <fullName>Delivery_Schedule__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Stores the relationship between Subscriptions and Delivery Schedule</description>
        <label>Delivery Schedule</label>
        <referenceTo>Delivery_Schedule__c</referenceTo>
        <relationshipLabel>Subscriptions</relationshipLabel>
        <relationshipName>Subscriptions</relationshipName>
        <type>Lookup</type>
    </CustomField>

force-app/main/default/objects/Subscription__c/fields/subscription_Status__c.field-meta.xml
<CustomField>
        <fullName>subscription_Status__c</fullName>
        <description>Stores the status of the subscription</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>New</fullName>
                </value>
                <value>
                    <fullName>TERMINATED</fullName>
                </value>
                <value>
                    <fullName>INACTIVE</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </CustomField>

force-app/main/default/classes/RouteApiTest.cls
@isTest
global class RouteApiTest {
    @isTest
    private static void test_RouteApi() {
        TestDataFactory.createTestRecords(1);
        Account acct = [SELECT Id FROM Account LIMIT 1];
        Route__c route = [SELECT Id FROM Route__c LIMIT 1];

        Subscription__c sub = [SELECT Id, subscription_Status__c FROM Subscription__c LIMIT 1];
        sub.subscription_Status__c = 'Active';
        update sub;

        List<Delivery_Schedule__c> schedules = [SELECT Id FROM Delivery_Schedule__c];
        for (Delivery_Schedule__c schedule : schedules) {
            
            schedule.Day_Monday__c = true;
            schedule.Day_Tuesday__c = true;
            schedule.Day_Wednesday__c = true;
            schedule.Day_Thursday__c = true;
            schedule.Day_Friday__c = true;
            schedule.Day_Saturday__c = true;
            schedule.Day_Sunday__c = true;
            schedule.Routelookup__c = route.Id;
        }
        update schedules;


        RestRequest req = new RestRequest(); 
        RestResponse res = new RestResponse();
        req.addHeader('httpMethod', 'POST');
        req.requestUri = '/services/apexrest/route/';       
        req.requestBody = Blob.valueof(JSON.serialize(new Map<String, Object>{
            'CustAccount' => acct.Id,
            'Route' => route.Id
        }));
        RestContext.request = req; 
        RestContext.response= res;

        Test.startTest();
            RouteApi.post();
        Test.stopTest();
    }

    @isTest
    private static void test_RouteApi_error_Json() {
        RestRequest req = new RestRequest(); 
        RestResponse res = new RestResponse();
        req.addHeader('httpMethod', 'POST');
        req.requestUri = '/services/apexrest/route/';       
        req.requestBody = Blob.valueof('{sfesef}sfesf');
        RestContext.request = req; 
        RestContext.response= res;

        Test.startTest();
            RouteApi.post();
        Test.stopTest();
    }

    @isTest
    private static void test_RouteApi_error_CustAccount() {
        RestRequest req = new RestRequest(); 
        RestResponse res = new RestResponse();
        req.addHeader('httpMethod', 'POST');
        req.requestUri = '/services/apexrest/route/';       
        req.requestBody = Blob.valueof(JSON.serialize(new Map<String, Object>{
            'CustAccount' => null,
            'Route' => 'test'
        }));
        RestContext.request = req; 
        RestContext.response= res;

        Test.startTest();
            RouteApi.post();
        Test.stopTest();
    }

    @isTest
    private static void test_RouteApi_error_Route() {
        RestRequest req = new RestRequest(); 
        RestResponse res = new RestResponse();
        req.addHeader('httpMethod', 'POST');
        req.requestUri = '/services/apexrest/route/';       
        req.requestBody = Blob.valueof(JSON.serialize(new Map<String, Object>{
            'CustAccount' => 'test',
            'Route' => null
        }));
        RestContext.request = req; 
        RestContext.response= res;

        Test.startTest();
            RouteApi.post();
        Test.stopTest();
    }

    @isTest
    private static void test_RouteApi_error_noDeliveries() {
        TestDataFactory.createTestRecords(1);
        Account acct = [SELECT Id FROM Account LIMIT 1];
        Route__c route = [SELECT Id FROM Route__c LIMIT 1];

        RestRequest req = new RestRequest(); 
        RestResponse res = new RestResponse();
        req.addHeader('httpMethod', 'POST');
        req.requestUri = '/services/apexrest/route/';       
        req.requestBody = Blob.valueof(JSON.serialize(new Map<String, Object>{
            'CustAccount' => acct.Id,
            'Route' => route.Id
        }));
        RestContext.request = req; 
        RestContext.response= res;

        Test.startTest();
            RouteApi.post();
        Test.stopTest();
    }
}