force-app/main/default/objects/Delivery_Schedule__c/Delivery_Schedule__c.object-meta.xml
<CustomObject>
    <description>Deliver Schedules control the address and which days a publication will be delivered as part of the press run.</description>
    <label>Delivery Schedule</label>
    <nameField>
        <displayFormat>DS-{0}</displayFormat>
        <label>Delivery Schedule Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Delivery Schedules</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Delivery_Schedule__c/fields/Day_Friday__c.field-meta.xml
<CustomField>
        <fullName>Day_Friday__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Friday</label>
        <type>Checkbox</type>
    </CustomField>

force-app/main/default/objects/Delivery_Schedule__c/fields/Day_Monday__c.field-meta.xml
<CustomField>
        <fullName>Day_Monday__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Monday</label>
        <type>Checkbox</type>
    </CustomField>

force-app/main/default/objects/Delivery_Schedule__c/fields/Day_Saturday__c.field-meta.xml
<CustomField>
        <fullName>Day_Saturday__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Saturday</label>
        <type>Checkbox</type>
    </CustomField>

force-app/main/default/objects/Delivery_Schedule__c/fields/Day_Sunday__c.field-meta.xml
<CustomField>
        <fullName>Day_Sunday__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Sunday</label>
        <type>Checkbox</type>
    </CustomField>

force-app/main/default/objects/Delivery_Schedule__c/fields/Day_Thursday__c.field-meta.xml
<CustomField>
        <fullName>Day_Thursday__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Thursday</label>
        <type>Checkbox</type>
    </CustomField>

force-app/main/default/objects/Delivery_Schedule__c/fields/Day_Tuesday__c.field-meta.xml
<CustomField>
        <fullName>Day_Tuesday__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Tuesday</label>
        <type>Checkbox</type>
    </CustomField>

force-app/main/default/objects/Delivery_Schedule__c/fields/Day_Wednesday__c.field-meta.xml
<CustomField>
        <fullName>Day_Wednesday__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Wednesday</label>
        <type>Checkbox</type>
    </CustomField>

force-app/main/default/objects/Delivery_Schedule__c/fields/End_Date__c.field-meta.xml
<CustomField>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </CustomField>

force-app/main/default/objects/Delivery_Schedule__c/fields/Offer_Product__c.field-meta.xml
<CustomField>
        <fullName>Offer_Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Offer Product</label>
        <referenceTo>Offer_Product__c</referenceTo>
        <relationshipLabel>Delivery Schedules</relationshipLabel>
        <relationshipName>Delivery_Schedules</relationshipName>
        <type>Lookup</type>
    </CustomField>

force-app/main/default/objects/Delivery_Schedule__c/fields/Start_Date__c.field-meta.xml
<CustomField>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </CustomField>

force-app/main/default/objects/Delivery_Schedule__c/fields/subscription_Subscription__c.field-meta.xml
<CustomField>
        <fullName>subscription_Subscription__c</fullName>
        <description>This fields lookups to the shadow object, Subscription</description>
        <label>Subscription</label>
        <referenceTo>Subscription__c</referenceTo>
        <relationshipLabel>Delivery Schedules</relationshipLabel>
        <relationshipName>Delivery_Schedules</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </CustomField>

force-app/main/default/objects/Offer__c/Offer__c.object-meta.xml
<CustomObject>
    <description>Controls price, delivery, term for a subscription including print, digital and alternate publications. Also holds links to the premiums offered and the campaigns which will utilize this offer.</description>
    <label>Offer</label>
    <nameField>
        <label>Offer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Offers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Offer__c/fields/End_Date__c.field-meta.xml
<CustomField>
        <fullName>End_Date__c</fullName>
        <description>Stores the end date of the offer</description>
        <label>End Date</label>
        <type>Date</type>
    </CustomField>

force-app/main/default/objects/Offer__c/fields/Per_Copy__c.field-meta.xml
<CustomField>
        <fullName>Per_Copy__c</fullName>
        <label>Per Copy</label>
        <precision>18</precision>
        <scale>4</scale>
        <type>Currency</type>
    </CustomField>

force-app/main/default/objects/Offer__c/fields/Start_Date__c.field-meta.xml
<CustomField>
        <fullName>Start_Date__c</fullName>
        <description>Stores the start date for this offer</description>
        <label>Start Date</label>
        <type>Date</type>
    </CustomField>

force-app/main/default/objects/Offer_Product__c/Offer_Product__c.object-meta.xml
<CustomObject>
    <label>Offer Product</label>
    <nameField>
        <label>Offer Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Offer Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Offer_Product__c/fields/Is_Digital__c.field-meta.xml
<CustomField>
        <fullName>Is_Digital__c</fullName>
        <formula>Product__r.IsDigital__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Is Digital</label>
        <type>Checkbox</type>
    </CustomField>

force-app/main/default/objects/Offer_Product__c/fields/Offer__c.field-meta.xml
<CustomField>
        <fullName>Offer__c</fullName>
        <label>Offer</label>
        <referenceTo>Offer__c</referenceTo>
        <relationshipLabel>Offer Products</relationshipLabel>
        <relationshipName>Offer_Products</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </CustomField>

force-app/main/default/objects/Offer_Product__c/fields/Per_Copy_Sunday__c.field-meta.xml
<CustomField>
        <fullName>Per_Copy_Sunday__c</fullName>
        <label>Per Copy Sunday</label>
        <precision>18</precision>
        <scale>4</scale>
        <type>Currency</type>
    </CustomField>

force-app/main/default/objects/Offer_Product__c/fields/Product__c.field-meta.xml
<CustomField>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Offer Products</relationshipLabel>
        <relationshipName>Offer_Products</relationshipName>
        <type>Lookup</type>
    </CustomField>

force-app/main/default/objects/Subscription__c/Subscription__c.object-meta.xml
<CustomObject>
    <description>This object stores the actual subscription details, including selected Offer, Premiums. Delivery Schedules, frequency and term.</description>
    <label>Subscription</label>
    <nameField>
        <displayFormat>Sub-{0000}</displayFormat>
        <label>Subscription Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Subscription__c/fields/Delivery_Schedule__c.field-meta.xml
<CustomField>
        <fullName>Delivery_Schedule__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Stores the relationship between Subscriptions and Delivery Schedule</description>
        <label>Delivery Schedule</label>
        <referenceTo>Delivery_Schedule__c</referenceTo>
        <relationshipLabel>Subscriptions</relationshipLabel>
        <relationshipName>Subscriptions</relationshipName>
        <type>Lookup</type>
    </CustomField>

force-app/main/default/objects/Subscription__c/fields/subscription_Offer__c.field-meta.xml
<CustomField>
        <fullName>subscription_Offer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Stores the relationship to Offer</description>
        <label>Offer</label>
        <referenceTo>Offer__c</referenceTo>
        <relationshipLabel>Subscriptions</relationshipLabel>
        <relationshipName>Subscriptions1</relationshipName>
        <type>Lookup</type>
    </CustomField>

force-app/main/default/classes/SubscriptionCreditCalculator.cls
public with sharing class SubscriptionCreditCalculator {
    private Subscription__c subscription;
    private Offer__c offer;

    private Date endDate;
    private Date startDate;
    private Set<Id> offerProductIds;

    private Decimal totalCredit;
    private Map<Id, Decimal> amountPerProduct;

    public SubscriptionCreditCalculator(Id subscriptionId, Date startDate, Date endDate, List<Id> offerProductIds) {
        this.subscription = SubscriptionDataAccessor.getSubscriptionById(subscriptionId);
        this.offer = OfferDataAccessor.getOfferById(subscription.subscription_Offer__c);        
        this.startDate = startDate;
        this.endDate = endDate;
        this.offerProductIds = new Set<Id>(offerProductIds);
    }

    public Decimal calculate() {
        totalCredit = 0;
        amountPerProduct = new Map<Id, Decimal>();
        sumCreditFromSchedules();
        sumCreditFromDigitalProducts();
        return totalCredit;
    }

    public Map<Id, Decimal> getAmountPerProduct() {
        if (amountPerProduct == null) {
            calculate();
        }
        return amountPerProduct;
    }

    private void sumCreditFromSchedules() {
        if (subscription.Delivery_Schedules__r == null) {
            return;
        }
        for (Delivery_Schedule__c schedule : subscription.Delivery_Schedules__r) {
            if (schedule.Start_Date__c <= startDate && schedule.End_Date__c >= endDate && offerProductIds.contains(schedule.Offer_Product__c)) {
                Integer regularDays = 0;
                Integer sundayDays = 0;
                Date currentDate = startDate;

                while (currentDate <= endDate) {
                    if (isScheduledAndRegularDay(currentDate, schedule)) {
                        regularDays++;
                    }
                    if (isScheduledAndSundayDay(currentDate, schedule)) {
                        sundayDays++;
                    }
                    currentDate = currentDate.addDays(1);
                }
                Decimal offerProdPerCopy = schedule.Offer_Product__r.Per_Copy__c;
                Decimal offerProdPerCopySunday = schedule.Offer_Product__r.Per_Copy_Sunday__c;
                Decimal combinedAmount = (offerProdPerCopy * regularDays) + (offerProdPerCopySunday * sundayDays);
                totalCredit += combinedAmount;
                amountPerProduct.put(schedule.Offer_Product__r.Product__c, combinedAmount);
            }
        }
    }

    private void sumCreditFromDigitalProducts() {
        if (offer == null || offer.Offer_Products__r == null) {
            return;
        }
        for (Offer_Product__c offerProduct : offer.Offer_Products__r) {
            if (offerProductIds.contains(offerProduct.Id) && offerProduct.Is_Digital__c) {
                
            }
        }
    }

    private Boolean isScheduledAndRegularDay(Date currentDate, Delivery_Schedule__c schedule) {
        Datetime dtime = DateTime.newInstance(currentDate, Time.newInstance(0, 0, 0, 0));
        String dayOfWeek = dtime.format('EEEE');
        return ((dayOfWeek == 'Monday' && schedule.Day_Monday__c) || 
            (dayOfWeek == 'Tuesday' && schedule.Day_Tuesday__c) || 
            (dayOfWeek == 'Wednesday' && schedule.Day_Wednesday__c) || 
            (dayOfWeek == 'Thursday' && schedule.Day_Thursday__c) || 
            (dayOfWeek == 'Friday' && schedule.Day_Friday__c) || 
            (dayOfWeek == 'Saturday' && schedule.Day_Saturday__c));
    }

    private Boolean isScheduledAndSundayDay(Date currentDate, Delivery_Schedule__c schedule) {
        Datetime dtime = DateTime.newInstance(currentDate, Time.newInstance(0, 0, 0, 0));
        String dayOfWeek = dtime.format('EEEE');
        return (dayOfWeek == 'Sunday' && schedule.Day_Sunday__c);
    }

    private Integer getSundayDays(Delivery_Schedule__c schedule) {
        Integer sundayDays = 0;
        if (schedule.Day_Sunday__c) {
            sundayDays++;
        }
        return sundayDays;
    }
}