force-app/main/default/objects/Delivery_Schedule__c/Delivery_Schedule__c.object-meta.xml
<CustomObject>
    <description>Deliver Schedules control the address and which days a publication will be delivered as part of the press run.</description>
    <label>Delivery Schedule</label>
    <nameField>
        <displayFormat>DS-{0}</displayFormat>
        <label>Delivery Schedule Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Delivery Schedules</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Delivery_Schedule__c/fields/Offer_Product__c.field-meta.xml
<CustomField>
        <fullName>Offer_Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Offer Product</label>
        <referenceTo>Offer_Product__c</referenceTo>
        <relationshipLabel>Delivery Schedules</relationshipLabel>
        <relationshipName>Delivery_Schedules</relationshipName>
        <type>Lookup</type>
    </CustomField>

force-app/main/default/objects/Offer__c/Offer__c.object-meta.xml
<CustomObject>
    <description>Controls price, delivery, term for a subscription including print, digital and alternate publications. Also holds links to the premiums offered and the campaigns which will utilize this offer.</description>
    <label>Offer</label>
    <nameField>
        <label>Offer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Offers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Offer_Product__c/Offer_Product__c.object-meta.xml
<CustomObject>
    <label>Offer Product</label>
    <nameField>
        <label>Offer Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Offer Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Offer_Product__c/fields/Offer__c.field-meta.xml
<CustomField>
        <fullName>Offer__c</fullName>
        <label>Offer</label>
        <referenceTo>Offer__c</referenceTo>
        <relationshipLabel>Offer Products</relationshipLabel>
        <relationshipName>Offer_Products</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </CustomField>

force-app/main/default/objects/Subscription__c/Subscription__c.object-meta.xml
<CustomObject>
    <description>This object stores the actual subscription details, including selected Offer, Premiums. Delivery Schedules, frequency and term.</description>
    <label>Subscription</label>
    <nameField>
        <displayFormat>Sub-{0000}</displayFormat>
        <label>Subscription Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Subscription__c/fields/Delivery_Schedule__c.field-meta.xml
<CustomField>
        <fullName>Delivery_Schedule__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Stores the relationship between Subscriptions and Delivery Schedule</description>
        <label>Delivery Schedule</label>
        <referenceTo>Delivery_Schedule__c</referenceTo>
        <relationshipLabel>Subscriptions</relationshipLabel>
        <relationshipName>Subscriptions</relationshipName>
        <type>Lookup</type>
    </CustomField>

force-app/main/default/objects/Subscription__c/fields/subscription_Offer__c.field-meta.xml
<CustomField>
        <fullName>subscription_Offer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Stores the relationship to Offer</description>
        <label>Offer</label>
        <referenceTo>Offer__c</referenceTo>
        <relationshipLabel>Subscriptions</relationshipLabel>
        <relationshipName>Subscriptions1</relationshipName>
        <type>Lookup</type>
    </CustomField>

force-app/main/default/objects/Transaction_Log__c/Transaction_Log__c.object-meta.xml
<CustomObject>
    <label>Transaction Log</label>
    <nameField>
        <displayFormat>TL-{0000}</displayFormat>
        <label>Transaction Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transaction Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Transaction_Log__c/fields/First_Date__c.field-meta.xml
<CustomField>
        <fullName>First_Date__c</fullName>
        <label>First Date</label>
        <type>Date</type>
    </CustomField>

force-app/main/default/objects/Transaction_Log__c/fields/Last_Date__c.field-meta.xml
<CustomField>
        <fullName>Last_Date__c</fullName>
        <label>Last Date</label>
        <type>Date</type>
    </CustomField>

force-app/main/default/objects/Transaction_Log__c/fields/Offer__c.field-meta.xml
<CustomField>
        <fullName>Offer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Offer</label>
        <referenceTo>Offer__c</referenceTo>
        <relationshipLabel>Transaction Logs</relationshipLabel>
        <relationshipName>Transaction_Logs</relationshipName>
        <type>Lookup</type>
    </CustomField>

force-app/main/default/objects/Transaction_Log__c/fields/Offer_Product__c.field-meta.xml
<CustomField>
        <fullName>Offer_Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Offer Product</label>
        <referenceTo>Offer_Product__c</referenceTo>
        <relationshipLabel>Transaction Logs</relationshipLabel>
        <relationshipName>Transaction_Logs</relationshipName>
        <type>Lookup</type>
    </CustomField>

force-app/main/default/objects/Transaction_Log__c/fields/Subscription__c.field-meta.xml
<CustomField>
        <fullName>Subscription__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Subscription</label>
        <referenceTo>Subscription__c</referenceTo>
        <relationshipLabel>Transaction Logs</relationshipLabel>
        <relationshipName>Transaction_Logs</relationshipName>
        <type>Lookup</type>
    </CustomField>

force-app/main/default/objects/Transaction_Log__c/recordTypes/Vacation.recordType-meta.xml
<RecordType>
        <fullName>Vacation</fullName>
        <active>true</active>
        <label>Vacation</label>
    </RecordType>

force-app/main/default/classes/VacationInfoApi.cls
@RestResource(urlMapping='/vacationinfo/*')
global with sharing class VacationInfoApi {
    @HttpPost
    global static void post() {
        RestResponse res = RestContext.response;
        try {
            VacationInfoInput input = (VacationInfoInput)JSON.deserialize(RestContext.request.requestbody.toString(), VacationInfoInput.class);
            validate(input);
            res.responseBody = Blob.valueOf(JSON.serialize(new VacationInfo(input.SubId)));
        } catch (GenericException e) {
            res.responseBody = Blob.valueOf(JSON.serialize(new ResponseError(e.getMessage())));
        } catch (Exception e) {
            System.debug(e.getStackTraceString());
            res.statusCode = 500;
        }
    }

    private static void validate (VacationInfoInput input) {
        if (!input.isValid()) {
            throw new GenericException('Invalid input');
        }
    }

    private class VacationInfoInput {
        public String SubId {get;set;}

        public Boolean isValid() {
            if (String.isEmpty(SubId)) {
                return false;
            }
            return true;
        }
    }

    private class VacationInfo {
        public Integer PubCount {get;set;}
        public String RestartOnly {get;set;}
        public String EarliestStop {get;set;}
        public String NextStart {get;set;}
        public String NextEnd {get;set;}

        public VacationInfo(Id subscriptionId) {
            Id transactionVacationHoldRecordTypeId = Schema.SObjectType.Transaction_Log__c.getRecordTypeInfosByDeveloperName().get('Vacation').getRecordTypeId();
            List<Subscription__c> subscription = [SELECT Id, subscription_Offer__c FROM Subscription__c WHERE Id = :subscriptionId];
            if (subscription.isEmpty()) {
                throw new GenericException('No subscription found');
            }
            
            // any current or future vacations
            List<Transaction_Log__c> earliestVacationHold = [
                SELECT Id, Subscription__c, First_Date__c, Last_Date__c 
                FROM Transaction_Log__c 
                WHERE RecordTypeId = :transactionVacationHoldRecordTypeId 
                AND Subscription__c = :subscriptionId 
                ORDER BY First_Date__c DESC LIMIT 1
            ];
            // using First_Date__c and Last_Date__c from Transaction Log
            if (!earliestVacationHold.isEmpty()) {
                Transaction_Log__c transactionLog = earliestVacationHold[0];
                NextStart = transactionLog.First_Date__c != null ? transactionLog.First_Date__c.format() : '';
                NextEnd = transactionLog.Last_Date__c != null ? transactionLog.Last_Date__c.format() : '';           
            } else {
                NextStart = '';
                NextEnd   = '';              
            }

            List<Offer_Product__c> offerProducts = [SELECT Id FROM Offer_Product__c WHERE Offer__c = :subscription[0].subscription_Offer__c];
            List<Delivery_Schedule__c> deliverySchedules = DeliveryScheduleDataAccessor.getDeliveryScheduleBySubId(subscriptionId);            
            Date earliestStopDate = SubscriptionDelivery.getEarliestStopDate(deliverySchedules);

            RestartOnly = 'N';  // default value
            PubCount = offerProducts.size();
            EarliestStop = (earliestStopDate != null) ? earliestStopDate.format() : '';
        }
    }
}