force-app/main/default/objects/Delivery_Schedule__c/Delivery_Schedule__c.object-meta.xml
<CustomObject>
    <description>Deliver Schedules control the address and which days a publication will be delivered as part of the press run.</description>
    <label>Delivery Schedule</label>
    <nameField>
        <displayFormat>DS-{0}</displayFormat>
        <label>Delivery Schedule Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Delivery Schedules</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Delivery_Schedule__c/fields/Offer_Product__c.field-meta.xml
<CustomField>
        <fullName>Offer_Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Offer Product</label>
        <referenceTo>Offer_Product__c</referenceTo>
        <relationshipLabel>Delivery Schedules</relationshipLabel>
        <relationshipName>Delivery_Schedules</relationshipName>
        <type>Lookup</type>
    </CustomField>

force-app/main/default/objects/Delivery_Schedule__c/fields/subscription_Subscription__c.field-meta.xml
<CustomField>
        <fullName>subscription_Subscription__c</fullName>
        <description>This fields lookups to the shadow object, Subscription</description>
        <label>Subscription</label>
        <referenceTo>Subscription__c</referenceTo>
        <relationshipLabel>Delivery Schedules</relationshipLabel>
        <relationshipName>Delivery_Schedules</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </CustomField>

force-app/main/default/objects/Offer_Product__c/Offer_Product__c.object-meta.xml
<CustomObject>
    <label>Offer Product</label>
    <nameField>
        <label>Offer Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Offer Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Offer_Product__c/fields/Code__c.field-meta.xml
<CustomField>
        <fullName>Code__c</fullName>
        <formula>Product__r.ProductCode</formula>
        <label>Code</label>
        <type>Text</type>
    </CustomField>

force-app/main/default/objects/Subscription__c/Subscription__c.object-meta.xml
<CustomObject>
    <description>This object stores the actual subscription details, including selected Offer, Premiums. Delivery Schedules, frequency and term.</description>
    <label>Subscription</label>
    <nameField>
        <displayFormat>Sub-{0000}</displayFormat>
        <label>Subscription Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Subscription__c/fields/Delivery_Schedule__c.field-meta.xml
<CustomField>
        <fullName>Delivery_Schedule__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Stores the relationship between Subscriptions and Delivery Schedule</description>
        <label>Delivery Schedule</label>
        <referenceTo>Delivery_Schedule__c</referenceTo>
        <relationshipLabel>Subscriptions</relationshipLabel>
        <relationshipName>Subscriptions</relationshipName>
        <type>Lookup</type>
    </CustomField>

force-app/main/default/objects/Subscription__c/fields/Digital_Opt_Out__c.field-meta.xml
<CustomField>
        <fullName>Digital_Opt_Out__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Digital Opt Out</label>
        <type>Checkbox</type>
    </CustomField>

force-app/main/default/objects/Subscription__c/fields/subscription_Account__c.field-meta.xml
<CustomField>
        <fullName>subscription_Account__c</fullName>
        <description>Relationship between Account and Subscriptions</description>
        <label>Household Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Subscriptions</relationshipLabel>
        <relationshipName>Subscriptions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </CustomField>

force-app/main/default/objects/Transaction_Log__c/Transaction_Log__c.object-meta.xml
<CustomObject>
    <label>Transaction Log</label>
    <nameField>
        <displayFormat>TL-{0000}</displayFormat>
        <label>Transaction Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transaction Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Transaction_Log__c/fields/Account__c.field-meta.xml
<CustomField>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Transaction Logs</relationshipLabel>
        <relationshipName>Transaction_Logs</relationshipName>
        <type>Lookup</type>
    </CustomField>

force-app/main/default/objects/Transaction_Log__c/fields/Cancelled__c.field-meta.xml
<CustomField>
        <fullName>Cancelled__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This transaction has been cancelled</description>
        <label>Cancelled</label>
        <type>Checkbox</type>
    </CustomField>

force-app/main/default/objects/Transaction_Log__c/fields/Category__c.field-meta.xml
<CustomField>
        <fullName>Category__c</fullName>
        <description>The Category of this transaction</description>
        <label>Category</label>
        <length>25</length>
        <type>Text</type>
    </CustomField>

force-app/main/default/objects/Transaction_Log__c/fields/Entry_Date__c.field-meta.xml
<CustomField>
        <fullName>Entry_Date__c</fullName>
        <label>Entry Date</label>
        <type>Date</type>
    </CustomField>

force-app/main/default/objects/Transaction_Log__c/fields/First_Date__c.field-meta.xml
<CustomField>
        <fullName>First_Date__c</fullName>
        <label>First Date</label>
        <type>Date</type>
    </CustomField>

force-app/main/default/objects/Transaction_Log__c/fields/Last_Date__c.field-meta.xml
<CustomField>
        <fullName>Last_Date__c</fullName>
        <label>Last Date</label>
        <type>Date</type>
    </CustomField>

force-app/main/default/objects/Transaction_Log__c/fields/Message__c.field-meta.xml
<CustomField>
        <fullName>Message__c</fullName>
        <label>Message</label>
        <type>TextArea</type>
    </CustomField>

force-app/main/default/objects/Transaction_Log__c/fields/Offer_Product__c.field-meta.xml
<CustomField>
        <fullName>Offer_Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Offer Product</label>
        <referenceTo>Offer_Product__c</referenceTo>
        <relationshipLabel>Transaction Logs</relationshipLabel>
        <relationshipName>Transaction_Logs</relationshipName>
        <type>Lookup</type>
    </CustomField>

force-app/main/default/objects/Transaction_Log__c/fields/Subscription__c.field-meta.xml
<CustomField>
        <fullName>Subscription__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Subscription</label>
        <referenceTo>Subscription__c</referenceTo>
        <relationshipLabel>Transaction Logs</relationshipLabel>
        <relationshipName>Transaction_Logs</relationshipName>
        <type>Lookup</type>
    </CustomField>

force-app/main/default/objects/Transaction_Log__c/fields/Transaction_Type__c.field-meta.xml
<CustomField>
        <fullName>Transaction_Type__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Transaction Type</label>
        <referenceTo>Transaction_Type__c</referenceTo>
        <relationshipLabel>Transaction Logs</relationshipLabel>
        <relationshipName>Transaction_Logs</relationshipName>
        <type>Lookup</type>
    </CustomField>

force-app/main/default/objects/Transaction_Log__c/fields/Trouble__c.field-meta.xml
<CustomField>
        <fullName>Trouble__c</fullName>
        <label>Trouble</label>
        <length>255</length>
        <type>Text</type>
    </CustomField>

force-app/main/default/objects/Transaction_Log__c/recordTypes/Complaint.recordType-meta.xml
<RecordType>
        <fullName>Complaint</fullName>
        <active>true</active>
        <label>Complaint</label>
    </RecordType>

force-app/main/default/objects/Transaction_Log__c/recordTypes/Vacation.recordType-meta.xml
<RecordType>
        <fullName>Vacation</fullName>
        <active>true</active>
        <label>Vacation</label>
    </RecordType>

force-app/main/default/objects/Transaction_Type__c/Transaction_Type__c.object-meta.xml
<CustomObject>
    <label>Transaction Type</label>
    <nameField>
        <label>Transaction Type Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Transaction Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Transaction_Type__c/fields/Apply_Credit_to_Subscription__c.field-meta.xml
<CustomField>
        <fullName>Apply_Credit_to_Subscription__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>If checked will apply the per copy for the date chosen.</inlineHelpText>
        <label>Apply Credit to Subscription</label>
        <type>Checkbox</type>
    </CustomField>

force-app/main/default/objects/Transaction_Type__c/fields/Category__c.field-meta.xml
<CustomField>
        <fullName>Category__c</fullName>
        <inlineHelpText>Choose appropriate for transaction viewer</inlineHelpText>
        <label>Category</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Carrier Me</fullName>
                </value>
                <value>
                    <fullName>CC_Request</fullName>
                </value>
                <value>
                    <fullName>Complaint</fullName>
                </value>
                <value>
                    <fullName>Credit_Card</fullName>
                </value>
                <value>
                    <fullName>Journal</fullName>
                </value>
                <value>
                    <fullName>Memo</fullName>
                </value>
                <value>
                    <fullName>Message</fullName>
                </value>
                <value>
                    <fullName>Move</fullName>
                </value>
                <value>
                    <fullName>Product Change</fullName>
                </value>
                <value>
                    <fullName>Start</fullName>
                </value>
                <value>
                    <fullName>Stop</fullName>
                </value>
                <value>
                    <fullName>Vacation Pack</fullName>
                </value>
                <value>
                    <fullName>VH</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </CustomField>

force-app/main/default/objects/Transaction_Type__c/fields/Code__c.field-meta.xml
<CustomField>
        <fullName>Code__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <inlineHelpText>Matches DSI Code</inlineHelpText>
        <label>Code</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </CustomField>

force-app/main/default/objects/Transaction_Type__c/fields/Message__c.field-meta.xml
<CustomField>
        <fullName>Message__c</fullName>
        <inlineHelpText>default message text</inlineHelpText>
        <label>Message</label>
        <length>255</length>
        <type>Text</type>
    </CustomField>

force-app/main/default/objects/Transaction_Type__c/fields/Trouble__c.field-meta.xml
<CustomField>
        <fullName>Trouble__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Trouble</label>
        <type>Checkbox</type>
    </CustomField>

force-app/main/default/classes/TransactionLogHandlerTest.cls
@isTest
public with sharing class TransactionLogHandlerTest {
	@testSetup static void buildDataSet(){
		TestDataFactory.createTestRecords(10);
	}
	@isTest static void shouldCreateComplaint(){
		List<Transaction_Log__c> toInsert = new List<Transaction_Log__c>();
		List<Subscription__c> subList = [SELECT Id, subscription_Account__c FROM Subscription__c];
		List<Offer_Product__c> offerProducts = [SELECT Id FROM Offer_Product__c];
		Transaction_Type__c complaintType = [SELECT Id FROM Transaction_Type__c WHERE Category__c = 'Complaint' LIMIT 1];
		Integer offerProductIndex = 0;
		for(Subscription__c sub : subList){
			toInsert.add(new Transaction_Log__c(
				First_Date__c = System.today(),
       			Last_Date__c = System.today(),
        		Entry_Date__c = System.today(),
       			Transaction_Type__c = complaintType.Id,
				Subscription__c = sub.Id,
				Account__c = sub.subscription_Account__c,
				Offer_Product__c = offerProducts.get(offerProductIndex).Id,
				Category__c = 'Complaint',
				Trouble__c = 'N',
				Message__c = 'Test Complaint'));
			offerProductIndex++;
		}
		insert toInsert;
	}
	@isTest static void shouldCreateCreditComplaint(){
		List<Transaction_Log__c> toInsert = new List<Transaction_Log__c>();
		List<Subscription__c> subList = [SELECT Id, subscription_Account__c FROM Subscription__c];
		List<Offer_Product__c> offerProducts = [SELECT Id FROM Offer_Product__c];
		Transaction_Type__c complaintType = [SELECT Id FROM Transaction_Type__c WHERE Apply_Credit_to_Subscription__c = true LIMIT 1];
		system.debug('--complaintType: '+complaintType);
		Integer offerProductIndex = 0;
		for(Subscription__c sub : subList){
			toInsert.add(new Transaction_Log__c(
				First_Date__c = System.today(),
       			Last_Date__c = System.today(),
        		Entry_Date__c = System.today(),
       			Transaction_Type__c = complaintType.Id,
				Subscription__c = sub.Id,
				Account__c = sub.subscription_Account__c,
				Offer_Product__c = offerProducts.get(offerProductIndex).Id,
				Category__c = 'Complaint',
				Trouble__c = 'N',
				Message__c = 'Test Complaint'));
			offerProductIndex++;
		}
		system.debug('--transLog: ' + toInsert);
		insert toInsert;
	}

	@isTest static void shouldCreateBulkDigitalOptOut(){
		List<Transaction_Log__c> toInsert = new List<Transaction_Log__c>();
		List<Subscription__c> subList = [SELECT Id, subscription_Account__c FROM Subscription__c];
		Transaction_Type__c optOutType = [SELECT Id FROM Transaction_Type__c WHERE Code__c = 'DO' LIMIT 1];
		for(Subscription__c sub : subList){
			toInsert.add(new Transaction_Log__c(
				First_Date__c = System.today(),
        		Entry_Date__c = System.today(),
       			Transaction_Type__c = optOutType.Id,
				Subscription__c = sub.Id));
		}
		insert toInsert;

		subList = [SELECT Id, Digital_Opt_Out__c FROM Subscription__c];
		Boolean stayTrueForDigitalOptOut = true;
		for(Subscription__c sub : subList){
			if(!sub.Digital_Opt_Out__c) 
				stayTrueForDigitalOptOut = false;
		}
		system.assert(stayTrueForDigitalOptOut);
	}

	@isTest static void shouldCreateEscalation(){
		List<Transaction_Log__c> toInsert = new List<Transaction_Log__c>();
		List<Subscription__c> subList = [SELECT Id, subscription_Account__c FROM Subscription__c LIMIT 1];
		Transaction_Type__c optOutType = [SELECT Id FROM Transaction_Type__c WHERE Code__c = 'ND' LIMIT 1];
		for(Subscription__c sub : subList){
			for(Integer i = 0; i < 4; i++){
				toInsert.add(new Transaction_Log__c(
					First_Date__c = System.today().addDays(-i),
					Entry_Date__c = System.today().addDays(-i),
					Transaction_Type__c = optOutType.Id,
					Subscription__c = sub.Id
				));
			}
			
		}
		insert toInsert;
	}

	@isTest static void testsetProductChangeDate() {
		List<Transaction_Log__c> transLogList = new List<Transaction_Log__c>();
		List<Subscription__c> subList = [SELECT Id, subscription_Account__c FROM Subscription__c LIMIT 1];
		Set<Id> subscriptionIds = new Set<Id>();
		for(Subscription__c sub : subList){
			for(Integer i = 0; i < 4; i++){
				transLogList.add(new Transaction_Log__c(
					First_Date__c = System.today().addDays(-i),
					Entry_Date__c = System.today().addDays(-i),
					Subscription__c = sub.Id
				));
			}
			subscriptionIds.add(sub.Id);
		}

		TransactionLogHandler.setProductChangeDate(transLogList,subscriptionIds);
	}

	@isTest static void testSetActualDate() {
		List<Transaction_Log__c> transLogList = new List<Transaction_Log__c>();
		List<Subscription__c> subList = [SELECT Id, subscription_Account__c FROM Subscription__c LIMIT 1];
		Set<Id> subscriptionIds = new Set<Id>();
		for(Subscription__c sub : subList){
			for(Integer i = 0; i < 4; i++){
				transLogList.add(new Transaction_Log__c(
					First_Date__c = System.today().addDays(-i),
					Last_Date__c = System.today().addDays(i),
					Entry_Date__c = System.today().addDays(-i),
					Subscription__c = sub.Id
				));
			}
			subscriptionIds.add(sub.Id);
		}
		//system.debug('--test--transLogList: ' + transLogList);
		//system.debug('--test--subIDs: ' + subscriptionIds);
		TransactionLogHandler.setActualDateFields(transLogList,subscriptionIds);
	}

	@isTest static void testValidateExisting() {
		List<Transaction_Log__c> transLogList = new List<Transaction_Log__c>();
		List<Subscription__c> subList = [SELECT Id, subscription_Account__c FROM Subscription__c LIMIT 1];
		List<Delivery_Schedule__c> scheduleList = [SELECT Id, subscription_Subscription__c FROM Delivery_Schedule__c LIMIT 1];
		Transaction_Type__c transType = [SELECT Id FROM Transaction_Type__c WHERE Code__c = 'VH' LIMIT 1];
		Set<Id> subscriptionIds = new Set<Id>();
		for(Subscription__c sub : subList){
			for(Integer i = 0; i < 4; i++){
				transLogList.add(new Transaction_Log__c(
					First_Date__c = System.today().addDays(-i),
					Last_Date__c = System.today().addDays(i),
					Entry_Date__c = System.today().addDays(-i),
					Transaction_Type__c = transType.Id,
					Category__c = 'Vacation Pack',
					Cancelled__c = false,
					Subscription__c = sub.Id
				));
			}
			subscriptionIds.add(sub.Id);
		}
		// system.debug('--test--scheduleList: ' +scheduleList);
		//insert transLogList;

        // system.debug('--test--transLogList: ' +transLogList);
		// system.debug('--test--subIDs: ' + subscriptionIds);

		TransactionLogHandler.validateExisting(transLogList,subscriptionIds);
	}

}