force-app/main/default/objects/Route__c/Route__c.object-meta.xml
<CustomObject>
    <label>Route</label>
    <nameField>
        <label>Route Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Route</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Route_Street__c/Route_Street__c.object-meta.xml
<CustomObject>
    <label>Route Street</label>
    <nameField>
        <label>Route Street Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Route Streets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Route_Street__c/fields/From__c.field-meta.xml
<CustomField>
        <fullName>From__c</fullName>
        <label>From</label>
        <type>DateTime</type>
    </CustomField>

force-app/main/default/objects/Route_Street__c/fields/House_High__c.field-meta.xml
<CustomField>
        <fullName>House_High__c</fullName>
        <label>House High</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </CustomField>

force-app/main/default/objects/Route_Street__c/fields/House_Low__c.field-meta.xml
<CustomField>
        <fullName>House_Low__c</fullName>
        <label>House Low</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </CustomField>

force-app/main/default/objects/Route_Street__c/fields/Route__c.field-meta.xml
<CustomField>
        <fullName>Route__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Route</label>
        <referenceTo>Route__c</referenceTo>
        <relationshipLabel>Route Streets</relationshipLabel>
        <relationshipName>Route_Streets</relationshipName>
        <type>Lookup</type>
    </CustomField>

force-app/main/default/objects/Route_Street__c/fields/Street_Name__c.field-meta.xml
<CustomField>
        <fullName>Street_Name__c</fullName>
        <label>Street Name</label>
        <length>25</length>
        <type>Text</type>
    </CustomField>

force-app/main/default/objects/Route_Street__c/fields/To__c.field-meta.xml
<CustomField>
        <fullName>To__c</fullName>
        <label>To</label>
        <type>DateTime</type>
    </CustomField>

force-app/main/default/objects/Route_Street__c/fields/ZIP__c.field-meta.xml
<CustomField>
        <fullName>ZIP__c</fullName>
        <label>ZIP</label>
        <length>10</length>
        <type>Text</type>
    </CustomField>

force-app/main/default/classes/RouteDataAccessor.cls
public with sharing class RouteDataAccessor {
    public static List<Route_Street__c> getRouteStreets(Decimal streetNumber, String streetName, String postalCode) {
        System.debug(streetName);
        return [
            SELECT Id, Route__c
            FROM Route_Street__c 
            WHERE House_Low__c <= :streetNumber AND House_High__c >= :streetNumber
            AND From__c <= TODAY AND To__c >= TODAY
            AND Street_Name__c = :streetName
            AND ZIP__c = :postalCode
        ];
    }
}