force-app/main/default/objects/Journal__c/Journal__c.object-meta.xml
<CustomObject>
    <label>Journal</label>
    <nameField>
        <displayFormat>Entry - {000000}</displayFormat>
        <label>Entry Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Journal Entries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Journal__c/fields/Subscription__c.field-meta.xml
<CustomField>
        <fullName>Subscription__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Subscription</label>
        <referenceTo>Subscription__c</referenceTo>
        <relationshipLabel>Journal Entries</relationshipLabel>
        <relationshipName>Journal_Entries</relationshipName>
        <type>Lookup</type>
    </CustomField>

force-app/main/default/objects/LastDrawDate__c/LastDrawDate__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Used by the Draw Calculator to keep track of which date to run</description>
    <label>Last Draw Date</label>
</CustomObject>

force-app/main/default/objects/LastDrawDate__c/fields/Last_Date__c.field-meta.xml
<CustomField>
    <fullName>Last_Date__c</fullName>
    <label>Last Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Offer__c/Offer__c.object-meta.xml
<CustomObject>
    <description>Controls price, delivery, term for a subscription including print, digital and alternate publications. Also holds links to the premiums offered and the campaigns which will utilize this offer.</description>
    <label>Offer</label>
    <nameField>
        <label>Offer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Offers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Offer__c/fields/Per_Copy__c.field-meta.xml
<CustomField>
        <fullName>Per_Copy__c</fullName>
        <label>Per Copy</label>
        <precision>18</precision>
        <scale>4</scale>
        <type>Currency</type>
    </CustomField>

force-app/main/default/objects/Offer_Product__c/Offer_Product__c.object-meta.xml
<CustomObject>
    <label>Offer Product</label>
    <nameField>
        <label>Offer Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Offer Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Offer_Product__c/fields/Offer__c.field-meta.xml
<CustomField>
        <fullName>Offer__c</fullName>
        <label>Offer</label>
        <referenceTo>Offer__c</referenceTo>
        <relationshipLabel>Offer Products</relationshipLabel>
        <relationshipName>Offer_Products</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </CustomField>

force-app/main/default/objects/Offer_Product__c/fields/Per_Copy_Sunday__c.field-meta.xml
<CustomField>
        <fullName>Per_Copy_Sunday__c</fullName>
        <label>Per Copy Sunday</label>
        <precision>18</precision>
        <scale>4</scale>
        <type>Currency</type>
    </CustomField>

force-app/main/default/objects/Offer_Product__c/fields/Product__c.field-meta.xml
<CustomField>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Offer Products</relationshipLabel>
        <relationshipName>Offer_Products</relationshipName>
        <type>Lookup</type>
    </CustomField>

force-app/main/default/objects/Product2/fields/IsDigital__c.field-meta.xml
<CustomField>
        <fullName>IsDigital__c</fullName>
        <defaultValue>false</defaultValue>
        <label>IsDigital</label>
        <type>Checkbox</type>
    </CustomField>

force-app/main/default/objects/Subscription__c/Subscription__c.object-meta.xml
<CustomObject>
    <description>This object stores the actual subscription details, including selected Offer, Premiums. Delivery Schedules, frequency and term.</description>
    <label>Subscription</label>
    <nameField>
        <displayFormat>Sub-{0000}</displayFormat>
        <label>Subscription Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Subscription__c/fields/Attention_Line__c.field-meta.xml
<CustomField>
        <fullName>Attention_Line__c</fullName>
        <label>Attention Line</label>
        <length>100</length>
        <type>Text</type>
    </CustomField>

force-app/main/default/objects/Subscription__c/fields/Delivery_Instructions__c.field-meta.xml
<CustomField>
        <fullName>Delivery_Instructions__c</fullName>
        <label>Delivery Instructions</label>
        <type>TextArea</type>
    </CustomField>

force-app/main/default/objects/Subscription__c/fields/Outstanding_Credit__c.field-meta.xml
<CustomField>
        <fullName>Outstanding_Credit__c</fullName>
        <label>Today's Balance</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </CustomField>

force-app/main/default/objects/Subscription__c/fields/subscription_Account__c.field-meta.xml
<CustomField>
        <fullName>subscription_Account__c</fullName>
        <description>Relationship between Account and Subscriptions</description>
        <label>Household Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Subscriptions</relationshipLabel>
        <relationshipName>Subscriptions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </CustomField>

force-app/main/default/objects/Subscription__c/fields/subscription_Offer__c.field-meta.xml
<CustomField>
        <fullName>subscription_Offer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Stores the relationship to Offer</description>
        <label>Offer</label>
        <referenceTo>Offer__c</referenceTo>
        <relationshipLabel>Subscriptions</relationshipLabel>
        <relationshipName>Subscriptions1</relationshipName>
        <type>Lookup</type>
    </CustomField>

force-app/main/default/objects/Subscription__c/fields/subscription_Status__c.field-meta.xml
<CustomField>
        <fullName>subscription_Status__c</fullName>
        <description>Stores the status of the subscription</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>New</fullName>
                </value>
                <value>
                    <fullName>TERMINATED</fullName>
                </value>
                <value>
                    <fullName>INACTIVE</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </CustomField>

force-app/main/default/classes/PressRunDigitalProcessTest.cls
@isTest
private class PressRunDigitalProcessTest {
    @testSetup 
    static void setup() {

         Account account = new Account(
            Name = 'Digital Account Test 1');
        insert account;
        
        Product2 digitalProduct = new Product2(Name = '160', IsDigital__c = true);
        insert digitalProduct;
        Offer__c digitalOffer = new Offer__c(Name = 'All Digital');
        insert digitalOffer;

        Offer_Product__c digitalOfferProduct = new Offer_Product__c(
            Offer__c = digitalOffer.Id,
            Product__c = digitalProduct.Id,
            Per_Copy__c = 0.25,
            Per_Copy_Sunday__c = 0.25
        );
        insert digitalOfferProduct;

        Subscription__c digitalSubscription = new Subscription__c(
            subscription_Account__c = account.Id,
            Attention_Line__c = 'Digital Sub',
            Delivery_Instructions__c = 'N/A',
            Outstanding_Credit__c = 20.00,
            subscription_Status__c = 'Active',
            subscription_Offer__c = digitalOffer.Id
        );
        insert digitalSubscription;

        LastDrawDate__c newDate = new LastDrawDate__c(Last_Date__c = Date.today().addDays(-2));
		insert newDate;
        
    }
    static testmethod void ShouldBatchRevenue() {        
        Test.startTest();
        PressRunDigitalProcess prp = new PressRunDigitalProcess();
        Double testCredit = [SELECT Outstanding_Credit__c FROM Subscription__c LIMIT 1].Outstanding_Credit__c;
        prp.dayOfWeek = 'Monday';
        Id batchId = Database.executeBatch(prp);
        prp.dayOfWeek = 'Tuesday';
        batchId = Database.executeBatch(prp);
        Test.stopTest();
        // Test Subscription
        List<Journal__c> journalEntries = [SELECT Id FROM Journal__c];
        System.debug(journalEntries);
        system.assert(journalEntries.size() == 2);
        LastDrawDate__c CurrentDrawDate = LastDrawDate__c.getInstance();
        system.assert(CurrentDrawDate.Last_Date__c == Date.today());
        testCredit = [SELECT Outstanding_Credit__c FROM Subscription__c LIMIT 1].Outstanding_Credit__c;
        system.assert(testCredit == 19.50);
        
    }
}