force-app/main/default/objects/Journal__c/Journal__c.object-meta.xml
<CustomObject>
    <label>Journal</label>
    <nameField>
        <displayFormat>Entry - {000000}</displayFormat>
        <label>Entry Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Journal Entries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Journal__c/fields/Debit__c.field-meta.xml
<CustomField>
        <fullName>Debit__c</fullName>
        <description>Amount if this item is a debit</description>
        <label>Debit</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Currency</type>
    </CustomField>

force-app/main/default/objects/Journal__c/fields/Entry_Date__c.field-meta.xml
<CustomField>
        <fullName>Entry_Date__c</fullName>
        <defaultValue>today()</defaultValue>
        <description>Date the item was entered</description>
        <label>Entry Date</label>
        <type>Date</type>
    </CustomField>

force-app/main/default/objects/Journal__c/fields/Entry_Type__c.field-meta.xml
<CustomField>
        <fullName>Entry_Type__c</fullName>
        <label>Entry Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Publication</fullName>
                </value>
                <value>
                    <fullName>Cash</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </CustomField>

force-app/main/default/objects/Journal__c/fields/Publication__c.field-meta.xml
<CustomField>
        <fullName>Publication__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Publication</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Publication</relationshipLabel>
        <relationshipName>Publication</relationshipName>
        <type>Lookup</type>
    </CustomField>

force-app/main/default/objects/Journal__c/fields/Subscription__c.field-meta.xml
<CustomField>
        <fullName>Subscription__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Subscription</label>
        <referenceTo>Subscription__c</referenceTo>
        <relationshipLabel>Journal Entries</relationshipLabel>
        <relationshipName>Journal_Entries</relationshipName>
        <type>Lookup</type>
    </CustomField>

force-app/main/default/objects/Offer__c/Offer__c.object-meta.xml
<CustomObject>
    <description>Controls price, delivery, term for a subscription including print, digital and alternate publications. Also holds links to the premiums offered and the campaigns which will utilize this offer.</description>
    <label>Offer</label>
    <nameField>
        <label>Offer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Offers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Offer__c/fields/Per_Copy__c.field-meta.xml
<CustomField>
        <fullName>Per_Copy__c</fullName>
        <label>Per Copy</label>
        <precision>18</precision>
        <scale>4</scale>
        <type>Currency</type>
    </CustomField>

force-app/main/default/objects/Offer_Product__c/Offer_Product__c.object-meta.xml
<CustomObject>
    <label>Offer Product</label>
    <nameField>
        <label>Offer Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Offer Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Offer_Product__c/fields/Is_Digital__c.field-meta.xml
<CustomField>
        <fullName>Is_Digital__c</fullName>
        <formula>Product__r.IsDigital__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Is Digital</label>
        <type>Checkbox</type>
    </CustomField>

force-app/main/default/objects/Offer_Product__c/fields/Offer__c.field-meta.xml
<CustomField>
        <fullName>Offer__c</fullName>
        <label>Offer</label>
        <referenceTo>Offer__c</referenceTo>
        <relationshipLabel>Offer Products</relationshipLabel>
        <relationshipName>Offer_Products</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </CustomField>

force-app/main/default/objects/Offer_Product__c/fields/Per_Copy_Sunday__c.field-meta.xml
<CustomField>
        <fullName>Per_Copy_Sunday__c</fullName>
        <label>Per Copy Sunday</label>
        <precision>18</precision>
        <scale>4</scale>
        <type>Currency</type>
    </CustomField>

force-app/main/default/objects/Offer_Product__c/fields/Product__c.field-meta.xml
<CustomField>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Offer Products</relationshipLabel>
        <relationshipName>Offer_Products</relationshipName>
        <type>Lookup</type>
    </CustomField>

force-app/main/default/objects/Premium_Day__mdt/Premium_Day__mdt.object-meta.xml
<CustomObject>
    <description>listing of days which a bonus edition will be issued.</description>
    <label>Premium Day</label>
    <pluralLabel>Premium Days</pluralLabel>
</CustomObject>

force-app/main/default/objects/Premium_Day__mdt/fields/Press_Date__c.field-meta.xml
<CustomField>
        <fullName>Press_Date__c</fullName>
        <description>Date which this premium will be issued.</description>
        <label>Press Date</label>
        <type>Date</type>
    </CustomField>

force-app/main/default/objects/Premium_Day__mdt/fields/Type__c.field-meta.xml
<CustomField>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Premium</fullName>
                    <default>true</default>
                    <label>Premium</label>
                </value>
                <value>
                    <fullName>Holiday</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </CustomField>

force-app/main/default/objects/Subscription__c/Subscription__c.object-meta.xml
<CustomObject>
    <description>This object stores the actual subscription details, including selected Offer, Premiums. Delivery Schedules, frequency and term.</description>
    <label>Subscription</label>
    <nameField>
        <displayFormat>Sub-{0000}</displayFormat>
        <label>Subscription Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Subscription__c/fields/Premium_Opt_Out__c.field-meta.xml
<CustomField>
        <fullName>Premium_Opt_Out__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Subscriber has opted out of premium issues.</description>
        <label>Premium Delivery Opt Out</label>
        <type>Checkbox</type>
    </CustomField>

force-app/main/default/objects/Subscription__c/fields/subscription_Offer__c.field-meta.xml
<CustomField>
        <fullName>subscription_Offer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Stores the relationship to Offer</description>
        <label>Offer</label>
        <referenceTo>Offer__c</referenceTo>
        <relationshipLabel>Subscriptions</relationshipLabel>
        <relationshipName>Subscriptions1</relationshipName>
        <type>Lookup</type>
    </CustomField>

force-app/main/default/objects/Subscription__c/fields/subscription_Status__c.field-meta.xml
<CustomField>
        <fullName>subscription_Status__c</fullName>
        <description>Stores the status of the subscription</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>New</fullName>
                </value>
                <value>
                    <fullName>TERMINATED</fullName>
                </value>
                <value>
                    <fullName>INACTIVE</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </CustomField>

force-app/main/default/classes/PressRunDigitalProcess.cls
global class PressRunDigitalProcess implements Database.Batchable<SObject> {

	global Date pressDay;
	global Boolean activePremium;
	global Boolean activeHoliday;
	global String dayOfWeek;
	

	global PressRunDigitalProcess() {
		pressDay = Date.today().addDays(1);
		/* Cast Date to DateTime to retrieve day of week */
		Datetime processDayDT = (DateTime)pressDay;
		processDayDT = processDayDT.addHours(12);
		dayOfWeek = processDayDT.format('EEEE');
		List<Premium_Day__mdt> premiumList = [SELECT Id, Press_Date__c, Type__c FROM Premium_Day__mdt WHERE Press_Date__c = :pressDay];
		activePremium = premiumList.isEmpty() ? false : true;
		activeHoliday = false;
		if(!premiumList.isEmpty()){
			for(Premium_Day__mdt pd : premiumList){
				if(pd.Type__c == 'Holiday')
					activeHoliday = true;
			}
		}
	}
	
	global Database.QueryLocator start(Database.BatchableContext context) {
		String dsQuery = '';
		if(activePremium){
			 //TODO: Review this query - Same as the other, but remove check for Day checkbox = true, and check for opt-out.
			 dsQuery = 'SELECT Id, Premium_Opt_Out__c, subscription_Offer__c FROM Subscription__c WHERE Premium_Opt_Out__c != TRUE AND subscription_Status__c = \'Active\'';
		}
		else{
			dsQuery = 'SELECT Id, Premium_Opt_Out__c, subscription_Offer__c FROM Subscription__c WHERE subscription_Status__c = \'Active\'';
		}
		return Database.getQueryLocator(dsQuery);
	}

   	global void execute(Database.BatchableContext context, List<Subscription__c> scope) {
		List<Journal__c> journalsToInsert = new List<Journal__c>();
		Decimal rate = 0.0;

        Set<Id> subIds = new Set<Id>();
        for(Subscription__c sub : scope){
            subIds.add(sub.Id);
        }
        
        Map<Id, Offer__c> offersMap = new Map<Id, Offer__c>([SELECT Id, (SELECT Name, Product__c, Per_Copy__c, Per_Copy_Sunday__c FROM Offer_Products__r WHERE Is_Digital__c = TRUE) 
            FROM Offer__c 
            WHERE Id in (SELECT subscription_Offer__c FROM Subscription__c WHERE Id IN :subIds)
        ]);
        
        
		for(Subscription__c sub : scope){
			Offer__c subsOffer;
            Offer_Product__c op;
            if(offersMap != null && offersMap.containsKey(sub.subscription_Offer__c)){
                subsOffer = offersMap.get(sub.subscription_Offer__c);
            }
            else continue;

            if(!subsOffer.Offer_Products__r.isEmpty()){
                op = subsOffer.Offer_Products__r[0];
            }
            else continue;

			rate = dayOfWeek.equals('Sunday') ? op.Per_Copy_Sunday__c : op.Per_Copy__c;

			/* Create Journal Entry Record: Always inserts a Standard Entry Type Journal, except for Holidays.*/
			Journal__c journal = new Journal__c(
				Entry_Type__c = activeHoliday ? 'Holiday' : 'Standard Delivery',
				Entry_Date__c = pressday,
				Debit__c = rate,
				Subscription__c = sub.Id,
				Publication__c = op.Product__c
			);
			journalsToInsert.add(journal);
			if(splitJournals || Test.isRunningTest()){
				journalsToInsert.add(new Journal__c(
				Entry_Type__c = 'Premium Delivery',
				Entry_Date__c = pressday,
				Debit__c = splitRate,
				Subscription__c = sub.Id,
				Publication__c = op.Product__c
				));
			}
		}
		if(!journalsToInsert.isEmpty())
			insert journalsToInsert;
	}
	
	/**
	 * @description gets invoked when the batch job finishes. Place any clean up code in this method.
	 * @param context contains the job ID
	 */ 
	global void finish(Database.BatchableContext context) {
		
	}
}