force-app/main/default/objects/Journal__c/Journal__c.object-meta.xml
<CustomObject>
    <label>Journal</label>
    <nameField>
        <displayFormat>Entry - {000000}</displayFormat>
        <label>Entry Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Journal Entries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Journal__c/fields/Credit__c.field-meta.xml
<CustomField>
        <fullName>Credit__c</fullName>
        <description>Amount if this is a credit</description>
        <label>Credit</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Currency</type>
    </CustomField>

force-app/main/default/objects/Journal__c/fields/Debit__c.field-meta.xml
<CustomField>
        <fullName>Debit__c</fullName>
        <description>Amount if this item is a debit</description>
        <label>Debit</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Currency</type>
    </CustomField>

force-app/main/default/objects/Journal__c/fields/Description__c.field-meta.xml
<CustomField>
        <fullName>Description__c</fullName>
        <description>Short description of this item</description>
        <label>Description</label>
        <length>150</length>
        <type>Text</type>
    </CustomField>

force-app/main/default/objects/Journal__c/fields/Entry_Date__c.field-meta.xml
<CustomField>
        <fullName>Entry_Date__c</fullName>
        <defaultValue>today()</defaultValue>
        <description>Date the item was entered</description>
        <label>Entry Date</label>
        <type>Date</type>
    </CustomField>

force-app/main/default/objects/Journal__c/fields/Entry_Type__c.field-meta.xml
<CustomField>
        <fullName>Entry_Type__c</fullName>
        <label>Entry Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Publication</fullName>
                </value>
                <value>
                    <fullName>Cash</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </CustomField>

force-app/main/default/objects/Journal__c/fields/Subscription__c.field-meta.xml
<CustomField>
        <fullName>Subscription__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Subscription</label>
        <referenceTo>Subscription__c</referenceTo>
        <relationshipLabel>Journal Entries</relationshipLabel>
        <relationshipName>Journal_Entries</relationshipName>
        <type>Lookup</type>
    </CustomField>

force-app/main/default/objects/Journal_Entry__b/Journal_Entry__b.object-meta.xml
<CustomObject>
    <indexes>
        <fullName>Base_Index</fullName>
        <fields>
            <name>Subscription__c</name>
            <sortDirection>ASC</sortDirection>
        </fields>
        <fields>
            <name>SFID__c</name>
            <sortDirection>ASC</sortDirection>
        </fields>
        <label>Base Index</label>
    </indexes>
    <label>Journal Entry</label>
    <pluralLabel>Journal Entries</pluralLabel>
</CustomObject>

force-app/main/default/objects/Journal_Entry__b/fields/Credit__c.field-meta.xml
<CustomField>
        <fullName>Credit__c</fullName>
        <label>Credit</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </CustomField>

force-app/main/default/objects/Journal_Entry__b/fields/Debit__c.field-meta.xml
<CustomField>
        <fullName>Debit__c</fullName>
        <label>Debit</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </CustomField>

force-app/main/default/objects/Journal_Entry__b/fields/Description__c.field-meta.xml
<CustomField>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>255</length>
        <type>Text</type>
    </CustomField>

force-app/main/default/objects/Journal_Entry__b/fields/Entry_Type__c.field-meta.xml
<CustomField>
        <fullName>Entry_Type__c</fullName>
        <label>Entry Type</label>
        <length>100</length>
        <type>Text</type>
    </CustomField>

force-app/main/default/objects/ReCurly_Transaction__b/ReCurly_Transaction__b.object-meta.xml
<CustomObject>
    <indexes>
        <fullName>Base_Index</fullName>
        <fields>
            <name>Subscription__c</name>
            <sortDirection>ASC</sortDirection>
        </fields>
        <fields>
            <name>SFID__c</name>
            <sortDirection>ASC</sortDirection>
        </fields>
        <label>Base Index</label>
    </indexes>
    <label>ReCurly_Transaction</label>
    <pluralLabel>ReCurly_Transactions</pluralLabel>
</CustomObject>

force-app/main/default/objects/ReCurly_Transaction__b/fields/Check_Number__c.field-meta.xml
<CustomField>
        <fullName>Check_Number__c</fullName>
        <label>Check Number</label>
        <length>18</length>
        <type>Text</type>
    </CustomField>

force-app/main/default/objects/ReCurly_Transaction__b/fields/recurly_Amount__c.field-meta.xml
<CustomField>
        <fullName>recurly_Amount__c</fullName>
        <label>Amount</label>
        <precision>10</precision>
        <scale>2</scale>
        <type>Number</type>
    </CustomField>

force-app/main/default/objects/ReCurly_Transaction__b/fields/recurly_Collected_At__c.field-meta.xml
<CustomField>
        <fullName>recurly_Collected_At__c</fullName>
        <label>Collected At</label>
        <type>DateTime</type>
    </CustomField>

force-app/main/default/objects/ReCurly_Transaction__b/fields/recurly_Payment_Card_Type__c.field-meta.xml
<CustomField>
        <fullName>recurly_Payment_Card_Type__c</fullName>
        <label>Card Type</label>
        <length>18</length>
        <type>Text</type>
    </CustomField>

force-app/main/default/objects/ReCurly_Transaction__b/fields/recurly_Payment_Last_Four__c.field-meta.xml
<CustomField>
        <fullName>recurly_Payment_Last_Four__c</fullName>
        <label>Last Four</label>
        <length>18</length>
        <type>Text</type>
    </CustomField>

force-app/main/default/objects/ReCurly_Transaction__b/fields/Subscription__c.field-meta.xml
<CustomField>
        <fullName>Subscription__c</fullName>
        <description>Is of the Subscription record this transaction is linked to.</description>
        <label>Subscription</label>
        <length>18</length>
        <required>true</required>
        <type>Text</type>
    </CustomField>

force-app/main/default/objects/Subscription__c/Subscription__c.object-meta.xml
<CustomObject>
    <description>This object stores the actual subscription details, including selected Offer, Premiums. Delivery Schedules, frequency and term.</description>
    <label>Subscription</label>
    <nameField>
        <displayFormat>Sub-{0000}</displayFormat>
        <label>Subscription Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/JournalEntryActions.cls
public class JournalEntryActions  {

    @AuraEnabled
    public static List<SuperJournalEntry> PullJournalEntries(String sobjId, String filterType){
        System.debug('the type filter is: ' + filterType);
        if(filterType == 'none' || filterType == null || String.isBlank(filterType)) {filterType = '%';}
        // get the type of Id sent
        Schema.SObjectType token = Id.valueOf(sobjId).getSobjectType();
        Schema.DescribeSObjectResult dr = token.getDescribe();
        // Pull the correct logs
        List<SuperJournalEntry> journalEntries = new List<SuperJournalEntry>();
        if(dr.getName() == 'Subscription__c'){
            journalEntries = getSubscriptionjournalEntries(sobjId, filterType);
        }
		journalEntries.sort();
        return journalEntries;
    }

    public static List<SuperJournalEntry> getSubscriptionjournalEntries(String subscriptionId, String filterType){
        List<SuperJournalEntry> lstResult = new List<SuperJournalEntry>();
        List<string> filterList = filterType.split(',');
        // add sObjects
        lstResult.addAll(JournalEntryActions.addSObjects(subscriptionId,filterList));
        // add big objects
        lstResult.addAll(JournalEntryActions.addBOJournalEntries(subscriptionId));
		lstResult.addAll(JournalEntryActions.addBORecurlyPayments(subscriptionId));
        // add TransactionComplaint BO
        return lstResult;
    }


    private static List<SuperJournalEntry> addSObjects(Id subId, List<string> FilterList){
        List<SuperJournalEntry> lstResult = new List<SuperJournalEntry>();
        List<Journal__c> pulledJE = [SELECT
                Credit__c,
                Debit__c,
                Description__c,
                Entry_Date__c,
                Entry_Type__c
            FROM Journal__c
            WHERE Subscription__c =: subId
            Limit 1000];
        for(Journal__c thisJE: pulledJE){
            SuperJournalEntry superJE = new SuperJournalEntry();
            superJE.Debit = thisJE.Debit__c;
			superJE.Credit = thisJE.Credit__c;
			superJE.EntryDate = thisJE.Entry_Date__c;
			superJE.EntryType = thisJE.Entry_Type__c;
			superJE.Description = thisJE.Description__c;
			superJE.Source = 'Journal';
            lstResult.add(superJE);
        }
        return lstResult;
    }
    private static List<SuperJournalEntry> addBOJournalEntries(Id subId){
        List<SuperJournalEntry> lstResult = new List<SuperJournalEntry>();
        //List<Journal_Entry__b> pulledJE = [SELECT
                //Credit__c,
                //Debit__c,
                //Description__c,
                //Entry_Date__c,
                //Entry_Type__c
            //FROM Journal_Entry__b
            //WHERE Subscription__c =: subId
            //Limit 1000];
        //for(Journal_Entry__b thisJE: pulledJE){
            //SuperJournalEntry superJE = new SuperJournalEntry();
            //superJE.Debit = thisJE.Debit__c;
			//superJE.Credit = thisJE.Credit__c;
			//superJE.EntryDate = thisJE.Entry_Date__c.date();
			//superJE.EntryType = thisJE.Entry_Type__c;
			//superJE.Description = thisJE.Description__c;
			//superJE.Source = 'Journal';

            //lstResult.add(superJE);
        //}
        return lstResult;
    }
    private static List<SuperJournalEntry> addBORecurlyPayments(Id subId){
        List<SuperJournalEntry> lstResult = new List<SuperJournalEntry>();
        //List<ReCurly_Transaction__b> pulledJE = [SELECT
				//Check_Number__c,
				//recurly_Amount__c,
				//recurly_Collected_At__c,
				//recurly_Payment_Card_Type__c,
				//recurly_Payment_Last_Four__c
			//FROM ReCurly_Transaction__b
            //WHERE Subscription__c =: subId
            //Limit 1000];
        //for(ReCurly_Transaction__b thisJE: pulledJE){
            //SuperJournalEntry superJE = new SuperJournalEntry();
			//if(thisJE.recurly_Amount__c>0){
				//superJE.Credit = thisJE.recurly_Amount__c;
			//}else{
				//superJE.Debit = -thisJE.recurly_Amount__c;				
			//}
			//superJE.EntryDate = thisJE.recurly_Collected_At__c.date();
			//superJE.EntryType = 'CC Payment';
			//superJE.Description = thisJE.recurly_Payment_Card_Type__c;
			//superJE.Source = 'Credit Card';
            //lstResult.add(superJE);
        //}
        return lstResult;
    }


    public class SuperJournalEntry implements Comparable{
        @AuraEnabled public double Debit {get;set;}
        @AuraEnabled public double Credit {get;set;}
        @AuraEnabled public String Description {get;set;}
        @AuraEnabled public Date EntryDate {get;set;}
        @AuraEnabled public String EntryType {get;set;}
        @AuraEnabled public String Source {get;set;}
				

		public Integer compareTo(Object compareTo){
			Integer intResult = 1;
			SuperJournalEntry st = (SuperJournalEntry)compareTo;
			if(EntryDate == st.EntryDate) intResult = 0;
			if(EntryDate > st.EntryDate) intResult = -1;
			return intResult;	
		}
    }
}