force-app/main/default/objects/Account/fields/Active_Subscriptions__c.field-meta.xml
<CustomField>
        <fullName>Active_Subscriptions__c</fullName>
        <label>Active Subscriptions</label>
        <summaryFilterItems>
            <field>Subscription__c.subscription_Status__c</field>
            <operation>equals</operation>
            <value>Active</value>
        </summaryFilterItems>
        <summaryForeignKey>Subscription__c.subscription_Account__c</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </CustomField>

force-app/main/default/objects/Subscription__c/Subscription__c.object-meta.xml
<CustomObject>
    <description>This object stores the actual subscription details, including selected Offer, Premiums. Delivery Schedules, frequency and term.</description>
    <label>Subscription</label>
    <nameField>
        <displayFormat>Sub-{0000}</displayFormat>
        <label>Subscription Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Subscription__c/fields/Contact__c.field-meta.xml
<CustomField>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Subscriptions</relationshipLabel>
        <relationshipName>Subscriptions</relationshipName>
        <type>Lookup</type>
    </CustomField>

force-app/main/default/objects/Subscription__c/fields/subscription_Account__c.field-meta.xml
<CustomField>
        <fullName>subscription_Account__c</fullName>
        <description>Relationship between Account and Subscriptions</description>
        <label>Household Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Subscriptions</relationshipLabel>
        <relationshipName>Subscriptions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </CustomField>

force-app/main/default/objects/Subscription__c/fields/subscription_Status__c.field-meta.xml
<CustomField>
        <fullName>subscription_Status__c</fullName>
        <description>Stores the status of the subscription</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>New</fullName>
                </value>
                <value>
                    <fullName>TERMINATED</fullName>
                </value>
                <value>
                    <fullName>INACTIVE</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </CustomField>

force-app/main/default/classes/ContactDataAccessor.cls
public class ContactDataAccessor {
    public static Contact getContactById(Id contactId) {
        return [ 
            SELECT Id, FirstName, LastName, AccountId, 
                (SELECT Id FROM Subscriptions__r WHERE subscription_Status__c = 'Active') 
            FROM Contact WHERE Id = :contactId
        ];
    }

    public static List<Contact> getContactsByEmail(String email) {
        return [
            SELECT Id, AccountId 
            FROM Contact 
            WHERE Email = :email
        ];
    }

    public static List<Contact> getContactsByPhone(String phone) {
        List<Contact> contacts;
        List<List<SObject>> searchList = [
            FIND :phone
            IN PHONE FIELDS
            RETURNING Contact(Id, AccountId, Account.BillingAddress, Account.Active_Subscriptions__c, FirstName, LastName)
        ];
        for (List<SObject> objects : searchList) {
            contacts = objects;
        }
        return contacts;
	}

    public static List<Contact> getContactsByPhoneAndBillingStreet(String phone, String street) {
		String houseWildcard = '%' + street + '%';
        List<Contact> contacts;
        List<List<SObject>> searchList = [
            FIND :phone
            IN PHONE FIELDS
            RETURNING Contact(Id, AccountId, Account.BillingAddress, Account.Active_Subscriptions__c, FirstName, LastName WHERE Account.BillingStreet LIKE :houseWildcard)
        ];
        for (List<SObject> objects : searchList) {
            contacts = objects;
        }
        return contacts;
	}
}