force-app/main/default/objects/Account/fields/DSI_Id__c.field-meta.xml
<CustomField>
        <fullName>DSI_Id__c</fullName>
        <externalId>true</externalId>
        <label>DSI Id</label>
        <length>50</length>
        <type>Text</type>
    </CustomField>

force-app/main/default/objects/Delivery_Address__c/Delivery_Address__c.object-meta.xml
<CustomObject>
    <description>Related Addresses to a Subscriber Household or Business and a Delivery Schedule of a Subscription.</description>
    <label>Delivery Address</label>
    <nameField>
        <displayFormat>DA-{0}</displayFormat>
        <label>Delivery Address Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Delivery Addresses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Delivery_Address__c/fields/Address_City__c.field-meta.xml
<CustomField>
        <fullName>Address_City__c</fullName>
        <label>City</label>
        <length>100</length>
        <type>Text</type>
    </CustomField>

force-app/main/default/objects/Delivery_Address__c/fields/Address_House__c.field-meta.xml
<CustomField>
        <fullName>Address_House__c</fullName>
        <label>House Number</label>
        <length>100</length>
        <type>Text</type>
    </CustomField>

force-app/main/default/objects/Delivery_Address__c/fields/Address_Postal_Route__c.field-meta.xml
<CustomField>
        <fullName>Address_Postal_Route__c</fullName>
        <label>Postal Route</label>
        <length>10</length>
        <type>Text</type>
    </CustomField>

force-app/main/default/objects/Delivery_Address__c/fields/Address_Street__c.field-meta.xml
<CustomField>
        <fullName>Address_Street__c</fullName>
        <label>Street</label>
        <length>200</length>
        <type>Text</type>
    </CustomField>

force-app/main/default/objects/Delivery_Address__c/fields/DSI_Id__c.field-meta.xml
<CustomField>
        <fullName>DSI_Id__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>DSI Id</label>
        <length>50</length>
        <type>Text</type>
        <unique>true</unique>
    </CustomField>

force-app/main/default/objects/Delivery_Schedule__c/Delivery_Schedule__c.object-meta.xml
<CustomObject>
    <description>Deliver Schedules control the address and which days a publication will be delivered as part of the press run.</description>
    <label>Delivery Schedule</label>
    <nameField>
        <displayFormat>DS-{0}</displayFormat>
        <label>Delivery Schedule Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Delivery Schedules</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Delivery_Schedule__c/fields/Customer_Notes__c.field-meta.xml
<CustomField>
        <fullName>Customer_Notes__c</fullName>
        <label>Customer Notes</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </CustomField>

force-app/main/default/objects/Delivery_Schedule__c/fields/Day_Friday__c.field-meta.xml
<CustomField>
        <fullName>Day_Friday__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Friday</label>
        <type>Checkbox</type>
    </CustomField>

force-app/main/default/objects/Delivery_Schedule__c/fields/Day_Monday__c.field-meta.xml
<CustomField>
        <fullName>Day_Monday__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Monday</label>
        <type>Checkbox</type>
    </CustomField>

force-app/main/default/objects/Delivery_Schedule__c/fields/Day_Saturday__c.field-meta.xml
<CustomField>
        <fullName>Day_Saturday__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Saturday</label>
        <type>Checkbox</type>
    </CustomField>

force-app/main/default/objects/Delivery_Schedule__c/fields/Day_Sunday__c.field-meta.xml
<CustomField>
        <fullName>Day_Sunday__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Sunday</label>
        <type>Checkbox</type>
    </CustomField>

force-app/main/default/objects/Delivery_Schedule__c/fields/Day_Thursday__c.field-meta.xml
<CustomField>
        <fullName>Day_Thursday__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Thursday</label>
        <type>Checkbox</type>
    </CustomField>

force-app/main/default/objects/Delivery_Schedule__c/fields/Day_Tuesday__c.field-meta.xml
<CustomField>
        <fullName>Day_Tuesday__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Tuesday</label>
        <type>Checkbox</type>
    </CustomField>

force-app/main/default/objects/Delivery_Schedule__c/fields/Day_Wednesday__c.field-meta.xml
<CustomField>
        <fullName>Day_Wednesday__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Wednesday</label>
        <type>Checkbox</type>
    </CustomField>

force-app/main/default/objects/Delivery_Schedule__c/fields/Delivery_Address__c.field-meta.xml
<CustomField>
        <fullName>Delivery_Address__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Delivery Address</label>
        <referenceTo>Delivery_Address__c</referenceTo>
        <relationshipLabel>Delivery Schedules</relationshipLabel>
        <relationshipName>Delivery_Schedules</relationshipName>
        <type>Lookup</type>
    </CustomField>

force-app/main/default/objects/Delivery_Schedule__c/fields/DSI_Id__c.field-meta.xml
<CustomField>
        <fullName>DSI_Id__c</fullName>
        <externalId>true</externalId>
        <label>DSI Id</label>
        <length>100</length>
        <type>Text</type>
    </CustomField>

force-app/main/default/objects/Delivery_Schedule__c/fields/End_Date__c.field-meta.xml
<CustomField>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </CustomField>

force-app/main/default/objects/Delivery_Schedule__c/fields/Frequency_Code__c.field-meta.xml
<CustomField>
        <fullName>Frequency_Code__c</fullName>
        <formula>IF( Day_Monday__c = true &amp;&amp; Day_Tuesday__c = true &amp;&amp; Day_Wednesday__c = true &amp;&amp; Day_Thursday__c = true &amp;&amp; Day_Friday__c = true &amp;&amp; Day_Saturday__c = true &amp;&amp; Day_Sunday__c = true, "7 Day Delivery (Monday-Sunday)",

If(Day_Monday__c = true &amp;&amp; Day_Tuesday__c = true &amp;&amp; Day_Wednesday__c = true &amp;&amp; Day_Thursday__c = true &amp;&amp; Day_Friday__c = true, "Monday-Friday Delivery",

If(Day_Monday__c = false &amp;&amp; Day_Tuesday__c = false &amp;&amp; Day_Wednesday__c = false &amp;&amp; Day_Thursday__c = false &amp;&amp; Day_Friday__c = false &amp;&amp; Day_Saturday__c = true &amp;&amp; Day_Sunday__c = true, "Saturday-Sunday Delivery",

If(Day_Monday__c = false &amp;&amp; Day_Tuesday__c = false &amp;&amp; Day_Wednesday__c = false &amp;&amp; Day_Thursday__c = false &amp;&amp; Day_Friday__c = false &amp;&amp; Day_Saturday__c = false &amp;&amp; Day_Sunday__c = true, "Sunday Only Delivery",

If(Day_Monday__c = false &amp;&amp; Day_Tuesday__c = false &amp;&amp; Day_Wednesday__c = false &amp;&amp; Day_Thursday__c = true &amp;&amp; Day_Friday__c = true &amp;&amp; Day_Saturday__c = true &amp;&amp; Day_Sunday__c = true, "Thursday-Sunday delivery","N/A" )

)
)))</formula>
        <label>Frequency Code</label>
        <type>Text</type>
    </CustomField>

force-app/main/default/objects/Delivery_Schedule__c/fields/Offer_Product__c.field-meta.xml
<CustomField>
        <fullName>Offer_Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Offer Product</label>
        <referenceTo>Offer_Product__c</referenceTo>
        <relationshipLabel>Delivery Schedules</relationshipLabel>
        <relationshipName>Delivery_Schedules</relationshipName>
        <type>Lookup</type>
    </CustomField>

force-app/main/default/objects/Delivery_Schedule__c/fields/Routelookup__c.field-meta.xml
<CustomField>
        <fullName>Routelookup__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Route</label>
        <referenceTo>Route__c</referenceTo>
        <relationshipLabel>Delivery Schedules</relationshipLabel>
        <relationshipName>Delivery_Schedules</relationshipName>
        <type>Lookup</type>
    </CustomField>

force-app/main/default/objects/Delivery_Schedule__c/fields/Start_Date__c.field-meta.xml
<CustomField>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </CustomField>

force-app/main/default/objects/Delivery_Schedule__c/fields/Status__c.field-meta.xml
<CustomField>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </CustomField>

force-app/main/default/objects/Delivery_Schedule__c/fields/subscription_Subscription__c.field-meta.xml
<CustomField>
        <fullName>subscription_Subscription__c</fullName>
        <description>This fields lookups to the shadow object, Subscription</description>
        <label>Subscription</label>
        <referenceTo>Subscription__c</referenceTo>
        <relationshipLabel>Delivery Schedules</relationshipLabel>
        <relationshipName>Delivery_Schedules</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </CustomField>

force-app/main/default/objects/Offer_Product__c/Offer_Product__c.object-meta.xml
<CustomObject>
    <label>Offer Product</label>
    <nameField>
        <label>Offer Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Offer Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Offer_Product__c/fields/DSI_Id__c.field-meta.xml
<CustomField>
        <fullName>DSI_Id__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>DSI Id</label>
        <length>100</length>
        <type>Text</type>
        <unique>true</unique>
    </CustomField>

force-app/main/default/objects/Offer_Product__c/fields/Frequency_Code__c.field-meta.xml
<CustomField>
        <fullName>Frequency_Code__c</fullName>
        <formula>IF( Monday__c = true &amp;&amp; Tuesday__c = true &amp;&amp; Wednesday__c = true &amp;&amp; Thursday__c = true &amp;&amp; Friday__c = true &amp;&amp; Saturday__c = true &amp;&amp; Sunday__c = true, "7 Day Delivery (Monday-Sunday)",

If(Monday__c = true &amp;&amp; Tuesday__c = true &amp;&amp; Wednesday__c = true &amp;&amp; Thursday__c = true &amp;&amp; Friday__c = true, "Monday-Friday Delivery",

If(Monday__c = false &amp;&amp; Tuesday__c = false &amp;&amp; Wednesday__c = false &amp;&amp; Thursday__c = false &amp;&amp; Friday__c = false &amp;&amp; Saturday__c = true &amp;&amp; Sunday__c = true, "Saturday-Sunday Delivery",

If(Monday__c = false &amp;&amp; Tuesday__c = false &amp;&amp; Wednesday__c = false &amp;&amp; Thursday__c = false &amp;&amp; Friday__c = false &amp;&amp; Saturday__c = false &amp;&amp; Sunday__c = true, "Sunday Only Delivery",

If(Monday__c = false &amp;&amp; Tuesday__c = false &amp;&amp; Wednesday__c = false &amp;&amp; Thursday__c = true &amp;&amp; Friday__c = true &amp;&amp; Saturday__c = true &amp;&amp; Sunday__c = true, "Thursday-Sunday delivery","N/A" )
)
)))</formula>
        <label>Frequency Code</label>
        <type>Text</type>
    </CustomField>

force-app/main/default/objects/Offer_Product__c/fields/Product__c.field-meta.xml
<CustomField>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Offer Products</relationshipLabel>
        <relationshipName>Offer_Products</relationshipName>
        <type>Lookup</type>
    </CustomField>

force-app/main/default/objects/Subscription__c/Subscription__c.object-meta.xml
<CustomObject>
    <description>This object stores the actual subscription details, including selected Offer, Premiums. Delivery Schedules, frequency and term.</description>
    <label>Subscription</label>
    <nameField>
        <displayFormat>Sub-{0000}</displayFormat>
        <label>Subscription Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Subscription__c/fields/Delivery_Schedule__c.field-meta.xml
<CustomField>
        <fullName>Delivery_Schedule__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Stores the relationship between Subscriptions and Delivery Schedule</description>
        <label>Delivery Schedule</label>
        <referenceTo>Delivery_Schedule__c</referenceTo>
        <relationshipLabel>Subscriptions</relationshipLabel>
        <relationshipName>Subscriptions</relationshipName>
        <type>Lookup</type>
    </CustomField>

force-app/main/default/classes/changeAddressController.cls
public with sharing class changeAddressController {

    @AuraEnabled
	public static void validateDeliverySchedules(Id subId){
        List<Profile> profileList = [SELECT Id, Name FROM Profile WHERE Id=:userinfo.getProfileId() LIMIT 1];
        String runningUserProfile = profileList[0].Name;
        if(runningUserProfile == 'CSR') return;
		List<Delivery_Schedule__c> result = [SELECT Id, Frequency_Code__c, Customer_Notes__c, DSI_Id__c,
		Day_Friday__c, Day_Monday__c, Day_Saturday__c, Day_Sunday__c, Day_Thursday__c, Day_Tuesday__c, Day_Wednesday__c,
		End_Date__c, Offer_Product__c, Start_Date__c, 
		Status__c, subscription_Subscription__c, Routelookup__c,
		Delivery_Address__c,  Delivery_Address__r.Address_City__c, Delivery_Address__r.Address_House__c, Delivery_Address__r.Address_Street__c, 
		Delivery_Address__r.Address_Postal_Route__c, Delivery_Address__r.Address_State__c, Offer_Product__r.Product__c
		FROM Delivery_Schedule__c WHERE subscription_Subscription__c = :subId];
		changeAddressController.validateSplitDelivery(result);
	}
	
	private static void validateSplitDelivery(List<Delivery_Schedule__c> dsList){
		for(Delivery_Schedule__c item1 : dsList){
			for(Delivery_Schedule__c item2 : dsList)
			if(item1.Start_Date__c <= item2.End_Date__c && 
			item1.End_Date__c >= item2.Start_Date__c && 
			item1.Id != item2.Id && 
			item1.Offer_Product__r.Product__c == item2.Offer_Product__r.Product__c){
				throw new AuraHandledException('A split delivery already exists for this subcription');
			}
		}
	}

    @AuraEnabled
    public static void updateBillingAddress(Id subId, Map<String, String> address) {
		try{
			Id accId = [SELECT subscription_Account__c FROM Subscription__c WHERE Id = :subId][0].subscription_Account__c;
            Account toUpdate = new Account(
                Id = accId,
                BillingStreet = address.get('street'),
                BillingState = address.get('state'),
                BillingPostalCode = address.get('postalCode'),
                BillingCity = address.get('city')
            );
            update toUpdate;
		}
		catch(Exception e){
			throw new AuraHandledException('Failed To Update Account');
		}	
    }

    @AuraEnabled
    public static String updateDeliveryAddress(Id subId, Id deliveryAddressId, Date effectiveDate) {
        System.debug('deliveryAddressId: ' + deliveryAddressId);
        Date startDate = effectiveDate;
		try{
            List<Delivery_Schedule__c> toUpsert = new List<Delivery_Schedule__c>();
            List<Id> publicationsList = new List<Id>(); 
            Date compareDate = Date.today().addDays(1);
            Date endDate = effectiveDate;
            Boolean beforeCutOff = CutOffManager.isBeforeCutOff('Carrier Memo');
            if (compareDate == effectiveDate) {
                if(!beforeCutOff){
                    startDate = startDate.addDays(1);
                }
            } else if (effectiveDate < compareDate && (effectiveDate.daysBetween(compareDate) == 1) ) {
                if(beforeCutOff){
                    startDate = startDate.addDays(1);
                } else {
                    startDate = startDate.addDays(2);
                }
            }
            // system.debug('---startDate---' + startDate);
            List<Delivery_Schedule__c> dsList = [
                SELECT Offer_Product__r.Product__c, Id, Customer_Notes__c, DSI_Id__c,
				Day_Friday__c, Day_Monday__c, Day_Saturday__c, Day_Sunday__c,
                 Day_Thursday__c, Day_Tuesday__c, Day_Wednesday__c,
				Delivery_Address__c, End_Date__c, Offer_Product__c, Start_Date__c, 
				Status__c, subscription_Subscription__c, Routelookup__c
			FROM Delivery_Schedule__c
			WHERE subscription_Subscription__c = :subId AND End_Date__c >= :endDate AND Start_Date__c <= :startDate ];

            for(Delivery_Schedule__c ds : dsList){
                if(!publicationsList.contains(ds.Offer_Product__c)){
                    Delivery_Schedule__c toInsert = new Delivery_Schedule__c(
                        Customer_Notes__c = ds.Customer_Notes__c,
                        Offer_Product__c = ds.Offer_Product__c,
                        Status__c = ds.Status__c,
                        Start_Date__c = startDate, 
                        End_Date__c = ds.End_Date__c,
                        Delivery_Address__c = deliveryAddressId,
                        subscription_Subscription__c = subId
                        );
                        setDeliveryDays(toInsert, dsList);
                        toUpsert.add(toInsert);
                }
                publicationsList.add(ds.Offer_Product__c);
                toUpsert.add(new Delivery_Schedule__c(Id = ds.Id, End_Date__c = startDate.addDays(-1)));
                
            }
              upsert toUpsert; 
        }
		catch(Exception e){
			throw new AuraHandledException('Failed To Update Account');
		}

        // set subscription 'Ready for DSI' flag
        if(subId != null){
            Subscription__c subToUpdate = new Subscription__c(Id = subId, Ready_for_DSI__c = true);
            update subToUpdate;
        }

        return startDate.format();
    }

    private static void setDeliveryDays(Delivery_Schedule__c toInsert, List<Delivery_Schedule__c> dsList){
        Map<String, Boolean> scheduleMap = new Map<String, Boolean>();
        scheduleMap.put('Day_Sunday__c', false);
        scheduleMap.put('Day_Monday__c', false);
        scheduleMap.put('Day_Tuesday__c', false);
        scheduleMap.put('Day_Wednesday__c', false);
        scheduleMap.put('Day_Thursday__c', false);
        scheduleMap.put('Day_Friday__c', false);
        scheduleMap.put('Day_Saturday__c', false);
        for(Delivery_Schedule__c ds : dsList){
            if(ds.Offer_Product__c == toInsert.Offer_Product__c){
                if(ds.Day_Sunday__c)
                    scheduleMap.put('Day_Sunday__c', true);
                if(ds.Day_Monday__c)
                    scheduleMap.put('Day_Monday__c', true);
                if(ds.Day_Tuesday__c)
                    scheduleMap.put('Day_Tuesday__c', true);
                if(ds.Day_Wednesday__c)
                    scheduleMap.put('Day_Wednesday__c', true);
                if(ds.Day_Thursday__c)
                    scheduleMap.put('Day_Thursday__c', true);
                if(ds.Day_Friday__c)
                    scheduleMap.put('Day_Friday__c', true);
                if(ds.Day_Saturday__c)
                    scheduleMap.put('Day_Saturday__c', true);
            }
        }
        toInsert.Day_Sunday__c = scheduleMap.get('Day_Sunday__c');
        toInsert.Day_Monday__c = scheduleMap.get('Day_Monday__c');
        toInsert.Day_Tuesday__c = scheduleMap.get('Day_Tuesday__c');
        toInsert.Day_Wednesday__c = scheduleMap.get('Day_Wednesday__c');
        toInsert.Day_Thursday__c = scheduleMap.get('Day_Thursday__c');
        toInsert.Day_Friday__c = scheduleMap.get('Day_Friday__c');
        toInsert.Day_Saturday__c = scheduleMap.get('Day_Saturday__c');
        
    }

}