force-app/main/default/objects/Subscription__c/Subscription__c.object-meta.xml
<CustomObject>
    <description>This object stores the actual subscription details, including selected Offer, Premiums. Delivery Schedules, frequency and term.</description>
    <label>Subscription</label>
    <nameField>
        <displayFormat>Sub-{0000}</displayFormat>
        <label>Subscription Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Subscription__c/fields/Auto_Renew_Tip__c.field-meta.xml
<CustomField>
        <fullName>Auto_Renew_Tip__c</fullName>
        <description>Tip amount for recurring automated invoices</description>
        <label>Auto Renew Tip</label>
        <precision>7</precision>
        <scale>2</scale>
        <type>Currency</type>
    </CustomField>

force-app/main/default/objects/Subscription__c/fields/subscription_Auto_Renew__c.field-meta.xml
<CustomField>
        <fullName>subscription_Auto_Renew__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Controls Auto Renew of Subscription</description>
        <inlineHelpText>If true, this denotes that the subscription is on EZ-pay</inlineHelpText>
        <label>Auto Renew</label>
        <type>Checkbox</type>
    </CustomField>

force-app/main/default/classes/AutoRenewSetupApi.cls
@RestResource(urlMapping='/autorenewsetup/*')
global with sharing class AutoRenewSetupApi {
    @HttpPost
    global static void post() {
        RestResponse res = RestContext.response;
        try {
            AutoRenewSetupInput input = (AutoRenewSetupInput)JSON.deserialize(RestContext.request.requestbody.toString(), AutoRenewSetupInput.class);
            validate(input);
			try {
				Subscription__c sub = SubscriptionDataAccessor.getSubscription(input.SubId);
				sub.Auto_Renew_Tip__c = input.Tip;
				sub.subscription_Auto_Renew__c = true;
				update sub;
                res.responseBody = Blob.valueOf(JSON.serialize(true));
			} catch (Exception e) {
				throw new GenericException('No subscription found');
			}
        } catch (GenericException e) {
            res.responseBody = Blob.valueOf(JSON.serialize(new ResponseError(e.getMessage())));
        } catch (Exception e) {
            res.statusCode = 500;
        }
    }

    private static void validate (AutoRenewSetupInput input) {
        if (!input.isValid()) {
            throw new GenericException('Invalid input');
        }
    }

    private class AutoRenewSetupInput {
        public String SubId {get;set;}
        public Decimal Tip {get;set;}

        public Boolean isValid() {
            if (String.isEmpty(SubId)) {
                return false;
            }
            if (Tip == null) {
                return false;
            }
            return true;
        }
    }
}