force-app/main/default/objects/Subscription__c/Subscription__c.object-meta.xml
<CustomObject>
    <description>This object stores the actual subscription details, including selected Offer, Premiums. Delivery Schedules, frequency and term.</description>
    <label>Subscription</label>
    <nameField>
        <displayFormat>Sub-{0000}</displayFormat>
        <label>Subscription Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Subscription__c/fields/Contact__c.field-meta.xml
<CustomField>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Subscriptions</relationshipLabel>
        <relationshipName>Subscriptions</relationshipName>
        <type>Lookup</type>
    </CustomField>

force-app/main/default/objects/Subscription__c/fields/subscription_Account__c.field-meta.xml
<CustomField>
        <fullName>subscription_Account__c</fullName>
        <description>Relationship between Account and Subscriptions</description>
        <label>Household Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Subscriptions</relationshipLabel>
        <relationshipName>Subscriptions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </CustomField>

force-app/main/default/classes/SubscriptionTriggerHandlerTest.cls
@IsTest
public class SubscriptionTriggerHandlerTest {
    @IsTest
    static void testCreateUserAfterSubscription(){
        Account acct = new Account(Name='Test Account');
        insert acct;

        Contact contact = new Contact(FirstName='Test',LastName='Contact', AccountId=acct.Id, Email='ApexTest@inquirer.com');
        insert contact;

        Subscription__c subscription = new Subscription__c(subscription_Account__c=acct.Id);
        subscription.Contact__c = contact.id;
        
        Test.startTest();
        Database.SaveResult result =  Database.insert(subscription, false);
        Test.stopTest();

        System.assert(result.isSuccess());
    }
}