force-app/main/default/objects/Subscription__c/Subscription__c.object-meta.xml
<CustomObject>
    <description>This object stores the actual subscription details, including selected Offer, Premiums. Delivery Schedules, frequency and term.</description>
    <label>Subscription</label>
    <nameField>
        <displayFormat>Sub-{0000}</displayFormat>
        <label>Subscription Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Subscription__c/fields/subscription_Account__c.field-meta.xml
<CustomField>
        <fullName>subscription_Account__c</fullName>
        <description>Relationship between Account and Subscriptions</description>
        <label>Household Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Subscriptions</relationshipLabel>
        <relationshipName>Subscriptions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </CustomField>

force-app/main/default/objects/Subscription__c/fields/Subscription_Amount__c.field-meta.xml
<CustomField>
        <fullName>Subscription_Amount__c</fullName>
        <formula>subscription_Offer__r.Total_Amount__c +  subscription_Offer__r.Activation_Fee__c</formula>
        <inlineHelpText>Total Subscription Amount plus Activation Fee</inlineHelpText>
        <label>Subscription Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </CustomField>

force-app/main/default/objects/Subscription__c/fields/subscription_Status__c.field-meta.xml
<CustomField>
        <fullName>subscription_Status__c</fullName>
        <description>Stores the status of the subscription</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>New</fullName>
                </value>
                <value>
                    <fullName>TERMINATED</fullName>
                </value>
                <value>
                    <fullName>INACTIVE</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </CustomField>

force-app/main/default/classes/RecurlyAccountDataAccessor.cls
public with sharing class RecurlyAccountDataAccessor {
    public static List<recurly_v2__Recurly_Account__c> getRecurlyAccountsByAccountId(Id accountId) {
        return [
            SELECT Id, recurly_v2__Code__c
            FROM recurly_v2__Recurly_Account__c
            WHERE recurly_v2__Account__c = :accountId
        ];
    }

    public static List<String> getRecurlyAcctIDsBySubscriptionId(Id subscriptionId){
        List<Subscription__c> subList = [
            SELECT Id, subscription_Account__c, subscription_Status__c, Subscription_Amount__c,
                (SELECT Id  FROM Recurly_Accounts__r)
            FROM Subscription__c
            WHERE Id = :subscriptionId
        ];

        List<String> recurlyAcctIds = new List<String>();
        for(Subscription__c sub : subList){
            for(recurly_v2__Recurly_Account__c ra : sub.Recurly_Accounts__r){
                system.debug('--recurly acct id: ' + ra.Id);
                recurlyAcctIds.add(ra.Id);
            }
        }
        return recurlyAcctIds;
    }
}