force-app/main/default/objects/Subscription__c/Subscription__c.object-meta.xml
<CustomObject>
    <description>This object stores the actual subscription details, including selected Offer, Premiums. Delivery Schedules, frequency and term.</description>
    <label>Subscription</label>
    <nameField>
        <displayFormat>Sub-{0000}</displayFormat>
        <label>Subscription Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Subscription__c/fields/Contact__c.field-meta.xml
<CustomField>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Subscriptions</relationshipLabel>
        <relationshipName>Subscriptions</relationshipName>
        <type>Lookup</type>
    </CustomField>

force-app/main/default/objects/Subscription__c/fields/subscription_Account__c.field-meta.xml
<CustomField>
        <fullName>subscription_Account__c</fullName>
        <description>Relationship between Account and Subscriptions</description>
        <label>Household Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Subscriptions</relationshipLabel>
        <relationshipName>Subscriptions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </CustomField>

force-app/main/default/objects/Subscription__c/fields/subscription_Status__c.field-meta.xml
<CustomField>
        <fullName>subscription_Status__c</fullName>
        <description>Stores the status of the subscription</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>New</fullName>
                </value>
                <value>
                    <fullName>TERMINATED</fullName>
                </value>
                <value>
                    <fullName>INACTIVE</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </CustomField>

force-app/main/default/classes/ChangePhoneApi.cls
@RestResource(urlMapping='/changephone/*')
global with sharing class ChangePhoneApi {
    @HttpPost
    global static void post() {
        RestResponse res = RestContext.response;
        try {
            ChangePhoneInput input = (ChangePhoneInput)JSON.deserialize(RestContext.request.requestbody.toString(), ChangePhoneInput.class);
            validate(input);
            updatePhone(input);
            res.responseBody = Blob.valueOf(JSON.serialize(true));
        } catch (GenericException e) {
            res.responseBody = Blob.valueOf(JSON.serialize(new ResponseError(e.getMessage())));
        } catch (Exception e) {
            res.statusCode = 500;
        }
    }

    private static void validate (ChangePhoneInput input) {
        if (!input.isValid()) {
            throw new GenericException('Invalid input');
        }
    }

    private static void updatePhone(ChangePhoneInput input) {
        Subscription__c activeSub = [SELECT Id, Contact__r.Id, Contact__r.Phone FROM Subscription__c WHERE subscription_Account__c = :input.CustAccount AND subscription_Status__c = 'Active' ];
        activeSub.Contact__r.Phone = input.NewPhone;
        update activeSub.Contact__r;
    }

    private class ChangePhoneInput {
        public String CustAccount {get;set;}
        public String NewPhone {get;set;}

        public Boolean isValid() {
            if (String.isEmpty(CustAccount)) {
                return false;
            }
            else if (String.isEmpty(NewPhone)) {
                return false;
            }
            return true;
        }
    }
}