force-app/main/default/objects/Subscription__c/Subscription__c.object-meta.xml
<CustomObject>
    <description>This object stores the actual subscription details, including selected Offer, Premiums. Delivery Schedules, frequency and term.</description>
    <label>Subscription</label>
    <nameField>
        <displayFormat>Sub-{0000}</displayFormat>
        <label>Subscription Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Subscription__c/fields/Outstanding_Credit__c.field-meta.xml
<CustomField>
        <fullName>Outstanding_Credit__c</fullName>
        <label>Today's Balance</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </CustomField>

force-app/main/default/objects/Subscription__c/fields/subscription_Status__c.field-meta.xml
<CustomField>
        <fullName>subscription_Status__c</fullName>
        <description>Stores the status of the subscription</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>New</fullName>
                </value>
                <value>
                    <fullName>TERMINATED</fullName>
                </value>
                <value>
                    <fullName>INACTIVE</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </CustomField>

force-app/main/default/objects/Subscription__c/fields/Total_Liability__c.field-meta.xml
<CustomField>
        <fullName>Total_Liability__c</fullName>
        <label>Total Liability</label>
        <precision>8</precision>
        <scale>2</scale>
        <type>Currency</type>
    </CustomField>

force-app/main/default/classes/PressRunSync.cls
global class PressRunSync implements Database.Batchable<SObject> {
	
	global Database.QueryLocator start(Database.BatchableContext context) {
		String query = 'SELECT Id, Outstanding_Credit__c, Total_Liability__c FROM Subscription__c WHERE subscription_Status__c = \'Active\'';
		return Database.getQueryLocator(query);
	}

   	global void execute(Database.BatchableContext context, List<Subscription__c> scope) {
		List<Subscription__c> subsToUpdate = new List<Subscription__c>();
        for(Subscription__c sub : scope){
            if(sub.Outstanding_Credit__c != sub.Total_Liability__c){
                subsToUpdate.add(
                    new Subscription__c(
                        Id = sub.Id,
                        Total_Liability__c = sub.Outstanding_Credit__c
                    )
                );
            }
        }
		if(!subsToUpdate.isEmpty()){}
			update subsToUpdate;
	}
	
	global void finish(Database.BatchableContext context) {
		PressRunProcess b = new PressRunProcess();
        database.executebatch(b);
	}
}