force-app/main/default/objects/Offer__c/Offer__c.object-meta.xml
<CustomObject>
    <description>Controls price, delivery, term for a subscription including print, digital and alternate publications. Also holds links to the premiums offered and the campaigns which will utilize this offer.</description>
    <label>Offer</label>
    <nameField>
        <label>Offer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Offers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Offer__c/fields/Activation_Fee__c.field-meta.xml
<CustomField>
        <fullName>Activation_Fee__c</fullName>
        <label>Activation Fee</label>
        <summarizedField>Offer_Product__c.Activation_Fee__c</summarizedField>
        <summaryFilterItems>
            <field>Offer_Product__c.Is_Activation_Fee__c</field>
            <operation>equals</operation>
            <value>True</value>
        </summaryFilterItems>
        <summaryForeignKey>Offer_Product__c.Offer__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </CustomField>

force-app/main/default/objects/Offer__c/fields/End_Date__c.field-meta.xml
<CustomField>
        <fullName>End_Date__c</fullName>
        <description>Stores the end date of the offer</description>
        <label>End Date</label>
        <type>Date</type>
    </CustomField>

force-app/main/default/objects/Offer__c/fields/Free_Trial__c.field-meta.xml
<CustomField>
        <fullName>Free_Trial__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This field is used to denote whether this offer is a free trial offer</description>
        <label>Free Trial?</label>
        <type>Checkbox</type>
    </CustomField>

force-app/main/default/objects/Offer__c/fields/Friday__c.field-meta.xml
<CustomField>
        <fullName>Friday__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Friday</label>
        <type>Checkbox</type>
    </CustomField>

force-app/main/default/objects/Offer__c/fields/Monday__c.field-meta.xml
<CustomField>
        <fullName>Monday__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Monday</label>
        <type>Checkbox</type>
    </CustomField>

force-app/main/default/objects/Offer__c/fields/Per_Copy__c.field-meta.xml
<CustomField>
        <fullName>Per_Copy__c</fullName>
        <label>Per Copy</label>
        <precision>18</precision>
        <scale>4</scale>
        <type>Currency</type>
    </CustomField>

force-app/main/default/objects/Offer__c/fields/Per_Week__c.field-meta.xml
<CustomField>
        <fullName>Per_Week__c</fullName>
        <formula>Total_Amount__c   /Number_of_Weeks__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>This value represents the Subscription Amount divided by the number of weeks</inlineHelpText>
        <label>Per Week</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </CustomField>

force-app/main/default/objects/Offer__c/fields/Renewal_Offer__c.field-meta.xml
<CustomField>
        <fullName>Renewal_Offer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Renewal Offer</label>
        <referenceTo>Offer__c</referenceTo>
        <relationshipLabel>Offers</relationshipLabel>
        <relationshipName>Offers</relationshipName>
        <type>Lookup</type>
    </CustomField>

force-app/main/default/objects/Offer__c/fields/Saturday__c.field-meta.xml
<CustomField>
        <fullName>Saturday__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Saturday</label>
        <type>Checkbox</type>
    </CustomField>

force-app/main/default/objects/Offer__c/fields/Start_Date__c.field-meta.xml
<CustomField>
        <fullName>Start_Date__c</fullName>
        <description>Stores the start date for this offer</description>
        <label>Start Date</label>
        <type>Date</type>
    </CustomField>

force-app/main/default/objects/Offer__c/fields/Total_Amount__c.field-meta.xml
<CustomField>
        <fullName>Total_Amount__c</fullName>
        <formula>Sunday_AmountRollup__c + AmountforRollup__c + Activation_Fee__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>This value is Subscription Amount plus Activation Fee if Activation fee exists for Offer</inlineHelpText>
        <label>Total Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </CustomField>

force-app/main/default/objects/Offer_Product__c/Offer_Product__c.object-meta.xml
<CustomObject>
    <label>Offer Product</label>
    <nameField>
        <label>Offer Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Offer Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Offer_Product__c/fields/Activation_Fee__c.field-meta.xml
<CustomField>
        <fullName>Activation_Fee__c</fullName>
        <label>Activation Fee</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Currency</type>
    </CustomField>

force-app/main/default/objects/Offer_Product__c/fields/Is_Activation_Fee__c.field-meta.xml
<CustomField>
        <fullName>Is_Activation_Fee__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Activation Fee</label>
        <type>Checkbox</type>
    </CustomField>

force-app/main/default/objects/Offer_Product__c/fields/Is_Digital__c.field-meta.xml
<CustomField>
        <fullName>Is_Digital__c</fullName>
        <formula>Product__r.IsDigital__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Is Digital</label>
        <type>Checkbox</type>
    </CustomField>

force-app/main/default/objects/Offer_Product__c/fields/Number_of_Weeks__c.field-meta.xml
<CustomField>
        <fullName>Number_of_Weeks__c</fullName>
        <label>Number of Weeks</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </CustomField>

force-app/main/default/objects/Offer_Product__c/fields/Offer__c.field-meta.xml
<CustomField>
        <fullName>Offer__c</fullName>
        <label>Offer</label>
        <referenceTo>Offer__c</referenceTo>
        <relationshipLabel>Offer Products</relationshipLabel>
        <relationshipName>Offer_Products</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </CustomField>

force-app/main/default/objects/Offer_Product__c/fields/Per_Copy_Sunday__c.field-meta.xml
<CustomField>
        <fullName>Per_Copy_Sunday__c</fullName>
        <label>Per Copy Sunday</label>
        <precision>18</precision>
        <scale>4</scale>
        <type>Currency</type>
    </CustomField>

force-app/main/default/objects/Offer_Product__c/fields/Per_Week__c.field-meta.xml
<CustomField>
        <fullName>Per_Week__c</fullName>
        <formula>(Amount__c + Sunday_Amount__c)/Term__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Per Week</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </CustomField>

force-app/main/default/objects/Offer_Product__c/fields/Product__c.field-meta.xml
<CustomField>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Offer Products</relationshipLabel>
        <relationshipName>Offer_Products</relationshipName>
        <type>Lookup</type>
    </CustomField>

force-app/main/default/objects/Offer_Product__c/fields/Sunday__c.field-meta.xml
<CustomField>
        <fullName>Sunday__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Sunday</label>
        <type>Checkbox</type>
    </CustomField>

force-app/main/default/objects/Offer_Product__c/fields/Thursday__c.field-meta.xml
<CustomField>
        <fullName>Thursday__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Thursday</label>
        <type>Checkbox</type>
    </CustomField>

force-app/main/default/objects/Offer_Product__c/fields/Total_Amount__c.field-meta.xml
<CustomField>
        <fullName>Total_Amount__c</fullName>
        <formula>Amount__c +  Sunday_Amount__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Total Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </CustomField>

force-app/main/default/objects/Offer_Product__c/fields/Tuesday__c.field-meta.xml
<CustomField>
        <fullName>Tuesday__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Tuesday</label>
        <type>Checkbox</type>
    </CustomField>

force-app/main/default/objects/Offer_Product__c/fields/Wednesday__c.field-meta.xml
<CustomField>
        <fullName>Wednesday__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Wednesday</label>
        <type>Checkbox</type>
    </CustomField>

force-app/main/default/objects/Subscription__c/Subscription__c.object-meta.xml
<CustomObject>
    <description>This object stores the actual subscription details, including selected Offer, Premiums. Delivery Schedules, frequency and term.</description>
    <label>Subscription</label>
    <nameField>
        <displayFormat>Sub-{0000}</displayFormat>
        <label>Subscription Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Subscription__c/fields/Activation_Fee__c.field-meta.xml
<CustomField>
        <fullName>Activation_Fee__c</fullName>
        <formula>subscription_Offer__r.Activation_Fee__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Activation Fee</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </CustomField>

force-app/main/default/objects/Subscription__c/fields/Friday__c.field-meta.xml
<CustomField>
        <fullName>Friday__c</fullName>
        <label>Friday</label>
        <summaryFilterItems>
            <field>Delivery_Schedule__c.Day_Friday__c</field>
            <operation>equals</operation>
            <value>True</value>
        </summaryFilterItems>
        <summaryForeignKey>Delivery_Schedule__c.subscription_Subscription__c</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </CustomField>

force-app/main/default/objects/Subscription__c/fields/Monday__c.field-meta.xml
<CustomField>
        <fullName>Monday__c</fullName>
        <label>Monday</label>
        <summaryFilterItems>
            <field>Delivery_Schedule__c.Day_Monday__c</field>
            <operation>equals</operation>
            <value>True</value>
        </summaryFilterItems>
        <summaryForeignKey>Delivery_Schedule__c.subscription_Subscription__c</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </CustomField>

force-app/main/default/objects/Subscription__c/fields/Saturday__c.field-meta.xml
<CustomField>
        <fullName>Saturday__c</fullName>
        <label>Saturday</label>
        <summaryFilterItems>
            <field>Delivery_Schedule__c.Day_Saturday__c</field>
            <operation>equals</operation>
            <value>True</value>
        </summaryFilterItems>
        <summaryForeignKey>Delivery_Schedule__c.subscription_Subscription__c</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </CustomField>

force-app/main/default/objects/Subscription__c/fields/subscription_Offer__c.field-meta.xml
<CustomField>
        <fullName>subscription_Offer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Stores the relationship to Offer</description>
        <label>Offer</label>
        <referenceTo>Offer__c</referenceTo>
        <relationshipLabel>Subscriptions</relationshipLabel>
        <relationshipName>Subscriptions1</relationshipName>
        <type>Lookup</type>
    </CustomField>

force-app/main/default/objects/Subscription__c/fields/Sunday__c.field-meta.xml
<CustomField>
        <fullName>Sunday__c</fullName>
        <label>Sunday</label>
        <summaryFilterItems>
            <field>Delivery_Schedule__c.Day_Sunday__c</field>
            <operation>equals</operation>
            <value>True</value>
        </summaryFilterItems>
        <summaryForeignKey>Delivery_Schedule__c.subscription_Subscription__c</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </CustomField>

force-app/main/default/objects/Subscription__c/fields/Thursday__c.field-meta.xml
<CustomField>
        <fullName>Thursday__c</fullName>
        <label>Thursday</label>
        <summaryFilterItems>
            <field>Delivery_Schedule__c.Day_Thursday__c</field>
            <operation>equals</operation>
            <value>True</value>
        </summaryFilterItems>
        <summaryForeignKey>Delivery_Schedule__c.subscription_Subscription__c</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </CustomField>

force-app/main/default/objects/Subscription__c/fields/Tuesday__c.field-meta.xml
<CustomField>
        <fullName>Tuesday__c</fullName>
        <label>Tuesday</label>
        <summaryFilterItems>
            <field>Delivery_Schedule__c.Day_Tuesday__c</field>
            <operation>equals</operation>
            <value>True</value>
        </summaryFilterItems>
        <summaryForeignKey>Delivery_Schedule__c.subscription_Subscription__c</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </CustomField>

force-app/main/default/objects/Subscription__c/fields/Wednesday__c.field-meta.xml
<CustomField>
        <fullName>Wednesday__c</fullName>
        <label>Wednesday</label>
        <summaryFilterItems>
            <field>Delivery_Schedule__c.Day_Wednesday__c</field>
            <operation>equals</operation>
            <value>True</value>
        </summaryFilterItems>
        <summaryForeignKey>Delivery_Schedule__c.subscription_Subscription__c</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </CustomField>

force-app/main/default/classes/OfferDataAccessor.cls
public with sharing class OfferDataAccessor {
    public static Offer__c getOfferById(Id offerId) {
        return [
            SELECT Id, Name, Per_Week__c, Number_of_Weeks__c, Total_Amount__c, Start_Date__c, End_Date__c, Monday__c, Tuesday__c, Wednesday__c, Thursday__c, Friday__c, Saturday__c, Sunday__c, Free_Trial__c,
                (SELECT Id, Name, Is_Activation_Fee__c, Is_Digital__c, Monday__c, Tuesday__c, Wednesday__c, Thursday__c, Friday__c, Saturday__c, Sunday__c, Product__r.Name, Product__c, Per_Copy__c, Per_Copy_Sunday__c, Activation_Fee__c FROM Offer_Products__r)
            FROM Offer__c 
            WHERE Id = :offerId
        ];
    }

    public static List<Offer__c> getOffersByIds(Set<Id> offerIds) {
        return [
            SELECT Id, Renewal_Offer__c
            FROM Offer__c 
            WHERE Id IN :offerIds
        ];
    }

    public static List<Offer__c> getSubscriptionDigitalOffers(Set<Id> subscriptionIds) {
        return [
            SELECT Id, (SELECT Name, Product__c, Per_Copy__c, Per_Copy_Sunday__c, subscription_Offer__c FROM Offer_Products__r WHERE Is_Digital__c = TRUE) 
            FROM Offer__c 
            WHERE Id in (SELECT subscription_Offer__c FROM Subscription__c WHERE Id IN :subscriptionIds)
        ];
    }
}