force-app/main/default/objects/Offer__c/Offer__c.object-meta.xml
<CustomObject>
    <description>Controls price, delivery, term for a subscription including print, digital and alternate publications. Also holds links to the premiums offered and the campaigns which will utilize this offer.</description>
    <label>Offer</label>
    <nameField>
        <label>Offer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Offers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Offer__c/fields/Renewal_Offer__c.field-meta.xml
<CustomField>
        <fullName>Renewal_Offer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Renewal Offer</label>
        <referenceTo>Offer__c</referenceTo>
        <relationshipLabel>Offers</relationshipLabel>
        <relationshipName>Offers</relationshipName>
        <type>Lookup</type>
    </CustomField>

force-app/main/default/objects/Subscription__c/Subscription__c.object-meta.xml
<CustomObject>
    <description>This object stores the actual subscription details, including selected Offer, Premiums. Delivery Schedules, frequency and term.</description>
    <label>Subscription</label>
    <nameField>
        <displayFormat>Sub-{0000}</displayFormat>
        <label>Subscription Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Subscription__c/fields/Pending_Offer__c.field-meta.xml
<CustomField>
        <fullName>Pending_Offer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Pending Offer</label>
        <referenceTo>Offer__c</referenceTo>
        <relationshipLabel>Subscriptions (Pending Offer)</relationshipLabel>
        <relationshipName>Subscriptions2</relationshipName>
        <type>Lookup</type>
    </CustomField>

force-app/main/default/objects/Subscription__c/fields/subscription_Offer__c.field-meta.xml
<CustomField>
        <fullName>subscription_Offer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Stores the relationship to Offer</description>
        <label>Offer</label>
        <referenceTo>Offer__c</referenceTo>
        <relationshipLabel>Subscriptions</relationshipLabel>
        <relationshipName>Subscriptions1</relationshipName>
        <type>Lookup</type>
    </CustomField>

force-app/main/default/classes/SubscriptionTriggerHandler.cls
public with sharing class SubscriptionTriggerHandler {
	private List<Subscription__c> newList;
	private List<Subscription__c> oldList;
	private Map<Id,Subscription__c> newMap;
	private Map<Id,Subscription__c> oldMap;

	private Set<Id> offerIds;
	private Map<Id, Offer__c> offers {
		get {
			if (offers == null) {
				offers = new Map<Id, Offer__c>(OfferDataAccessor.getOffersByIds(offerIds));
			}
			return offers;
		} private set;
	}

	public SubscriptionTriggerHandler(List<Subscription__c> newList, List<Subscription__c> oldList, Map<Id,Subscription__c> newMap, Map<Id,Subscription__c> oldMap) {
		this.newList = newList;
		this.oldList = oldList;
		this.newMap = newMap;
		this.oldMap = oldMap;
		init();
	}
	
	public void onBeforeInsert() {
		for (Subscription__c subscription : newList) {
			setOfferRelatedFields(subscription);
		}
	}

	private void setOfferRelatedFields(Subscription__c subscription) {
		if (offers != null) {
			Offer__c offer = offers.get(subscription.subscription_Offer__c);
			if (offer != null) {
				subscription.Pending_Offer__c = offer.Renewal_Offer__c;
			}
		}
	}

	private void init() {
		offerIds = new Set<Id>();
		for (Subscription__c subscription : newList) {
			if (subscription.subscription_Offer__c != null) {
				offerIds.add(subscription.subscription_Offer__c);
			}
		}
	}
}