force-app/main/default/objects/Delivery_Address__c/Delivery_Address__c.object-meta.xml
<CustomObject>
    <description>Related Addresses to a Subscriber Household or Business and a Delivery Schedule of a Subscription.</description>
    <label>Delivery Address</label>
    <nameField>
        <displayFormat>DA-{0}</displayFormat>
        <label>Delivery Address Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Delivery Addresses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Delivery_Address__c/fields/Address_City__c.field-meta.xml
<CustomField>
        <fullName>Address_City__c</fullName>
        <label>City</label>
        <length>100</length>
        <type>Text</type>
    </CustomField>

force-app/main/default/objects/Delivery_Address__c/fields/Address_House__c.field-meta.xml
<CustomField>
        <fullName>Address_House__c</fullName>
        <label>House Number</label>
        <length>100</length>
        <type>Text</type>
    </CustomField>

force-app/main/default/objects/Delivery_Address__c/fields/Address_State__c.field-meta.xml
<CustomField>
        <fullName>Address_State__c</fullName>
        <label>State</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Alabama</fullName>
                </value>
                <value>
                    <fullName>Alaska</fullName>
                </value>
                <value>
                    <fullName>Arizona</fullName>
                </value>
                <value>
                    <fullName>Arkansas</fullName>
                </value>
                <value>
                    <fullName>California</fullName>
                </value>
                <value>
                    <fullName>Colorado</fullName>
                </value>
                <value>
                    <fullName>Connecticut</fullName>
                </value>
                <value>
                    <fullName>Delaware</fullName>
                </value>
                <value>
                    <fullName>Florida</fullName>
                </value>
                <value>
                    <fullName>Georgia</fullName>
                </value>
                <value>
                    <fullName>Hawaii</fullName>
                </value>
                <value>
                    <fullName>Idaho</fullName>
                </value>
                <value>
                    <fullName>Illinois</fullName>
                </value>
                <value>
                    <fullName>Indiana</fullName>
                </value>
                <value>
                    <fullName>Iowa</fullName>
                </value>
                <value>
                    <fullName>Kansas</fullName>
                </value>
                <value>
                    <fullName>Kentucky</fullName>
                </value>
                <value>
                    <fullName>Louisiana</fullName>
                </value>
                <value>
                    <fullName>Maine</fullName>
                </value>
                <value>
                    <fullName>Maryland</fullName>
                </value>
                <value>
                    <fullName>Massachusetts</fullName>
                </value>
                <value>
                    <fullName>Michigan</fullName>
                </value>
                <value>
                    <fullName>Minnesota</fullName>
                </value>
                <value>
                    <fullName>Mississippi</fullName>
                </value>
                <value>
                    <fullName>Missouri</fullName>
                </value>
                <value>
                    <fullName>Montana</fullName>
                </value>
                <value>
                    <fullName>Nebraska</fullName>
                </value>
                <value>
                    <fullName>Nevada</fullName>
                </value>
                <value>
                    <fullName>New Hampshire</fullName>
                </value>
                <value>
                    <fullName>New Jersey</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </CustomField>

force-app/main/default/objects/Delivery_Address__c/fields/Address_Street__c.field-meta.xml
<CustomField>
        <fullName>Address_Street__c</fullName>
        <label>Street</label>
        <length>200</length>
        <type>Text</type>
    </CustomField>

force-app/main/default/objects/Delivery_Address__c/fields/Address_Suffix__c.field-meta.xml
<CustomField>
        <fullName>Address_Suffix__c</fullName>
        <label>Suffix</label>
        <length>10</length>
        <type>Text</type>
    </CustomField>

force-app/main/default/objects/Delivery_Address__c/fields/DSI_Id__c.field-meta.xml
<CustomField>
        <fullName>DSI_Id__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>DSI Id</label>
        <length>50</length>
        <type>Text</type>
        <unique>true</unique>
    </CustomField>

force-app/main/default/objects/Delivery_Address__c/fields/Melissa_Response__c.field-meta.xml
<CustomField>
        <fullName>Melissa_Response__c</fullName>
        <description>Response code returned</description>
        <label>Melissa Response</label>
        <length>50</length>
        <type>Text</type>
    </CustomField>

force-app/main/default/objects/Delivery_Address__c/fields/Post_Direction__c.field-meta.xml
<CustomField>
        <fullName>Post_Direction__c</fullName>
        <label>Post Direction</label>
        <length>10</length>
        <type>Text</type>
    </CustomField>

force-app/main/default/objects/Delivery_Address__c/fields/Pre_Direction__c.field-meta.xml
<CustomField>
        <fullName>Pre_Direction__c</fullName>
        <label>Pre Direction</label>
        <length>10</length>
        <type>Text</type>
    </CustomField>

force-app/main/default/objects/Delivery_Address__c/fields/Ready_for_DSI__c.field-meta.xml
<CustomField>
        <fullName>Ready_for_DSI__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Ready for DSI</label>
        <type>Checkbox</type>
    </CustomField>

force-app/main/default/objects/Delivery_Address__c/fields/Route__c.field-meta.xml
<CustomField>
        <fullName>Route__c</fullName>
        <label>Route #</label>
        <length>50</length>
        <type>Text</type>
    </CustomField>

force-app/main/default/objects/Delivery_Address__c/fields/Route_Number__c.field-meta.xml
<CustomField>
        <fullName>Route_Number__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Route #</label>
        <referenceTo>Route__c</referenceTo>
        <relationshipLabel>Delivery Addresses</relationshipLabel>
        <relationshipName>Delivery_Addresses</relationshipName>
        <type>Lookup</type>
    </CustomField>

force-app/main/default/objects/Delivery_Address__c/fields/Zip__c.field-meta.xml
<CustomField>
        <fullName>Zip__c</fullName>
        <label>Zip</label>
        <length>10</length>
        <type>Text</type>
    </CustomField>

force-app/main/default/objects/Route__c/Route__c.object-meta.xml
<CustomObject>
    <label>Route</label>
    <nameField>
        <label>Route Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Route</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Route_Street__c/Route_Street__c.object-meta.xml
<CustomObject>
    <label>Route Street</label>
    <nameField>
        <label>Route Street Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Route Streets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Route_Street__c/fields/Route__c.field-meta.xml
<CustomField>
        <fullName>Route__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Route</label>
        <referenceTo>Route__c</referenceTo>
        <relationshipLabel>Route Streets</relationshipLabel>
        <relationshipName>Route_Streets</relationshipName>
        <type>Lookup</type>
    </CustomField>

force-app/main/default/objects/Route_Street__c/fields/ZIP__c.field-meta.xml
<CustomField>
        <fullName>ZIP__c</fullName>
        <label>ZIP</label>
        <length>10</length>
        <type>Text</type>
    </CustomField>

force-app/main/default/classes/DeliveryAddressTriggerHandler.cls
public class DeliveryAddressTriggerHandler {
    private Map<Id, Delivery_Address__c> deliveryAddresses;
    private Map<Id, Delivery_Address__c> oldDeliveryAddresses;

    public DeliveryAddressTriggerHandler(Map<Id, Delivery_Address__c> deliveryAddresses, Map<Id, Delivery_Address__c> oldDeliveryAddresses) {
        this.deliveryAddresses = deliveryAddresses;
        this.oldDeliveryAddresses = oldDeliveryAddresses;
    }
    
    public void resetMelissaResponseBeforePersonatorExecutes() {
        if (!Test.isRunningTest() && !System.isFuture() && !System.isBatch() && deliveryAddresses.size() == 1) {
            Delivery_Address__c deliveryAddress = deliveryAddresses.values()[0];
            if ((oldDeliveryAddresses == null || addressFieldsChanged(deliveryAddress)) && !dsiIdHasChanged(deliveryAddress)) {
                deliveryAddress.Melissa_Response__c = null;
            }
        }
    }

	public void runMelissaDataPersonator() {
        if (!Test.isRunningTest() && !System.isFuture() && !System.isBatch() && deliveryAddresses.size() == 1) {
            Delivery_Address__c deliveryAddress = deliveryAddresses.values()[0];
            if ((oldDeliveryAddresses == null || addressFieldsChanged(deliveryAddress)) && (oldDeliveryAddresses == null || !dsiIdHasChanged(deliveryAddress))) {
                MDPERSONATOR.MD_PersonatorWSExt.doOnePersonator((String)deliveryAddress.Id);
            }
        }
    }

    public void updateAddressAfterPersonatorExecutes() {
        if (System.isFuture() && !System.isBatch() && deliveryAddresses.size() == 1) {
            for (Delivery_Address__c deliveryAddress : deliveryAddresses.values()) {
                if(!dsiIdHasChanged(deliveryAddress)){
                    MDPERSONATOR__MD_personatorResult__c personatorResult = getPersonatorResult(deliveryAddress.Id);
                    applyDeliveryCleanSuiteChanges(deliveryAddress, personatorResult);
                    setRouteFromDeliveryAddress(deliveryAddress);
                    if (deliveryAddress.Route_Number__c != null) {
                        deliveryAddress.Ready_for_DSI__c = true;
                    }
                }
            }
        }
    }

    private void setRouteFromDeliveryAddress(Delivery_Address__c deliveryAddress) {
        if (!String.isEmpty(deliveryAddress.Address_House__c)) {
            List<Route_Street__c> relatedRouteStreets = RouteDataAccessor.getRouteStreets(Decimal.valueOf(deliveryAddress.Address_House__c), deliveryAddress.Address_Street__c, deliveryAddress.Zip__c);
            deliveryAddress.Route_Number__c = (relatedRouteStreets.isEmpty()) ? null : relatedRouteStreets[0].Route__c;
        }
    }

    private Boolean addressFieldsChanged(Delivery_Address__c deliveryAddress) {
        Delivery_Address__c oldDeliveryAddress = oldDeliveryAddresses.get(deliveryAddress.Id);

        return (deliveryAddress.Address_House__c  != oldDeliveryAddress.Address_House__c) ||
            (deliveryAddress.Pre_Direction__c  != oldDeliveryAddress.Pre_Direction__c) ||
            (deliveryAddress.Address_Street__c  != oldDeliveryAddress.Address_Street__c) ||
            (deliveryAddress.Address_Suffix__c  != oldDeliveryAddress.Address_Suffix__c) ||
            (deliveryAddress.Post_Direction__c  != oldDeliveryAddress.Post_Direction__c) ||
            (deliveryAddress.Address_City__c != oldDeliveryAddress.Address_City__c) ||
            (deliveryAddress.Address_State__c != oldDeliveryAddress.Address_State__c) ||
            (deliveryAddress.Zip__c != oldDeliveryAddress.Zip__c);
    }

    private void applyDeliveryCleanSuiteChanges(Delivery_Address__c deliveryAddress, MDPERSONATOR__MD_personatorResult__c personator) {
        if (personator != null) {
            deliveryAddress.Address_House__c = personator.MDPERSONATOR__AddressHouseNumber__c;
            deliveryAddress.Pre_Direction__c = personator.MDPERSONATOR__AddressPreDirection__c;
            deliveryAddress.Post_Direction__c = personator.MDPERSONATOR__AddressPostDirection__c;
            deliveryAddress.Address_Street__c = personator.MDPERSONATOR__AddressStreetName__c;
            deliveryAddress.Address_Suffix__c = personator.MDPERSONATOR__AddressStreetSuffix__c;
            deliveryAddress.Address_City__c = personator.MDPERSONATOR__City__c;
            deliveryAddress.Address_State__c = personator.MDPERSONATOR__State__c;
            deliveryAddress.Zip__c = personator.MDPERSONATOR__PostalCode__c.substring(0, 5);
        }
    }

    private MDPERSONATOR__MD_personatorResult__c getPersonatorResult(Id recordId) {
        return [ SELECT Id, MDPERSONATOR__AddressHouseNumber__c, 
                MDPERSONATOR__AddressPreDirection__c, 
                MDPERSONATOR__AddressPostDirection__c, 
                MDPERSONATOR__AddressStreetName__c, 
                MDPERSONATOR__AddressStreetSuffix__c, 
                MDPERSONATOR__AddressLine1__c, 
                MDPERSONATOR__City__c, 
                MDPERSONATOR__State__c	, 
                MDPERSONATOR__PostalCode__c
            FROM MDPERSONATOR__MD_personatorResult__c 
            WHERE MDPERSONATOR__RecordID__c = :recordId
        ];
    }

    private Boolean dsiIdHasChanged(Delivery_Address__c deliveryAddress){
        Delivery_Address__c oldDeliveryAddress = oldDeliveryAddresses.get(deliveryAddress.Id);
        if (oldDeliveryAddress.DSI_Id__c != deliveryAddress.DSI_Id__c) {
            return true;
        }   
        return false;
    }
}