force-app/main/default/objects/Delivery_Address__c/Delivery_Address__c.object-meta.xml
<CustomObject>
    <description>Related Addresses to a Subscriber Household or Business and a Delivery Schedule of a Subscription.</description>
    <label>Delivery Address</label>
    <nameField>
        <displayFormat>DA-{0}</displayFormat>
        <label>Delivery Address Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Delivery Addresses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Delivery_Address__c/fields/Address_City__c.field-meta.xml
<CustomField>
        <fullName>Address_City__c</fullName>
        <label>City</label>
        <length>100</length>
        <type>Text</type>
    </CustomField>

force-app/main/default/objects/Delivery_Address__c/fields/Address_House__c.field-meta.xml
<CustomField>
        <fullName>Address_House__c</fullName>
        <label>House Number</label>
        <length>100</length>
        <type>Text</type>
    </CustomField>

force-app/main/default/objects/Delivery_Address__c/fields/Address_Postal_Route__c.field-meta.xml
<CustomField>
        <fullName>Address_Postal_Route__c</fullName>
        <label>Postal Route</label>
        <length>10</length>
        <type>Text</type>
    </CustomField>

force-app/main/default/objects/Delivery_Address__c/fields/Address_Street__c.field-meta.xml
<CustomField>
        <fullName>Address_Street__c</fullName>
        <label>Street</label>
        <length>200</length>
        <type>Text</type>
    </CustomField>

force-app/main/default/objects/Delivery_Address__c/fields/DSI_Id__c.field-meta.xml
<CustomField>
        <fullName>DSI_Id__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>DSI Id</label>
        <length>50</length>
        <type>Text</type>
        <unique>true</unique>
    </CustomField>

force-app/main/default/objects/Delivery_Schedule__c/Delivery_Schedule__c.object-meta.xml
<CustomObject>
    <description>Deliver Schedules control the address and which days a publication will be delivered as part of the press run.</description>
    <label>Delivery Schedule</label>
    <nameField>
        <displayFormat>DS-{0}</displayFormat>
        <label>Delivery Schedule Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Delivery Schedules</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Delivery_Schedule__c/fields/Customer_Notes__c.field-meta.xml
<CustomField>
        <fullName>Customer_Notes__c</fullName>
        <label>Customer Notes</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </CustomField>

force-app/main/default/objects/Delivery_Schedule__c/fields/Day_Friday__c.field-meta.xml
<CustomField>
        <fullName>Day_Friday__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Friday</label>
        <type>Checkbox</type>
    </CustomField>

force-app/main/default/objects/Delivery_Schedule__c/fields/Day_Monday__c.field-meta.xml
<CustomField>
        <fullName>Day_Monday__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Monday</label>
        <type>Checkbox</type>
    </CustomField>

force-app/main/default/objects/Delivery_Schedule__c/fields/Day_Saturday__c.field-meta.xml
<CustomField>
        <fullName>Day_Saturday__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Saturday</label>
        <type>Checkbox</type>
    </CustomField>

force-app/main/default/objects/Delivery_Schedule__c/fields/Day_Sunday__c.field-meta.xml
<CustomField>
        <fullName>Day_Sunday__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Sunday</label>
        <type>Checkbox</type>
    </CustomField>

force-app/main/default/objects/Delivery_Schedule__c/fields/Day_Thursday__c.field-meta.xml
<CustomField>
        <fullName>Day_Thursday__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Thursday</label>
        <type>Checkbox</type>
    </CustomField>

force-app/main/default/objects/Delivery_Schedule__c/fields/Day_Tuesday__c.field-meta.xml
<CustomField>
        <fullName>Day_Tuesday__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Tuesday</label>
        <type>Checkbox</type>
    </CustomField>

force-app/main/default/objects/Delivery_Schedule__c/fields/Day_Wednesday__c.field-meta.xml
<CustomField>
        <fullName>Day_Wednesday__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Wednesday</label>
        <type>Checkbox</type>
    </CustomField>

force-app/main/default/objects/Delivery_Schedule__c/fields/Delivery_Address__c.field-meta.xml
<CustomField>
        <fullName>Delivery_Address__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Delivery Address</label>
        <referenceTo>Delivery_Address__c</referenceTo>
        <relationshipLabel>Delivery Schedules</relationshipLabel>
        <relationshipName>Delivery_Schedules</relationshipName>
        <type>Lookup</type>
    </CustomField>

force-app/main/default/objects/Delivery_Schedule__c/fields/DSI_Id__c.field-meta.xml
<CustomField>
        <fullName>DSI_Id__c</fullName>
        <externalId>true</externalId>
        <label>DSI Id</label>
        <length>100</length>
        <type>Text</type>
    </CustomField>

force-app/main/default/objects/Delivery_Schedule__c/fields/End_Date__c.field-meta.xml
<CustomField>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </CustomField>

force-app/main/default/objects/Delivery_Schedule__c/fields/Frequency_Code__c.field-meta.xml
<CustomField>
        <fullName>Frequency_Code__c</fullName>
        <formula>IF( Day_Monday__c = true &amp;&amp; Day_Tuesday__c = true &amp;&amp; Day_Wednesday__c = true &amp;&amp; Day_Thursday__c = true &amp;&amp; Day_Friday__c = true &amp;&amp; Day_Saturday__c = true &amp;&amp; Day_Sunday__c = true, "7 Day Delivery (Monday-Sunday)",

If(Day_Monday__c = true &amp;&amp; Day_Tuesday__c = true &amp;&amp; Day_Wednesday__c = true &amp;&amp; Day_Thursday__c = true &amp;&amp; Day_Friday__c = true, "Monday-Friday Delivery",

If(Day_Monday__c = false &amp;&amp; Day_Tuesday__c = false &amp;&amp; Day_Wednesday__c = false &amp;&amp; Day_Thursday__c = false &amp;&amp; Day_Friday__c = false &amp;&amp; Day_Saturday__c = true &amp;&amp; Day_Sunday__c = true, "Saturday-Sunday Delivery",

If(Day_Monday__c = false &amp;&amp; Day_Tuesday__c = false &amp;&amp; Day_Wednesday__c = false &amp;&amp; Day_Thursday__c = false &amp;&amp; Day_Friday__c = false &amp;&amp; Day_Saturday__c = false &amp;&amp; Day_Sunday__c = true, "Sunday Only Delivery",

If(Day_Monday__c = false &amp;&amp; Day_Tuesday__c = false &amp;&amp; Day_Wednesday__c = false &amp;&amp; Day_Thursday__c = true &amp;&amp; Day_Friday__c = true &amp;&amp; Day_Saturday__c = true &amp;&amp; Day_Sunday__c = true, "Thursday-Sunday delivery","N/A" )

)
)))</formula>
        <label>Frequency Code</label>
        <type>Text</type>
    </CustomField>

force-app/main/default/objects/Delivery_Schedule__c/fields/Offer_Product__c.field-meta.xml
<CustomField>
        <fullName>Offer_Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Offer Product</label>
        <referenceTo>Offer_Product__c</referenceTo>
        <relationshipLabel>Delivery Schedules</relationshipLabel>
        <relationshipName>Delivery_Schedules</relationshipName>
        <type>Lookup</type>
    </CustomField>

force-app/main/default/objects/Delivery_Schedule__c/fields/Routelookup__c.field-meta.xml
<CustomField>
        <fullName>Routelookup__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Route</label>
        <referenceTo>Route__c</referenceTo>
        <relationshipLabel>Delivery Schedules</relationshipLabel>
        <relationshipName>Delivery_Schedules</relationshipName>
        <type>Lookup</type>
    </CustomField>

force-app/main/default/objects/Delivery_Schedule__c/fields/Start_Date__c.field-meta.xml
<CustomField>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </CustomField>

force-app/main/default/objects/Delivery_Schedule__c/fields/Status__c.field-meta.xml
<CustomField>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </CustomField>

force-app/main/default/objects/Delivery_Schedule__c/fields/subscription_Subscription__c.field-meta.xml
<CustomField>
        <fullName>subscription_Subscription__c</fullName>
        <description>This fields lookups to the shadow object, Subscription</description>
        <label>Subscription</label>
        <referenceTo>Subscription__c</referenceTo>
        <relationshipLabel>Delivery Schedules</relationshipLabel>
        <relationshipName>Delivery_Schedules</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </CustomField>

force-app/main/default/objects/Offer_Product__c/Offer_Product__c.object-meta.xml
<CustomObject>
    <label>Offer Product</label>
    <nameField>
        <label>Offer Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Offer Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Offer_Product__c/fields/DSI_Id__c.field-meta.xml
<CustomField>
        <fullName>DSI_Id__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>DSI Id</label>
        <length>100</length>
        <type>Text</type>
        <unique>true</unique>
    </CustomField>

force-app/main/default/objects/Offer_Product__c/fields/Frequency_Code__c.field-meta.xml
<CustomField>
        <fullName>Frequency_Code__c</fullName>
        <formula>IF( Monday__c = true &amp;&amp; Tuesday__c = true &amp;&amp; Wednesday__c = true &amp;&amp; Thursday__c = true &amp;&amp; Friday__c = true &amp;&amp; Saturday__c = true &amp;&amp; Sunday__c = true, "7 Day Delivery (Monday-Sunday)",

If(Monday__c = true &amp;&amp; Tuesday__c = true &amp;&amp; Wednesday__c = true &amp;&amp; Thursday__c = true &amp;&amp; Friday__c = true, "Monday-Friday Delivery",

If(Monday__c = false &amp;&amp; Tuesday__c = false &amp;&amp; Wednesday__c = false &amp;&amp; Thursday__c = false &amp;&amp; Friday__c = false &amp;&amp; Saturday__c = true &amp;&amp; Sunday__c = true, "Saturday-Sunday Delivery",

If(Monday__c = false &amp;&amp; Tuesday__c = false &amp;&amp; Wednesday__c = false &amp;&amp; Thursday__c = false &amp;&amp; Friday__c = false &amp;&amp; Saturday__c = false &amp;&amp; Sunday__c = true, "Sunday Only Delivery",

If(Monday__c = false &amp;&amp; Tuesday__c = false &amp;&amp; Wednesday__c = false &amp;&amp; Thursday__c = true &amp;&amp; Friday__c = true &amp;&amp; Saturday__c = true &amp;&amp; Sunday__c = true, "Thursday-Sunday delivery","N/A" )
)
)))</formula>
        <label>Frequency Code</label>
        <type>Text</type>
    </CustomField>

force-app/main/default/objects/Offer_Product__c/fields/Product__c.field-meta.xml
<CustomField>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Offer Products</relationshipLabel>
        <relationshipName>Offer_Products</relationshipName>
        <type>Lookup</type>
    </CustomField>

force-app/main/default/objects/Subscription__c/Subscription__c.object-meta.xml
<CustomObject>
    <description>This object stores the actual subscription details, including selected Offer, Premiums. Delivery Schedules, frequency and term.</description>
    <label>Subscription</label>
    <nameField>
        <displayFormat>Sub-{0000}</displayFormat>
        <label>Subscription Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Subscription__c/fields/Delivery_Schedule__c.field-meta.xml
<CustomField>
        <fullName>Delivery_Schedule__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Stores the relationship between Subscriptions and Delivery Schedule</description>
        <label>Delivery Schedule</label>
        <referenceTo>Delivery_Schedule__c</referenceTo>
        <relationshipLabel>Subscriptions</relationshipLabel>
        <relationshipName>Subscriptions</relationshipName>
        <type>Lookup</type>
    </CustomField>

force-app/main/default/classes/SplitDeliveryController.cls
public class SplitDeliveryController  {
	@AuraEnabled
	public static List<Delivery_Schedule__c> getDeliverySchedules(Id subId){
		List<Delivery_Schedule__c> result = [SELECT Id, Frequency_Code__c, Customer_Notes__c, DSI_Id__c,
		Day_Friday__c, Day_Monday__c, Day_Saturday__c, Day_Sunday__c, Day_Thursday__c, Day_Tuesday__c, Day_Wednesday__c,
		End_Date__c, Offer_Product__c, Start_Date__c, 
		Status__c, subscription_Subscription__c, Routelookup__c,
		Delivery_Address__c,  Delivery_Address__r.Address_City__c, Delivery_Address__r.Address_House__c, Delivery_Address__r.Address_Street__c, 
		Delivery_Address__r.Address_Postal_Route__c, Delivery_Address__r.Address_State__c, Offer_Product__r.Product__c
		FROM Delivery_Schedule__c WHERE subscription_Subscription__c = :subId];
		SplitDeliveryController.validateSplitDelivery(result);
		return result;
	}
	
	private static void validateSplitDelivery(List<Delivery_Schedule__c> dsList){
		for(Delivery_Schedule__c item1 : dsList){
			for(Delivery_Schedule__c item2 : dsList)
			if(item1.Start_Date__c <= item2.End_Date__c && 
			item1.End_Date__c >= item2.Start_Date__c && 
			item1.Id != item2.Id && 
			item1.Offer_Product__r.Product__c == item2.Offer_Product__r.Product__c){
				throw new AuraHandledException('A split delivery already exists for this subcription');
			}
		}
	}

    @AuraEnabled
    public static void rebuildDeliverySchedules(Id subId, Date startDate, Date endDate, Id weekdaySelection, Id weekendSelection){
		// init for cutoff rule
		Date currentDate = Date.today();
		Date theDayAfter = Date.today().addDays(1);

		Boolean beforeCutOff = CutOffManager.isBeforeCutOff('Carrier Memo');
		// apply cutoff rule
		if (currentDate == startDate) {
			if(beforeCutOff){
				startDate = startDate.addDays(1);
			} else {
				startDate = startDate.addDays(2);
			}
		} else if (theDayAfter == startDate){
			if(!beforeCutOff) {
				startDate = startDate.addDays(1);
			}
		}
		//system.debug('--SplitDeliveryController--rebuildDeliverySchedules---');
		//system.debug('--startDate--' + startDate);
		//system.debug('--endDate----' + endDate);

		List<Delivery_Schedule__c> toUpsert = new List<Delivery_Schedule__c>();
		Map<Id, List<Delivery_Schedule__c>> dsByPublication = new Map<Id, List<Delivery_Schedule__c>>();
		List<Delivery_Schedule__c> dsList = [
			SELECT Offer_Product__r.Product__c, Id, Customer_Notes__c, DSI_Id__c,
				Day_Friday__c, Day_Monday__c, Day_Saturday__c, Day_Sunday__c, Day_Thursday__c, Day_Tuesday__c, Day_Wednesday__c,
				Delivery_Address__c, End_Date__c, Offer_Product__c, Start_Date__c, 
				Status__c, subscription_Subscription__c, Routelookup__c
			FROM Delivery_Schedule__c
			WHERE subscription_Subscription__c = :subId AND Day_Monday__c = TRUE AND Day_Tuesday__c = TRUE AND Day_Wednesday__c = TRUE
			AND Day_Thursday__c = TRUE AND Day_Friday__c = TRUE AND Day_Sunday__c = TRUE];
		if(dsList.size() == 0)
			throw new AuraHandledException('No delivery schedules are available to split. A delivery schedule must have both weekday and weekend deliveries.');
		Map<String,Boolean> scheduleMap = new Map<String, Boolean>();
		for(Delivery_Schedule__c ds : dsList){
			if(dsByPublication.get(ds.Offer_Product__r.Product__c) == null){
				dsByPublication.put(ds.Offer_Product__r.Product__c, new List<Delivery_Schedule__c>{ds});
			}
			else{
				List<Delivery_Schedule__c> toUpdate = dsByPublication.get(ds.Offer_Product__r.Product__c);
				toUpdate.add(ds);
				dsByPublication.put(ds.Offer_Product__r.Product__c, toUpdate);
			}
		}
		for(Id pubId : dsByPublication.keySet()){
			scheduleMap.put('Day_Sunday__c', false);
			scheduleMap.put('Day_Monday__c', false);
			scheduleMap.put('Day_Tuesday__c', false);
			scheduleMap.put('Day_Wednesday__c', false);
			scheduleMap.put('Day_Thursday__c', false);
			scheduleMap.put('Day_Friday__c', false);
			scheduleMap.put('Day_Saturday__c', false);

			for(Delivery_Schedule__c ds : dsByPublication.get(pubId)){
				if(ds.Day_Sunday__c)
					scheduleMap.put('Day_Sunday__c', true);
				if(ds.Day_Monday__c)
					scheduleMap.put('Day_Monday__c', true);
				if(ds.Day_Tuesday__c)
					scheduleMap.put('Day_Tuesday__c', true);
				if(ds.Day_Wednesday__c)
					scheduleMap.put('Day_Wednesday__c', true);
				if(ds.Day_Thursday__c)
					scheduleMap.put('Day_Thursday__c', true);
				if(ds.Day_Friday__c)
					scheduleMap.put('Day_Friday__c', true);
				if(ds.Day_Saturday__c)
					scheduleMap.put('Day_Saturday__c', true);
			}
			system.debug('==SplitDelivery: ' + startDate + ' | ' + endDate);

			Delivery_Schedule__c existingDs = dsByPublication.get(pubId)[0];
			Delivery_Schedule__c weekdayDs = new Delivery_Schedule__c(
				Day_Monday__c = scheduleMap.get('Day_Monday__c'),
				Day_Tuesday__c = scheduleMap.get('Day_Tuesday__c'),
				Day_Wednesday__c = scheduleMap.get('Day_Wednesday__c'),
				Day_Thursday__c = scheduleMap.get('Day_Thursday__c'),
				Day_Friday__c = scheduleMap.get('Day_Friday__c'),
				Customer_Notes__c = existingDs.Customer_Notes__c,
				Offer_Product__c = existingDs.Offer_Product__c,
				Status__c = existingDs.Status__c,
				Start_Date__c = startDate, 
				End_Date__c = endDate != null ? endDate : existingDs.End_Date__c,
				Delivery_Address__c = weekdaySelection,
				subscription_Subscription__c = subId
			);
			toUpsert.add(weekdayDs);

			Delivery_Schedule__c weekendDs = new Delivery_Schedule__c(	
				Day_Saturday__c = scheduleMap.get('Day_Saturday__c'),
				Day_Sunday__c = scheduleMap.get('Day_Sunday__c'),
				Customer_Notes__c = existingDs.Customer_Notes__c,
				Offer_Product__c = existingDs.Offer_Product__c,
				Status__c = existingDs.Status__c,
				Start_Date__c = startDate, 
				End_Date__c = endDate != null ? endDate : existingDs.End_Date__c,
				Delivery_Address__c = weekendSelection,
				subscription_Subscription__c = subId	
			);
			toUpsert.add(weekendDs);

			for(Delivery_Schedule__c ds : dsByPublication.get(pubId)){
				if(endDate == null){
					ds.End_Date__c = startDate.addDays(-1);
				}
				else if(ds.End_Date__c > endDate){
					toUpsert.add(new Delivery_Schedule__c(
						Day_Monday__c = ds.Day_Monday__c,
						Day_Tuesday__c = ds.Day_Tuesday__c,
						Day_Wednesday__c = ds.Day_Wednesday__c,
						Day_Thursday__c = ds.Day_Thursday__c,
						Day_Friday__c = ds.Day_Friday__c,
						Day_Saturday__c = ds.Day_Saturday__c,
						Day_Sunday__c = ds.Day_Sunday__c,
						Customer_Notes__c = ds.Customer_Notes__c,
						Offer_Product__c = ds.Offer_Product__c,
						Status__c = ds.Status__c,
						Start_Date__c = endDate.addDays(1), 
						End_Date__c = ds.End_Date__c,
						Delivery_Address__c = ds.Delivery_Address__c,
						subscription_Subscription__c = ds.subscription_Subscription__c
					));
					ds.End_Date__c = startDate.addDays(-1);
				}
				toUpsert.add(ds);
			}
		}
		Subscription__c toUpdate = new Subscription__c(Id = subId, Ready_for_DSI__c = true);
		update toUpdate;
		upsert toUpsert;
    }
}