force-app/main/default/objects/Delivery_Address__c/Delivery_Address__c.object-meta.xml
<CustomObject>
    <description>Related Addresses to a Subscriber Household or Business and a Delivery Schedule of a Subscription.</description>
    <label>Delivery Address</label>
    <nameField>
        <displayFormat>DA-{0}</displayFormat>
        <label>Delivery Address Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Delivery Addresses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Delivery_Address__c/fields/District__c.field-meta.xml
<CustomField>
        <fullName>District__c</fullName>
        <label>District</label>
        <length>50</length>
        <type>Text</type>
    </CustomField>

force-app/main/default/objects/Delivery_Schedule__c/Delivery_Schedule__c.object-meta.xml
<CustomObject>
    <description>Deliver Schedules control the address and which days a publication will be delivered as part of the press run.</description>
    <label>Delivery Schedule</label>
    <nameField>
        <displayFormat>DS-{0}</displayFormat>
        <label>Delivery Schedule Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Delivery Schedules</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Delivery_Schedule__c/fields/Day_Friday__c.field-meta.xml
<CustomField>
        <fullName>Day_Friday__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Friday</label>
        <type>Checkbox</type>
    </CustomField>

force-app/main/default/objects/Delivery_Schedule__c/fields/Day_Monday__c.field-meta.xml
<CustomField>
        <fullName>Day_Monday__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Monday</label>
        <type>Checkbox</type>
    </CustomField>

force-app/main/default/objects/Delivery_Schedule__c/fields/Day_Saturday__c.field-meta.xml
<CustomField>
        <fullName>Day_Saturday__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Saturday</label>
        <type>Checkbox</type>
    </CustomField>

force-app/main/default/objects/Delivery_Schedule__c/fields/Day_Sunday__c.field-meta.xml
<CustomField>
        <fullName>Day_Sunday__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Sunday</label>
        <type>Checkbox</type>
    </CustomField>

force-app/main/default/objects/Delivery_Schedule__c/fields/Day_Thursday__c.field-meta.xml
<CustomField>
        <fullName>Day_Thursday__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Thursday</label>
        <type>Checkbox</type>
    </CustomField>

force-app/main/default/objects/Delivery_Schedule__c/fields/Day_Tuesday__c.field-meta.xml
<CustomField>
        <fullName>Day_Tuesday__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Tuesday</label>
        <type>Checkbox</type>
    </CustomField>

force-app/main/default/objects/Delivery_Schedule__c/fields/Day_Wednesday__c.field-meta.xml
<CustomField>
        <fullName>Day_Wednesday__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Wednesday</label>
        <type>Checkbox</type>
    </CustomField>

force-app/main/default/objects/Delivery_Schedule__c/fields/Delivery_Address__c.field-meta.xml
<CustomField>
        <fullName>Delivery_Address__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Delivery Address</label>
        <referenceTo>Delivery_Address__c</referenceTo>
        <relationshipLabel>Delivery Schedules</relationshipLabel>
        <relationshipName>Delivery_Schedules</relationshipName>
        <type>Lookup</type>
    </CustomField>

force-app/main/default/objects/Delivery_Schedule__c/fields/District__c.field-meta.xml
<CustomField>
        <fullName>District__c</fullName>
        <label>District</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>105</fullName>
                </value>
                <value>
                    <fullName>108</fullName>
                </value>
                <value>
                    <fullName>110</fullName>
                </value>
                <value>
                    <fullName>111</fullName>
                </value>
                <value>
                    <fullName>112</fullName>
                </value>
                <value>
                    <fullName>113</fullName>
                </value>
                <value>
                    <fullName>114</fullName>
                </value>
                <value>
                    <fullName>117</fullName>
                </value>
                <value>
                    <fullName>118</fullName>
                </value>
                <value>
                    <fullName>119</fullName>
                </value>
                <value>
                    <fullName>121</fullName>
                </value>
                <value>
                    <fullName>127</fullName>
                </value>
                <value>
                    <fullName>148</fullName>
                </value>
                <value>
                    <fullName>218</fullName>
                </value>
                <value>
                    <fullName>245</fullName>
                </value>
                <value>
                    <fullName>252</fullName>
                </value>
                <value>
                    <fullName>255</fullName>
                </value>
                <value>
                    <fullName>366</fullName>
                </value>
                <value>
                    <fullName>367</fullName>
                </value>
                <value>
                    <fullName>368</fullName>
                </value>
                <value>
                    <fullName>392</fullName>
                </value>
                <value>
                    <fullName>399</fullName>
                </value>
                <value>
                    <fullName>492</fullName>
                </value>
                <value>
                    <fullName>495</fullName>
                </value>
                <value>
                    <fullName>499</fullName>
                </value>
                <value>
                    <fullName>593</fullName>
                </value>
                <value>
                    <fullName>608</fullName>
                </value>
                <value>
                    <fullName>609</fullName>
                </value>
                <value>
                    <fullName>612</fullName>
                </value>
                <value>
                    <fullName>613</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </CustomField>

force-app/main/default/objects/Delivery_Schedule__c/fields/Offer_Product__c.field-meta.xml
<CustomField>
        <fullName>Offer_Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Offer Product</label>
        <referenceTo>Offer_Product__c</referenceTo>
        <relationshipLabel>Delivery Schedules</relationshipLabel>
        <relationshipName>Delivery_Schedules</relationshipName>
        <type>Lookup</type>
    </CustomField>

force-app/main/default/objects/Delivery_Schedule__c/fields/Routelookup__c.field-meta.xml
<CustomField>
        <fullName>Routelookup__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Route</label>
        <referenceTo>Route__c</referenceTo>
        <relationshipLabel>Delivery Schedules</relationshipLabel>
        <relationshipName>Delivery_Schedules</relationshipName>
        <type>Lookup</type>
    </CustomField>

force-app/main/default/objects/Delivery_Schedule__c/fields/subscription_Subscription__c.field-meta.xml
<CustomField>
        <fullName>subscription_Subscription__c</fullName>
        <description>This fields lookups to the shadow object, Subscription</description>
        <label>Subscription</label>
        <referenceTo>Subscription__c</referenceTo>
        <relationshipLabel>Delivery Schedules</relationshipLabel>
        <relationshipName>Delivery_Schedules</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </CustomField>

force-app/main/default/objects/Offer_Product__c/Offer_Product__c.object-meta.xml
<CustomObject>
    <label>Offer Product</label>
    <nameField>
        <label>Offer Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Offer Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Route__c/Route__c.object-meta.xml
<CustomObject>
    <label>Route</label>
    <nameField>
        <label>Route Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Route</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Route__c/fields/District__c.field-meta.xml
<CustomField>
        <fullName>District__c</fullName>
        <label>District</label>
        <length>25</length>
        <type>Text</type>
    </CustomField>

force-app/main/default/objects/Route__c/fields/Redelivery_Allowed__c.field-meta.xml
<CustomField>
        <fullName>Redelivery_Allowed__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Redelivery Allowed</label>
        <type>Checkbox</type>
    </CustomField>

force-app/main/default/objects/Subscription__c/Subscription__c.object-meta.xml
<CustomObject>
    <description>This object stores the actual subscription details, including selected Offer, Premiums. Delivery Schedules, frequency and term.</description>
    <label>Subscription</label>
    <nameField>
        <displayFormat>Sub-{0000}</displayFormat>
        <label>Subscription Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Subscription__c/fields/Delivery_Schedule__c.field-meta.xml
<CustomField>
        <fullName>Delivery_Schedule__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Stores the relationship between Subscriptions and Delivery Schedule</description>
        <label>Delivery Schedule</label>
        <referenceTo>Delivery_Schedule__c</referenceTo>
        <relationshipLabel>Subscriptions</relationshipLabel>
        <relationshipName>Subscriptions</relationshipName>
        <type>Lookup</type>
    </CustomField>

force-app/main/default/objects/Subscription__c/fields/subscription_Account__c.field-meta.xml
<CustomField>
        <fullName>subscription_Account__c</fullName>
        <description>Relationship between Account and Subscriptions</description>
        <label>Household Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Subscriptions</relationshipLabel>
        <relationshipName>Subscriptions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </CustomField>

force-app/main/default/objects/Subscription__c/fields/subscription_Auto_Renew__c.field-meta.xml
<CustomField>
        <fullName>subscription_Auto_Renew__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Controls Auto Renew of Subscription</description>
        <inlineHelpText>If true, this denotes that the subscription is on EZ-pay</inlineHelpText>
        <label>Auto Renew</label>
        <type>Checkbox</type>
    </CustomField>

force-app/main/default/objects/Subscription__c/fields/subscription_Status__c.field-meta.xml
<CustomField>
        <fullName>subscription_Status__c</fullName>
        <description>Stores the status of the subscription</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>New</fullName>
                </value>
                <value>
                    <fullName>TERMINATED</fullName>
                </value>
                <value>
                    <fullName>INACTIVE</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </CustomField>

force-app/main/default/classes/DeliveryScheduleDataAccessor.cls
public class DeliveryScheduleDataAccessor {
    private static String todaysDayOfWeek = System.now().format('EEEE');

    public static List<Delivery_Schedule__c> getCurrentDayDeliverySchedule(String accountId, String routeId) {
        String baseQuery = 'SELECT Id, Day_Sunday__c, Day_Monday__c, Day_Tuesday__c, Day_Wednesday__c, Day_Thursday__c, Day_Friday__c, Day_Saturday__c, Offer_Product__r.Name, Routelookup__r.Redelivery_Allowed__c, subscription_Subscription__r.subscription_Account__c, subscription_Subscription__r.subscription_Status__c, subscription_Subscription__c FROM Delivery_Schedule__c';
        String identifier = (String.isNotEmpty(routeId)) ? 'Routelookup__c = :routeId' : 'subscription_Subscription__r.subscription_Account__c = :accountId';
        String isSubActive = 'subscription_Subscription__r.subscription_Status__c = \'Active\'';
        String todaysFieldIsTrue = 'Day_' + todaysDayOfWeek + '__c' + ' = TRUE';
        return Database.query(String.join(new List<String>{baseQuery, 'WHERE', identifier, 'AND', isSubActive, 'AND', todaysFieldIsTrue}, ' '));
    }

    public static List<Delivery_Schedule__c> getDeliveryScheduleBySubId(Id subId) {
        return [
            SELECT Id, Day_Sunday__c, Day_Monday__c, Day_Tuesday__c, Day_Wednesday__c, Day_Thursday__c, Day_Friday__c, Day_Saturday__c,
                Offer_Product__r.Name, Routelookup__r.Redelivery_Allowed__c, subscription_Subscription__r.subscription_Account__c, Delivery_Address__c, 
                subscription_Subscription__r.subscription_Status__c, subscription_Subscription__c, Routelookup__c, Routelookup__r.District__c,
				subscription_Subscription__r.subscription_Auto_Renew__c
            FROM Delivery_Schedule__c
            WHERE subscription_Subscription__c = :SubId
        ];
    }
}