force-app/main/default/objects/Delivery_Address__c/Delivery_Address__c.object-meta.xml
<CustomObject>
    <description>Related Addresses to a Subscriber Household or Business and a Delivery Schedule of a Subscription.</description>
    <label>Delivery Address</label>
    <nameField>
        <displayFormat>DA-{0}</displayFormat>
        <label>Delivery Address Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Delivery Addresses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Delivery_Address__c/fields/Address_City__c.field-meta.xml
<CustomField>
        <fullName>Address_City__c</fullName>
        <label>City</label>
        <length>100</length>
        <type>Text</type>
    </CustomField>

force-app/main/default/objects/Delivery_Address__c/fields/Address_State__c.field-meta.xml
<CustomField>
        <fullName>Address_State__c</fullName>
        <label>State</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Alabama</fullName>
                </value>
                <value>
                    <fullName>Alaska</fullName>
                </value>
                <value>
                    <fullName>Arizona</fullName>
                </value>
                <value>
                    <fullName>Arkansas</fullName>
                </value>
                <value>
                    <fullName>California</fullName>
                </value>
                <value>
                    <fullName>Colorado</fullName>
                </value>
                <value>
                    <fullName>Connecticut</fullName>
                </value>
                <value>
                    <fullName>Delaware</fullName>
                </value>
                <value>
                    <fullName>Florida</fullName>
                </value>
                <value>
                    <fullName>Georgia</fullName>
                </value>
                <value>
                    <fullName>Hawaii</fullName>
                </value>
                <value>
                    <fullName>Idaho</fullName>
                </value>
                <value>
                    <fullName>Illinois</fullName>
                </value>
                <value>
                    <fullName>Indiana</fullName>
                </value>
                <value>
                    <fullName>Iowa</fullName>
                </value>
                <value>
                    <fullName>Kansas</fullName>
                </value>
                <value>
                    <fullName>Kentucky</fullName>
                </value>
                <value>
                    <fullName>Louisiana</fullName>
                </value>
                <value>
                    <fullName>Maine</fullName>
                </value>
                <value>
                    <fullName>Maryland</fullName>
                </value>
                <value>
                    <fullName>Massachusetts</fullName>
                </value>
                <value>
                    <fullName>Michigan</fullName>
                </value>
                <value>
                    <fullName>Minnesota</fullName>
                </value>
                <value>
                    <fullName>Mississippi</fullName>
                </value>
                <value>
                    <fullName>Missouri</fullName>
                </value>
                <value>
                    <fullName>Montana</fullName>
                </value>
                <value>
                    <fullName>Nebraska</fullName>
                </value>
                <value>
                    <fullName>Nevada</fullName>
                </value>
                <value>
                    <fullName>New Hampshire</fullName>
                </value>
                <value>
                    <fullName>New Jersey</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </CustomField>

force-app/main/default/objects/Delivery_Address__c/fields/Address_Street__c.field-meta.xml
<CustomField>
        <fullName>Address_Street__c</fullName>
        <label>Street</label>
        <length>200</length>
        <type>Text</type>
    </CustomField>

force-app/main/default/objects/Delivery_Schedule__c/Delivery_Schedule__c.object-meta.xml
<CustomObject>
    <description>Deliver Schedules control the address and which days a publication will be delivered as part of the press run.</description>
    <label>Delivery Schedule</label>
    <nameField>
        <displayFormat>DS-{0}</displayFormat>
        <label>Delivery Schedule Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Delivery Schedules</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Delivery_Schedule__c/fields/Day_Monday__c.field-meta.xml
<CustomField>
        <fullName>Day_Monday__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Monday</label>
        <type>Checkbox</type>
    </CustomField>

force-app/main/default/objects/Delivery_Schedule__c/fields/Day_Thursday__c.field-meta.xml
<CustomField>
        <fullName>Day_Thursday__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Thursday</label>
        <type>Checkbox</type>
    </CustomField>

force-app/main/default/objects/Delivery_Schedule__c/fields/Day_Tuesday__c.field-meta.xml
<CustomField>
        <fullName>Day_Tuesday__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Tuesday</label>
        <type>Checkbox</type>
    </CustomField>

force-app/main/default/objects/Delivery_Schedule__c/fields/Day_Wednesday__c.field-meta.xml
<CustomField>
        <fullName>Day_Wednesday__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Wednesday</label>
        <type>Checkbox</type>
    </CustomField>

force-app/main/default/objects/Delivery_Schedule__c/fields/Delivery_Address__c.field-meta.xml
<CustomField>
        <fullName>Delivery_Address__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Delivery Address</label>
        <referenceTo>Delivery_Address__c</referenceTo>
        <relationshipLabel>Delivery Schedules</relationshipLabel>
        <relationshipName>Delivery_Schedules</relationshipName>
        <type>Lookup</type>
    </CustomField>

force-app/main/default/objects/Delivery_Schedule__c/fields/Delivery_Instructions__c.field-meta.xml
<CustomField>
        <fullName>Delivery_Instructions__c</fullName>
        <label>Delivery Instructions</label>
        <length>200</length>
        <type>Text</type>
    </CustomField>

force-app/main/default/objects/Delivery_Schedule__c/fields/Offer_Product__c.field-meta.xml
<CustomField>
        <fullName>Offer_Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Offer Product</label>
        <referenceTo>Offer_Product__c</referenceTo>
        <relationshipLabel>Delivery Schedules</relationshipLabel>
        <relationshipName>Delivery_Schedules</relationshipName>
        <type>Lookup</type>
    </CustomField>

force-app/main/default/objects/Delivery_Schedule__c/fields/subscription_Subscription__c.field-meta.xml
<CustomField>
        <fullName>subscription_Subscription__c</fullName>
        <description>This fields lookups to the shadow object, Subscription</description>
        <label>Subscription</label>
        <referenceTo>Subscription__c</referenceTo>
        <relationshipLabel>Delivery Schedules</relationshipLabel>
        <relationshipName>Delivery_Schedules</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </CustomField>

force-app/main/default/objects/Journal__c/Journal__c.object-meta.xml
<CustomObject>
    <label>Journal</label>
    <nameField>
        <displayFormat>Entry - {000000}</displayFormat>
        <label>Entry Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Journal Entries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Journal__c/fields/Delivery_Address__c.field-meta.xml
<CustomField>
        <fullName>Delivery_Address__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Delivery Address</label>
        <referenceTo>Delivery_Address__c</referenceTo>
        <relationshipLabel>Journal Entries</relationshipLabel>
        <relationshipName>Journal_Entries</relationshipName>
        <type>Lookup</type>
    </CustomField>

force-app/main/default/objects/Journal__c/fields/Subscription__c.field-meta.xml
<CustomField>
        <fullName>Subscription__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Subscription</label>
        <referenceTo>Subscription__c</referenceTo>
        <relationshipLabel>Journal Entries</relationshipLabel>
        <relationshipName>Journal_Entries</relationshipName>
        <type>Lookup</type>
    </CustomField>

force-app/main/default/objects/Offer__c/Offer__c.object-meta.xml
<CustomObject>
    <description>Controls price, delivery, term for a subscription including print, digital and alternate publications. Also holds links to the premiums offered and the campaigns which will utilize this offer.</description>
    <label>Offer</label>
    <nameField>
        <label>Offer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Offers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Offer__c/fields/Per_Copy__c.field-meta.xml
<CustomField>
        <fullName>Per_Copy__c</fullName>
        <label>Per Copy</label>
        <precision>18</precision>
        <scale>4</scale>
        <type>Currency</type>
    </CustomField>

force-app/main/default/objects/Offer_Product__c/Offer_Product__c.object-meta.xml
<CustomObject>
    <label>Offer Product</label>
    <nameField>
        <label>Offer Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Offer Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Offer_Product__c/fields/Offer__c.field-meta.xml
<CustomField>
        <fullName>Offer__c</fullName>
        <label>Offer</label>
        <referenceTo>Offer__c</referenceTo>
        <relationshipLabel>Offer Products</relationshipLabel>
        <relationshipName>Offer_Products</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </CustomField>

force-app/main/default/objects/Offer_Product__c/fields/Per_Copy_Sunday__c.field-meta.xml
<CustomField>
        <fullName>Per_Copy_Sunday__c</fullName>
        <label>Per Copy Sunday</label>
        <precision>18</precision>
        <scale>4</scale>
        <type>Currency</type>
    </CustomField>

force-app/main/default/objects/Offer_Product__c/fields/Product__c.field-meta.xml
<CustomField>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Offer Products</relationshipLabel>
        <relationshipName>Offer_Products</relationshipName>
        <type>Lookup</type>
    </CustomField>

force-app/main/default/objects/Product2/fields/IsDigital__c.field-meta.xml
<CustomField>
        <fullName>IsDigital__c</fullName>
        <defaultValue>false</defaultValue>
        <label>IsDigital</label>
        <type>Checkbox</type>
    </CustomField>

force-app/main/default/objects/Subscription__c/Subscription__c.object-meta.xml
<CustomObject>
    <description>This object stores the actual subscription details, including selected Offer, Premiums. Delivery Schedules, frequency and term.</description>
    <label>Subscription</label>
    <nameField>
        <displayFormat>Sub-{0000}</displayFormat>
        <label>Subscription Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Subscription__c/fields/Attention_Line__c.field-meta.xml
<CustomField>
        <fullName>Attention_Line__c</fullName>
        <label>Attention Line</label>
        <length>100</length>
        <type>Text</type>
    </CustomField>

force-app/main/default/objects/Subscription__c/fields/Delivery_Instructions__c.field-meta.xml
<CustomField>
        <fullName>Delivery_Instructions__c</fullName>
        <label>Delivery Instructions</label>
        <type>TextArea</type>
    </CustomField>

force-app/main/default/objects/Subscription__c/fields/Delivery_Schedule__c.field-meta.xml
<CustomField>
        <fullName>Delivery_Schedule__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Stores the relationship between Subscriptions and Delivery Schedule</description>
        <label>Delivery Schedule</label>
        <referenceTo>Delivery_Schedule__c</referenceTo>
        <relationshipLabel>Subscriptions</relationshipLabel>
        <relationshipName>Subscriptions</relationshipName>
        <type>Lookup</type>
    </CustomField>

force-app/main/default/objects/Subscription__c/fields/Outstanding_Credit__c.field-meta.xml
<CustomField>
        <fullName>Outstanding_Credit__c</fullName>
        <label>Today's Balance</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </CustomField>

force-app/main/default/objects/Subscription__c/fields/Premium_Opt_Out__c.field-meta.xml
<CustomField>
        <fullName>Premium_Opt_Out__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Subscriber has opted out of premium issues.</description>
        <label>Premium Delivery Opt Out</label>
        <type>Checkbox</type>
    </CustomField>

force-app/main/default/objects/Subscription__c/fields/subscription_Account__c.field-meta.xml
<CustomField>
        <fullName>subscription_Account__c</fullName>
        <description>Relationship between Account and Subscriptions</description>
        <label>Household Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Subscriptions</relationshipLabel>
        <relationshipName>Subscriptions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </CustomField>

force-app/main/default/objects/Subscription__c/fields/subscription_Offer__c.field-meta.xml
<CustomField>
        <fullName>subscription_Offer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Stores the relationship to Offer</description>
        <label>Offer</label>
        <referenceTo>Offer__c</referenceTo>
        <relationshipLabel>Subscriptions</relationshipLabel>
        <relationshipName>Subscriptions1</relationshipName>
        <type>Lookup</type>
    </CustomField>

force-app/main/default/objects/Subscription__c/fields/subscription_Status__c.field-meta.xml
<CustomField>
        <fullName>subscription_Status__c</fullName>
        <description>Stores the status of the subscription</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>New</fullName>
                </value>
                <value>
                    <fullName>TERMINATED</fullName>
                </value>
                <value>
                    <fullName>INACTIVE</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </CustomField>

force-app/main/default/classes/PressRunProcessTest.cls
@isTest
private class PressRunProcessTest {
    @testSetup 
    static void setup() {

         Account account = new Account(
            Name = 'RelationEdge');
        insert account;
        Subscription__c subscription = new Subscription__c(
            subscription_Account__c = account.Id,
            Attention_Line__c = 'RelationEdge',
            Delivery_Instructions__c = 'Leave at front door',
            Outstanding_Credit__c = 20.25,
            subscription_Status__c = 'Active'
        );
        insert subscription;
        Subscription__c subscriptionOptOut = new Subscription__c(
            subscription_Account__c = account.Id,
            Attention_Line__c = 'RelationEdgeOptOut',
            Delivery_Instructions__c = 'Leave at front door',
            Outstanding_Credit__c = 40.25,
            subscription_Status__c = 'Active',
            Premium_Opt_Out__c = true
        );
        insert subscriptionOptOut;
        

        Product2 product = new Product2(Name = '175');
        insert product;
        Offer__c offer = new Offer__c(Name = 'Offer1');
        insert offer;

        Product2 digitalProduct = new Product2(Name = '160', IsDigital__c = true);
        insert digitalProduct;
        Offer__c digitalOffer = new Offer__c(Name = 'Offer1');
        insert digitalOffer;

        
        

        Offer_Product__c offerProduct1 = new Offer_Product__c(
            Offer__c = offer.Id,
            Product__c = product.Id,
            Per_Copy__c = 1.25,
            Per_Copy_Sunday__c = 2.5
        );
        insert offerProduct1;

        Offer_Product__c offerProduct2 = new Offer_Product__c(
            Offer__c = offer.Id,
            Product__c = product.Id,
            Per_Copy__c = 2.0,
            Per_Copy_Sunday__c = 4.0
        );
        insert offerProduct2;

        Offer_Product__c digitalOfferProduct = new Offer_Product__c(
            Offer__c = digitalOffer.Id,
            Product__c = digitalProduct.Id,
            Per_Copy__c = 3.0,
            Per_Copy_Sunday__c = 5.0
        );
        insert digitalOfferProduct;

        Subscription__c digitalSubscription = new Subscription__c(
            subscription_Account__c = account.Id,
            Attention_Line__c = 'Digital RelationEdge',
            Delivery_Instructions__c = 'N/A',
            Outstanding_Credit__c = 10.55,
            subscription_Status__c = 'Active',
            subscription_Offer__c = digitalOffer.Id
        );
        insert digitalSubscription;

        Delivery_Address__c deliveryAddress = new Delivery_Address__c();
        deliveryAddress.Address_Street__c = '1265 Lombardi Ave';
        deliveryAddress.Address_City__c = 'Green Bay';
        deliveryAddress.Address_State__c = 'WI';
        insert deliveryAddress;

        Delivery_Schedule__c deliveryScheduleNoDays = new Delivery_Schedule__c();
        deliveryScheduleNoDays.subscription_Subscription__c = subscription.Id;
        deliveryScheduleNoDays.Delivery_Address__c = deliveryAddress.Id;
        deliveryScheduleNoDays.Day_Monday__c = false;
        deliveryScheduleNoDays.Day_Tuesday__c = false;
        deliveryScheduleNoDays.Day_Wednesday__c = false;
        deliveryScheduleNoDays.Day_Thursday__c = false;
        deliveryScheduleNoDays.Day_Friday__c = false;
        deliveryScheduleNoDays.Day_Saturday__c = false;
        deliveryScheduleNoDays.Day_Sunday__c = false;
        deliveryScheduleNoDays.Start_Date__c = Date.today();
        deliveryScheduleNoDays.End_Date__c = Date.today()+7;
        deliveryScheduleNoDays.Offer_Product__c = offerProduct1.Id;

        Delivery_Schedule__c deliveryScheduleAllDays = new Delivery_Schedule__c();
        deliveryScheduleAllDays.subscription_Subscription__c = subscription.Id;
        deliveryScheduleAllDays.Delivery_Address__c = deliveryAddress.Id;
        deliveryScheduleAllDays.Day_Monday__c = true;
        deliveryScheduleAllDays.Day_Tuesday__c = true;
        deliveryScheduleAllDays.Day_Wednesday__c = true;
        deliveryScheduleAllDays.Day_Thursday__c = true;
        deliveryScheduleAllDays.Day_Friday__c = true;
        deliveryScheduleAllDays.Day_Saturday__c = true;
        deliveryScheduleAllDays.Day_Sunday__c = true;
        deliveryScheduleAllDays.Start_Date__c = Date.today();
        deliveryScheduleAllDays.End_Date__c = Date.today()+7;
        deliveryScheduleAllDays.Offer_Product__c = offerProduct1.Id;

        Delivery_Schedule__c deliveryScheduleAllDaysOptOut = new Delivery_Schedule__c();
        deliveryScheduleAllDaysOptOut.subscription_Subscription__c = subscriptionOptOut.Id;
        deliveryScheduleAllDaysOptOut.Delivery_Address__c = deliveryAddress.Id;
        deliveryScheduleAllDaysOptOut.Day_Monday__c = true;
        deliveryScheduleAllDaysOptOut.Day_Tuesday__c = true;
        deliveryScheduleAllDaysOptOut.Day_Wednesday__c = true;
        deliveryScheduleAllDaysOptOut.Day_Thursday__c = true;
        deliveryScheduleAllDaysOptOut.Day_Friday__c = true;
        deliveryScheduleAllDaysOptOut.Day_Saturday__c = true;
        deliveryScheduleAllDaysOptOut.Day_Sunday__c = true;
        deliveryScheduleAllDaysOptOut.Start_Date__c = Date.today();
        deliveryScheduleAllDaysOptOut.End_Date__c = Date.today()+7;
        deliveryScheduleAllDaysOptOut.Offer_Product__c = offerProduct2.Id;

        Delivery_Schedule__c deliveryScheduleNoDaysOptOut = new Delivery_Schedule__c();
        deliveryScheduleNoDaysOptOut.subscription_Subscription__c = subscriptionOptOut.Id;
        deliveryScheduleNoDaysOptOut.Delivery_Address__c = deliveryAddress.Id;
        deliveryScheduleNoDaysOptOut.Day_Monday__c = false;
        deliveryScheduleNoDaysOptOut.Day_Tuesday__c = false;
        deliveryScheduleNoDaysOptOut.Day_Wednesday__c = false;
        deliveryScheduleNoDaysOptOut.Day_Thursday__c = false;
        deliveryScheduleNoDaysOptOut.Day_Friday__c = false;
        deliveryScheduleNoDaysOptOut.Day_Saturday__c = false;
        deliveryScheduleNoDaysOptOut.Day_Sunday__c = false;
        deliveryScheduleNoDaysOptOut.Start_Date__c = Date.today();
        deliveryScheduleNoDaysOptOut.End_Date__c = Date.today()+7;
        deliveryScheduleNoDaysOptOut.Offer_Product__c = offerProduct2.Id;


        
        insert deliveryScheduleNoDays;
        insert deliveryScheduleAllDays;
        insert deliveryScheduleAllDaysOptOut;
        insert deliveryScheduleNoDaysOptOut;
        
    }
    static testmethod void shouldBatchInactivePressDay() {        
        Test.startTest();
        PressRunProcess prp = new PressRunProcess();
        prp.activePremium = false;
        prp.dayOfWeek = 'Monday';
        Id batchId = Database.executeBatch(prp);
		Test.stopTest();
        List<Journal__c> journalEntries = [SELECT Id FROM Journal__c];
        system.assert(journalEntries.size() > 0);

        
    }
    static testmethod void shouldBatchInactivePressDaySunday() {        
        Test.startTest();
        PressRunProcess prp = new PressRunProcess();
        prp.activePremium = false;
        prp.dayOfWeek = 'Sunday';
        Id batchId = Database.executeBatch(prp);
        Test.stopTest();
        List<Journal__c> journalEntries = [SELECT Id FROM Journal__c];
        system.assert(journalEntries.size() > 0);
        
    }

    static testmethod void shouldBatchActivePressDay() {        
        Test.startTest();
        PressRunProcess prp = new PressRunProcess();
        prp.activePremium = true;
        prp.dayOfWeek = 'Monday';
        Id batchId = Database.executeBatch(prp);
        Test.stopTest();
        List<Journal__c> journalEntries = [SELECT Id FROM Journal__c];
        system.assert(journalEntries.size() > 0);
        
    }

    static testmethod void shouldBatchActivePressDaySunday() {        
        Test.startTest();
        PressRunProcess prp = new PressRunProcess();
        prp.activePremium = true;
        prp.dayOfWeek = 'Sunday';
        Id batchId = Database.executeBatch(prp);
        Test.stopTest();
        List<Journal__c> journalEntries = [SELECT Id FROM Journal__c];
        system.assert(journalEntries.size() > 0);
        
    }
    
    static testmethod void shouldScheduleBatchJob(){
        
        String CRON_EXP = '0 0 0 15 3 ? *';
        Test.startTest();
            String jobId = System.schedule('ScheduleApexClassTest',  CRON_EXP, new PressRunScheduler());
            CronTrigger ct = [SELECT Id, CronExpression, TimesTriggered, NextFireTime FROM CronTrigger WHERE id = :jobId];
            System.assertEquals(CRON_EXP, ct.CronExpression);
            System.assertEquals(0, ct.TimesTriggered);

        Test.stopTest();
    }

    static testmethod void shouldCallAllJobs(){
        
        Test.startTest();
            PressRunSync prp = new PressRunSync();
            Id batchId = Database.executeBatch(prp);
        Test.stopTest();
    }
    
}