force-app/main/default/objects/Delivery_Address__c/Delivery_Address__c.object-meta.xml
<CustomObject>
    <description>Related Addresses to a Subscriber Household or Business and a Delivery Schedule of a Subscription.</description>
    <label>Delivery Address</label>
    <nameField>
        <displayFormat>DA-{0}</displayFormat>
        <label>Delivery Address Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Delivery Addresses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Delivery_Address__c/fields/Route__c.field-meta.xml
<CustomField>
        <fullName>Route__c</fullName>
        <label>Route #</label>
        <length>50</length>
        <type>Text</type>
    </CustomField>

force-app/main/default/objects/Delivery_Address__c/fields/Route_Number__c.field-meta.xml
<CustomField>
        <fullName>Route_Number__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Route #</label>
        <referenceTo>Route__c</referenceTo>
        <relationshipLabel>Delivery Addresses</relationshipLabel>
        <relationshipName>Delivery_Addresses</relationshipName>
        <type>Lookup</type>
    </CustomField>

force-app/main/default/objects/Delivery_Schedule__c/Delivery_Schedule__c.object-meta.xml
<CustomObject>
    <description>Deliver Schedules control the address and which days a publication will be delivered as part of the press run.</description>
    <label>Delivery Schedule</label>
    <nameField>
        <displayFormat>DS-{0}</displayFormat>
        <label>Delivery Schedule Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Delivery Schedules</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Delivery_Schedule__c/fields/Delivery_Address__c.field-meta.xml
<CustomField>
        <fullName>Delivery_Address__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Delivery Address</label>
        <referenceTo>Delivery_Address__c</referenceTo>
        <relationshipLabel>Delivery Schedules</relationshipLabel>
        <relationshipName>Delivery_Schedules</relationshipName>
        <type>Lookup</type>
    </CustomField>

force-app/main/default/objects/Delivery_Schedule__c/fields/End_Date__c.field-meta.xml
<CustomField>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </CustomField>

force-app/main/default/objects/Delivery_Schedule__c/fields/Offer_Product__c.field-meta.xml
<CustomField>
        <fullName>Offer_Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Offer Product</label>
        <referenceTo>Offer_Product__c</referenceTo>
        <relationshipLabel>Delivery Schedules</relationshipLabel>
        <relationshipName>Delivery_Schedules</relationshipName>
        <type>Lookup</type>
    </CustomField>

force-app/main/default/objects/Delivery_Schedule__c/fields/Route__c.field-meta.xml
<CustomField>
        <fullName>Route__c</fullName>
        <label>Route</label>
        <length>100</length>
        <type>Text</type>
    </CustomField>

force-app/main/default/objects/Delivery_Schedule__c/fields/Start_Date__c.field-meta.xml
<CustomField>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </CustomField>

force-app/main/default/objects/Delivery_Schedule__c/fields/subscription_Subscription__c.field-meta.xml
<CustomField>
        <fullName>subscription_Subscription__c</fullName>
        <description>This fields lookups to the shadow object, Subscription</description>
        <label>Subscription</label>
        <referenceTo>Subscription__c</referenceTo>
        <relationshipLabel>Delivery Schedules</relationshipLabel>
        <relationshipName>Delivery_Schedules</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </CustomField>

force-app/main/default/objects/Journal__c/Journal__c.object-meta.xml
<CustomObject>
    <label>Journal</label>
    <nameField>
        <displayFormat>Entry - {000000}</displayFormat>
        <label>Entry Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Journal Entries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Journal__c/fields/Debit__c.field-meta.xml
<CustomField>
        <fullName>Debit__c</fullName>
        <description>Amount if this item is a debit</description>
        <label>Debit</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Currency</type>
    </CustomField>

force-app/main/default/objects/Journal__c/fields/Delivery_Address__c.field-meta.xml
<CustomField>
        <fullName>Delivery_Address__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Delivery Address</label>
        <referenceTo>Delivery_Address__c</referenceTo>
        <relationshipLabel>Journal Entries</relationshipLabel>
        <relationshipName>Journal_Entries</relationshipName>
        <type>Lookup</type>
    </CustomField>

force-app/main/default/objects/Journal__c/fields/Entry_Date__c.field-meta.xml
<CustomField>
        <fullName>Entry_Date__c</fullName>
        <defaultValue>today()</defaultValue>
        <description>Date the item was entered</description>
        <label>Entry Date</label>
        <type>Date</type>
    </CustomField>

force-app/main/default/objects/Journal__c/fields/Entry_Type__c.field-meta.xml
<CustomField>
        <fullName>Entry_Type__c</fullName>
        <label>Entry Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Publication</fullName>
                </value>
                <value>
                    <fullName>Cash</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </CustomField>

force-app/main/default/objects/Journal__c/fields/Publication__c.field-meta.xml
<CustomField>
        <fullName>Publication__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Publication</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Publication</relationshipLabel>
        <relationshipName>Publication</relationshipName>
        <type>Lookup</type>
    </CustomField>

force-app/main/default/objects/Journal__c/fields/Route__c.field-meta.xml
<CustomField>
        <fullName>Route__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Route</label>
        <referenceTo>Route__c</referenceTo>
        <relationshipLabel>Journal Entries</relationshipLabel>
        <relationshipName>Journal_Entries</relationshipName>
        <type>Lookup</type>
    </CustomField>

force-app/main/default/objects/Journal__c/fields/Subscription__c.field-meta.xml
<CustomField>
        <fullName>Subscription__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Subscription</label>
        <referenceTo>Subscription__c</referenceTo>
        <relationshipLabel>Journal Entries</relationshipLabel>
        <relationshipName>Journal_Entries</relationshipName>
        <type>Lookup</type>
    </CustomField>

force-app/main/default/objects/Offer_Product__c/Offer_Product__c.object-meta.xml
<CustomObject>
    <label>Offer Product</label>
    <nameField>
        <label>Offer Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Offer Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Offer_Product__c/fields/Per_Copy_Sunday__c.field-meta.xml
<CustomField>
        <fullName>Per_Copy_Sunday__c</fullName>
        <label>Per Copy Sunday</label>
        <precision>18</precision>
        <scale>4</scale>
        <type>Currency</type>
    </CustomField>

force-app/main/default/objects/Offer_Product__c/fields/Product__c.field-meta.xml
<CustomField>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Offer Products</relationshipLabel>
        <relationshipName>Offer_Products</relationshipName>
        <type>Lookup</type>
    </CustomField>

force-app/main/default/objects/Premium_Day__mdt/Premium_Day__mdt.object-meta.xml
<CustomObject>
    <description>listing of days which a bonus edition will be issued.</description>
    <label>Premium Day</label>
    <pluralLabel>Premium Days</pluralLabel>
</CustomObject>

force-app/main/default/objects/Premium_Day__mdt/fields/Press_Date__c.field-meta.xml
<CustomField>
        <fullName>Press_Date__c</fullName>
        <description>Date which this premium will be issued.</description>
        <label>Press Date</label>
        <type>Date</type>
    </CustomField>

force-app/main/default/objects/Premium_Day__mdt/fields/Type__c.field-meta.xml
<CustomField>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Premium</fullName>
                    <default>true</default>
                    <label>Premium</label>
                </value>
                <value>
                    <fullName>Holiday</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </CustomField>

force-app/main/default/objects/Route__c/Route__c.object-meta.xml
<CustomObject>
    <label>Route</label>
    <nameField>
        <label>Route Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Route</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Subscription__c/Subscription__c.object-meta.xml
<CustomObject>
    <description>This object stores the actual subscription details, including selected Offer, Premiums. Delivery Schedules, frequency and term.</description>
    <label>Subscription</label>
    <nameField>
        <displayFormat>Sub-{0000}</displayFormat>
        <label>Subscription Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Subscription__c/fields/Delivery_Schedule__c.field-meta.xml
<CustomField>
        <fullName>Delivery_Schedule__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Stores the relationship between Subscriptions and Delivery Schedule</description>
        <label>Delivery Schedule</label>
        <referenceTo>Delivery_Schedule__c</referenceTo>
        <relationshipLabel>Subscriptions</relationshipLabel>
        <relationshipName>Subscriptions</relationshipName>
        <type>Lookup</type>
    </CustomField>

force-app/main/default/objects/Subscription__c/fields/Premium_Opt_Out__c.field-meta.xml
<CustomField>
        <fullName>Premium_Opt_Out__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Subscriber has opted out of premium issues.</description>
        <label>Premium Delivery Opt Out</label>
        <type>Checkbox</type>
    </CustomField>

force-app/main/default/objects/Subscription__c/fields/subscription_Status__c.field-meta.xml
<CustomField>
        <fullName>subscription_Status__c</fullName>
        <description>Stores the status of the subscription</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>New</fullName>
                </value>
                <value>
                    <fullName>TERMINATED</fullName>
                </value>
                <value>
                    <fullName>INACTIVE</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </CustomField>

force-app/main/default/classes/PressRunProcess.cls
global class PressRunProcess implements Database.Batchable<SObject> {

	global Date pressDay;
	global Boolean activePremium;
	global Boolean activeHoliday;
	global String dayOfWeek;
	

	global PressRunProcess() {
		pressDay = Date.today().addDays(1);
		/* Cast Date to DateTime to retrieve day of week */
		Datetime processDayDT = (DateTime)pressDay;
		processDayDT = processDayDT.addHours(12);
		dayOfWeek = processDayDT.format('EEEE');
		List<Premium_Day__mdt> premiumList = [SELECT Id, Press_Date__c, Type__c FROM Premium_Day__mdt WHERE Press_Date__c = :pressDay];
		activePremium = premiumList.isEmpty() ? false : true;
		activeHoliday = false;
		if(!premiumList.isEmpty()){
			for(Premium_Day__mdt pd : premiumList){
				if(pd.Type__c == 'Holiday')
					activeHoliday = true;
			}
		}
	}
	
	global Database.QueryLocator start(Database.BatchableContext context) {
		String dsQuery = '';
		if(activePremium){
			 //TODO: Review this query - Same as the other, but remove check for Day checkbox = true, and check for opt-out.
			 dsQuery = 'SELECT Id, Delivery_Address__c, Delivery_Address__r.Route_Number__c, subscription_Subscription__r.Premium_Opt_Out__c, Offer_Product__r.Product__c, Offer_Product__r.Per_Copy__c, Offer_Product__r.Per_Copy_Sunday__c, subscription_Subscription__c FROM Delivery_Schedule__c WHERE (subscription_Subscription__r.Premium_Opt_Out__c != TRUE AND Day_' + dayOfWeek + '__c = FALSE) AND Start_Date__c <= TODAY AND End_Date__c >= TODAY AND subscription_Subscription__r.subscription_Status__c = \'Active\'';
		}
		else{
			dsQuery = 'SELECT Id, Delivery_Address__c, Delivery_Address__r.Route_Number__c, subscription_Subscription__r.Premium_Opt_Out__c, Offer_Product__r.Product__c, Offer_Product__r.Per_Copy__c, Offer_Product__r.Per_Copy_Sunday__c, subscription_Subscription__c FROM Delivery_Schedule__c WHERE Day_' + dayOfWeek + '__c = TRUE AND Start_Date__c <= TODAY AND End_Date__c >= TODAY AND subscription_Subscription__r.subscription_Status__c = \'Active\'';
		}
		System.debug(dsQuery);
		return Database.getQueryLocator(dsQuery);
	}

   	global void execute(Database.BatchableContext context, List<Delivery_Schedule__c> scope) {
		List<Journal__c> journalsToInsert = new List<Journal__c>();
		Decimal rate = 0.0;
		Boolean splitJournals = false;
		Decimal splitRate = 0.0;

		for(Delivery_Schedule__c ds : scope){
			
			/* Calculate Adjustments */
			if(activePremium){
				if(ds.subscription_Subscription__r.Premium_Opt_Out__c || activeHoliday){ 
					//UseRate = Offer Product.DailyRate
					rate = ds.Offer_Product__r.Per_Copy__c;
				}
				else{
					rate = ds.Offer_Product__r.Per_Copy__c;
					splitJournals = true;
					splitRate = ds.Offer_Product__r.Per_Copy_Sunday__c - ds.Offer_Product__r.Per_Copy__c;
				}
			}
			else{
				rate = dayOfWeek.equals('Sunday') ? ds.Offer_Product__r.Per_Copy_Sunday__c : ds.Offer_Product__r.Per_Copy__c;
			}

			/* Create Journal Entry Record: Always inserts a Standard Entry Type Journal, except for Holidays.*/
			Journal__c journal = new Journal__c(
				Entry_Type__c = activeHoliday ? 'Holiday' : 'Standard Delivery',
				Entry_Date__c = pressday,
				Debit__c = rate,
				Subscription__c = ds.subscription_Subscription__c,
				Publication__c = ds.Offer_Product__r.Product__c,
				Delivery_Address__c = ds.Delivery_Address__c,
				Route__c = ds.Delivery_Address__r.Route_Number__c
			);
			journalsToInsert.add(journal);
			if(splitJournals){
				journalsToInsert.add(new Journal__c(
				Entry_Type__c = 'Premium Delivery',
				Entry_Date__c = pressday,
				Debit__c = splitRate,
				Subscription__c = ds.subscription_Subscription__c,
				Publication__c = ds.Offer_Product__r.Product__c,
				Delivery_Address__c = ds.Delivery_Address__c,
				Route__c = ds.Delivery_Address__r.Route_Number__c
				));
			}
		}
		if(!journalsToInsert.isEmpty())
			insert journalsToInsert;
	}
	
	global void finish(Database.BatchableContext context) {
		PressRunDigitalProcess b = new PressRunDigitalProcess();
        database.executebatch(b);
	}
}