force-app/main/default/objects/Delivery_Address__c/Delivery_Address__c.object-meta.xml
<CustomObject>
    <description>Related Addresses to a Subscriber Household or Business and a Delivery Schedule of a Subscription.</description>
    <label>Delivery Address</label>
    <nameField>
        <displayFormat>DA-{0}</displayFormat>
        <label>Delivery Address Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Delivery Addresses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Delivery_Schedule__c/Delivery_Schedule__c.object-meta.xml
<CustomObject>
    <description>Deliver Schedules control the address and which days a publication will be delivered as part of the press run.</description>
    <label>Delivery Schedule</label>
    <nameField>
        <displayFormat>DS-{0}</displayFormat>
        <label>Delivery Schedule Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Delivery Schedules</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Delivery_Schedule__c/fields/Delivery_Address__c.field-meta.xml
<CustomField>
        <fullName>Delivery_Address__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Delivery Address</label>
        <referenceTo>Delivery_Address__c</referenceTo>
        <relationshipLabel>Delivery Schedules</relationshipLabel>
        <relationshipName>Delivery_Schedules</relationshipName>
        <type>Lookup</type>
    </CustomField>

force-app/main/default/objects/Subscription__c/Subscription__c.object-meta.xml
<CustomObject>
    <description>This object stores the actual subscription details, including selected Offer, Premiums. Delivery Schedules, frequency and term.</description>
    <label>Subscription</label>
    <nameField>
        <displayFormat>Sub-{0000}</displayFormat>
        <label>Subscription Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Subscription__c/fields/Delivery_Schedule__c.field-meta.xml
<CustomField>
        <fullName>Delivery_Schedule__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Stores the relationship between Subscriptions and Delivery Schedule</description>
        <label>Delivery Schedule</label>
        <referenceTo>Delivery_Schedule__c</referenceTo>
        <relationshipLabel>Subscriptions</relationshipLabel>
        <relationshipName>Subscriptions</relationshipName>
        <type>Lookup</type>
    </CustomField>

force-app/main/default/classes/DeliveryAddressDataAccessorTest.cls
@isTest
private class DeliveryAddressDataAccessorTest {
    @isTest static void shouldValidateDeliveryAddress() {
        TestDataFactory.createTestRecords(3);
        List<Delivery_Address__c> addressList = [SELECT Id FROM Delivery_Address__c];
        List<Delivery_Schedule__c> scheduleList = [SELECT Id FROM Delivery_Schedule__c];
        Id result = DeliveryAddressDataAccessor.hasValidDeliveryAddress(addressList[0].Id);

        List<Delivery_Address__c> resultList = DeliveryAddressDataAccessor.getByScheduleSubId(scheduleList[0].Id);
        List<Delivery_Address__c> resultList2 = DeliveryAddressDataAccessor.getByFullStreetCityStateZip(null, 'Villanova', 'PA', '19132', null);
    }
    @isTest static void shouldDeleteAddress() {
        TestDataFactory.createTestRecords(3);
        List<Delivery_Address__c> addressList = [SELECT Id FROM Delivery_Address__c];
        DeliveryAddressDataAccessor.deleteDeliveryAddress(addressList[0].Id);
    }

    @isTest static void shouldCreateDeliveryAddress(){
        TestDataFactory.createTestRecords(1);
        Subscription__c sub = [SELECT Id FROM Subscription__c LIMIT 1];
        Map<String, String> deliveryMap = new Map<String, String>();
        deliveryMap.put('city', 'Philadelphia');
        deliveryMap.put('postalCode', '19132');
        deliveryMap.put('state', 'PA');
        deliveryMap.put('street', '2032 W Hagert St');
        
        Id addressId = DeliveryAddressDataAccessor.createNewDeliveryAddress(sub.Id, deliveryMap);
        DeliveryAddressDataAccessor.getById(addressId);
    }

    
}