force-app/main/default/objects/Delivery_Address__c/Delivery_Address__c.object-meta.xml
<CustomObject>
    <description>Related Addresses to a Subscriber Household or Business and a Delivery Schedule of a Subscription.</description>
    <label>Delivery Address</label>
    <nameField>
        <displayFormat>DA-{0}</displayFormat>
        <label>Delivery Address Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Delivery Addresses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Delivery_Address__c/fields/Address_City__c.field-meta.xml
<CustomField>
        <fullName>Address_City__c</fullName>
        <label>City</label>
        <length>100</length>
        <type>Text</type>
    </CustomField>

force-app/main/default/objects/Delivery_Address__c/fields/Address_Full_Street__c.field-meta.xml
<CustomField>
        <fullName>Address_Full_Street__c</fullName>
        <formula>IF(NOT(ISBLANK(Address_House__c)), Address_House__c+ ' ', '') +
IF(NOT(ISBLANK(Pre_Direction__c)), Pre_Direction__c + ' ', '') +  
IF(NOT(ISBLANK(Address_Street__c)), Address_Street__c+ ' ', '') +
IF(NOT(ISBLANK(Address_Suffix__c)), Address_Suffix__c+ ' ', '') +
IF(NOT(ISBLANK(Post_Direction__c)), Post_Direction__c + ' ', '')</formula>
        <label>Full Street</label>
        <type>Text</type>
    </CustomField>

force-app/main/default/objects/Delivery_Address__c/fields/Address_House__c.field-meta.xml
<CustomField>
        <fullName>Address_House__c</fullName>
        <label>House Number</label>
        <length>100</length>
        <type>Text</type>
    </CustomField>

force-app/main/default/objects/Delivery_Address__c/fields/Address_Postal_Route__c.field-meta.xml
<CustomField>
        <fullName>Address_Postal_Route__c</fullName>
        <label>Postal Route</label>
        <length>10</length>
        <type>Text</type>
    </CustomField>

force-app/main/default/objects/Delivery_Address__c/fields/Address_State__c.field-meta.xml
<CustomField>
        <fullName>Address_State__c</fullName>
        <label>State</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Alabama</fullName>
                </value>
                <value>
                    <fullName>Alaska</fullName>
                </value>
                <value>
                    <fullName>Arizona</fullName>
                </value>
                <value>
                    <fullName>Arkansas</fullName>
                </value>
                <value>
                    <fullName>California</fullName>
                </value>
                <value>
                    <fullName>Colorado</fullName>
                </value>
                <value>
                    <fullName>Connecticut</fullName>
                </value>
                <value>
                    <fullName>Delaware</fullName>
                </value>
                <value>
                    <fullName>Florida</fullName>
                </value>
                <value>
                    <fullName>Georgia</fullName>
                </value>
                <value>
                    <fullName>Hawaii</fullName>
                </value>
                <value>
                    <fullName>Idaho</fullName>
                </value>
                <value>
                    <fullName>Illinois</fullName>
                </value>
                <value>
                    <fullName>Indiana</fullName>
                </value>
                <value>
                    <fullName>Iowa</fullName>
                </value>
                <value>
                    <fullName>Kansas</fullName>
                </value>
                <value>
                    <fullName>Kentucky</fullName>
                </value>
                <value>
                    <fullName>Louisiana</fullName>
                </value>
                <value>
                    <fullName>Maine</fullName>
                </value>
                <value>
                    <fullName>Maryland</fullName>
                </value>
                <value>
                    <fullName>Massachusetts</fullName>
                </value>
                <value>
                    <fullName>Michigan</fullName>
                </value>
                <value>
                    <fullName>Minnesota</fullName>
                </value>
                <value>
                    <fullName>Mississippi</fullName>
                </value>
                <value>
                    <fullName>Missouri</fullName>
                </value>
                <value>
                    <fullName>Montana</fullName>
                </value>
                <value>
                    <fullName>Nebraska</fullName>
                </value>
                <value>
                    <fullName>Nevada</fullName>
                </value>
                <value>
                    <fullName>New Hampshire</fullName>
                </value>
                <value>
                    <fullName>New Jersey</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </CustomField>

force-app/main/default/objects/Delivery_Address__c/fields/Address_Street__c.field-meta.xml
<CustomField>
        <fullName>Address_Street__c</fullName>
        <label>Street</label>
        <length>200</length>
        <type>Text</type>
    </CustomField>

force-app/main/default/objects/Delivery_Address__c/fields/Address_Suffix__c.field-meta.xml
<CustomField>
        <fullName>Address_Suffix__c</fullName>
        <label>Suffix</label>
        <length>10</length>
        <type>Text</type>
    </CustomField>

force-app/main/default/objects/Delivery_Address__c/fields/Clean_Suite_Personator_Result__c.field-meta.xml
<CustomField>
        <fullName>Clean_Suite_Personator_Result__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Clean Suite Personator Result</label>
        <referenceTo>MDPERSONATOR__MD_personatorResult__c</referenceTo>
        <relationshipLabel>Delivery Addresses</relationshipLabel>
        <relationshipName>Delivery_Addresses</relationshipName>
        <type>Lookup</type>
    </CustomField>

force-app/main/default/objects/Delivery_Address__c/fields/DSI_Id__c.field-meta.xml
<CustomField>
        <fullName>DSI_Id__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>DSI Id</label>
        <length>50</length>
        <type>Text</type>
        <unique>true</unique>
    </CustomField>

force-app/main/default/objects/Delivery_Address__c/fields/Melissa_Response__c.field-meta.xml
<CustomField>
        <fullName>Melissa_Response__c</fullName>
        <description>Response code returned</description>
        <label>Melissa Response</label>
        <length>50</length>
        <type>Text</type>
    </CustomField>

force-app/main/default/objects/Delivery_Address__c/fields/Post_Direction__c.field-meta.xml
<CustomField>
        <fullName>Post_Direction__c</fullName>
        <label>Post Direction</label>
        <length>10</length>
        <type>Text</type>
    </CustomField>

force-app/main/default/objects/Delivery_Address__c/fields/Pre_Direction__c.field-meta.xml
<CustomField>
        <fullName>Pre_Direction__c</fullName>
        <label>Pre Direction</label>
        <length>10</length>
        <type>Text</type>
    </CustomField>

force-app/main/default/objects/Delivery_Address__c/fields/Route__c.field-meta.xml
<CustomField>
        <fullName>Route__c</fullName>
        <label>Route #</label>
        <length>50</length>
        <type>Text</type>
    </CustomField>

force-app/main/default/objects/Delivery_Address__c/fields/Route_Number__c.field-meta.xml
<CustomField>
        <fullName>Route_Number__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Route #</label>
        <referenceTo>Route__c</referenceTo>
        <relationshipLabel>Delivery Addresses</relationshipLabel>
        <relationshipName>Delivery_Addresses</relationshipName>
        <type>Lookup</type>
    </CustomField>

force-app/main/default/objects/Delivery_Address__c/fields/Unit__c.field-meta.xml
<CustomField>
        <fullName>Unit__c</fullName>
        <label>Unit</label>
        <length>100</length>
        <type>Text</type>
    </CustomField>

force-app/main/default/objects/Delivery_Address__c/fields/Zip__c.field-meta.xml
<CustomField>
        <fullName>Zip__c</fullName>
        <label>Zip</label>
        <length>10</length>
        <type>Text</type>
    </CustomField>

force-app/main/default/objects/Delivery_Schedule__c/Delivery_Schedule__c.object-meta.xml
<CustomObject>
    <description>Deliver Schedules control the address and which days a publication will be delivered as part of the press run.</description>
    <label>Delivery Schedule</label>
    <nameField>
        <displayFormat>DS-{0}</displayFormat>
        <label>Delivery Schedule Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Delivery Schedules</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Delivery_Schedule__c/fields/Delivery_Address__c.field-meta.xml
<CustomField>
        <fullName>Delivery_Address__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Delivery Address</label>
        <referenceTo>Delivery_Address__c</referenceTo>
        <relationshipLabel>Delivery Schedules</relationshipLabel>
        <relationshipName>Delivery_Schedules</relationshipName>
        <type>Lookup</type>
    </CustomField>

force-app/main/default/objects/Delivery_Schedule__c/fields/DSI_Id__c.field-meta.xml
<CustomField>
        <fullName>DSI_Id__c</fullName>
        <externalId>true</externalId>
        <label>DSI Id</label>
        <length>100</length>
        <type>Text</type>
    </CustomField>

force-app/main/default/objects/Delivery_Schedule__c/fields/Route__c.field-meta.xml
<CustomField>
        <fullName>Route__c</fullName>
        <label>Route</label>
        <length>100</length>
        <type>Text</type>
    </CustomField>

force-app/main/default/objects/Delivery_Schedule__c/fields/subscription_Subscription__c.field-meta.xml
<CustomField>
        <fullName>subscription_Subscription__c</fullName>
        <description>This fields lookups to the shadow object, Subscription</description>
        <label>Subscription</label>
        <referenceTo>Subscription__c</referenceTo>
        <relationshipLabel>Delivery Schedules</relationshipLabel>
        <relationshipName>Delivery_Schedules</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </CustomField>

force-app/main/default/objects/Organization_Settings__mdt/Organization_Settings__mdt.object-meta.xml
<CustomObject>
    <label>Organization Setting</label>
    <pluralLabel>Organization Settings</pluralLabel>
</CustomObject>

force-app/main/default/objects/Organization_Settings__mdt/fields/Organization_Id__c.field-meta.xml
<CustomField>
        <fullName>Organization_Id__c</fullName>
        <label>Organization Id</label>
        <length>18</length>
        <type>Text</type>
    </CustomField>

force-app/main/default/objects/Organization_Settings__mdt/fields/Validate_DSI_ID_on_New_Delivery_Address__c.field-meta.xml
<CustomField>
        <fullName>Validate_DSI_ID_on_New_Delivery_Address__c</fullName>
        <defaultValue>false</defaultValue>
        <description>If this value is true, the Split Delivery, Address Change, and Shore Move components will wait for Delivery Address DSI Id to be returned via Informatica before successfully creating the address.</description>
        <inlineHelpText>If this value is true, the Split Delivery, Address Change, and Shore Move components will wait for Delivery Address DSI Id to be returned via Informatica before successfully creating the address.</inlineHelpText>
        <label>Validate DSI ID on New Delivery Address</label>
        <type>Checkbox</type>
    </CustomField>

force-app/main/default/objects/Route__c/Route__c.object-meta.xml
<CustomObject>
    <label>Route</label>
    <nameField>
        <label>Route Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Route</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Route_Street__c/Route_Street__c.object-meta.xml
<CustomObject>
    <label>Route Street</label>
    <nameField>
        <label>Route Street Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Route Streets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Route_Street__c/fields/Route__c.field-meta.xml
<CustomField>
        <fullName>Route__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Route</label>
        <referenceTo>Route__c</referenceTo>
        <relationshipLabel>Route Streets</relationshipLabel>
        <relationshipName>Route_Streets</relationshipName>
        <type>Lookup</type>
    </CustomField>

force-app/main/default/objects/Route_Street__c/fields/ZIP__c.field-meta.xml
<CustomField>
        <fullName>ZIP__c</fullName>
        <label>ZIP</label>
        <length>10</length>
        <type>Text</type>
    </CustomField>

force-app/main/default/classes/DeliveryAddressDataAccessor.cls
public with sharing class DeliveryAddressDataAccessor {
    public static Delivery_Address__c getById(Id deliveryAddressId) {
        return [
            SELECT Id, Address_Full_Street__c, Address_House__c, Pre_Direction__c, Address_Street__c, Address_City__c, Address_State__c, Zip__c, Unit__c, Route_Number__c, Melissa_Response__c, 
                Clean_Suite_Personator_Result__r.MDPERSONATOR__AddressHouseNumber__c, 
                Clean_Suite_Personator_Result__r.MDPERSONATOR__AddressPreDirection__c, 
                Clean_Suite_Personator_Result__r.MDPERSONATOR__AddressPostDirection__c, 
                Clean_Suite_Personator_Result__r.MDPERSONATOR__AddressStreetName__c, 
                Clean_Suite_Personator_Result__r.MDPERSONATOR__AddressStreetSuffix__c, 
                Clean_Suite_Personator_Result__r.MDPERSONATOR__AddressLine1__c, 
                Clean_Suite_Personator_Result__r.MDPERSONATOR__City__c, 
                Clean_Suite_Personator_Result__r.MDPERSONATOR__State__c	, 
                Clean_Suite_Personator_Result__r.MDPERSONATOR__PostalCode__c,
                DSI_Id__c
            FROM Delivery_Address__c
            WHERE Id = :deliveryAddressId
        ];
    }

    public static List<Delivery_Address__c> getByFullStreetCityStateZip(String fullStreet, String city, String state, String postalCode, String unit) {
        return [
            SELECT Id, Address_Full_Street__c, Address_House__c, Pre_Direction__c, Address_Street__c, Address_City__c, Address_State__c, Zip__c, Unit__c, Route_Number__c, Melissa_Response__c
            FROM Delivery_Address__c
            WHERE Address_Full_Street__c = :fullStreet
            AND Address_City__c = :city
            AND Address_State__c = :state
            AND Address_Postal_Route__c = :postalCode
            AND Unit__c = :unit
        ];
    }

    public static List<Delivery_Address__c> getByScheduleSubId(Id subId) {
        return [
            SELECT Id, Address_Full_Street__c, Address_House__c, Pre_Direction__c, Address_Street__c, Address_City__c, Address_State__c, Zip__c, Unit__c, Route_Number__c, Melissa_Response__c
            FROM Delivery_Address__c
            WHERE Id IN (SELECT Delivery_Address__c FROM Delivery_Schedule__c WHERE subscription_Subscription__c = :subId)
        ];
    }

    @AuraEnabled
    public static Id createNewDeliveryAddress(Id subId, Map<String, String> address) {
		try{
			Delivery_Address__c toInsert = new Delivery_Address__c(	
			Address_City__c = address.get('city'),
			Zip__c = address.get('postalCode'),
			Address_State__c = address.get('state'),
			Address_Street__c = address.get('street'));
			insert toInsert;
            return toInsert.Id;
		}
		catch(Exception e){
			return null;
		}
    }

    	@AuraEnabled
	public static Id hasValidDeliveryAddress(Id newAddressId) {
        System.debug('Id: ' + newAddressId);
        Delivery_Address__c deliveryAddress = [SELECT Id, Pre_Direction__c, Post_Direction__c, Address_Full_Street__c, Address_Suffix__c, Address_Postal_Route__c, Address_City__c, Melissa_Response__c, Address_State__c, DSI_Id__c, Address_House__c, Address_Street__c, Zip__c, Unit__c FROM Delivery_Address__c WHERE Id = :newAddressId LIMIT 1];

        if (!String.isEmpty(deliveryAddress.Address_House__c)) {
            List<Route_Street__c> relatedRouteStreets = RouteDataAccessor.getRouteStreets(Decimal.valueOf(deliveryAddress.Address_House__c), deliveryAddress.Address_Street__c, deliveryAddress.Zip__c);
            deliveryAddress.Route_Number__c = (relatedRouteStreets.isEmpty()) ? null : relatedRouteStreets[0].Route__c;
			
            /*Depends on custom metadata type to check if dsi id replication is linked*/
          
			if (deliveryAddress.Route_Number__c != null || Test.isRunningTest()) {
				update deliveryAddress;
			}
			else {
				throw new GenericException('No route found for this address.');
			}
        }

        if(deliveryAddress.Melissa_Response__c != null || Test.isRunningTest()){
            List<Delivery_Address__c> dupAddresses = DeliveryAddressDataAccessor.getDuplicateAddresses(deliveryAddress.Id, deliveryAddress.Pre_Direction__c, deliveryAddress.Post_Direction__c, deliveryAddress.Address_House__c, deliveryAddress.Address_Street__c, deliveryAddress.Address_Suffix__c, deliveryAddress.Unit__c, deliveryAddress.Zip__c);
            System.debug('dupAddresses: ' + dupAddresses);
            if(!dupAddresses.isEmpty()){
                deliveryAddress = dupAddresses[0];
                DeliveryAddressDataAccessor.deleteDeliveryAddress(newAddressId);
            }
            else{
                Organization org = [SELECT Id FROM Organization LIMIT 1];
                Organization_Settings__mdt orgSetting = [
                    SELECT Validate_DSI_ID_on_New_Delivery_Address__c 
                    FROM Organization_Settings__mdt 
                    WHERE Organization_Id__c = :org.Id LIMIT 1];
                
                if(orgSetting.Validate_DSI_ID_on_New_Delivery_Address__c && 
                    deliveryAddress.DSI_Id__c == null) throw new GenericException('No DSI Id found for this address');
            }
        }
        
        if(deliveryAddress.Melissa_Response__c != null && deliveryAddress.Melissa_Response__c.contains('AS01'))
                return deliveryAddress.Id;

        throw new GenericException('Melissa response is invalid');
        
    }

    @AuraEnabled(Cacheable=true)
    public static List<Delivery_Address__c> getDeliveryAddresses(Id subId) {
        return [SELECT Id, Address_City__c, Address_House__c, Address_Street__c, Address_Postal_Route__c, Address_State__c 
		FROM Delivery_Address__c WHERE Id IN (SELECT Delivery_Address__c FROM Delivery_Schedule__c WHERE subscription_Subscription__c = :subId)];
    }

    @AuraEnabled
    public static void deleteDeliveryAddress(Id newAddressId){
        if(newAddressId != null){
            Delivery_Address__c toDelete = new Delivery_Address__c(Id = newAddressId);
            delete toDelete;
        }       
    }


    private static List<Delivery_Address__c> getDuplicateAddresses(Id addressId, String preDirection, String postDirection, String houseNumber, String street, String suffix, String unit, String zip){
        return [
            SELECT Id, Pre_Direction__c, Post_Direction__c, Address_Full_Street__c, Address_Suffix__c, Address_Postal_Route__c, Address_City__c, Melissa_Response__c, Address_State__c, DSI_Id__c, Address_House__c, Address_Street__c, Zip__c, Unit__c 
            FROM Delivery_Address__c
            WHERE Pre_Direction__c = :preDirection AND Post_Direction__c = :postDirection AND Address_House__c = :houseNumber 
            AND Address_Street__c = :street AND Address_Suffix__c = :suffix AND Unit__c = :unit AND Zip__c = :zip
            AND Id != :addressId
        ];
    }
}