force-app/main/default/objects/Piano_Api_Setting__mdt/Piano_Api_Setting__mdt.object-meta.xml
<CustomObject>
    <label>Piano Api Setting</label>
    <pluralLabel>Piano Api Settings</pluralLabel>
</CustomObject>

force-app/main/default/objects/Piano_Api_Setting__mdt/fields/Base_URI__c.field-meta.xml
<CustomField>
        <fullName>Base_URI__c</fullName>
        <label>Base URI</label>
        <length>255</length>
        <type>Text</type>
    </CustomField>

force-app/main/default/objects/Piano_Api_Setting__mdt/fields/Term_Id__c.field-meta.xml
<CustomField>
        <fullName>Term_Id__c</fullName>
        <label>Term Id</label>
        <length>50</length>
        <type>Text</type>
    </CustomField>

force-app/main/default/objects/Piano_Api_Setting__mdt/fields/Term_Name__c.field-meta.xml
<CustomField>
        <fullName>Term_Name__c</fullName>
        <label>Term Name</label>
        <length>50</length>
        <type>Text</type>
    </CustomField>

force-app/main/default/classes/PianoClient.cls
public with sharing class PianoClient {
	private Piano_Api_Setting__mdt settings; 

	public PianoClient() {
		Boolean isSandbox = [SELECT IsSandbox FROM Organization LIMIT 1].IsSandbox;
		String settingsName = isSandbox ? 'dev' : 'prod';
		settings = [SELECT Id, Term_Id__c, Term_Name__c, Base_URI__c FROM Piano_Api_Setting__mdt WHERE DeveloperName = :settingsName];
	}

	public Map<String, Object> callPiano(String trackingId) {
		String pianoParams = 'term_id=' + settings.Term_Id__c + '&term_name=' + settings.Term_Name__c + '&tracking_id=' + EncodingUtil.urlEncode(trackingId, 'UTF-8');
		HttpRequest req = new HttpRequest();
		req.setEndpoint(settings.Base_URI__c);
		req.setMethod('POST');
		req.setHeader('Content-Type', 'application/x-www-form-urlencoded');
		req.setBody(pianoParams);
		HttpResponse res = new Http().send(req);
		return (Map<String, Object>) JSON.deserializeUntyped(res.getBody());
	}
}