force-app/main/default/objects/Contact/fields/Attention_Line__c.field-meta.xml
<CustomField>
        <fullName>Attention_Line__c</fullName>
        <label>Attention Line</label>
        <length>100</length>
        <type>Text</type>
    </CustomField>

force-app/main/default/objects/Contact/fields/Delivery_Instructions__c.field-meta.xml
<CustomField>
        <fullName>Delivery_Instructions__c</fullName>
        <label>Delivery Instructions</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </CustomField>

force-app/main/default/objects/Delivery_Address__c/Delivery_Address__c.object-meta.xml
<CustomObject>
    <description>Related Addresses to a Subscriber Household or Business and a Delivery Schedule of a Subscription.</description>
    <label>Delivery Address</label>
    <nameField>
        <displayFormat>DA-{0}</displayFormat>
        <label>Delivery Address Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Delivery Addresses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Delivery_Address__c/fields/Melissa_Response__c.field-meta.xml
<CustomField>
        <fullName>Melissa_Response__c</fullName>
        <description>Response code returned</description>
        <label>Melissa Response</label>
        <length>50</length>
        <type>Text</type>
    </CustomField>

force-app/main/default/objects/Delivery_Schedule__c/Delivery_Schedule__c.object-meta.xml
<CustomObject>
    <description>Deliver Schedules control the address and which days a publication will be delivered as part of the press run.</description>
    <label>Delivery Schedule</label>
    <nameField>
        <displayFormat>DS-{0}</displayFormat>
        <label>Delivery Schedule Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Delivery Schedules</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Delivery_Schedule__c/fields/Delivery_Address__c.field-meta.xml
<CustomField>
        <fullName>Delivery_Address__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Delivery Address</label>
        <referenceTo>Delivery_Address__c</referenceTo>
        <relationshipLabel>Delivery Schedules</relationshipLabel>
        <relationshipName>Delivery_Schedules</relationshipName>
        <type>Lookup</type>
    </CustomField>

force-app/main/default/objects/Delivery_Schedule__c/fields/Delivery_Instructions__c.field-meta.xml
<CustomField>
        <fullName>Delivery_Instructions__c</fullName>
        <label>Delivery Instructions</label>
        <length>200</length>
        <type>Text</type>
    </CustomField>

force-app/main/default/objects/Delivery_Schedule__c/fields/End_Date__c.field-meta.xml
<CustomField>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </CustomField>

force-app/main/default/objects/Delivery_Schedule__c/fields/Offer_Product__c.field-meta.xml
<CustomField>
        <fullName>Offer_Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Offer Product</label>
        <referenceTo>Offer_Product__c</referenceTo>
        <relationshipLabel>Delivery Schedules</relationshipLabel>
        <relationshipName>Delivery_Schedules</relationshipName>
        <type>Lookup</type>
    </CustomField>

force-app/main/default/objects/Delivery_Schedule__c/fields/Start_Date__c.field-meta.xml
<CustomField>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </CustomField>

force-app/main/default/objects/Delivery_Schedule__c/fields/subscription_Subscription__c.field-meta.xml
<CustomField>
        <fullName>subscription_Subscription__c</fullName>
        <description>This fields lookups to the shadow object, Subscription</description>
        <label>Subscription</label>
        <referenceTo>Subscription__c</referenceTo>
        <relationshipLabel>Delivery Schedules</relationshipLabel>
        <relationshipName>Delivery_Schedules</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </CustomField>

force-app/main/default/objects/Offer__c/Offer__c.object-meta.xml
<CustomObject>
    <description>Controls price, delivery, term for a subscription including print, digital and alternate publications. Also holds links to the premiums offered and the campaigns which will utilize this offer.</description>
    <label>Offer</label>
    <nameField>
        <label>Offer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Offers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Offer__c/fields/End_Date__c.field-meta.xml
<CustomField>
        <fullName>End_Date__c</fullName>
        <description>Stores the end date of the offer</description>
        <label>End Date</label>
        <type>Date</type>
    </CustomField>

force-app/main/default/objects/Offer__c/fields/Per_Copy__c.field-meta.xml
<CustomField>
        <fullName>Per_Copy__c</fullName>
        <label>Per Copy</label>
        <precision>18</precision>
        <scale>4</scale>
        <type>Currency</type>
    </CustomField>

force-app/main/default/objects/Offer__c/fields/Start_Date__c.field-meta.xml
<CustomField>
        <fullName>Start_Date__c</fullName>
        <description>Stores the start date for this offer</description>
        <label>Start Date</label>
        <type>Date</type>
    </CustomField>

force-app/main/default/objects/Offer_Product__c/Offer_Product__c.object-meta.xml
<CustomObject>
    <label>Offer Product</label>
    <nameField>
        <label>Offer Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Offer Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Offer_Product__c/fields/Offer__c.field-meta.xml
<CustomField>
        <fullName>Offer__c</fullName>
        <label>Offer</label>
        <referenceTo>Offer__c</referenceTo>
        <relationshipLabel>Offer Products</relationshipLabel>
        <relationshipName>Offer_Products</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </CustomField>

force-app/main/default/objects/Offer_Product__c/fields/Per_Copy_Sunday__c.field-meta.xml
<CustomField>
        <fullName>Per_Copy_Sunday__c</fullName>
        <label>Per Copy Sunday</label>
        <precision>18</precision>
        <scale>4</scale>
        <type>Currency</type>
    </CustomField>

force-app/main/default/objects/Offer_Product__c/fields/Product__c.field-meta.xml
<CustomField>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Offer Products</relationshipLabel>
        <relationshipName>Offer_Products</relationshipName>
        <type>Lookup</type>
    </CustomField>

force-app/main/default/objects/Product2/fields/IsDigital__c.field-meta.xml
<CustomField>
        <fullName>IsDigital__c</fullName>
        <defaultValue>false</defaultValue>
        <label>IsDigital</label>
        <type>Checkbox</type>
    </CustomField>

force-app/main/default/objects/Subscription__c/Subscription__c.object-meta.xml
<CustomObject>
    <description>This object stores the actual subscription details, including selected Offer, Premiums. Delivery Schedules, frequency and term.</description>
    <label>Subscription</label>
    <nameField>
        <displayFormat>Sub-{0000}</displayFormat>
        <label>Subscription Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Subscription__c/fields/Attention_Line__c.field-meta.xml
<CustomField>
        <fullName>Attention_Line__c</fullName>
        <label>Attention Line</label>
        <length>100</length>
        <type>Text</type>
    </CustomField>

force-app/main/default/objects/Subscription__c/fields/Contact__c.field-meta.xml
<CustomField>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Subscriptions</relationshipLabel>
        <relationshipName>Subscriptions</relationshipName>
        <type>Lookup</type>
    </CustomField>

force-app/main/default/objects/Subscription__c/fields/Delivery_Instructions__c.field-meta.xml
<CustomField>
        <fullName>Delivery_Instructions__c</fullName>
        <label>Delivery Instructions</label>
        <type>TextArea</type>
    </CustomField>

force-app/main/default/objects/Subscription__c/fields/Delivery_Schedule__c.field-meta.xml
<CustomField>
        <fullName>Delivery_Schedule__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Stores the relationship between Subscriptions and Delivery Schedule</description>
        <label>Delivery Schedule</label>
        <referenceTo>Delivery_Schedule__c</referenceTo>
        <relationshipLabel>Subscriptions</relationshipLabel>
        <relationshipName>Subscriptions</relationshipName>
        <type>Lookup</type>
    </CustomField>

force-app/main/default/objects/Subscription__c/fields/Outstanding_Credit__c.field-meta.xml
<CustomField>
        <fullName>Outstanding_Credit__c</fullName>
        <label>Today's Balance</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </CustomField>

force-app/main/default/objects/Subscription__c/fields/subscription_Account__c.field-meta.xml
<CustomField>
        <fullName>subscription_Account__c</fullName>
        <description>Relationship between Account and Subscriptions</description>
        <label>Household Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Subscriptions</relationshipLabel>
        <relationshipName>Subscriptions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </CustomField>

force-app/main/default/objects/Subscription__c/fields/subscription_Offer__c.field-meta.xml
<CustomField>
        <fullName>subscription_Offer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Stores the relationship to Offer</description>
        <label>Offer</label>
        <referenceTo>Offer__c</referenceTo>
        <relationshipLabel>Subscriptions</relationshipLabel>
        <relationshipName>Subscriptions1</relationshipName>
        <type>Lookup</type>
    </CustomField>

force-app/main/default/classes/ChangeAddressControllerTest.cls
@isTest
private class ChangeAddressControllerTest {
    @isTest static void shouldGetSubscription() {
        Product2 product = new Product2(Name = '175');
        insert product;
        Offer__c offer3 = new Offer__c(Name = 'Offer1');
        insert offer3;

        Product2 digitalProduct = new Product2(Name = '160', IsDigital__c = true);
        insert digitalProduct;
        Offer__c digitalOffer = new Offer__c(Name = 'Offer1');
        insert digitalOffer;

        
        

        Offer_Product__c offerProduct1 = new Offer_Product__c(
            Offer__c = offer3.Id,
            Product__c = product.Id,
            Per_Copy__c = 1.25,
            Per_Copy_Sunday__c = 2.5
        );
        insert offerProduct1;

        Offer_Product__c offerProduct2 = new Offer_Product__c(
            Offer__c = offer3.Id,
            Product__c = product.Id,
            Per_Copy__c = 2.0,
            Per_Copy_Sunday__c = 4.0
        );
        insert offerProduct2;
        Account account = new Account(
            Name = 'RelationEdge');
        insert account;
        Offer__c offer = new Offer__c();
        offer.Name = 'TestOffer';
        insert offer;
        Contact contact = new Contact(FirstName = 'Relation', LastName = 'Edge', Email='Test@Test.com');
        insert contact;
        Subscription__c subscription = new Subscription__c(
            subscription_Account__c = account.Id,
            Attention_Line__c = 'RelationEdge',
            Delivery_Instructions__c = 'Throw it at the front door.',
            Outstanding_Credit__c = 20.25,
            subscription_Offer__c = offer.Id,
            contact__c = contact.Id
            );
        insert subscription;
        Map<String, String> address = new Map<String, String>();
        address.put('city', 'Villanova');
        address.put('postalCode', '19132');
        address.put('state', 'PA');
        address.put('street', '2030 W Hagert St');

        Id addressId = DeliveryAddressDataAccessor.createNewDeliveryAddress(subscription.Id, address);
        Delivery_Address__c toUpdate = new Delivery_Address__c(Id = addressId, Melissa_Response__c = 'AS01');
        update toUpdate;

        Boolean beforeCutOff = CutOffManager.isBeforeCutOff('Carrier Memo');
        Date startDate = Date.today().addDays(-5);
        if(!beforeCutOff){
            startDate = startDate.addDays(1);
        }
        Delivery_Schedule__c ds = new Delivery_Schedule__c();
        ds.subscription_Subscription__c = subscription.Id;
        ds.Delivery_Address__c = toUpdate.Id;
        ds.Offer_Product__c = offerProduct1.Id;
        ds.Start_Date__c = startDate;
        ds.End_Date__c = Date.today().addDays(5);
        
        insert ds;
        
        Id addressId2 = DeliveryAddressDataAccessor.createNewDeliveryAddress(subscription.Id, address);
        Delivery_Address__c toUpdate2 = new Delivery_Address__c(Id = addressId2, Melissa_Response__c = 'AS01');
        update toUpdate2;

        changeAddressController.validateDeliverySchedules(subscription.Id);
        changeAddressController.updateBillingAddress(subscription.Id, address);
        DeliveryAddressDataAccessor.createNewDeliveryAddress(subscription.Id, address);
        addressId = DeliveryAddressDataAccessor.hasValidDeliveryAddress(addressId);
        changeAddressController.updateDeliveryAddress(subscription.Id, addressId, Date.today().addDays(1));
    }

}