force-app/main/default/objects/Contact/fields/Status__c.field-meta.xml
<CustomField>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </CustomField>

force-app/main/default/objects/Email_Subscriber__c/Email_Subscriber__c.object-meta.xml
<CustomObject>
    <label>Email Subscriber</label>
    <nameField>
        <displayFormat>ESN-{0000}</displayFormat>
        <label>Email Subscriber Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Email Subscribers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Email_Subscriber__c/fields/Contact__c.field-meta.xml
<CustomField>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Email Subscribers</relationshipLabel>
        <relationshipName>Email_Subscribers</relationshipName>
        <type>Lookup</type>
    </CustomField>

force-app/main/default/objects/Email_Subscriber__c/fields/Email_Subscription__c.field-meta.xml
<CustomField>
        <fullName>Email_Subscription__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Email Subscription</label>
        <referenceTo>Email_Subscription__c</referenceTo>
        <relationshipLabel>Email Subscribers</relationshipLabel>
        <relationshipName>Email_Subscribers</relationshipName>
        <type>Lookup</type>
    </CustomField>

force-app/main/default/objects/Email_Subscriber__c/fields/Status__c.field-meta.xml
<CustomField>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Subscribed</fullName>
                </value>
                <value>
                    <fullName>Unsubscribed</fullName>
                </value>
                <value>
                    <fullName>No Preference</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </CustomField>

force-app/main/default/objects/Email_Subscriber__c/fields/Subscribe_Date__c.field-meta.xml
<CustomField>
        <fullName>Subscribe_Date__c</fullName>
        <label>Subscribe Date</label>
        <type>Date</type>
    </CustomField>

force-app/main/default/objects/Email_Subscriber__c/fields/Unsubscribe_Date__c.field-meta.xml
<CustomField>
        <fullName>Unsubscribe_Date__c</fullName>
        <label>Unsubscribe Date</label>
        <type>Date</type>
    </CustomField>

force-app/main/default/objects/Email_Subscription__c/Email_Subscription__c.object-meta.xml
<CustomObject>
    <label>Email Subscription</label>
    <nameField>
        <label>Email Subscription Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Email Subscriptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/ManageSubscriptionsController.cls
public without sharing class ManageSubscriptionsController {

    public List<Email_Subscriber__c> emailSubscribersToUpdate {get; set;}
    public List<SubWrapper> emailSubscriptions {get; set;}
    public String contactID {get; set;}
    public String listID {get; set;}
    public String subscriberid {get; set;}
    public String status {get; set;}
    public String unSubscribeAllStatus {get; set;}
    public String message {get;set;}

    public ManageSubscriptionsController() {
        contactID = ApexPages.currentPage().getParameters().get('cid');
        listID = ApexPages.currentPage().getParameters().get('listid');

        emailSubscribersToUpdate = [SELECT id, name, Contact__c,Email_Subscription__c,Email_Subscription__r.Name ,Status__c,Unsubscribe_Date__c FROM Email_Subscriber__c WHERE Contact__c=:contactID AND Email_Subscription__c=:listID ];
        system.debug(emailSubscribersToUpdate.size());
        contactID = ApexPages.currentPage().getParameters().get('cid');

        UpdateSubscriptions();

    }

    public void UpdateSubscriptions(){
        emailSubscriptions = new List<SubWrapper>();
        for(Email_Subscription__c es:[SELECT id, name, (Select id, Contact__c,Email_Subscription__c, Name ,Status__c,Unsubscribe_Date__c from Email_Subscribers__r WHERE Contact__c =:contactID) FROM Email_Subscription__c order by Name ASC])
        {
            SubWrapper sw = new SubWrapper();
            sw.subscriptionID = es.id;
            sw.subscriptionName = es.Name;
            system.debug('-----' + es.Email_Subscribers__r.size());
            if(es.Email_Subscribers__r!=null && es.Email_Subscribers__r.size()>0) {
                if(es.Email_Subscribers__r[0].Status__c == 'Subscribed')
                {
                    sw.subscriptionStatus = 'Subscribed';
                    sw.subscriberId = es.Email_Subscribers__r[0].Id;
                }
                else{
                    sw.subscriptionStatus = 'Unsubscribed';
                    sw.subscriberId = es.Email_Subscribers__r[0].Id;
                }
            }
            else{
                sw.subscriptionStatus = 'No Preference';
            }
            system.debug(sw);
            emailSubscriptions.add(sw);
        }

    }


    public void unsubscribe(){

        for(Email_Subscriber__c ES:emailSubscribersToUpdate){
            ES.Status__c = 'Unsubscribed';
            ES.Unsubscribe_Date__c = system.today();
        }

        update emailSubscribersToUpdate;

        UpdateSubscriptions();

    }
    //Actions for Unsubscribe from all link on the bottom of VFP
    public void unsubscribeToAll(){

        try {
            Contact c = new Contact(id = contactid);
            c.HasOptedOutOfEmail = true;
            update c;


            List<Email_Subscriber__c> ESS = [SELECT id, name, Contact__c,Email_Subscription__c,Status__c,Unsubscribe_Date__c FROM Email_Subscriber__c WHERE Contact__c = :contactID AND Status__c != 'Unsubscribed'];
            for (Email_Subscriber__c ES : ESS) {
                ES.Status__c = 'Unsubscribed';
                ES.Unsubscribe_Date__c = system.today();
            }

            update ESS;

            unSubscribeAllStatus = 'You have been unsubscribed from all communications.';
            message = 'Your preferences have been updated.';
        }
        catch(Exception ex)
        {
            system.debug(ex.getMessage());
            message = 'An error occurred: ' + ex.getMessage();
        }
    }

    public void UpdateStatus(){
        system.debug(subscriberid);
        system.debug(status);

//        Email_Subscriber__c es = new Email_Subscriber__c();
//        if(subscriberid!=null && subscriberid!='') {
//            es.id = subscriberid;
//        }
//        es.Status__c = status;
//        if (status == 'Subscribed') {
//            es.Subscribe_Date__c = system.today();
//        } else if (status == 'Unsubscribed') {
//            es.Unsubscribe_Date__c = system.today();
//        }
//        upsert es;

        for(SubWrapper sw:emailSubscriptions){
            if(sw.subscriberID == subscriberid)
            {
                sw.subscriptionStatus = status;
            }
        }

    }

    public void Submit(){
        try {
            List<Email_Subscriber__c> esToUpdate = new List<Email_Subscriber__c>();

            for(SubWrapper sw:emailSubscriptions){
                system.debug('---');
                system.debug(sw.subscriberId);
                system.debug(contactID);
                system.debug(sw.subscriptionID);
                Email_Subscriber__c es = new Email_Subscriber__c();
                es.id = sw.subscriberId;
                es.Contact__c = contactID;
                es.Email_Subscription__c = sw.subscriptionID;

                es.Status__c = sw.subscriptionStatus;
                if(sw.subscriptionStatus == 'Subscribed')
                {
                    es.Subscribe_date__c = system.today();
                }
                else if(sw.subscriptionStatus == 'Unsubscribed')
                {
                    es.Unsubscribe_date__c = system.today();
                }

                if(sw.subscriptionStatus !='No Preference'){
                    esToUpdate.add(es);
                }

            }


            upsert esToUpdate;
            message = 'Your preferences have been updated.';

            UpdateSubscriptions();
        }
        catch(Exception ex)
        {
            system.debug(ex.getMessage());
            message = ex.getMessage();
        }

    }


    public class SubWrapper{

        public String contactId {get;set;}
        public String subscriberID {get;set;}
        public String subscriptionName {get;set;}
        public String subscriptionID {get;set;}
        public String subscriptionStatus {get;set;}

        public SubWrapper(){

        }
    }
}