force-app/main/default/objects/c1as_sso_pwd__c/c1as_sso_pwd__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>c1as sso pwd</description>
    <label>c1as_sso_pwd</label>
</CustomObject>

force-app/main/default/objects/c1as_sso_pwd__c/fields/pwd__c.field-meta.xml
<CustomField>
        <fullName>pwd__c</fullName>
        <label>pwd</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </CustomField>

force-app/main/default/objects/c1as_sso_pwd__c/fields/user__c.field-meta.xml
<CustomField>
        <fullName>user__c</fullName>
        <description>user name</description>
        <label>user</label>
        <length>64</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </CustomField>

force-app/main/default/objects/User/fields/SingleSignOn__c.field-meta.xml
<CustomField>
        <fullName>SingleSignOn__c</fullName>
        <defaultValue>false</defaultValue>
        <label>SingleSignOn</label>
        <type>Checkbox</type>
    </CustomField>

force-app/main/default/objects/User/fields/SSO_AgentId__c.field-meta.xml
<CustomField>
        <fullName>SSO_AgentId__c</fullName>
        <label>SSO_AgentId</label>
        <length>50</length>
        <type>Text</type>
    </CustomField>

force-app/main/default/objects/User/fields/SSO_Extension__c.field-meta.xml
<CustomField>
        <fullName>SSO_Extension__c</fullName>
        <label>SSO_Extension</label>
        <length>50</length>
        <type>Text</type>
    </CustomField>

force-app/main/default/objects/User/fields/SSO_Pwd__c.field-meta.xml
<CustomField>
        <fullName>SSO_Pwd__c</fullName>
        <label>SSO_Pwd</label>
        <length>50</length>
        <type>Text</type>
    </CustomField>

force-app/main/default/objects/User/fields/userToken__c.field-meta.xml
<CustomField>
        <fullName>userToken__c</fullName>
        <description>user token</description>
        <label>userToken</label>
        <length>64</length>
        <type>Text</type>
    </CustomField>

force-app/main/default/classes/Apex_UserInfo.cls
global class Apex_UserInfo{

webService static String getCurrUserSSOInfo() { 
    system.debug('getCurrUserSSOInfo: Enter ');
   
    User u = [SELECT SingleSignOn__c, SSO_AgentId__c,userToken__c, SSO_Extension__c FROM User WHERE Id = :UserInfo.getUserId()];
   	 try{
    	c1as_sso_pwd__c upwd = [SELECT user__c, pwd__c FROM c1as_sso_pwd__c WHERE name = :UserInfo.getUserId()];
        system.debug('getCurrUserSSOInfo: Encrypted PWD' + upwd.pwd__c);
         
        Blob DecodedPWD= EncodingUtil.base64Decode(upwd.pwd__c);
        Blob DecodedKey= EncodingUtil.base64Decode(u.userToken__c);
        Blob decryptedData = Crypto.decryptWithManagedIV('AES256', DecodedKey, DecodedPWD);
		u.SSO_Pwd__c=decryptedData.toString();
        system.debug('getCurrUserSSOInfo: Decrypted PWD' + decryptedData.toString());
        String JSONString = JSON.serialize(u);
    	system.debug('getCurrUserSSOInfo: Exit ');  
        return JSONString;
    }
    catch(Exception e)
        {
          system.debug('**fwr Exception caught:' + e.getMessage());
     
        }
    return JSON.serialize(u);
   }
   

webService static Void saveCurrUserSSOInfo(String agentId, String pwd, String extension) {
      // User u = new User(); 
   	User u = [SELECT SSO_AgentId__c,userToken__c, SSO_Extension__c FROM User WHERE Id = :UserInfo.getUserId()];  
	system.debug('saveCurrUserSSOInfo: Enter ');
    try{
    	if (u.userToken__c.length()>10 )
       	 	{
    			system.debug('saveCurrUserSSOInfo: there is a saved cryptoKey abort!!! ' + u.userToken__c);
            	return;
        	} 
    	}
    catch(Exception e)
        {
            system.debug('saveCurrUserSSOInfo: cannot find saved cryptoKey continue to get a new cryptoKey. ' );
        }
    
    try{     
        Blob cryptoKey = Crypto.generateAesKey(256);
    	system.debug('saveCurrUserSSOInfo: new generated cryptoKey: ' + EncodingUtil.base64Encode(cryptoKey));
        Blob data = Blob.valueOf(pwd);
		Blob encryptedData = Crypto.encryptWithManagedIV('AES256', cryptoKey, data);
	    u.Id = UserInfo.getUserId();
       system.debug('saveCurrUserSSOInfo: getUserId: ' + UserInfo.getUserId());
       u.SSO_AgentId__c = agentId;
       u.userToken__c = EncodingUtil.base64Encode(cryptoKey); 
       u.SSO_Extension__c = extension;
           
        try{
        
        update u; 
        }
        catch(Exception e)
        {
            //insert u;
            system.debug('saveCurrUserSSOInfo: can not update user data');
        }

        try{
       		              
    		c1as_sso_pwd__c currentpassword=new c1as_sso_pwd__c();
    		currentpassword.pwd__c=EncodingUtil.base64Encode(encryptedData);
    		system.debug('saveCurrUserSSOInfo: encryptedData: ' + EncodingUtil.base64Encode(encryptedData));
    		currentpassword.name= UserInfo.getUserId();
    		currentpassword.user__c = UserInfo.getUserId();
        	insert currentpassword;
        }
        catch(Exception e)
        { 
            c1as_sso_pwd__c currentpassword=  [SELECT name, user__c, pwd__c FROM c1as_sso_pwd__c WHERE user__c = :UserInfo.getUserId()]; 
    		currentpassword.pwd__c=EncodingUtil.base64Encode(encryptedData);
            update currentpassword;
            system.debug('saveCurrUserSSOInfo: Trouble saving pwd');
        }
    
    system.debug('saveCurrUserSSOInfo: Exit ');
    }
     catch(Exception e)
        {
          system.debug('**save Exception caught:' + e.getMessage());
        }
   }



}