force-app/main/default/objects/ctiMsg__c/ctiMsg__c.object-meta.xml
<CustomObject>
    <label>ctiMsg</label>
    <nameField>
        <label>ctiMsg Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ctiMsgs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ctiMsg__c/fields/message__c.field-meta.xml
<CustomField>
        <fullName>message__c</fullName>
        <label>message</label>
        <length>255</length>
        <type>Text</type>
    </CustomField>

force-app/main/default/objects/ctiMsg__c/fields/user__c.field-meta.xml
<CustomField>
        <fullName>user__c</fullName>
        <label>user</label>
        <length>60</length>
        <type>Text</type>
    </CustomField>

force-app/main/default/classes/notificationTester.cls
@isTest
public class notificationTester {
	@isTest
    static void TestForgotPassword()
    {
        NotificationController.updateCallVar();
        NotificationController.getSessionId();
        NotificationController.getUserId();
        String result=NotificationController.pushCTITopic('param=dwewewrerw');
        
        ctiMsg__c tempMessage = new ctiMsg__c();
        tempMessage.message__c = 'temp';
        tempMessage.Name = 'temp';
        tempMessage.user__c = UserInfo.getUserId();
        insert tempMessage;
        
        result=NotificationController.pushCTITopic('param=dwewewrerw');
        //System.assertEquals(null, result);
    }
}