force-app/main/default/objects/Transaction_Log__c/Transaction_Log__c.object-meta.xml
<CustomObject>
    <label>Transaction Log</label>
    <nameField>
        <displayFormat>TL-{0000}</displayFormat>
        <label>Transaction Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transaction Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Transaction_Log__c/fields/Account__c.field-meta.xml
<CustomField>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Transaction Logs</relationshipLabel>
        <relationshipName>Transaction_Logs</relationshipName>
        <type>Lookup</type>
    </CustomField>

force-app/main/default/objects/Transaction_Log__c/fields/Actual_Restart__c.field-meta.xml
<CustomField>
        <fullName>Actual_Restart__c</fullName>
        <label>Actual Restart</label>
        <type>Date</type>
    </CustomField>

force-app/main/default/objects/Transaction_Log__c/fields/Actual_Start__c.field-meta.xml
<CustomField>
        <fullName>Actual_Start__c</fullName>
        <label>Actual Start</label>
        <type>Date</type>
    </CustomField>

force-app/main/default/objects/Transaction_Log__c/fields/Date__c.field-meta.xml
<CustomField>
        <fullName>Date__c</fullName>
        <label>Date</label>
        <type>Date</type>
    </CustomField>

force-app/main/default/objects/Transaction_Log__c/fields/Transaction_Type__c.field-meta.xml
<CustomField>
        <fullName>Transaction_Type__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Transaction Type</label>
        <referenceTo>Transaction_Type__c</referenceTo>
        <relationshipLabel>Transaction Logs</relationshipLabel>
        <relationshipName>Transaction_Logs</relationshipName>
        <type>Lookup</type>
    </CustomField>

force-app/main/default/objects/Transaction_Log__c/recordTypes/Complaint.recordType-meta.xml
<RecordType>
        <fullName>Complaint</fullName>
        <active>true</active>
        <label>Complaint</label>
    </RecordType>

force-app/main/default/objects/Transaction_Type__c/Transaction_Type__c.object-meta.xml
<CustomObject>
    <label>Transaction Type</label>
    <nameField>
        <label>Transaction Type Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Transaction Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Transaction_Type__c/fields/Code__c.field-meta.xml
<CustomField>
        <fullName>Code__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <inlineHelpText>Matches DSI Code</inlineHelpText>
        <label>Code</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </CustomField>

force-app/main/default/classes/TransactionDataAccessor.cls
public class TransactionDataAccessor {
    public static List<Transaction_Log__c> getLatestComplaintTransactions(Id accountId, Integer count) {
        Id transactionComplaintRecordTypeId = Schema.SObjectType.Transaction_Log__c.getRecordTypeInfosByDeveloperName().get('Complaint').getRecordTypeId();
        return [
            SELECT Id, Date__c FROM Transaction_Log__c
            WHERE RecordTypeId = :transactionComplaintRecordTypeId
            AND Account__c = :accountId
            ORDER BY Date__c DESC
            LIMIT :count
       ];
    }

    public static Transaction_Log__c getTransaction(Id transactionId) {
        return [
            SELECT Id, Actual_Start__c, Actual_Restart__c
            FROM Transaction_Log__c
            WHERE Id = :transactionId
       ];
    }

    public static Transaction_Type__c getFirstTransactionTypeByCode(String code) {
        return [
            SELECT Id
            FROM Transaction_Type__c
            WHERE Code__c = :code
            LIMIT 1
        ];
    }
}