force-app/main/default/objects/Cut_Offs_Time__mdt/Cut_Offs_Time__mdt.object-meta.xml
<CustomObject>
    <label>Cut-Offs Time</label>
    <pluralLabel>Cut Off Times</pluralLabel>
</CustomObject>

force-app/main/default/objects/Cut_Offs_Time__mdt/fields/Community_Redeliver__c.field-meta.xml
<CustomField>
        <fullName>Community_Redeliver__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Community Redeliver</label>
        <type>Checkbox</type>
    </CustomField>

force-app/main/default/objects/Cut_Offs_Time__mdt/fields/Cut_Off_Type__c.field-meta.xml
<CustomField>
        <fullName>Cut_Off_Type__c</fullName>
        <description>Type of deadline</description>
        <label>Cut Off Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Re-delivery</fullName>
                    <default>true</default>
                    <label>Re-delivery</label>
                </value>
                <value>
                    <fullName>Press Run</fullName>
                </value>
                <value>
                    <fullName>Carrier Memo</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </CustomField>

force-app/main/default/objects/Cut_Offs_Time__mdt/fields/Day_of_Week__c.field-meta.xml
<CustomField>
        <fullName>Day_of_Week__c</fullName>
        <description>Day of the week for the cut-off</description>
        <label>Day of Week</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Sunday</fullName>
                    <default>true</default>
                    <label>Sunday</label>
                </value>
                <value>
                    <fullName>Monday</fullName>
                </value>
                <value>
                    <fullName>Tuesday</fullName>
                </value>
                <value>
                    <fullName>Wednesday</fullName>
                </value>
                <value>
                    <fullName>Thursday</fullName>
                </value>
                <value>
                    <fullName>Friday</fullName>
                </value>
                <value>
                    <fullName>Saturday</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </CustomField>

force-app/main/default/objects/Cut_Offs_Time__mdt/fields/Delivery_Type__c.field-meta.xml
<CustomField>
        <fullName>Delivery_Type__c</fullName>
        <label>Delivery Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Weekday</fullName>
                    <default>true</default>
                    <label>Weekday</label>
                </value>
                <value>
                    <fullName>Saturday</fullName>
                </value>
                <value>
                    <fullName>Sunday</fullName>
                </value>
                <value>
                    <fullName>Not Sunday</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </CustomField>

force-app/main/default/objects/Cut_Offs_Time__mdt/fields/Hour__c.field-meta.xml
<CustomField>
        <fullName>Hour__c</fullName>
        <description>Hour of deadline</description>
        <label>Hour</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </CustomField>

force-app/main/default/objects/Cut_Offs_Time__mdt/fields/Minute__c.field-meta.xml
<CustomField>
        <fullName>Minute__c</fullName>
        <description>Minute of deadline</description>
        <label>Minute</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </CustomField>

force-app/main/default/objects/Transaction_Type__c/Transaction_Type__c.object-meta.xml
<CustomObject>
    <label>Transaction Type</label>
    <nameField>
        <label>Transaction Type Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Transaction Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Transaction_Type__c/fields/Category__c.field-meta.xml
<CustomField>
        <fullName>Category__c</fullName>
        <inlineHelpText>Choose appropriate for transaction viewer</inlineHelpText>
        <label>Category</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Carrier Me</fullName>
                </value>
                <value>
                    <fullName>CC_Request</fullName>
                </value>
                <value>
                    <fullName>Complaint</fullName>
                </value>
                <value>
                    <fullName>Credit_Card</fullName>
                </value>
                <value>
                    <fullName>Journal</fullName>
                </value>
                <value>
                    <fullName>Memo</fullName>
                </value>
                <value>
                    <fullName>Message</fullName>
                </value>
                <value>
                    <fullName>Move</fullName>
                </value>
                <value>
                    <fullName>Product Change</fullName>
                </value>
                <value>
                    <fullName>Start</fullName>
                </value>
                <value>
                    <fullName>Stop</fullName>
                </value>
                <value>
                    <fullName>Vacation Pack</fullName>
                </value>
                <value>
                    <fullName>VH</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </CustomField>

force-app/main/default/objects/Transaction_Type__c/fields/Code__c.field-meta.xml
<CustomField>
        <fullName>Code__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <inlineHelpText>Matches DSI Code</inlineHelpText>
        <label>Code</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </CustomField>

force-app/main/default/objects/Transaction_Type__c/fields/Redeliver__c.field-meta.xml
<CustomField>
        <fullName>Redeliver__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Instruction for DSI</inlineHelpText>
        <label>Redeliver</label>
        <type>Checkbox</type>
    </CustomField>

force-app/main/default/objects/Transaction_Type__c/fields/Type_Name__c.field-meta.xml
<CustomField>
        <fullName>Type_Name__c</fullName>
        <inlineHelpText>Delivery, COMO etc.</inlineHelpText>
        <label>Type Name</label>
        <length>255</length>
        <type>Text</type>
    </CustomField>

force-app/main/default/classes/CutOffManager.cls
public class CutOffManager  {

	public CutOffManager(){}

	@InvocableMethod
	public static List<Boolean> isBeforeCutOff(List<String> CutOffType){
		List<Boolean> booResult = new List<Boolean>();
		for(String str: CutOffType){
			booResult.add(isBefore(str));
		}
		return booResult;
	}
	public static Boolean isBeforeCutOff(String CutOffType){
		Boolean booResult = false;
		booResult = isBefore(CutOffType);
		return booResult;
	}
	
	public static String DeliveryDayType(Date selectedDate){
		// based on selected date input, returns {Weekday, Saturday, Sunday}
		String result = '';
		String CutOffType = 'Re-delivery';  //default CutOffType

        Datetime selectedDT = datetime.newInstance(selectedDate.year(), selectedDate.month(),selectedDate.day());
		// system.debug('--DeliveryDayType--selectedDate: '+ selectedDate);
		// system.debug('--DeliveryDayType--DayOfWeek   : '+ selectedDT.format('EEEE'));

		// get the record
		Cut_Offs_Time__mdt cot = [SELECT Delivery_Type__c 
					FROM Cut_Offs_Time__mdt 
					WHERE Day_of_Week__c =: selectedDT.format('EEEE')
					AND Cut_Off_Type__c =: CutOffType];
		
		system.debug('--DeliveryDayType returned: ' + cot.Delivery_Type__c );
		result = cot.Delivery_Type__c;
		return result;
	}

	private static Boolean isBefore(String CutOffType){
		Boolean booResult = false;
		
		// get current day and time
		Datetime currDateTime = Datetime.now();
		// get the cut-off record
		Cut_Offs_Time__mdt co = [SELECT Hour__c, Minute__c, Community_Redeliver__c
					FROM Cut_Offs_Time__mdt 
					WHERE Day_of_Week__c =: currDateTime.format('EEEE')
					AND Cut_Off_Type__c =: CutOffType];
		// compare date
		booResult = currDateTime.time() < Time.newInstance(Integer.valueOf(co.Hour__c), Integer.valueOf(co.Minute__c), 0, 0);
		Boolean communityRedelivery = (UserInfo.getUserType() != 'Standard' &&  co.Community_Redeliver__c && CutOffType == 'Re-delivery');
		return booResult || communityRedelivery;
	}

	public static Transaction_Type__c communityDeliveryHelper(Id transactionTypeId, Date transactionDate){
        Date currentDate = Date.today();
		DateTime transDateDT = DateTime.newInstance(currentDate.year(), currentDate.month(), currentDate.day(), 12, 0, 0);
		/* Check CMT for Community_Redeliver__c flag and user type. */
		Cut_Offs_Time__mdt co = [SELECT Community_Redeliver__c
				FROM Cut_Offs_Time__mdt 
				WHERE Day_of_Week__c =: transDateDT.format('EEEE')
				AND Cut_Off_Type__c =: 'Re-delivery'];
				System.debug('co: ' + co);

		if(UserInfo.getUserType() == 'Standard' || !co.Community_Redeliver__c)
			return null;
        /*Verify current day is selected*/
        if(currentDate != transactionDate) 
			return null;
		List<Transaction_Type__c> transTypeList = [SELECT Id, Name, Code__c, Type_Name__c, Category__c, Redeliver__c
            FROM Transaction_Type__c 
            WHERE Code__c = 'NE' OR Code__c = 'CM' OR Id = :transactionTypeId];
		
		Transaction_Type__c nextDayRecovery;
		Transaction_Type__c missingManufacturerCoupons;
		Transaction_Type__c oldTransType;
		for(Transaction_Type__c tt : transTypeList){
			if(tt.Code__c == 'NE')
				nextDayRecovery = tt;
			if(tt.Code__c == 'CM')
				missingManufacturerCoupons = tt;
			if(tt.Id == transactionTypeId)
				oldTransType = tt;
		}
		if(oldTransType.Name == 'Missing Manufacturer Coupons'){
			return missingManufacturerCoupons;
		}    
		else{
			if(!oldTransType.Redeliver__c)
				return null;
			return nextDayRecovery;
		} 
    }
}